### ISSUE TITLE
POST endpoint not working on Cloudflare Pages

### ISSUE THREAD

**Issue by JacobWeinbren** [withastro/astro#10073]
### Astro Info

```block
Astro                    v4.3.5
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/react
```

### Describe the Bug

Hosting on Localhost and Vercel, POST requests work fine, but on Cloudflare Pages, I get this error:

```
{
  "outcome": "ok",
  "scriptName": "pages-worker--1940235-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "01:38:10 [WARN] [router] No API Route handler exists for the method \"POST\" for the route /api/signup.\nFound handlers: \"POST\"\n"
      ],
      "level": "log",
      "timestamp": 1707442690732
    }
  ],
}
```

### What's the expected result?

The expected result would either be an error from the POST request response or a successful POST request response.

### Link to Minimal Reproducible Example

https://github.com/JacobWeinbren/Kafkaesque

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
The linked reproduction can't be built without API keys. You might want open a support thread.

[astro.build/chat](https://astro.build/chat)

**Comment by carlosesquivelroisenvit** [comment]
@lilnasy I'm having this issue with a slight variation. The first call to the script fails with this message (there's no reference to window, the script just calls another API). Subsequent calls show the exact same message as in the original issue. Is it possible to get access to the discord thread?

`  "logs": [
    {
      "message": [
        "16:50:21 [ERROR] ReferenceError: window is not defined\n    at worker.mjs:891:252\n    at worker.mjs:5:245\n    at worker.mjs:891:9039\n    at worker.mjs:5:212\n    at worker.mjs:891:24564\n    at worker.mjs:5:212\n    at worker.mjs:891:25088\n    at async e.render (worker.mjs:1190:18694)\n    at async Object.fetch (worker.mjs:1190:22066)"
      ],
      "level": "error",
      "timestamp": 1712163021801
    }
  ],`

**Comment by lilnasy** [comment]
Could you open a new issue in withastro/adapters?
