### ISSUE TITLE
Bad error message when the `transition:name` property is the wrong type

### ISSUE THREAD

**Issue by godalming123** [withastro/astro#10150]
### Astro Info

```block
Astro                    v4.3.7
Node                     v20.10.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
which: no xclip in (/home/jg/Documents/website/node_modules/.bin:/home/jg/Documents/website/node_modules/.bin:/home/jg/Documents/website/node_modules/.bin:/home/jg/Documents/node_modules/.bin:/home/jg/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/lib/node_modules_20/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:~/go/bin/:/home/jg/.cargo/bin:/home/jg/.local/share/pnpm:~/go/bin/:/home/jg/.local/bin:/home/jg/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
```
```


### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

The error message when the wrong type is passed to the `transition:name property` is as follows:
18:06:34 ▶ src/pages/index.astro
18:06:34   └─ /index.html/home/jg/Documents/website/node_modules/cssesc/cssesc.js:33
	var firstChar = string.charAt(0);
	                      ^

TypeError: string.charAt is not a function
    at cssesc (/home/jg/Documents/website/node_modules/cssesc/cssesc.js:33:25)
    at renderTransition (file:///home/jg/Documents/website/dist/chunks/astro_CF1PFtNQ.mjs:1451:33)
    at file:///home/jg/Documents/website/dist/chunks/prerender_C4LV0kBl.mjs:81:105
    at Array.map (<anonymous>)
    at Object.default (file:///home/jg/Documents/website/dist/chunks/prerender_C4LV0kBl.mjs:80:1105)
    at new AstroComponentInstance (file:///home/jg/Documents/website/dist/chunks/astro_CF1PFtNQ.mjs:886:30)
    at createAstroComponentInstance (file:///home/jg/Documents/website/dist/chunks/astro_CF1PFtNQ.mjs:930:20)
    at renderAstroComponent (file:///home/jg/Documents/website/dist/chunks/astro_CF1PFtNQ.mjs:1319:20)
    at renderComponent (file:///home/jg/Documents/website/dist/chunks/astro_CF1PFtNQ.mjs:1338:12)
    at file:///home/jg/Documents/website/dist/chunks/prerender_C4LV0kBl.mjs:80:27

### What's the expected result?

An error message that is musch more easy to understand, for example:
> At *[insert location here]*:
> - `transition:name` should be a string (recieved *`[insert value here]`* which is of type *`[insert type here]`*)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fie6dy?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hello @godalming123, thank you for opening this issue. I'll take a look at this.

**Comment by martrapp** [comment]
This is the output from `npx astro check`:
![image](https://github.com/withastro/astro/assets/94928215/e7be185c-69fc-42ae-86d2-2d3df7c3b7a4)

**Comment by martrapp** [comment]
You should also see an error in the IDE (here VS Code) when you write code like this:
![image](https://github.com/withastro/astro/assets/94928215/e46ac0df-1e3b-4edb-b7ba-0c29a72b00f4)

**Comment by godalming123** [comment]
Yeah, I haven't been able to get the LSP working in helix, I think that it's because I didn't specify the typescript install path
