### ISSUE TITLE
Internal server error: No hoisted script at index 0 Bug

### ISSUE THREAD

**Issue by Boss-of-Trees** [withastro/astro#10209]
### Astro Info

```block
Astro                    v4.4.2
Node                     v18.17.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I was just following along the tutorial and somewhere in this step (https://docs.astro.build/en/tutorial/3-components/4/) I started to encounter an error.
Everytime I substitute the main page with the BaseLayout (as shown in the tutorial), I get "[ERROR] [vite] Internal server error: No hoisted script at index 0". When I have the page the way it was before it doesn't happen. This only happens with the index.astro file all the others (blog.astro and about.astro, which I also substituted with BaseLayout) work just fine.

The Error in full:
21:47:33 [ERROR] [vite] Internal server error: No hoisted script at index 0
at Context.load (file:///C:/Users/Main/WebstormProjects/astrotest/node_modules/astro/dist/vite-plugin-astro/index.js:85:19)
at Object.load (file:///C:/Users/Main/WebstormProjects/astrotest/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:50809:64)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async loadAndTransform (file:///C:/Users/Main/WebstormProjects/astrotest/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:53535:24)
at async viteTransformMiddleware (file:///C:/Users/Main/WebstormProjects/astrotest/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:63409:32)

I basically use the same code as in the tutrial, but for reference here is my code:
index.astro (substituted):
```
---
import BaseLayout from '../layouts/BaseLayout.astro';
const pageTitle = "Home Page";
---
<BaseLayout>
  <h2>My awesome blog subtitle</h2>
</BaseLayout>
```

index.astro (original):
```
---
import Header from '../components/Header.astro';
import Footer from '../components/Footer.astro';
import '../styles/global.css';
const { pageTitle } = Astro.props;
---

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <meta name="viewport" content="width=device-width" />
        <meta name="generator" content={Astro.generator} />
        <title>{pageTitle}</title>
    </head>
    <body>
        <Header />
        <h1>{pageTitle}</h1>
        <h2>My awesome blog subtitle</h2>
        <Footer />

        <script>
            import "../scripts/menu.js";
        </script>
    </body>
</html>

```
BaseLayout:
```
---
import Header from '../components/Header.astro';
import Footer from '../components/Footer.astro';
import '../styles/global.css';
const { pageTitle } = Astro.props;
---

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <meta name="viewport" content="width=device-width" />
        <meta name="generator" content={Astro.generator} />
        <title>{pageTitle}</title>
    </head>
    <body>
        <Header />
        <h1>{pageTitle}</h1>
        <slot />
        <Footer />

        <script>
            import "../scripts/menu.js";
        </script>
    </body>
</html>
```

### What's the expected result?

When I substitute large parts of the index.astro file with the Layout defined in BaseLayout.astro (as described in the tutorial), it should still look the same.

### Link to Minimal Reproducible Example

https://docs.astro.build/en/tutorial/0-introduction/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I can't seem to reproduce this. The update works fine for me. Does the error still appear after a manual page reload? Do you enable some sort of prefetching options in your browser?

**Comment by Boss-of-Trees** [comment]
The error only doesn't occur every time, just like every 3rd time or so.
I actually did check the prefetching options in my browser they are all turned off, since I already had problems with them using express. I have also manually reloaded the page and it then always disappears, but when I go click on the home link again it gets thrown again. I also restarted the server and my computer and it still happens.

I have uploaded the project to:
https://github.com/Boss-of-Trees/astrotest

**Comment by lilnasy** [comment]
I didn't see the error either. It's possible it's OS-specific. I'll try on windows.

**Comment by lilnasy** [comment]
Even after substitution, works just fine on windows too.

**Comment by Boss-of-Trees** [comment]
Hey, thanks for your help and efforts.
I was just reading your messages and wanted to see, if I can help further, but the error actually didn't occur to me any more. I don't know what was causing it, I haven't done anything else (no update, no code changes). But it works now.
If you'd like to you can close this issue, now.

**Comment by lilnasy** [comment]
Thanks for reporting back! Feel free to let us know in our discord (https://astro.build/chat) if you need more help more with astro.

**Comment by g012** [comment]
Hello,

I've just encountered this issue as well, when launching the project again (yarn dev) after turning it off for the night:

```
10:40:45 [404] /fonts/BSBlack.woff2 1ms
10:40:45 [ERROR] [vite] Internal server error: No hoisted script at index 0
      at Context.load (file:///C:/data/cuborph/www/node_modules/astro/dist/vite-plugin-astro/index.js:108:19)
      at Object.load (file:///C:/data/cuborph/www/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52289:64)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/data/cuborph/www/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:54993:24)
10:40:45 [ERROR] [vite] Internal server error: No cached compile metadata found for "/src/components/BaseHead.astro?astro&type=script&index=0&lang.ts". The main Astro module "C:/data/cuborph/www/src/components/BaseHead.astro" should have compiled and filled the metadata first, before its virtual modules can be requested.
      at Context.load (file:///C:/data/cuborph/www/node_modules/astro/dist/vite-plugin-astro/index.js:70:15)
      at async Object.load (file:///C:/data/cuborph/www/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52289:32)
      at async loadAndTransform (file:///C:/data/cuborph/www/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:54993:24)
10:48:56 [200] / 3ms
```

To note, it shouldn't request "/fonts/BSBlack.woff2" since I moved it to "/bsblack.woff2" and updated the reference in the css file yesterday - and it was working yesterday as is.

Playing around with this theme: https://astro.build/themes/details/astromax/

**Comment by g012** [comment]
Seeing it was looking for BaseHead.astro in cache, which I had renamed to Head.astro, I renamed it back to BaseHead.astro, but now it's complaining about Head.astro. I don't know where is the cache so I can delete all that... gonna look for this info.

```
13:07:31 watching for file changes...
13:07:37 [ERROR] [vite] Internal server error: No cached compile metadata found for "/src/components/Head.astro?astro&type=script&index=0&lang.ts". The main Astro module "C:/data/cuborph/www/src/components/Head.astro" should have compiled and filled the metadata first, before its virtual modules can be requested.
      at Context.load (file:///C:/data/cuborph/www/node_modules/astro/dist/vite-plugin-astro/index.js:70:15)
      at async Object.load (file:///C:/data/cuborph/www/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52289:32)
      at async loadAndTransform (file:///C:/data/cuborph/www/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:54993:24)
13:07:37 [ERROR] [vite] Internal server error: No hoisted script at index 0
      at Context.load (file:///C:/data/cuborph/www/node_modules/astro/dist/vite-plugin-astro/index.js:108:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.load (file:///C:/data/cuborph/www/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52289:32)
      at async loadAndTransform (file:///C:/data/cuborph/www/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:54993:24)
```

**Comment by zqqcee** [comment]
restart the server, and solve it!

**Comment by matronator** [comment]
Also had this issue. Have no idea what causes it, but it's pretty annoying. I have to restart the dev server all the time and it's almost impossible to get anything done...

```
12:22:57 [ERROR] [vite] Internal server error: No script at index 0
      at LoadPluginContext.load (file:///Users/matejbystricky/Documents/Work/Matronator%20Brand/projects/gh.nosync/Bez%20na%CC%81zvu/portfolio/node_modules/.pnpm/astro@5.13.3_@types+node@24.3.0_jiti@2.5.1_lightningcss@1.30.1_rollup@4.48.0_typescript@5.8.3_yaml@2.8.1/node_modules/astro/dist/vite-plugin-astro/index.js:113:19)
      at EnvironmentPluginContainer.load (file:///Users/matejbystricky/Documents/Work/Matronator%20Brand/projects/gh.nosync/Bez%20na%CC%81zvu/portfolio/node_modules/.pnpm/vite@6.3.5_@types+node@24.3.0_jiti@2.5.1_lightningcss@1.30.1_yaml@2.8.1/node_modules/vite/dist/node/chunks/dep-DBxKXgDP.js:42265:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///Users/matejbystricky/Documents/Work/Matronator%20Brand/projects/gh.nosync/Bez%20na%CC%81zvu/portfolio/node_modules/.pnpm/vite@6.3.5_@types+node@24.3.0_jiti@2.5.1_lightningcss@1.30.1_yaml@2.8.1/node_modules/vite/dist/node/chunks/dep-DBxKXgDP.js:35669:22)
      at async viteTransformMiddleware (file:///Users/matejbystricky/Documents/Work/Matronator%20Brand/projects/gh.nosync/Bez%20na%CC%81zvu/portfolio/node_modules/.pnpm/vite@6.3.5_@types+node@24.3.0_jiti@2.5.1_lightningcss@1.30.1_yaml@2.8.1/node_modules/vite/dist/node/chunks/dep-DBxKXgDP.js:37250:24)
```
