### ISSUE TITLE
injectRoute entrypoint containing a dot folder prevents build

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#10294]
### Astro Info

```block
Astro                    v4.4.8
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             custom
```

### Describe the Bug

When specifying a path like `./.astro/index.astro` for injectRoute's entrypoint, astro build fails with this error message:
```
17:19:12 [ERROR] [vite] x Build failed in 535ms
[astro:build] The argument 'path' must be a string or Uint8Array without null bytes. Received '/home/projects/github-poqvts/\x00@astro-page:@_@astro/tsconfig.json'
file: @astro-page:@_@astro/index.astro
  Stack trace:
    at __node_internal_ (https://githubpoqvts-1ybi.w-credentialless-staticblitz.com/blitz.c9a8a620.js:36:5406)
    at __node_internal_ (https://githubpoqvts-1ybi.w-credentialless-staticblitz.com/blitz.c9a8a620.js:67:2994)
    at __node_internal_ (https://githubpoqvts-1ybi.w-credentialless-staticblitz.com/blitz.c9a8a620.js:67:5771)
    at findUp (file:///home/projects/github-poqvts/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:13847:18)
    at parse$f (file:///home/projects/github-poqvts/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:14059:59)
    at async Module.transformWithEsbuild (file:///home/projects/github-poqvts/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:14615:36)
    at async Object.transform (file:///home/projects/github-poqvts/node_modules/astro/dist/vite-plugin-astro/index.js:154:31)
    at async ModuleLoader.addModuleSource (file:///home/projects/github-poqvts/node_modules/rollup/dist/es/shared/node-entry.js:18722:36)
```
It works fine in dev mode. I suspect the same issue for absolute paths

### What's the expected result?

It should build

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-poqvts?file=astro.config.mjs

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Issue is likely around here https://github.com/withastro/astro/blob/4b6e2fb69b241c982c82a2f13d603b2057c345af/packages/astro/src/vite-plugin-integrations-container/index.ts#L27

**Comment by Fryuni** [comment]
I think for relative paths it should not start with `./`. Just `.astro/...`

**Comment by florian-lefebvre** [comment]
i think it's okay. fyi i have the same error with absolute

**Comment by BryceRussell** [comment]
I think it is this function: https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/plugins/util.ts#L53

It replaces any instances of `.astro` in the path with `@_@astro`, including directory names

**Comment by florian-lefebvre** [comment]
Sounds very likely!
