### ISSUE TITLE
Redirects crash in SSR with certain characters in URL

### ISSUE THREAD

**Issue by gambolputty** [withastro/astro#10404]
### Astro Info

```block
Astro                    v4.5.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

I'm using the node adapter and configured "redirects" in my `astro.config.mjs`:

```js
redirects: {
  '/sample/[slug]': '/samples/[slug]',
},
```

If `slug` contains a certain character, the route crashes in development and production.

In this case, `slug` contained `’` (a German apostrophe):

## Route
 `/sample/Las Vegas’`

## Error
```bash
TypeError: Cannot convert argument to a ByteString because the character at index 18 has a value of 8217 which is greater than 255.
    at a.converters.ByteString (https://githubbttmvn-tb1k.w-credentialless-staticblitz.com/blitz.dc33e3af.js:194:28157)
    at Object.record<ByteString, ByteString> (https://githubbttmvn-tb1k.w-credentialless-staticblitz.com/blitz.dc33e3af.js:194:26639)
    at m.converters.HeadersInit (https://githubbttmvn-tb1k.w-credentialless-staticblitz.com/blitz.dc33e3af.js:194:35703)
    at Object.ResponseInit (https://githubbttmvn-tb1k.w-credentialless-staticblitz.com/blitz.dc33e3af.js:194:27549)
    at new $ (https://githubbttmvn-tb1k.w-credentialless-staticblitz.com/blitz.dc33e3af.js:194:77432)
    at Module.renderRedirect (file:///home/projects/github-bttmvn/node_modules/astro/dist/core/redirects/render.js:22:10)
    at eval (file:///home/projects/github-bttmvn/node_modules/astro/dist/core/render-context.js:93:195)
    at next (file:///home/projects/github-bttmvn/node_modules/astro/dist/core/middleware/callMiddleware.js:22:31)
    at eval (file:///home/projects/github-bttmvn/node_modules/astro/dist/core/middleware/sequence.js:34:18)
    at onRequest (noop-middleware:3:45)
```

It crashes as well with en-dash (`–`) and other quote marks (_Guillemets_, such as `»` and `«`). Didn't test it further with other characters.

### What's the expected result?

It should not throw an error. When I open the URL I'm redirecting to in my Astro config, I get no error as well: `/samples/Las Vegas’` ("samples" instead of "sample").

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bttmvn?file=src%2Fpages%2Fsamples%2F%5Bslug%5D.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mingjunlu** [comment]
@lilnasy Oops! Sorry I didn't notice that you already submitted a PR
