### ISSUE TITLE
Cannot read properties of undefined (reading 'Symbol(drizzle:Columns)')

### ISSUE THREAD

**Issue by Jak2k** [withastro/astro#10458]
### Astro Info

```block
Astro                    v4.5.4
Node                     v21.7.1
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/vercel
Integrations             unocss
                         astro-sitemap
                         @astrojs/vue
                         @astrojs/mdx
                         astro:db
                         @astrojs/db/file-url
                         astro-icon
```

### Describe the Bug

```typescript
// src/db/config.ts
import { defineDb, defineTable, column } from 'astro:db';

const Status = defineTable({
    columns: {
        id: column.number({ primaryKey: true }),
        text: column.text(),
        url: column.text(),
    }
})

export default defineDb({
    tables: {
        Status,
    },
})
```

```astro
---
import { db, Status } from "astro:db";

const statuses = await db.select().from(Status);
---
  <ul>
    {
      statuses.map((post) => (
        <li>
            {post.text}
        </li>
      ))
    }
  </ul>

```

Stacktrace:
```
TypeError: Cannot read properties of undefined (reading 'Symbol(drizzle:Columns)')
    at getTableColumns (file:///home/jak2k/Projects/website/node_modules/.pnpm/drizzle-orm@0.29.5_@libsql+client@0.5.6/node_modules/drizzle-orm/utils.js:108:15)
    at SQLiteSelectBuilder.from (file:///home/jak2k/Projects/website/node_modules/.pnpm/drizzle-orm@0.29.5_@libsql+client@0.5.6/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:45:16)
    at /home/jak2k/Projects/website/src/pages/status/index.astro:5:36
    at index (/home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/runtime/server/astro-component.js:18:12)
    at callComponentAsTemplateResultOrResponse (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/runtime/server/render/astro/render.js:87:31)
    at renderToAsyncIterable (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/runtime/server/render/astro/render.js:115:32)
    at renderPage (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/runtime/server/render/page.js:31:30)
    at Response.status (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/core/render-context.js:80:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callMiddleware (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/core/middleware/callMiddleware.js:11:10)
    at async RenderContext.render (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/core/render-context.js:96:22)
    at async handleRoute (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/vite-plugin-astro-server/route.js:212:18)
    at async run (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/vite-plugin-astro-server/request.js:42:14)
    at async runWithErrorHandling (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/vite-plugin-astro-server/controller.js:64:5)
    at async handleRequest (file:///home/jak2k/Projects/website/node_modules/.pnpm/astro@4.5.4_typescript@5.4.2/node_modules/astro/dist/vite-plugin-astro-server/request.js:36:3)
```

### What's the expected result?

List of statuses should render without astro crashing.

### Link to Minimal Reproducible Example

`npx astro add db` crashes in stackbliz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This seems to work just fine for me: https://stackblitz.com/edit/github-4wcynv?file=src%2Fpages%2Findex.astro

**Comment by Jak2k** [comment]
Maybe I could force update everything again.

**Comment by jasonhale** [comment]
@Jak2k - I had the same issue and fixed my issue locally.

Problem is that your file `src/db/config.ts` should be at root level, outside the /src folder (ie. `db/config.ts`)

**Comment by Jak2k** [comment]
That's weird. Aren't these technically source files?

**Comment by jasonhale** [comment]
> That's weird. Aren't these technically source files?

I feel they'd be considered more _configuration_ files than _application source_ files.  Which makes sense considering this is a database setup and configuration, rather than application source code - also why it made more sense to me after I moved my `_root_/src/db/**` files to `_root_/db/`.

**Comment by proweb** [comment]
> Problem is that your file `src/db/config.ts` should be at root level, outside the /src folder (ie. `db/config.ts`)

Thanks man
