### ISSUE TITLE
Expected ";" but found "const" - typescript transformer

### ISSUE THREAD

**Issue by bartlomiejzuber** [withastro/astro#10663]
### Astro Info

```block
Astro                    v4.0.6
Node                     v20.9.0
System                   Mac
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

Code below fails with this error: "Expected ";" but found "const""

`index.astro`
```typescript
---
import { Urls } from "@web/const";
import personSmilingThroughWindowImage from "/images/people-photos/person-smiling-through-window.jpg";
import smilingAwayFromPhoneImage from "/images/people-photos/smiling-away-from-phone.jpg";

export const previewCards = [
  {
    title: "About us",
    text: "lorem ipsum",
    cta: "submit",
    image: smilingAwayFromPhoneImage,
    alt: "Person smiling away from their phone",
    path: Urls.AboutUs,
  },
  {
    title: "For our customers",
    text: "lorem ipsum",
    cta: "submit",
    image: personSmilingThroughWindowImage,
    alt: "Person smiling through window",
    path: Urls.AboutUsOurCustomers,
  }] as const;
---
<div>test</div>
```

For context this is how `Urls` object looks like.

`site-urls.ts`
```typescript
export const Urls = {
  Homepage: "/",
  AboutUs: "/about-us/",
  AboutUsOurCustomers: "/about-us/our-customers/",
} as const;
```

Here's the stack trace:
```
Error: Transform failed with 1 error:
index.astro:61:4: ERROR: Expected ";" but found "const"
    at failureErrorWithLog (\node_modules\.pnpm\esbuild@0.19.10\node_modules\esbuild\lib\main.js:1650:15)
    at \node_modules\.pnpm\esbuild@0.19.10\node_modules\esbuild\lib\main.js:848:29
    at responseCallbacks.<computed> (\node_modules\.pnpm\esbuild@0.19.10\node_modules\esbuild\lib\main.js:703:9)
    at handleIncomingPacket (\node_modules\.pnpm\esbuild@0.19.10\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (\node_modules\.pnpm\esbuild@0.19.10\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
```

### What's the expected result?

Casting to 'const' should work const assertions in TypeScript typically works. I.e. that code shouldn't fail.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uz3jim-u4awnf

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
This is an issue with `esbuild`. I suggest filing an issue there: [link to their playground](https://esbuild.github.io/try/#dAAwLjIwLjIAAGV4cG9ydCBjb25zdCBwcmV2aWV3Q2FyZHMgPSBbCiAgewogICAgdGl0bGU6ICJBYm91dCB1cyIsCiAgICB0ZXh0OiAibG9yZW0gaXBzdW0iLAogICAgY3RhOiAic3VibWl0IiwKICAgIGltYWdlOiBzbWlsaW5nQXdheUZyb21QaG9uZUltYWdlLAogICAgYWx0OiAiUGVyc29uIHNtaWxpbmcgYXdheSBmcm9tIHRoZWlyIHBob25lIiwKICAgIHBhdGg6IFVybHMuQWJvdXRVcywKICB9LAogIHsKICAgIHRpdGxlOiAiRm9yIG91ciBjdXN0b21lcnMiLAogICAgdGV4dDogImxvcmVtIGlwc3VtIiwKICAgIGN0YTogInN1Ym1pdCIsCiAgICBpbWFnZTogcGVyc29uU21pbGluZ1Rocm91Z2hXaW5kb3dJbWFnZSwKICAgIGFsdDogIlBlcnNvbiBzbWlsaW5nIHRocm91Z2ggd2luZG93IiwKICAgIHBhdGg6IFVybHMuQWJvdXRVc091ckN1c3RvbWVycywKICB9XSBhcyBjb25zdDs)
