### ISSUE TITLE
Astro cannot load Sharp

### ISSUE THREAD

**Issue by jcf** [withastro/astro#10699]
### Astro Info

```
Astro                    v4.5.16
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

```
Could not process image request: MissingSharp: Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
    at loadSharp (/Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/assets/services/sharp.js:19:11)
    at async Object.transform (/Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/assets/services/sharp.js:32:15)
    at async Module.GET (/Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/assets/endpoint/node.js:94:30)
    at async renderEndpoint (file:///Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/runtime/server/endpoint.js:34:20)
    at async callMiddleware (file:///Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/core/middleware/callMiddleware.js:11:10)
    at async RenderContext.render (file:///Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/core/render-context.js:110:22)
    at async handleRoute (file:///Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/vite-plugin-astro-server/route.js:212:18)
    at async run (file:///Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:14)
    at async runWithErrorHandling (file:///Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/vite-plugin-astro-server/controller.js:64:5)
    at async handleRequest (file:///Users/jcf/code/astro-pnpm-sharp/node_modules/.pnpm/astro@4.5.16_typescript@5.4.4/node_modules/astro/dist/vite-plugin-astro-server/request.js:34:3) {
  loc: undefined,
  title: 'Could not find Sharp.',
  hint: "See Sharp's installation instructions for more information: https://sharp.pixelplumbing.com/install. If you are not relying on `astro:assets` to optimize, transform, or process any images, you can configure a passthrough image service instead of installing Sharp. See https://docs.astro.build/en/reference/errors/missing-sharp for more information.\n" +
    '\n' +
    'See https://docs.astro.build/en/guides/images/#default-image-service for more information on how to migrate to another image service.',
  frame: undefined,
  type: 'AstroError'
}
```

### What's the expected result?

If I can load Sharp via `node`, I'd expect Astro to be able to load it, too.

https://github.com/withastro/astro/issues/9268#issuecomment-1842905760

### Link to Minimal Reproducible Example

https://github.com/jcf/astro-pnpm-sharp

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jcf** [comment]
It looks like I'm not the only one who's run into this: https://github.com/withastro/astro/issues/9268#issuecomment-1842905760

**Comment by jcf** [comment]
I've solved the issue with a workaround. One has to be sure the version of `libtool` that's picked up is the built-in version that comes with macOS. If you have a different version, Sharp may fail to build.

https://github.com/jcf/astro-pnpm-sharp?tab=readme-ov-file#libtool-unrecognized-option--static-when-building

**Comment by jcf** [comment]
I've fixed this in the repro repository but the problem persists in the original repository.
