### ISSUE TITLE
Astro DB with Vercel Serverless

### ISSUE THREAD

**Issue by pseudovar** [withastro/astro#10781]
### Astro Info

```block
Astro                    v4.6.1
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/react
                         @astrojs/partytown
                         astro:db
                         @astrojs/db/file-url
                         astro-icon
```

### Describe the Bug

I've been using AstroDB for local development and it's been exactly what I needed.

However, I am now looking to run an environment in Vercel, and there seems to be an issue with connecting to Astro Studio.

I can deploy the full code base, but when I access route that involves the DB, I get errors. I have both pages and pages/api routes that rely on the db connection.

```23:46:49 [ERROR] Error: Failed to connect to database: `/vercel/path0/.astro/content.db`
    at new Database (/var/task/vercel/path0/node_modules/libsql/index.js:72:17)
    at _createClient (file:///var/task/vercel/path0/node_modules/@libsql/client/lib-esm/sqlite3.js:39:16)
    at _createClient (file:///var/task/vercel/path0/node_modules/@libsql/client/lib-esm/node.js:21:16)
    at createClient (file:///var/task/vercel/path0/node_modules/@libsql/client/lib-esm/node.js:11:12)
    at createLocalDatabaseClient (file:///var/task/vercel/path0/node_modules/@astrojs/db/dist/runtime/db-client.js:9:18)
    at file:///var/task/vercel/path0/.vercel/output/_functions/chunks/pages/brand_BwHfBG4B.mjs:6:14
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async NodeApp.render (file:///var/task/vercel/path0/.vercel/output/_functions/entry.mjs:1651:45)
    at async Server.handler (file:///var/task/vercel/path0/.vercel/output/_functions/entry.mjs:2011:25)```

It looks as though it's trying to connect to a file version of the db on Vercel, instead of using the token and connecting to Astro Studio, but I'm not sure 🤷

To confirm:
- AstroDB works locally `astro dev`
- Astro Studio works locally `astro dev --remote`
- Project is hosted in GitHub, automatically deploying to Vercel
- Vercel has the `ASTRO_STUDIO_APP_TOKEN` set in environment variables
- The rest of the site works, just nothing to do with DB

What I've tried:
- Creating a new Astro Studio Token
- Manual build command in Vercel `astro build --remote` | `astro check && ASTRO_STUDIO_APP_TOKEN=token astro build --remote`
- Updating all too the latest

Similar issue posted in [Discord](https://discord.com/channels/830184174198718474/1220688013751877703) by another user.

### What's the expected result?

It's expected that simply running a deployment on Vercel with the Environment variable setup would connect to Astro Studio and work as designed.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pseudovar** [comment]
I will close this issue. I've been debugging, and it seems to be working on a single route now through Vercel. Unfortunately, as it all works locally, it's hard to debug why there is a problem when deploying to Vercel.
