### ISSUE TITLE
SVG rendering error - "unsupported file type"

### ISSUE THREAD

**Issue by HiDeoo** [withastro/astro#10847]
### Astro Info

```block
Astro                    v4.6.3
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

_This issue was initially found in the Starlight repository through another [issue](https://github.com/withastro/starlight/issues/1771) but I'm posting a new issue here as the original issue contained other issues as well and to also include a smaller reproduction case._ cc @OliverSpeir @TheGreatAxios 

Rendering _some_ SVGs (the repro link includes an example of such SVG file) using Astro's Image API, e.g. in some basic Markdown, can trigger an error.

```md
# Broken

![An SVG file](../assets/my-file.svg)
```

The error is:

```
TypeError: unsupported file type: undefined
    at Module.lookup (file:///home/projects/github-f2xprf/node_modules/astro/dist/assets/utils/vendor/image-size/lookup.js:34:9)
    at Module.imageMetadata (file:///home/projects/github-f2xprf/node_modules/astro/dist/assets/utils/metadata.js:19:53)
    at Module.emitESMImage (file:///home/projects/github-f2xprf/node_modules/astro/dist/assets/utils/emitAsset.js:32:43)
    at async Context.load (file:///home/projects/github-f2xprf/node_modules/astro/dist/assets/vite-plugin-assets.js:187:33)
    at async Object.load (file:///home/projects/github-f2xprf/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:51153:32)
    at async loadAndTransform (file:///home/projects/github-f2xprf/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:53857:24)
```

My initial suspicion would be this [`image-size` error](https://github.com/image-size/image-size/issues/397) as `image-size` is now [vendored](https://github.com/withastro/astro/pull/9976) with Astro since version `4.4.0`.

Downgrading Astro to version `4.3.6` fixes the issue and the SVG is rendered correctly.

### What's the expected result?

The SVG should be rendered correctly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-f2xprf?file=src%2Fpages%2Fbroken.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Yeah, the SVG in the repro is weird and it seems like `image-size` doesn't detect it correctly.

**Comment by Princesseuh** [comment]
Closing in favour of the upstream issue, in the meantime I'd suggest cleaning the SVG of the weird metadata.

**Comment by widcardw** [comment]
I have also encountered this problem. However, it does not raise `unsupported type`. Instead, it raises `NoImageMetadata`. Here is the reproduction https://stackblitz.com/edit/withastro-astro-ephpw9
