### ISSUE TITLE
Image support on newer linux distributions

### ISSUE THREAD

**Issue by kaliatech** [withastro/astro#10966]
### Astro Info

```block
Astro                    v4.7.1
Node                     v20.12.2
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

Running `astro build`  on newer linux distibutions (`Amazon Linux 2` or `Ubuntu 22.04`) results in errors like this:

```
[ERROR] [vite] x Build failed in 653ms
[astro:assets:esm] Could not load ~/experiments/website/src/assets/abstract3.webp (imported by src/pages/index.astro): unsupported file type: undefined
  Stack trace:
    at lookup (file:///~/experiments/website/node_modules/astro/dist/assets/utils/vendor/image-size/lookup.js:18:9)
    at emitESMImage (file:///~/experiments/website/node_modules/astro/dist/assets/utils/emitAsset.js:17:30)
    at async PluginDriver.hookFirstAndGetPlugin (file:///~/experiments/website/node_modules/rollup/dist/es/shared/node-entry.js:19678:28)
    at async Queue.work (file:///~/experiments/website/node_modules/rollup/dist/es/shared/node-entry.js:19888:32)
```

The error does not occur when building on Windows 11 and it does not occur on Stackblitz. This _might_ simply be a documentation issue.

### What's the expected result?

Expect webp, jpg, etc images to be supported on newer versions of linux.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-d9zjrs?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kaliatech** [comment]
I found that this is not specific to webp images. Jpg images result in same error.

**Comment by kaliatech** [comment]
Never mind.  This was not related to astro. For some reason Git LFS was not working in my linux test environments and so upon checkout in those environments, these were not actual image files.
