### ISSUE TITLE
Could not find Sharp

### ISSUE THREAD

**Issue by andresantiagohellmann** [withastro/astro#10978]
### Astro Info

```block
Astro                    v4.7.1
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          yarn
Output                   server
```

### If this issue only occurs in one browser, which browser is a problem?

chrome, safari

### Describe the Bug

1 - I created a new project with the command "yarn create astro" with the options "include sample files", "typescript", "strict", "install dependencies: yes", "initialize git repository: yes"
2 - I added a folder named images inside the src folder
3 - I added an image with the name "imagem.jpeg" to the folder
4 - I imported the image into my index.hml
5 - I imported the Image component from astro "import { Image } from "astro:assets";"
6 - I added the Image component with "Imagem" "<Image src={Imagem} width={300} height={300} alt="test" />" 
7 - I ran "yarn dev" and it resulted in the error below

Could not process image request: MissingSharp: Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
    at loadSharp (/Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/assets/services/sharp.js:19:11)
    at async Object.transform (/Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/assets/services/sharp.js:32:15)
    at async Module.GET (/Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/assets/endpoint/node.js:94:30)
    at async renderEndpoint (file:///Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/runtime/server/endpoint.js:34:20)
    at async callMiddleware (file:///Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/core/middleware/callMiddleware.js:11:10)
    at async RenderContext.render (file:///Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/core/render-context.js:110:22)
    at async handleRoute (file:///Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/vite-plugin-astro-server/route.js:212:18)
    at async run (file:///Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:14)
    at async runWithErrorHandling (file:///Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/vite-plugin-astro-server/controller.js:64:5)
    at async handleRequest (file:///Users/andrehellmann/Documents/testes/apagar/teste-images/node_modules/astro/dist/vite-plugin-astro-server/request.js:34:3) {
  loc: undefined,
  title: 'Could not find Sharp.',
  hint: "See Sharp's installation instructions for more information: https://sharp.pixelplumbing.com/install. If you are not relying on `astro:assets` to optimize, transform, or process any images, you can configure a passthrough image service instead of installing Sharp. See https://docs.astro.build/en/reference/errors/missing-sharp for more information.\n" +
    '\n' +
    'See https://docs.astro.build/en/guides/images/#default-image-service for more information on how to migrate to another image service.',
  frame: undefined,
  type: 'AstroError'
}
18:57:42 [500] /_image 13ms

### What's the expected result?

I would just like to reproduce the site showing the only imported image.

Comments:
1 - This version that is not working is the latest 4.7.1 I have another project running version "^4.5.5" that is working normally.

2 - Whether running "yarn dev" locally on my mac or running it in github's codspace I get the same error

### Link to Minimal Reproducible Example

https://github.com/andresantiagohellmann/astroimagesharperror

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Yarn 1, which I assume is what you're using, requires specific steps to install Sharp, see https://sharp.pixelplumbing.com/install

We recommend at least updating to Yarn 4, or using another package manager (pnpm is quite popular if you don't want to use npm)

**Comment by andresantiagohellmann** [comment]
> O Yarn 1, que presumo ser o que você está usando, requer etapas específicas para instalar o Sharp, consulte https://sharp.pixelplumbing.com/install
> 
> Recomendamos pelo menos atualizar para o Yarn 4 ou usar outro gerenciador de pacotes (o pnpm é bastante popular se você não quiser usar o npm)

Sorry, my fault was in an environment I don't usually work in.
Thank you very much for your help, I will close the issue.
