### ISSUE TITLE
bcrypt amd bycrptjs error on building process

### ISSUE THREAD

**Issue by eltranseunteurbano** [withastro/astro#11105]
### Astro Info

```block
Astro                    v4.8.1
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @playform/compress
                         @playform/inline
                         @astrojs/sitemap
                         astro-robots-txt
                         astro:db
                         @astrojs/db/file-url
                         @astrojs/alpinejs
```

### Describe the Bug

I implementing the auth feature using Astro and Lucia. I using bycrpt.js to hash the passwords. When I `run npm run build --remote` I got the following error at the last step:

```
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "crypto" imported from "node_modules/bcryptjs/dist/bcrypt.js". Consider disabling ssr.noExternal or remove the built-in dependency.
file: /Users/eltranseunte/work/koko/stc/stc-web/node_modules/bcryptjs/dist/bcrypt.js
  Stack trace:
    at getRollupError (file:///Users/eltranseunte/work/koko/stc/stc-web/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at Object.error (file:///Users/eltranseunte/work/koko/stc/stc-web/node_modules/rollup/dist/es/shared/node-entry.js:19598:20)
    at Object.handler (file:///Users/eltranseunte/work/koko/stc/stc-web/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:67676:19)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/eltranseunte/work/koko/stc/stc-web/node_modules/rollup/dist/es/shared/node-entry.js:19683:28)
    at async ModuleLoader.resolveId (file:///Users/eltranseunte/work/koko/stc/stc-web/node_modules/rollup/dist/es/shared/node-entry.js:18767:15)
```

I tried this on the `astro.config` file:

```
{
  output: "server",
  adapter: cloudflare(),
   vite: {
     ssr: {
         noExternal: ["bcrypt", "bcryptjs", "crypto"],
      },
      resolve: {
        alias: {
          path: "path-browserify",
        }
      },
   ...
  }
```

### What's the expected result?

Get the build process done successfully 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-qx6nya

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Trombach** [comment]
The error message is not ideal, but I believe this is not an Astro issue. Cloudflare workers don't support all node.js apis (https://developers.cloudflare.com/workers/runtime-apis/). I think the recommended way of doing password hashing is to use [`crypto.subtle.deriveKey`](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/#derivekey). I'm assuming the library you're using doesn't do this in the right way, so maybe try and use the `deriveKey` method to hash the password

**Comment by ematipico** [comment]
Closing, because that's expected, as @Trombach perfectly explained.
