### ISSUE TITLE
Container API usage within an Astro project fails to build when using pnpm

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/astro#11128]
### Astro Info

```block
Astro                    v4.9.0
Node                     v20.12.2
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Building a project using the container API fails with the following stacktrace:
```
14:19:09 [ERROR] [vite] x Build failed in 3.64s
[vite]: Rollup failed to resolve import "fsevents" from "/home/otterlord/Documents/Repos/container-repro/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
  Stack trace:
    at viteWarn (file:///home/otterlord/Documents/Repos/container-repro/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:67612:27)
    at onwarn (file:///home/otterlord/Documents/Repos/container-repro/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:67356:13)
    at Object.logger [as onLog] (file:///home/otterlord/Documents/Repos/container-repro/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:20162:9)
    at ModuleLoader.resolveDynamicImport (file:///home/otterlord/Documents/Repos/container-repro/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19162:58)
```
This only occurs when using pnpm. Using npm the project builds correctly.

**NOTE**: The GitHub repo link is intentional, as you'll need to use gitpod/local or something that actually uses pnpm. Stackblitz works fine as it uses something else iirc.

### What's the expected result?

Builds correctly when using pnpm

### Link to Minimal Reproducible Example

https://github.com/TheOtterlord/container-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by 1v3n** [comment]
+1

**Comment by ematipico** [comment]
@1v3n please use the reactions to upvote the issue. No need to add comment if it doesn't any additional information
