### ISSUE TITLE
Astro db build error: Cannot read properties of undefined (reading 'send')

### ISSUE THREAD

**Issue by chunrapeepat** [withastro/astro#11196]
### Astro Info

```block
Astro                    v4.3.2
Node                     v20.14.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/svelte
                         astro-expressive-code
                         @astrojs/mdx
                         astro-meta-tags
                         @astrojs/sitemap
                         @astrojs/react
                         astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

Got the below error message during the build (command: `astro build --remote`)

```
Cannot read properties of undefined (reading 'send')
  Stack trace:
    at getTempViteServer (file:///Users/chunza2542/Documents/learnalgorithm.com/node_modules/@astrojs/db/dist/core/integration/index.js:188:38)
    at async withTakingALongTimeMsg (file:///Users/chunza2542/Documents/learnalgorithm.com/node_modules/astro/dist/integrations/index.js:24:18)
    at async ssrBuild (file:///Users/chunza2542/Documents/learnalgorithm.com/node_modules/astro/dist/core/build/static-build.js:210:34)
    at async AstroBuilder.build (file:///Users/chunza2542/Documents/learnalgorithm.com/node_modules/astro/dist/core/build/index.js:137:48)
    at async build (file:///Users/chunza2542/Documents/learnalgorithm.com/node_modules/astro/dist/core/build/index.js:47:3)
```

The `tempViteServer.hot` is `undefined` during executing `astro:build:setup` hook

https://github.com/withastro/astro/blob/48d53094cdbbcd4363d6c77aac13161c5cde5064/packages/db/src/core/integration/index.ts#L220-L239

### What's the expected result?

Build with no error

### Link to Minimal Reproducible Example

none

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by chunrapeepat** [comment]
remove `node_modules` and reinstall solved the problem.
