### ISSUE TITLE
Error in DB push

### ISSUE THREAD

**Issue by javimata** [withastro/astro#11229]
### Astro Info

```block
Astro                    v4.7.0
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
                         @astrojs/tailwind
                         astro-auth
                         astro:db
                         @astrojs/db/file-url
                         astro-icon
```

### If this issue only occurs in one browser, which browser is a problem?

cli

### Describe the Bug

I have this schema but i receive a error

`
Database schema is out of date.
Pushing database schema updates...
https://db.services.astro.build/db/push failed: 400 Bad Request
{"success":false,"error":{"code":"SQL_QUERY_FAILED","details":"SQLITE_CONSTRAINT: SQLite error: FOREIGN KEY constraint failed"}}
/db/push fetch failed: 400 Bad Request
`

```javascript
import { column, defineDb } from 'astro:db'

const Users = {
	columns: {
		userName: column.text(),
		userEmail: column.text({ primaryKey: true }),
		userImage: column.text({ optional: true }),
		createdAt: column.date({ default: new Date() }),
		lastVisit: column.date({ default: new Date() }),
		accountType: column.text({ default: 'free' }),
		accountProvider: column.text({ default: 'email' }),
		userPassword: column.text({ optional: true }),
		userStatus: column.number({ default: 1 }),
		credits: column.number({ default: 5 }),
		notes: column.text({ optional: true })
	}
}

const Recipes = {
	columns: {
		id: column.number({ primaryKey: true }),
		prompt: column.text(),
		tokens: column.text(),
		result: column.text(),
		user: column.text({ references: () => Users.columns.userEmail }),
		createdAt: column.date({ default: new Date() }),
		favorite: column.boolean({ default: false }),
		rating: column.number({ default: 0 }),
		status: column.number({ default: 1 }),
		modelVersion: column.text(),
		slug: column.text({ unique: true })
	}
}

const Settings = {
	columns: {
		id: column.number({ primaryKey: true }),
		user: column.text({ references: () => Users.columns.userEmail }),
		languageResponse: column.text({ default: 'spanish' }),
		measurement: column.text({ default: 'international' }),
		vegetarian: column.boolean({ default: false }),
		vegan: column.boolean({ default: false }),
		keto: column.boolean({ default: false }),
		sugarfree: column.boolean({ default: false }),
		glutenfree: column.boolean({ default: false }),
		notificationsEmail: column.boolean({ default: true }),
		notificationsPush: column.boolean({ default: true }),
		theme: column.text({ default: 'default' })
	}
}

export default defineDb({
	tables: {
		Users,
		Recipes,
		Settings
	}
})
```

### What's the expected result?

a clean push to studio

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rjvwlr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by javimata** [comment]
When the DB is empty this schema work fine, when the DB have info this crash

**Comment by javimata** [comment]
> Did you add or remove any columns when this happened?

I add a new column, i use --force-reset and my db is erased and add the new columns, but i need do --forcec-reset each that i need do a push, and i don't wanna erase my db info in each update

**Comment by matthewp** [comment]
Which is the new column you added that triggered this problem?

**Comment by javimata** [comment]
> Which is the new column you added that triggered this problem?

The last one is un Users the column notes, now i'm adding 2 new tables and receive the same error, always need put --force-reset, this is not functional for me

**Comment by jonaspm** [comment]
I get the same issue even with --force-push

```
bunx astro db push --force-reset
Database schema is out of date.
√ Reset your database? All of your data will be erased and your schema created from scratch. ... yes
Force-pushing to the database. All existing data will be erased.
Pushing database schema updates...
SQLITE_CONSTRAINT: SQLite error: FOREIGN KEY constraint failed
  Location:
    C:\Users\jonaspm\Development\repos\sorteos.click\node_modules\@libsql\client\lib-esm\hrana.js:268:16      
  Stack trace:
    at mapHranaError (file:///C:/Users/jonaspm/Development/repos/sorteos.click/node_modules/@libsql/client/lib-esm/hrana.js:268:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async LibSQLSession.transaction (file:///C:/Users/jonaspm/Development/repos/sorteos.click/node_modules/drizzle-orm/libsql/session.js:53:22)
    at async cmd (file:///C:/Users/jonaspm/Development/repos/sorteos.click/node_modules/@astrojs/db/dist/core/cli/commands/push/index.js:61:5)
    at async db (file:///C:/Users/jonaspm/Development/repos/sorteos.click/node_modules/astro/dist/cli/db/index.js:23:3)
  Caused by:
  SQLite error: FOREIGN KEY constraint failed
```

**Comment by RobbieTheWagner** [comment]
I'm hitting this too. I think that `--force-reset` should probably forcibly delete everything and ignore constraints.

**Comment by mrestrepoj10** [comment]
Hello! Any updates or workaround about this ? Thanks in advance!

**Comment by ascorbic** [comment]
I'm closing this because Astro Studio has been sunset. If you are still having issues with a different DB, please open a new issue.

**Comment by alex-campos-calvo** [comment]
This happens without studio, im connecting astro with turso db.

I have a table with data, and cannot add a new column without the --force-reset parameter.

¿Is it possible to alter my bbdd in turso and the scheme separately?
