### ISSUE TITLE
Duplicated `C:\` in import paths on Windows

### ISSUE THREAD

**Issue by wojtekmaj** [withastro/astro#11399]
### Astro Info

```block
Astro                    v4.11.3
Node                     v22.3.0
System                   Windows (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/netlify
Integrations             @astrojs/react
                         @astrojs/starlight
```

### If this issue only occurs in one browser, which browser is a problem?

n/a

### Describe the Bug

Upon cloning https://github.com/biomejs/website, installing using `pnpm i` and starting dev server with `pnpm run start` on Windows I was met with the following error:

```
  X [ERROR] ENOENT: no such file or directory, open 'C:\C:\Users\wojte\Projekty\Open%20source%20projects\biomejs-website\src\frontend-scripts\hover.ts' [plugin vite:dep-scan]

    script:C:/Users/wojte/Projekty/Open source projects/biomejs-website/src/components/starlight/Hero.astro?id=0:2:9:
      2 │   import "@/frontend-scripts/hover.ts";
        ╵          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at failureErrorWithLog (C:\Users\wojte\Projekty\Open source projects\biomejs-website\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1472:15)
    at C:\Users\wojte\Projekty\Open source projects\biomejs-website\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:945:25
    at runOnEndCallbacks (C:\Users\wojte\Projekty\Open source projects\biomejs-website\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1315:45)
    at buildResponseToResult (C:\Users\wojte\Projekty\Open source projects\biomejs-website\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:943:7)
    at C:\Users\wojte\Projekty\Open source projects\biomejs-website\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:955:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (C:\Users\wojte\Projekty\Open source projects\biomejs-website\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:954:54)
    at handleRequest (C:\Users\wojte\Projekty\Open source projects\biomejs-website\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:647:17)
    at handleIncomingPacket (C:\Users\wojte\Projekty\Open source projects\biomejs-website\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:672:7)
    at Socket.readFromStdout (C:\Users\wojte\Projekty\Open source projects\biomejs-website\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:600:7)
```

Notice how `C:\` in the path is duplicated. It should be C:\Users\... instead of C:\C:\Users\...

I double checked the path and the following file definitely exists:

```
C:\Users\wojte\Projekty\Open%20source%20projects\biomejs-website\src\frontend-scripts\hover.ts
```

### What's the expected result?

Dev server to resolve the paths on Windows and start up successfully.

### Link to Minimal Reproducible Example

https://github.com/biomejs/website

Sorry for no minimal reproducible example (yet), it's literally the first time I encountered Astro and I have absolutely no idea what I'm doing. If I get time, I'll try to cut the excess from biomejs/website, but I figured maybe raising an issue first wouldn't hurt, perhaps to someone more familar with Astro the issue would be obvious.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Please reduce this down further and submit a new issue. We can't debug a full app as there's many things (like integrations) that can cause it to fail.
