### ISSUE TITLE
Poor error message in production build when client directive used on astro component

### ISSUE THREAD

**Issue by felixhuttmann** [withastro/astro#11623]
### Astro Info

```block
Astro                    v4.13.1
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

Directives like `client:idle` should only be used on framework components. When a client directive is used on an astro component, the command `npm run dev` print a helpful error message:
```
You are attempting to render <Header client:idle />, but Header is an Astro component. Astro components do not render in the client and should not have a hydration directive. Please use a framework component for client rendering.
```
However, the site renders normally in dev mode, and the developer can easily overlook this error message in the dev mode terminal.

In contrast, the command `npm run build` prints a confusing error message in this case:
```
 building client (vite)
11:04:29 [vite] ✓ 0 modules transformed.
11:04:29 [ERROR] [vite] x Build failed in 5ms
[astro:build] The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '$REPO_ROOT/\x00astro-entry:$REPO_ROOT/src/components/tsconfig.json'
file: astro-entry:$REPO_ROOT/src/components/Header.astro
  Stack trace:
    at Object.stat (node:fs:1581:10)
    at find (file://$REPO_ROOT/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:18324:2)
    at async loadTsconfigJsonForFile (file://$REPO_ROOT/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:19372:20)
    at async compileAstro (file://$REPO_ROOT/node_modules/astro/dist/vite-plugin-astro/compile.js:14:21)
    at async transform (file://$REPO_ROOT/node_modules/rollup/dist/es/shared/node-entry.js:18787:16)
```
Developers will usually run only `astro build` in the CI pipeline.

Enough people have stumbled over this for there to be a stackoverflow question for it: https://stackoverflow.com/questions/77508923/the-argument-path-must-be-a-string-uint8array-or-url-without-null-bytes-rec

### What's the expected result?

The same helpful error message that is printed in dev mode should also be printed when running `npm run build`.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Firaenix** [comment]
Thank god for this issue!
I was chasing this error for ages.

Would be great to have this sorted

**Comment by rgant** [comment]
Added a backlink to this issue to the StackOverflow question as that is showing up first when I searched for this error. It would be very nice if the error message was the same for `astro build`.

**Comment by quentin-decre** [comment]
Thanks, happy to have found your issue !

**Comment by Odogwudozilla** [comment]
This helps!!!
