### ISSUE TITLE
Astro dev server not running with bun

### ISSUE THREAD

**Issue by tolubori07** [withastro/astro#11668]
### Astro Info

```block
Astro                    v4.13.3
Node                     v20.6.0
System                   macOS (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I'm using bun as my pm and when i try to start an astro dev server(bun run dev) it fails every time with the following error: 
`/NEA/test/node_modules/@babel/core/lib/index.js:7
Object.defineProperty(exports, "File", {
       ^

TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/Users/moshoodbello/Coding/NEA/test/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/moshoodbello/Coding/NEA/test/node_modules/@babel/core/lib/config/helpers/config-api.js:16:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.6.0
error: script "dev" exited with code 1`
The issue started randomly when i tried to make changes to an astro project i had and now no astro project runs. I've uninstalled bun completely and re-installed it, i've also updated all packages that can be updated in the project

### What's the expected result?

I expect to start a dev server.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=README.md&on=stackblitz
Not neccessary as this is on my machine

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
We don't officially support bun, and since bun is a drop-replacement for Node.js, you should file an issue at their repository
