### ISSUE TITLE
Astro actions cookies broken, too large sometimes

### ISSUE THREAD

**Issue by michaelpayne02** [withastro/astro#11675]
### Astro Info

```block
Astro                    v4.13.3
Node                     v20.9.0
System                   macOS (x64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/sitemap
                         pagefind
                         @astrojs/mdx
                         @astrojs/tailwind
```

### Describe the Bug

When using astro form actions with more than two or three fields being validated, the large url-encoded cookie becomes too big to store in the browser and exceeds the 4096 character limit. It also contains an entire stacktrace. This means the Astro.getActionResult() does not return anything on the source/fallback page (the one in the Referrer header with the original form).

<img width="570" alt="Screenshot 2024-08-12 at 12 10 16 AM" src="https://github.com/user-attachments/assets/b4cc0b01-9885-49b9-8271-888c3fd9f9f2">

I also get strange 'deleted' cookies that break the entire project permenantly until the stackblitz is restarted.

<img width="703" alt="Screenshot 2024-08-12 at 12 43 04 AM" src="https://github.com/user-attachments/assets/abf2bccf-932f-4410-a45e-40e34e75dc8c">

And this associated stacktrace:
```
SyntaxError: Unexpected token 'd', "deleted" is not valid JSON
    at JSON.parse (<anonymous>)
    at AstroCookie.json (file:///home/projects/github-g63nyt-zhjdjc/node_modules/astro/dist/core/cookies/cookies.js:29:17)
    at eval (/home/projects/github-g63nyt-zhjdjc/node_modules/astro/dist/actions/runtime/middleware.js:23:103)
    at applyHandle (/home/projects/github-g63nyt-zhjdjc/node_modules/astro/dist/core/middleware/sequence.js:20:22)
    at eval (/home/projects/github-g63nyt-zhjdjc/node_modules/astro/dist/core/middleware/sequence.js:17:12)
    at applyHandle (file:///home/projects/github-g63nyt-zhjdjc/node_modules/astro/dist/core/middleware/sequence.js:31:22)
    at eval (file:///home/projects/github-g63nyt-zhjdjc/node_modules/astro/dist/core/middleware/sequence.js:50:18)
    at payload (file:///home/projects/github-g63nyt-zhjdjc/node_modules/astro/dist/i18n/middleware.js:26:34)
    at applyHandle (file:///home/projects/github-g63nyt-zhjdjc/node_modules/astro/dist/core/middleware/sequence.js:31:22)
    at eval (file:///home/projects/github-g63nyt-zhjdjc/node_modules/astro/dist/core/middleware/sequence.js:28:12)
```

### What's the expected result?

The client should be correctly redirected to the original page with the correct cookies/error messages. It should also work if both the confirmation page needs data and the originating page needs errors. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-g63nyt-zhjdjc?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for reporting! We can probably find a smaller encoding to cut down on size. The `stack` is only present in development as well, so we can investigate storing that in-memory or with a separate cookie if needed

**Comment by michaelpayne02** [comment]
Thanks Ben, I appreciate all your work. There's some potential solutions I thought of but I have no idea how feasible they would be to implement:
- Split the action payload inputErrors into multiple cookies for each field, with errors thrown from the handler also separated. This would cut down on the amount of characters needed to URL encode & double-escape some of the backslashes for the deeply-nested payload object. 
- Inject a script into the page that contains the payload. This is probably more complex of a change and would hinder the NoJS experience.

**Comment by gaytanmisael** [comment]
Was this fixed? I'm having problems and I'm running Astro 14.5.4......

**Comment by bholmesdev** [comment]
This should have been fixed in the latest, yes @gaytanmisael. If you're having an problem, feel free to open a new issue with a repro!
