### ISSUE TITLE
Can not import from astro:env/client and astro:env/server

### ISSUE THREAD

**Issue by nemanjam** [withastro/astro#11816]
### Astro Info

```block
Node: `v20.13.1`
Astro: `"astro": "^4.14.4"`
```

### If this issue only occurs in one browser, which browser is a problem?

In Node.js

### Describe the Bug

I am unable to import anything from `'astro:env/client'` and `'astro:env/server'` in any `.ts` or `.astro` file.

```
import { SITE_URL } from 'astro:env/client';
import { NODE_ENV, PREVIEW_MODE } from 'astro:env/server';
```

![image](https://github.com/user-attachments/assets/8bcc664a-84f7-4ad2-8838-10138425966e)

Steps to reproduce:

Clone https://github.com/nemanjam/nemanjam.github.io and checkout this branch `feature/refactor-theme-script`. Run `yarn install`. Then run either `yarn dev`, `yarn sync` or `yarn build`, imports in `src/config.ts` will fail and you will get the following output:

Also try importing in any other `.ts` or `.astro` file imports will fail.

**yarn dev**

```
username@computer3:~/Desktop/nemanjam.github.io$ yarn dev
yarn run v1.22.22
$ astro dev
10:43:15 AM [vite] Pre-transform error: Failed to load url astro:env/client (resolved id: astro:env/client) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
10:43:15 AM [vite] Pre-transform error: Failed to load url astro:env/server (resolved id: astro:env/server) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
10:43:15 AM [vite] Pre-transform error: Failed to load url @/schemas/config (resolved id: @/schemas/config) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
10:43:15 AM [vite] Pre-transform error: Failed to load url @/utils/log (resolved id: @/utils/log) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
10:43:15 AM [vite] Pre-transform error: Failed to load url @/utils/validation (resolved id: @/utils/validation) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
parsed PROCESS_ENV:

├─ NODE_ENV: development
├─ PREVIEW_MODE: false
└─ SITE_URL: http://localhost:3000
10:43:15 AM [vite] Error when evaluating SSR module /src/config.ts: failed to import "astro:env/client"
|- Error: Cannot find module 'astro:env/client' imported from '/home/username/Desktop/nemanjam.github.io/src/config.ts'
    at nodeImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52945:19)
    at ssrImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:22)
    at eval (/home/username/Desktop/nemanjam.github.io/src/config.ts:3:50)
    at instantiateModule (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:11)

10:43:15 AM [vite] Error when evaluating SSR module /src/libs/integrations/sitemap.ts: failed to import "astro:env/client"
|- Error: Cannot find module 'astro:env/client' imported from '/home/username/Desktop/nemanjam.github.io/src/config.ts'
    at nodeImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52945:19)
    at ssrImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:22)
    at eval (/home/username/Desktop/nemanjam.github.io/src/config.ts:3:50)
    at instantiateModule (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:11)

10:43:15 AM [vite] Error when evaluating SSR module /home/username/Desktop/nemanjam.github.io/astro.config.ts: failed to import "astro:env/client"
|- Error: Cannot find module 'astro:env/client' imported from '/home/username/Desktop/nemanjam.github.io/src/config.ts'
    at nodeImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52945:19)
    at ssrImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:22)
    at eval (/home/username/Desktop/nemanjam.github.io/src/config.ts:3:50)
    at instantiateModule (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:11)

[astro] Unable to load your Astro config

Cannot find module 'astro:env/client' imported from '/home/username/Desktop/nemanjam.github.io/src/config.ts'
  Stack trace:
    at nodeImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52945:19)
    at eval (/home/username/Desktop/nemanjam.github.io/src/config.ts:3:50)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**yarn build**

```
username@computer3:~/Desktop/nemanjam.github.io$ yarn build
yarn run v1.22.22
$ astro build
10:43:46 AM [vite] Pre-transform error: Failed to load url astro:env/client (resolved id: astro:env/client) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
10:43:46 AM [vite] Pre-transform error: Failed to load url astro:env/server (resolved id: astro:env/server) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
10:43:46 AM [vite] Pre-transform error: Failed to load url @/schemas/config (resolved id: @/schemas/config) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
10:43:46 AM [vite] Pre-transform error: Failed to load url @/utils/log (resolved id: @/utils/log) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
10:43:46 AM [vite] Pre-transform error: Failed to load url @/utils/validation (resolved id: @/utils/validation) in /home/username/Desktop/nemanjam.github.io/src/config.ts. Does the file exist?
parsed PROCESS_ENV:

├─ NODE_ENV: production
├─ PREVIEW_MODE: false
└─ SITE_URL: http://localhost:3000
10:43:47 AM [vite] Error when evaluating SSR module /src/config.ts: failed to import "astro:env/client"
|- Error: Cannot find module 'astro:env/client' imported from '/home/username/Desktop/nemanjam.github.io/src/config.ts'
    at nodeImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52945:19)
    at ssrImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:22)
    at eval (/home/username/Desktop/nemanjam.github.io/src/config.ts:3:50)
    at instantiateModule (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:11)

10:43:47 AM [vite] Error when evaluating SSR module /src/libs/integrations/sitemap.ts: failed to import "astro:env/client"
|- Error: Cannot find module 'astro:env/client' imported from '/home/username/Desktop/nemanjam.github.io/src/config.ts'
    at nodeImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52945:19)
    at ssrImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:22)
    at eval (/home/username/Desktop/nemanjam.github.io/src/config.ts:3:50)
    at instantiateModule (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:11)

10:43:47 AM [vite] Error when evaluating SSR module /home/username/Desktop/nemanjam.github.io/astro.config.ts: failed to import "astro:env/client"
|- Error: Cannot find module 'astro:env/client' imported from '/home/username/Desktop/nemanjam.github.io/src/config.ts'
    at nodeImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52945:19)
    at ssrImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:22)
    at eval (/home/username/Desktop/nemanjam.github.io/src/config.ts:3:50)
    at instantiateModule (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:11)

[astro] Unable to load your Astro config

Cannot find module 'astro:env/client' imported from '/home/username/Desktop/nemanjam.github.io/src/config.ts'
  Stack trace:
    at nodeImport (file:///home/username/Desktop/nemanjam.github.io/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52945:19)
    at eval (/home/username/Desktop/nemanjam.github.io/src/config.ts:3:50)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
username@computer3:~/Desktop/nemanjam.github.io$ 
```

### What's the expected result?

Should be able to import typed environment variables from `'astro:env/client'` and `'astro:env/server'`.

### Link to Minimal Reproducible Example

https://github.com/nemanjam/nemanjam.github.io/tree/feature/refactor-theme-script

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nemanjam** [comment]
It wasn't bug in Astro. I found two issues in my code:

1. I imported config file with `'astro:env/client'` and `'astro:env/server'` into one of the files that was again imported back in `astro.config.ts`.
2. I had one server import `'astro:env/server'` into component that has `<script is:inline />`

Although error messages that Astro produced wasn't much obvious and helpful.

**Comment by florian-lefebvre** [comment]
Unfortunately, I don't think we can provide better errors?
1. It ran before Astro kicked off so I believe we can't do anything, unless we do something in loadConfig?
2. We don't process is:inline on purpose so idk if we could do something here

@bluwy wdyt?

**Comment by bluwy** [comment]
Yeah for `astro.config.js` files, we can't support it because it would've been too early. We can technically provide better errors because we're using Vite to load it, and can add a plugin to reject importing any `astro:` modules, however, I hope we can move away from Vite-ism in those config files so I'm not sure if it's a good idea.

For `config.ts` (content collection / layer), they should also work as they use the complete Vite server and config ([even with `astro sync`](https://github.com/withastro/astro/blob/cf65476b27053333cf5a36f6f9f46b794c98dfa2/packages/astro/src/core/sync/index.ts#L169-L179)), so I think that should work. But IIUC the issue at the end is related to `astro.config.js` files, so i think this is mostly unrelated?

**Comment by florian-lefebvre** [comment]
Yeah content/config.ts is fixed. But can we do anything about inline scripts importing `astro:env/*`? I know they're not processed but are we parsing them so we can warn?
