### ISSUE TITLE
Failed to resolve import "...\db\seed.js" from "astro:db". Does the file exist?

### ISSUE THREAD

**Issue by ameneses67** [withastro/astro#11833]
### Astro Info

```block
Astro                    v4.14.5
Node                     v22.6.0
System                   Windows (x64)
Package Manager          pnpm
Output                   server
Adapter                  none
Integrations             astro:db
                         @astrojs/db/file-url
                         @astrojs/tailwind
                         simple-stack-query
                         astro-icon
```

### Describe the Bug

Suddenly this error message began to happen when trying to run "pnpm dev". 

I'm using typescript strict mode, but error message refers to seed.js. I modified seed.ts to seed.js and after that the same error now refers to seed.ts.

Failed to resolve import "D:\amene\Documents\Proyectos\shopping-cart\db\seed.js" from "astro:db". Does the file exist?
at TransformPluginContext._formatError (file:///D:/amene/Documents/Proyectos/shopping-cart/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49159:41)
    at TransformPluginContext.error (file:///D:/amene/Documents/Proyectos/shopping-cart/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49154:16)
    at normalizeUrl (file:///D:/amene/Documents/Proyectos/shopping-cart/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:63936:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async TransformPluginContext.transform (file:///D:/amene/Documents/Proyectos/shopping-cart/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:64218:12)
    at async PluginContainer.transform (file:///D:/amene/Documents/Proyectos/shopping-cart/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49000:18)
    at async loadAndTransform (file:///D:/amene/Documents/Proyectos/shopping-cart/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51822:27)
    at async viteTransformMiddleware (file:///D:/amene/Documents/Proyectos/shopping-cart/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:61776:24)

### What's the expected result?

Being able to run dev server.

### Link to Minimal Reproducible Example

Couldn't reproduce the error.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by snithfferx** [comment]
I think you are calling the DB when is not created, I mean you are importing in any way a file which is trying to access the seed when is not created or trying to query the DB in load event without proper treatment. You should look for a file which is trying to query or access directly the DB from client side.

I have this problem, when I was trying to generate a SKU and MPN for a product, but because I don't want duplicated results, I query the DB for this new SKU, MPN, but I was doing this in load (importing the function file inside the HTML) and on dev, the db is only accessible via Astro server.

I resolve this doing fetch to the TS file, not importing the file.
