### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'nodeType') (Astro + Svelte 5)

### ISSUE THREAD

**Issue by AdrianButler** [withastro/astro#11888]
### Astro Info

```block
Astro                    v4.14.5
Node                     v22.6.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
                         @astrojs/tailwind
                         @astrojs/svelte
                         @playform/compress
                         astro-compressor
```

### Describe the Bug

I am getting this error and my svelte component will not load at all. It works perfectly fine in dev environment but when I build or run preview it stops working and the error is thrown in the console.

faq/:1 [astro-island] Error hydrating /_astro/FaqQuestion.B9nkJrIu.js TypeError: Cannot read properties of null (reading 'nodeType')
    at Ut (template.BZob6Wd_.js:1:8993)
    at G (FaqQuestion.B9nkJrIu.js:1:1234)
    at render.Eek01tEQ.js:1:1270
    at Sn (template.BZob6Wd_.js:1:5360)
    at U (template.BZob6Wd_.js:1:6097)
    at k (template.BZob6Wd_.js:1:2186)
    at bt (template.BZob6Wd_.js:1:2805)
    at render.Eek01tEQ.js:1:1212
    at Sn (template.BZob6Wd_.js:1:5360)
    at U (template.BZob6Wd_.js:1:6097)

### What's the expected result?

The component loads correctly with no errors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1mfzqq?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by NikolaRHristov** [comment]
@AdrianButler https://github.com/PlayForm/Compress/releases/tag/AstroCompress%2Fv2.3.2

**Comment by Princesseuh** [comment]
This does not seems to happens anymore on the latest version of everything. I'll note that the reproduction was using a beta version of Svelte. Please re-open an issue if you can still get this using the latest version of your dependencies!
