### ISSUE TITLE
Astro 5.0.0-alpha > 4 and Vitest fail

### ISSUE THREAD

**Issue by lloydjatkinson** [withastro/astro#12007]
### Astro Info

```block
Astro                    v5.0.0-alpha.6
Node                     v21.6.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             astro-expressive-code
                         @astrojs/tailwind
                         @astrojs/preact
                         @astrojs/react
                         @astrojs/sitemap
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Build

### Describe the Bug

Astro and Vitest fail to run as an exception is thrown. Alpha 4 works, alpha 5 and alpha 6 result in the stack trace.

```ts
/// <reference types="vitest" />
import { getViteConfig } from 'astro/config';

export default getViteConfig({
});

// tried with empty config, same error.

export default getViteConfig({
    test: {
        exclude: [
            '**/node_modules/**',
            '**/integration/playwright/**'
        ],
        environment: 'jsdom', // or 'jsdom', 'node'
        alias: {
            react: 'preact/compat',
            'react-dom': 'preact/compat',
        },
    },
});
```

```json
    "test:unit": "vitest run",
```

```shell
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Startup Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯TypeError: Cannot read properties of undefined (reading 'hrefRoot')
    at createDefaultRoutes (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/astro@5.0.0-alpha.6_@types+node@22.5.5_rollup@4.21.3_typescript@5.6.2/node_modules/astro/dist/core/routing/default.js:19:33)
    at new DevPipeline (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/astro@5.0.0-alpha.6_@types+node@22.5.5_rollup@4.21.3_typescript@5.6.2/node_modules/astro/dist/vite-plugin-astro-server/pipeline.js:16:93)
    at DevPipeline.create (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/astro@5.0.0-alpha.6_@types+node@22.5.5_rollup@4.21.3_typescript@5.6.2/node_modules/astro/dist/vite-plugin-astro-server/pipeline.js:42:22)
    at configureServer (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/astro@5.0.0-alpha.6_@types+node@22.5.5_rollup@4.21.3_typescript@5.6.2/node_modules/astro/dist/vite-plugin-astro-server/plugin.js:29:36)
    at _createServer (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/vite@5.4.5_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:63019:26)
    at async createViteServer (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/vitest@2.1.1_@types+node@22.5.5_@vitest+ui@2.1.1_happy-dom@15.7.4_jsdom@25.0.0/node_modules/vitest/dist/chunks/cli-api.BKkmK21J.js:9050:18)
    at async createVitest (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/vitest@2.1.1_@types+node@22.5.5_@vitest+ui@2.1.1_happy-dom@15.7.4_jsdom@25.0.0/node_modules/vitest/dist/chunks/cli-api.BKkmK21J.js:10851:18)
    at async prepareVitest (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/vitest@2.1.1_@types+node@22.5.5_@vitest+ui@2.1.1_happy-dom@15.7.4_jsdom@25.0.0/node_modules/vitest/dist/chunks/cli-api.BKkmK21J.js:11265:15)
    at async startVitest (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/vitest@2.1.1_@types+node@22.5.5_@vitest+ui@2.1.1_happy-dom@15.7.4_jsdom@25.0.0/node_modules/vitest/dist/chunks/cli-api.BKkmK21J.js:11191:15)
    at async start (file:///C:/Users/Lloyd/source/repos/lloydatkinson.net/node_modules/.pnpm/vitest@2.1.1_@types+node@22.5.5_@vitest+ui@2.1.1_happy-dom@15.7.4_jsdom@25.0.0/node_modules/vitest/dist/chunks/cac.BVmpoFAv.js:1505:17)
```

### What's the expected result?

Vitest runs correctly.

### Link to Minimal Reproducible Example

https://github.com/lloydjatkinson/mre

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks, not sure why Vitest has an issue with this, but I'll take a look.

**Comment by matthewp** [comment]
Fixed in https://github.com/withastro/astro/pull/12009, thanks for the good report!

**Comment by lloydjatkinson** [comment]
Glad to be of help! Thanks for fixing it
