### ISSUE TITLE
MDX processor is not initialized

### ISSUE THREAD

**Issue by LekoArts** [withastro/astro#12015]
### Astro Info

```block
Astro                    v4.15.6
Node                     v20.13.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/netlify
Integrations             @astrojs/sitemap
                         @astrojs/mdx
                         @astrojs/react
```

### Describe the Bug

During a GitHub action run ([logs direct link](https://github.com/LekoArts/portfolio-v3/actions/runs/10898182128/job/30240913094#step:8:42)) I receive the following error:

**MDX processor is not initialized. This is an internal error. Please file an issue.**

```shell
[@mdx-js/rollup] [plugin @mdx-js/rollup] src/pages/about.mdx: MDX processor is not initialized. This is an internal error. Please file an issue.
file: /home/runner/work/portfolio-v3/portfolio-v3/src/pages/about.mdx
  Stack trace:
    at getRollupError (file:///home/runner/work/portfolio-v3/portfolio-v3/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at Object.error (file:///home/runner/work/portfolio-v3/portfolio-v3/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/node-entry.js:19734:20)
    at Object.transform (file:///home/runner/work/portfolio-v3/portfolio-v3/node_modules/.pnpm/@astrojs+mdx@3.1.6_astro@4.15.6_@types+node@20.16.5_rollup@4.21.3_typescript@5.6.2_/node_modules/@astrojs/mdx/dist/vite-plugin-mdx.js:40:21)
    at file:///home/runner/work/portfolio-v3/portfolio-v3/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/node-entry.js:19919:40
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

The page in question has the following contents ([direkt link](https://github.com/LekoArts/portfolio-v3/blob/e51542c0ff6a14ddcf15fa9477ac07c4f8435c64/src/pages/about.mdx)):

```mdx
---
layout: ../layouts/mdx.astro
title: About
description: A little bit about me and what I'm passionate about, what I do at work, and what else I do in my free time. Maybe you're also into photography or hiking?
---

# {frontmatter.title}

<div className="img-left-wrap-text">

![Me in a blue t-shirt in front of the beautiful alpes in austria](../assets/lennart-profile-pic.jpg)

**Hi, I'm Lennart 👋**<br /><br />
I'm a designer turned software engineer from Darmstadt, Germany.
I enjoy working on open source projects & making the web more inclusive through them.<br />
My [OSS code](https://github.com/LekoArts) has been used by thousands of people & I regularly share educational content in the form of [posts](/writing/), [presentations](/appearances/), and [videos](/appearances/).

</div>

## TEXT

TEXT
```

I tried to reproduce the error in https://stackblitz.com/edit/github-rprccr?file=src%2Fpages%2Findex.mdx but wasn't successful.

On my end, this error started happening after updating Astro MDX from 3.1.4 to 3.1.6 and Astro from 4.14.5 to 4.15.6 ([commit](https://github.com/LekoArts/portfolio-v3/commit/3fc687d56954742afc999553a8fa4deea934b698)).

Unfortunately, I can't reproduce this locally. This only happens in GitHub actions at the moment.

### What's the expected result?

Astro site builds successfully.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rprccr?file=src%2Fpages%2Findex.mdx

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by LekoArts** [comment]
Thank you @bluwy, your PR fixed my issue 👍
