### ISSUE TITLE
Node for Astro 5 Beta

### ISSUE THREAD

**Issue by wildfiremedia** [withastro/astro#12061]
### Astro Info

```block
Not able to show, only error after node integration is installed on Asto 5 beta.
```

### If this issue only occurs in one browser, which browser is a problem?

NA

### Describe the Bug

Tried the beta release.
```
npm create astro@latest -- --ref next
```

Testing out with node intergration.
```npx astro install node```

I get:

```
 npx astro dev 
12:08:27 AM [vite] Pre-transform error: Failed to load url @astrojs/node (resolved id: @astrojs/node) in /Users/s/Documents/astro5beta/radiant-remnant/astro.config.mjs. Does the file exist?
12:08:27 AM [vite] Error when evaluating SSR module /Users/s/Documents/astro5beta/radiant-remnant/astro.config.mjs: failed to import "@astrojs/node"
|- Error: Cannot find module '@astrojs/node' imported from '/Users/s/Documents/astro5beta/radiant-remnant/astro.config.mjs'
    at nodeImport (file:///Users/s/Documents/astro5beta/radiant-remnant/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:52989:19)
    at ssrImport (file:///Users/s/Documents/astro5beta/radiant-remnant/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:52856:22)
    at eval (/Users/s/Documents/astro5beta/radiant-remnant/astro.config.mjs:4:37)
    at async instantiateModule (file:///Users/s/Documents/astro5beta/radiant-remnant/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:52914:5)

[astro] Unable to load your Astro config

Cannot find module '@astrojs/node' imported from '/Users/s/Documents/astro5beta/radiant-remnant/astro.config.mjs'
  Stack trace:
    at nodeImport (file:///Users/s/Documents/astro5beta/radiant-remnant/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:52989:19)
    at eval (/Users/s/Documents/astro5beta/radiant-remnant/astro.co
```

astro.config.mjs
```
// @ts-check
import { defineConfig } from 'astro/config';

import node from '@astrojs/node';

// https://astro.build/config
export default defineConfig({
  output: 'server',

  adapter: node({
    mode: 'standalone'
  })
});
```

### What's the expected result?

It should run.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You need to install the beta version of the Node adapter.
