### ISSUE TITLE
Errors thrown from components return 200 and are uncatchable in middleware

### ISSUE THREAD

**Issue by MatthewLymer** [withastro/astro#12383]
### Astro Info

```block
Astro                    v4.16.9
Node                     v20.13.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             MyIntegration
```

### Describe the Bug

When a component throws an error in its frontmatter, the error is not catchable by middleware.  

Furthermore, the server responds with an "Internal server error" text message, but with a `200 OK` status code.

Comparatively, throwing an error on a `*.astro` page's frontmatter _is_ catchable within middleware, and returns a `500 Internal Server Error` message as expected.

This happens with both the dev server _and_ when using the node adapter.

## The "good" scenario (page fails with 500)
The "good" scenario of the page failing as expected is as follows:

```sh
curl http://localhost:4321/good -v

*   Trying 127.0.0.1:4321...
* connect to 127.0.0.1 port 4321 failed: Connection refused
*   Trying [::1]:4321...
* Connected to localhost (::1) port 4321 (#0)
> GET /good HTTP/1.1
> Host: localhost:4321
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 05 Nov 2024 20:55:24 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
```

## The "bad" scenario (component fails with 200)

```sh
curl http://localhost:4321/bad -v

*   Trying 127.0.0.1:4321...
* connect to 127.0.0.1 port 4321 failed: Connection refused
*   Trying [::1]:4321...
* Connected to localhost (::1) port 4321 (#0)
> GET /bad HTTP/1.1
> Host: localhost:4321
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: text/html
< Date: Tue, 05 Nov 2024 20:56:45 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
Internal server error
```

### What's the expected result?

Throwing errors within components should behave the same as throwing errors within pages (it should be catchable by middleware and return a 500).

### Link to Minimal Reproducible Example

https://github.com/MatthewLymer/astro-error-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Regarding the dev server, we deliberately throw the error because that's usually a runtime error that should be caught early and fixed, so we display it in the overlay.

What's the reason why you need to catch errors in the middleware? Trying to understand the use case

**Comment by MatthewLymer** [comment]
If I (forcefully) disable streaming, then I get the behaviour that I want.  My middleware gets executed, the response status code is 500, and it renders the `500.astro` page as expected.

```js
const OriginalApp = Object.getPrototypeOf(NodeApp);

function MyConstructor(arg1: any, streaming?: boolean) {
  return new OriginalApp(arg1, false); // set streaming to false
}

Object.setPrototypeOf(NodeApp, MyConstructor);
```

It would be nice if this was a property that is supposed, however.

**Comment by MatthewLymer** [comment]
In addition to the above, it actually breaks the 404 handling behaviour, so it's not that great of a workaround:
```sh
[ERROR] [@astrojs/node] Unhandled rejection while rendering undefined
TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at App.match (file:///Users/mlymer/src/MyAstroApp/dist/server/chunks/_@astrojs-ssr-adapter_D7KIb8t0.mjs:732:17)
    at App.render (file:///Users/mlymer/src/MyAstroApp/dist/server/chunks/_@astrojs-ssr-adapter_D7KIb8t0.mjs:834:24)
    at file:///Users/mlymer/src/MyAstroApp/dist/server/chunks/_@astrojs-ssr-adapter_D7KIb8t0.mjs:1390:40
    at file:///Users/mlymer/src/MyAstroApp/dist/server/chunks/_@astrojs-ssr-adapter_D7KIb8t0.mjs:1664:39
    at SendStream.<anonymous> (file:///Users/mlymer/src/MyAstroApp/dist/server/chunks/_@astrojs-ssr-adapter_D7KIb8t0.mjs:1582:17)
    at SendStream.emit (node:events:519:28)
    at SendStream.error (/Users/mlymer/src/MyAstroApp/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/mlymer/src/MyAstroApp/node_modules/send/index.js:417:12)
    at next (/Users/mlymer/src/MyAstroApp/node_modules/send/index.js:730:16) {
  code: 'ERR_INVALID_URL',
  input: '/foobarbaz'
}
```

**Comment by MatthewLymer** [comment]
@angelikatyborska the solution that ended up working for us is to create a middleware that copies the entire stream before returning.

The caveat is that this prevents the streaming behaviour, however, it's necessary as we need the entire response to be rendered in order to catch errors from sub-components.

**Comment by Fryuni** [comment]
Errors thrown from a component are catchable from a middleware, they just aren't catchable from the `next()` call since they are not thrown there.

```ts
defineMiddleware((ctx, next) => {
  try {
    const res = await next();
	if (!res.body) return; // Responses without body can't fail during streaming

 	const body = new ReadableStream({
		start: async controller => {
			try {
				for await (const chunk of res.body) {
					// Forward every chunk
					controller.enqueue(chunk);
				}
			} catch (error) {
				// Every chunk read can fail, here you catch errors that
				// happen during streaming, such as component errors.
				throw error;
			} finally {
				controller.close();
			}
		},
	});

    return new Response(body, res);
  } catch (error) {
    // This error comes from the top-level of the page, before streaming starts
  }
});
```

**Comment by dccarmo** [comment]
I wonder if this behavior is a bug or expected? I was catching errors thrown from nested Astro components in the middleware to redirect users (to protect specific routes without using the middleware for that.)

**Comment by florian-lefebvre** [comment]
Did it stop working from a specific version?

**Comment by dccarmo** [comment]
@florian-lefebvre that's a good question, I tried going back to at least `5.0.0` and the issue is still there, now I'm wondering if this ever worked. I'll try to go back to `~4.0.0`and report back.

**Comment by elite174** [comment]
![Image](https://github.com/user-attachments/assets/50bd9862-ae0e-44a0-a6c3-fbc109f31ecc)

Ok, I managed to improve the situation a bit. I added this to my site and after this server continued to work. But with slightly different error.

```
17:17:16 [ERROR] [@astrojs/node] Unhandled rejection while rendering undefined
1775 |         return OutgoingMessagePrototype.write.@call(this, chunk, encoding, callback);
1776 |     if (this[headerStateSymbol] !== 2 /* sent */)
1777 |       handle.cork(() => {
1778 |         handle.writeHead(this.statusCode, this.statusMessage, this[headersSymbol]), this[headerStateSymbol] = 2 /* sent */, result = handle.write(chunk, encoding);
1779 |       });
1780 |       result = handle.write(chunk, encoding);
                         ^
error: Stream already ended
 code: "ERR_STREAM_WRITE_AFTER_END"

      at write (node:http:1780:28)
      at ondata (internal:streams/readable:627:19)
      at emit (node:events:327:22)
      at addChunk (internal:streams/readable:134:47)
      at readableAddChunkPushByteMode (internal:streams/readable:112:18)
      at <anonymous> (internal:fs/streams:330:16)
      at <anonymous> (node:fs:286:82)
```

**Comment by artemkliaus** [comment]
Hi! I read the messages, but I still don't understand the correct approach for error handling.
I have a Svelte component where I intentionally trigger a rendering error, and I want the 500.astro page to be rendered.
However, it's not being displayed — I only get an "Internal Server Error" response with a 200 status.

P.S. I tried the middleware approach mentioned above, but it's also unclear how to redirect to another page, since by the time the error occurs, the middleware has already run.
It's a bit strange that this functionality isn't clearly documented, considering that rendering errors are a common occurrence.

**Comment by elite174** [comment]
Small update: I moved to bun and custom adapter - works perfectly

**Comment by Fryuni** [comment]
@artemkliaus redirecting on rendering error is conceptually incompatible with response streaming. The prior code has already been sent to the client, the server has _no control_ over it anymore, the page is already being shown to the user.

That is why your components that can fail should render an error state, not fail to render.

A full page rewrite on render error is possible without streaming, I have an option for that on one of my integrations: https://inox-tools.fryuni.dev/cut-short#disablestreaming

**Comment by delucis** [comment]
Closing as it seems the consensus is that this behaviour is expected. Would be good to update our error page docs to make this clearer!
