### ISSUE TITLE
__vite_ssr_import_1__.render(...) is not a function

### ISSUE THREAD

**Issue by szmarczak** [withastro/astro#12415]
### Astro Info

```block
> npx astro info
Astro                    v4.16.6
Node                     v22.7.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
                         @astrojs/preact
                         @astrojs/tailwind
```

### Describe the Bug

```

TypeError: __vite_ssr_import_1__.render(...) is not a function
    at Object.default (C:\Users\wkute\Desktop\inżynierka\inzynierka\src\pages\rooms.astro:1:1)
    at new AstroComponentInstance (C:\Users\wkute\Desktop\inżynierka\inzynierka\node_modules\astro\dist\runtime\server\render\astro\instance.js:20:30)
    at Module.createAstroComponentInstance (C:\Users\wkute\Desktop\inżynierka\inzynierka\node_modules\astro\dist\runtime\server\render\astro\instance.js:63:20)
    at renderAstroComponent (C:\Users\wkute\Desktop\inżynierka\inzynierka\node_modules\astro\dist\runtime\server\render\component.js:363:20)
    at Module.renderComponent (C:\Users\wkute\Desktop\inżynierka\inzynierka\node_modules\astro\dist\runtime\server\render\component.js:382:12)
    at C:\Users\wkute\Desktop\inżynierka\inzynierka\src\pages\rooms.astro:1:1
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async callComponentAsTemplateResultOrResponse (file:///C:/Users/wkute/Desktop/in%C5%BCynierka/inzynierka/node_modules/astro/dist/runtime/server/render/astro/render.js:90:25)
    at async renderToAsyncIterable (file:///C:/Users/wkute/Desktop/in%C5%BCynierka/inzynierka/node_modules/astro/dist/runtime/server/render/astro/render.js:132:26)
    at async renderPage (file:///C:/Users/wkute/Desktop/in%C5%BCynierka/inzynierka/node_modules/astro/dist/runtime/server/render/page.js:31:24)
```

### What's the expected result?

No error.

### Link to Minimal Reproducible Example

Not reproducible. Happened only once. Refreshed the page again and it worked.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
If we can't reproduce the issue, we can't fix it. I leave the issue open for a few days

**Comment by szmarczak** [comment]
> If we can't reproduce the issue, we can't fix it.

Not always. You have the stack trace, that should at least hint what's wrong.

**Comment by ematipico** [comment]
That's not enough. We don't know what the project looks like, or what's inside the files you're rendering.

**Comment by szmarczak** [comment]
> We don't know what the project looks like, or what's inside the files you're rendering.

<details>
<summary>The page itself looks like this.</summary>

```astro
---
import Layout from '../layouts/Layout.astro';
import { Image } from 'astro:assets';
import beach from "../../public/beach.jpg";
import Navigation from '../components/astro/Navigation.astro';
import Input from '../components/astro/Input.astro';
import { supabase } from '../lib/supabase';

if (!Astro.locals.user) {
    return Astro.redirect('/');
}

let roomAdded = false;
let addingRoomError;

if (Astro.request.method === 'POST') {
    const data = await Astro.request.formData();

    const { error } = await supabase.from('room').insert({
        user: Astro.locals.user?.id,
        name: data.get('room')
    });

    if (!error) {
        roomAdded = true;
    } else {
        addingRoomError = error;
    }
}

const { data: rooms, error: roomsError } = await Astro.locals.supabase.from('room').select();
---

<Layout title="Choose Room">
<Navigation />
<div class="container mx-auto flex flex-col gap-4">
    <div class="flex flex-col gap-4 bg-white p-4 rounded-2xl">
        <span class="font-medium text-2xl">Create new room</span>
        {roomAdded && (
            <span class="text-emerald-600">Room added successfully!</span>
        )}
        {(() => {
            if (!addingRoomError) {
                return;
            }

            if (addingRoomError.code === '23505') {
                //postgres_code unique_violation = 23505
                return <span class="text-red-600">Room already exists.</span>;
            }

            return <span class="text-red-600">Database error. Room not added.</span>;
        })()}
        <form class="flex gap-2" method="POST">
            <Input placeholder="Room name" name="room" />
            <button class="p-2 bg-emerald-600 hover:bg-emerald-800 text-white rounded-2xl">Add Room</button>
        </form>
    </div>
    <div class="flex flex-col gap-4 bg-white p-4 rounded-2xl">
        <h1 class="font-medium text-2xl">My rooms</h1>

        <div class="flex mx-auto w-fit gap-4 flex-wrap">
            {(() => {
                if (!rooms) {
                    return <>Database error.</>;
                }

                return rooms.map(room => (
                    <a href="#" class="flex rounded-2xl p-2 h-64 w-64 bg-cover items-center justify-center" style={'background-image: url(\'' + beach.src + '\')'}>
                        <span class="text-white font-semibold text-4xl text-shadow" style="--text-shadow-color: black">{room.name}</span>
                    </a>
                ));
            })()}
        </div>
    </div>
</div>
</Layout>
```
</details>

<details>
<summary>Layout.astro</summary>

https://github.com/withastro/astro/blob/471e7127a3a92f3008a71aa25a093e5f9b309176/examples/basics/src/layouts/Layout.astro

</details>

<details>
<summary>Input.astro</summary>

```astro
---
const { class: className, ...rest } = Astro.props;

---
<input {...rest} class:list={[className, 'p-2 outline-gray-200 focus-visible:outline-teal-400 outline outline-2 rounded-2xl']}>
```
</details>

<details>
<summary>lib/supabase.ts</summary>

```ts
import { createClient } from "@supabase/supabase-js";

export const supabase = createClient(
    import.meta.env.SUPABASE_URL,
    import.meta.env.SUPABASE_ANON_KEY,
);
```
</details>

<details>
<summary>middleware.ts</summary>

```ts
import { defineMiddleware } from "astro:middleware";
import { supabase } from "./lib/supabase";
import { createClient } from "@supabase/supabase-js";

export const onRequest = defineMiddleware(async (context, next) => {
    const token = context.cookies.get('sb-access-token')?.value;

    context.locals.supabase = createClient(
        import.meta.env.SUPABASE_URL,
        import.meta.env.SUPABASE_ANON_KEY,
        {
            accessToken: async () => token ?? ''
        }
    );

    if (token) {
        const {data, error} = await supabase.auth.getUser(token);

        if (!error) {
            context.locals.user = data.user;
        }
    }

    return next();
});
```
</details>

<details>
<summary>Navigation.astro</summary>

Fully static with SVG, WEBP, PNG, `Input.astro` and `Fragment set:html` for SVG, also it includes `<script src="flowbite"></script>`.
</details>

<details>
<summary>astro.config.mjs</summary>

```js
import { defineConfig } from 'astro/config';
import react from "@astrojs/react";

import preact from "@astrojs/preact";

import tailwind from "@astrojs/tailwind";

import vercel from "@astrojs/vercel/serverless";

// https://astro.build/config
export default defineConfig({
  integrations: [react({
    include: "**/react/*"
  }), preact({
    include: "**/preact/*"
  }), tailwind()],
  adapter: vercel(),
  output: "server"
});
```
</details>

<details>
<summary>tailwind.config.mjs</summary>

```js
/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}', './node_modules/flowbite/**/*.js'],
	theme: {
		extend: {},
	},
	plugins: [
		require('flowbite/plugin')
	],
}
```
</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "projekt-frontend",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.9.3",
    "@astrojs/preact": "^3.5.2",
    "@astrojs/react": "^3.6.2",
    "@astrojs/tailwind": "^5.1.1",
    "@astrojs/vercel": "^7.8.2",
    "@preact/signals": "^1.3.0",
    "@supabase/supabase-js": "^2.45.6",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "astro": "^4.15.1",
    "flowbite": "^2.5.2",
    "micromatch": "^4.0.8",
    "preact": "^10.23.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-toastify": "^10.0.6",
    "tailwindcss": "^3.4.13",
    "typescript": "^5.5.4",
    "vercel": "^37.11.0"
  },
  "devDependencies": {
    "@types/micromatch": "^4.0.9"
  }
}
```
</details>

That's all that should be relevant, the rest is defaults. Unfortunately I'm unable to share the full project code. I'm fine with this issue being closed if it doesn't happen again anytime soon.

**Comment by bluwy** [comment]
I'm familiar with the Vite SSR handling issues as shown in the stack trace, but I'm not able to tell where the issue is either without a proper repro here. My only guess is to try untangling any circular imports if you have it in your codebase.

**Comment by szmarczak** [comment]
There's no circular imports in the project.
