### ISSUE TITLE
[5.0.0-beta.9] SVG component not accepting some SVGs

### ISSUE THREAD

**Issue by vrabe** [withastro/astro#12500]
### Astro Info

```block
Astro                    v5.0.0-beta.9
Node                     v23.1.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

I found that some SVGs can't be shown by the SVG component. 

The SVG file:
![dragon](https://github.com/user-attachments/assets/8ef04902-6a87-4d91-856f-8e1cb7c44c96)
(from <https://www.freeimages.com/vector/dragoncraftstrokepng-5690499>)

Stack Trace:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at C (file:///home/user/program/violet-visual/node_modules/.pnpm/ultrahtml@1.5.3/node_modules/ultrahtml/dist/index.js:1:4250)
    at parseSvg (file:///home/user/program/violet-visual/node_modules/.pnpm/astro@5.0.0-beta.9_rollup@4.27.3_typescript@5.6.3/node_modules/astro/dist/assets/utils/svg.js:6:16)
    at makeSvgComponent (file:///home/user/program/violet-visual/node_modules/.pnpm/astro@5.0.0-beta.9_rollup@4.27.3_typescript@5.6.3/node_modules/astro/dist/assets/utils/svg.js:11:42)
    at LoadPluginContext.load (file:///home/user/program/violet-visual/node_modules/.pnpm/astro@5.0.0-beta.9_rollup@4.27.3_typescript@5.6.3/node_modules/astro/dist/assets/vite-plugin-assets.js:179:20)
    at async EnvironmentPluginContainer.load (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/chunks/dep-D4jOq5eU.js:49089:22)
    at async loadAndTransform (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/chunks/dep-D4jOq5eU.js:43100:22)
    at async fetchModule (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/chunks/dep-D4jOq5eU.js:53213:16)
    at async SSRCompatModuleRunner.getModuleInformation (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/module-runner.js:968:73)
    at async request (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/module-runner.js:986:88)
    at async eval (/home/user/program/violet-visual/src/content/blog/using-mdx.mdx:24:1)
```

### What's the expected result?

The SVG is rendered correctly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-buzorg

(I put the SVG in `src/content/blog/using-mdx.mdx`)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
The error seems to come from the library we use for parsing the HTML 😭

**Comment by stramel** [comment]
Hi @vrabe! Thank you for testing this out! I filed an downstream issue in `ultrahtml`.  (https://github.com/natemoo-re/ultrahtml/issues/76).

As a workaround until we get this fixed, please remove the `<?xml>` tag from the start of the file.

**Comment by vrabe** [comment]
@stramel Thanks for your investigation! It's indeed because of something before `svg` tag.

**Comment by vrabe** [comment]
Why it's not closed? I'm closing it.
