### ISSUE TITLE
Script cannot be detected as server or static mode on Astro v5.x

### ISSUE THREAD

**Issue by cworld1** [withastro/astro#12609]
### Astro Info

```block
$ astro info
Astro                    v5.0.1
Node                     v23.2.0
System                   Windows (x64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/vercel
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         @astrojs/mdx
                         astro-icon
```

### If this issue only occurs in one browser, which browser is a problem?

Firefox

### Describe the Bug

For file `src/utils.ts`

```ts
export function A() {
  // Used in dynamic astro page P
}

export function B() {
  // Used as a static typescript function in a simple component S using <script>import xxx</script>
}
```

but when component S inserted in dynamic server page P, astro seems cannot split out scripts and shows warnings.

> Note: this method can work on Astro v4.x

```log
The "astro:content" module is only available server-side.
Stack Trace
at generateContentEntryFile (file:///D:/code/web/astro-theme-pure/node_modules/astro/dist/content/vite-plugin-content-virtual-mod.js:197:11)
    at LoadPluginContext.load (file:///D:/code/web/astro-theme-pure/node_modules/astro/dist/content/vite-plugin-content-virtual-mod.js:93:28)
    at EnvironmentPluginContainer.load (file:///D:/code/web/astro-theme-pure/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:46981:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async loadAndTransform (file:///D:/code/web/astro-theme-pure/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:40782:22)
    at async viteTransformMiddleware (file:///D:/code/web/astro-theme-pure/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:42292:24)
```

### What's the expected result?

```ts
// src/utils.ts
export function A() {
  // Used in dynamic astro page P
}

export function B() {
  // Used as a static typescript function in a simple component S using <script>import xxx</script>
}
```

When component S inserted in dynamic server page P, astro can work well.

### Link to Minimal Reproducible Example

https://github.com/cworld1/astro-blog-test/tree/utils

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by cworld1** [comment]
Well! Here's the minimal reproduction: 
https://github.com/cworld1/astro-blog-test/tree/utils
(Main branch is about another issue)

**Comment by cworld1** [comment]
Error: The "astro:content" module is only available server-side.

Error info on AstroError:

```log
at generateContentEntryFile (file:///D:/code/test/astro-blog-test/node_modules/.pnpm/astro@5.0.3_rollup@4.28.0_typescript@5.7.2/node_modules/astro/dist/content/vite-plugin-content-virtual-mod.js:195:11)
    at LoadPluginContext.load (file:///D:/code/test/astro-blog-test/node_modules/.pnpm/astro@5.0.3_rollup@4.28.0_typescript@5.7.2/node_modules/astro/dist/content/vite-plugin-content-virtual-mod.js:91:28)
    at EnvironmentPluginContainer.load (file:///D:/code/test/astro-blog-test/node_modules/.pnpm/vite@6.0.3/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:46974:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async loadAndTransform (file:///D:/code/test/astro-blog-test/node_modules/.pnpm/vite@6.0.3/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:40786:22)
    at async viteTransformMiddleware (file:///D:/code/test/astro-blog-test/node_modules/.pnpm/vite@6.0.3/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:42296:24)
```

Error info on build (currently on Vercel, and locally deploy is the same):

```log
  Error reference:
    https://docs.astro.build/en/reference/errors/server-only-module/
  Stack trace:
    at generateContentEntryFile (file:///vercel/path0/node_modules/.pnpm/astro@5.0.3_rollup@4.28.0_typescript@5.7.2/node_modules/astro/dist/content/vite-plugin-content-virtual-mod.js:195:11)
    at Object.handler (file:///vercel/path0/node_modules/.pnpm/vite@6.0.3/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:50826:15)
    at async PluginDriver.hookFirstAndGetPlugin (file:///vercel/path0/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:20712:28)
    at async Queue.work (file:///vercel/path0/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:20922:32)
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```

**Comment by Jazee6** [comment]
same

**Comment by cworld1** [comment]
@Jazee6 A temporary solution is split out the utility scripts to another file, like `server.ts` (you can check an example at https://github.com/cworld1/astro-theme-pure/blob/v3-1-5/packages/pure/utils/server.ts), then only call on functions using this file instead.

**Comment by cworld1** [comment]
@Jazee6 (Other content not related to this issue) 你的博客在境内访问速度很堪忧，或者说几乎无法打开，建议优化访问速度

**Comment by Jazee6** [comment]
> @Jazee6 (Other content not related to this issue) 你的博客在境内访问速度很堪忧，或者说几乎无法打开，建议优化访问速度

There is no need for people who cannot open the website to visit, they are not the target audience.

**Comment by bernatGene** [comment]
facing the same issue, but I'm unable to pin down the exact issue and/or how to split the utilities file into two as suggested above. The issue came up after trying to upgrade to v5 and merging some changes from an upstream repo.

**Comment by FJRG2007** [comment]
I also get this error after migrating to Astro 5.

**Comment by moon0101** [comment]
Same error here after migrating to Astro 5. 


`The "astro:content" module is only available server-side.`

**Comment by cworld1** [comment]
@bluwy It is a known issue and should not be closed without official solution. Can u consider it again? So many developers faced the same problem.🙏

**Comment by mseele** [comment]
I've digged down deeper. It's this line of code that triggers the error: https://github.com/mseele/sve-website/blob/ec75d17a182fbca49c1a04eed844ba659f60116c/src/types.ts#L2

```typescript
import { z } from 'astro:content'
```

**Comment by cworld1** [comment]
@mseele Zod is a classical module which should be used for server side. This has been told at official docs. I suggest you to use Astro integration instead, which also can be processed and import by Vite.
Example: https://github.com/cworld1/astro-theme-pure/blob/v4.0.1-beta/packages/pure/index.ts where I process user configuration.

**Comment by moon0101** [comment]
I fixed the `The "astro:content" module is only available server-side.` in  my setup. In the Upgrade guide to Astro 5, you can read that astro:content is no longer available on the client side (https://docs.astro.build/en/guides/upgrade-to/v5/#changed-astrocontent-can-no-longer-be-used-on-the-client).
To fix the issue you need to find the locations where you import astro:content properties outside of this scope.
In my case I used the getCollection method in a js file to get the collection and return filtered posts. Moving getCollection() into the [bracket].astro files and rewrite the contentFilter.js file did the trick for this specific error. It surfaced other issues with the updated content collection API but this is subject to another issue.

1. Find the locations where you import astro:content
2. move it into a corresponding astro parent file
3. hand down the collection data as prop

**Comment by cworld1** [comment]
@moon0101 It is not a easy thing. The more interaction & integration you add, the more difficulties you will face. As an example https://github.com/cworld1/astro-theme-pure/blob/v3.1.4/src/components/search/Search.astro the integration Fuse.js will not be supported easily.
