### ISSUE TITLE
UnhandledRejection

### ISSUE THREAD

**Issue by Prashant20nov2003** [withastro/astro#12659]
### Astro Info

```block
npm run dev

> portfolio@0.0.1 dev
> astro dev

05:40:20 [types] Generated 1ms
05:40:21 [vite] Re-optimizing dependencies because vite config has changed

 astro  v4.16.9 ready in 576 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

05:40:21 watching for file changes...
05:40:23 [ERROR] [UnhandledRejection] Astro detected an unhandled rejection. Here's the stack trace:
ReferenceError: module is not defined
    at file:///D:/zero/Portfolio-XD/tailwind.config.js:2:1
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:395:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1414:24)
    at Module._compile (node:internal/modules/cjs/loader:1547:5)
    at Object..js (node:internal/modules/cjs/loader:1677:16)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
  Hint:
    Make sure your promises all have an `await` or a `.catch()` handler.
  Error reference:
    https://docs.astro.build/en/reference/errors/unhandled-rejection/
  Stack trace:
    at file:///D:/zero/Portfolio-XD/tailwind.config.js:2:1
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
    at Module._compile (node:internal/modules/cjs/loader:1547:5)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    [...] See full stack trace in the browser, or rerun with --verbose.
05:40:24 [200] / 75ms
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome , Brave

### Describe the Bug

![Screenshot 2024-12-06 054112](https://github.com/user-attachments/assets/f4580801-477b-493d-b8da-9c2c5ec6b003)
file path nodemodules/astro/dist/vite-plugin-astro-server/plugin.js

### What's the expected result?

![Screenshot 2024-12-06 054423](https://github.com/user-attachments/assets/f28ef922-72c3-4f70-aee8-f68c9e33e179)

### Link to Minimal Reproducible Example

...

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JorgeLoaizaArmienta** [comment]
i have de same problem

**Comment by prashsamosa** [comment]
hey update vite and astro.
mine got fixed
