### ISSUE TITLE
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "tty" imported from "node_modules/consola/dist/chunks/prompt.mjs". Consider disabling environments.ssr.noExternal or remove the built-in dependency. [Cloudflare]

### ISSUE THREAD

**Issue by lassegit** [withastro/astro#12670]
### Astro Info

```block
Astro                    v5.0.3
Node                     v20.15.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

Trying to upgrade from `v4` to `v5` and build on it Cloudflare integration. Here is the build error:

```
17:15:48.511	16:15:48 [ERROR] [vite] x Build failed in 4.93s
17:15:48.741	[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "tty" imported from "node_modules/consola/dist/chunks/prompt.mjs". Consider disabling environments.ssr.noExternal or remove the built-in dependency.
17:15:48.742	  Stack trace:
17:15:48.742	    at getRollupError (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
17:15:48.742	    at Object.error (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:20622:20)
17:15:48.742	    at Object.handler (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:50806:15)
17:15:48.742	    at async PluginDriver.hookFirstAndGetPlugin (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:20707:28)
17:15:48.742	    at async ModuleLoader.resolveId (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:19740:15)
17:15:48.792	Failed: Error while executing user command. Exited with error code: 1
17:15:48.838	Failed: build command exited with code: 1
17:15:50.145	Failed: error occurred while running build command
```

Here is the `astro.config.mjs`:

```js
import cloudflare from '@astrojs/cloudflare';
import react from '@astrojs/react';
import tailwind from '@astrojs/tailwind';
import { defineConfig } from 'astro/config';

export default defineConfig({
  prefetch: true,
  output: 'server',
  server: { port: 3000 },
  adapter: cloudflare({ imageService: 'passthrough', platformProxy: { enabled: true } }),
  integrations: [tailwind({ applyBaseStyles: false }), react()],
  vite: {
    ssr: {
      external: ['node:process', 'node:tty', 'node:util', 'node:path', 'node:stream', 'node:buffer', 'node:readline'],
    },
  },
});
```

It threw errors for each of the added external `node:*` packages too (like need to update the docs). Web app deploys to Cloudflare using `v4` without issues (https://www.websitefeedback.ai).

### What's the expected result?

I expect the app to build without issues and/or the needed configuration be described in https://docs.astro.build/en/guides/integrations-guide/cloudflare.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rewgio

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by thomas-callahan-collibra** [comment]
Related to this maybe?
https://github.com/withastro/adapters/issues/470

**Comment by alexanderniebuhr** [comment]
`tty` is not supported in Cloudflare. It should not have worked with v4 either. Maybe we changed some bundling behavior in Astro v5

**Comment by alexanderniebuhr** [comment]
Looks like we found the root cause https://github.com/withastro/adapters/issues/470#issuecomment-2525365865

We are working on a fix and will ship it as soon as possible. Please apologize the inconvenience.

**Comment by florian-lefebvre** [comment]
https://github.com/withastro/adapters/pull/476 was merged and released in december
