### ISSUE TITLE
Content collections build: "Vite module runner has been closed."

### ISSUE THREAD

**Issue by crummy** [withastro/astro#12689]
### Astro Info

```block
Astro                    v5.0.3
Node                     v23.2.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

I read files to generate a content collection. Works fine during development, but fails during build with this output:

```
❯ astro build
17:09:47 [content] Syncing content
17:09:47 [content] Content config changed
17:09:47 [content] Clearing content store
Vite module runner has been closed.
  Location:
    /home/projects/withastro-astro-7t9i3ppv/node_modules/vite/dist/node/module-runner.js:1217:13
  Stack trace:
    at SSRCompatModuleRunner.getModuleInformation (file:///home/projects/withastro-astro-7t9i3ppv/node_modules/vite/dist/node/module-runner.js:1217:13)
    at request (file:///home/projects/withastro-astro-7t9i3ppv/node_modules/vite/dist/node/module-runner.js:1243:99)
    at ./examples/csv/grammar.txt (/home/projects/withastro-astro-7t9i3ppv/src/content.config.ts:7:89)
    at eval (file:///home/projects/withastro-astro-7t9i3ppv/node_modules/zod/lib/index.mjs:3492:40)
    at eval (file:///home/projects/withastro-astro-7t9i3ppv/node_modules/astro/dist/content/content-layer.js:188:18)
```

### What's the expected result?

Should behave identically to dev.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-7t9i3ppv?file=src%2Fcontent.config.ts

In the console, run `astro build`.

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Ran into this issue updating an old website of mine, if an additional reproduction is needed: https://github.com/Princesseuh/astro-issues/pull/1

Note that I do not use content collections

**Comment by crummy** [comment]
It happens to me any time I import a file in a collection. Here's the smallest repro I've come up with:

```
export const examples = defineCollection({
  loader: async () => {
    const file = await import('/src/examples/csv/grammar.txt');
    return [];
  },
});
```
Commenting out `const file...` means build will succeed.

**Comment by crummy** [comment]
> Ran into this issue updating an old website of mine, if an additional reproduction is needed: [Princesseuh/astro-issues#1](https://github.com/Princesseuh/astro-issues/pull/1)

On your repo I replaced this line:
```scripts/vite-plugin-stats.ts
const allStats = import.meta.glob("/src/data/*.json");
```
With this line:
```scripts/vite-plugin-stats.ts
const allStats = {}
```
And the error disappeared (it was replaced with a later error but presumably that's because this object is not expected to be empty).

I wondered if dynamic imports were broken entirely but I put this at the top of an astro file and it worked fine:
```
const f = await import("/src/examples/csv/grammar.txt?raw")
```

**Comment by Adammatthiesen** [comment]
can also confirm that this issue is happening with the following vite dynamic import functions from an integration hook (`astro:config:setup`) as well... we (StudioCMS team) had to disable our config file loading system (Load a users `studiocms.config.{mjs|js|ts|mts|cjs|cts}` in order to upgrade to v5).  hopefully there will be a fix soon!
```js
const mod = await import(configPath)
```

**Comment by bluwy** [comment]
Maybe same as https://github.com/vitejs/vite/issues/18962

**Comment by crummy** [comment]
I have a fix, reading files with `fs.readFile`. Here is my loader:

```
    loader: async () => {
        const files = await fastGlob("src/examples/*.json");
        return await Promise.all(files.map(async f => {
            const contents = await fs.readFile(f, "utf-8")
            const json = JSON.parse(contents);
            return {
                id: json.title,
                title: json.title,
                grammar: json.grammar,
                input: json.input,
                highlighted: json.highlighted
            }
        }));
    },
```

**Comment by bluwy** [comment]
I'll close this for now as the above Vite issue linked has also been fixed, which I think is the same issue here.

**Comment by bluwy** [comment]
Nevermind, I ran the repro and the issue is still happening.

**Comment by mhagendoorn-9292** [comment]
This issue is still present in Astro@5.1.3.

**Comment by smac89** [comment]
The issue occurs in a custom astro plugin, when a dynamic import occurs. I get the following inside the `astro:build:setup` hook:

> Vite module runner has been closed.
  Location:
    /home/chigozirim/Development/website/node_modules/.pnpm/vite@6.0.11_@types+node@22.10.5_jiti@1.21.7_lightningcss@1.28.2_terser@5.37.0_yaml@2.7.0/node_modules/vite/dist/node/module-runner.js:1188:13
  Stack trace:
    at SSRCompatModuleRunner.getModuleInformation (file:///home/chigozirim/Development/website/node_modules/.pnpm/vite@6.0.11_@types+node@22.10.5_jiti@1.21.7_lightningcss@1.28.2_terser@5.37.0_yaml@2.7.0/node_modules/vite/dist/node/module-runner.js:1188:13)
    at request (file:///home/chigozirim/Development/website/node_modules/.pnpm/vite@6.0.11_@types+node@22.10.5_jiti@1.21.7_lightningcss@1.28.2_terser@5.37.0_yaml@2.7.0/node_modules/vite/dist/node/module-runner.js:1214:99)
    at astro:build:setup (/home/chigozirim/Development/website/plugins/astro-css-renamer.ts:30:36)
    at ssrBuild (file:///home/chigozirim/Development/website/node_modules/.pnpm/astro@5.1.9_@types+node@22.10.5_jiti@1.21.7_lightningcss@1.28.2_rollup@4.32.0_terser@5.37.0_typescript@5.7.3_yaml@2.7.0/node_modules/astro/dist/core/build/static-build.js:174:40)
    at async AstroBuilder.build (file:///home/chigozirim/Development/website/node_modules/.pnpm/astro@5.1.9_@types+node@22.10.5_jiti@1.21.7_lightningcss@1.28.2_rollup@4.32.0_terser@5.37.0_typescript@5.7.3_yaml@2.7.0/node_modules/astro/dist/core/build/index.js:144:48)
 ELIFECYCLE  Command failed with exit code 1

The line that triggers the error is:

```
const cssRenamer = await import("postcss-rename").then((p) => p.default);
```

**Comment by Adammatthiesen** [comment]
Coming back with an update for the integration's standpoint... but i was able to get it working properly for resolving a user's config (`studiocms.config.mjs`) file by implementing a build step to convert my `.ts` files to `.js`.  After some of us were discussing in the [Discord](https://discord.com/channels/830184174198718474/1197638002764152843/1330815661265387560) the v5 change that effects this issue is [this](https://docs.astro.build/en/guides/upgrade-to/v5/#changed-js-dependencies-in-config-file-are-no-longer-processed-by-vite)

So this seems to be related to `.ts` files in certain steps that are not in the normal Astro runtime

**Comment by KiritoKing** [comment]
I ran into this issue in my website, too.
I started a new blog framework with latest AstroWind template with astro@5.0.3.

When I was using [notion-astro-loader](https://github.com/NotWoods/travel/tree/main/packages/notion-astro-loader) to build my content layer collection with notion, the same error happened.

I looked up the loader's repo and find the related code. It just uses the `getImage` API.

```typescript
#fetchImage = async (imageFileObject) => {
        try {
            const fetchedImageData = await fileToImageAsset(imageFileObject);
            this.#imagePaths.push(fetchedImageData.src);
            return fetchedImageData.src;
        }
        catch (error) {
            console.error(error)
            this.#logger.error(`Failed to fetch image when rendering page.
Have you added \`image: { remotePatterns: [{ protocol: "https", hostname: "*.amazonaws.com" }] }\` to your Astro config file?\n
Error: ${getErrorMessage(error)}`);
            // Fall back to using the remote URL directly.
            return fileToUrl(imageFileObject);
        }
    };

/**
 * Extract and locally cache the image from a file object.
 * @see https://developers.notion.com/reference/file-object
 */
export async function fileToImageAsset(
  file: FileObject,
): Promise<GetImageResult> {
  return getImage({
    src: fileToUrl(file),
    inferSize: true,
  });
}

export function fileToUrl(file: FileObject): string;
export function fileToUrl(file: FileObject | null): string | undefined;
export function fileToUrl(file: FileObject | null): string | undefined {
  switch (file?.type) {
    case "external":
      return file.external.url;
    case "file":
      return file.file.url;
    default:
      return undefined;
  }
}

```

Here is the stack trace. It seems that it is caused by dynamic import, which is mentioned at a closed Vite issue.

```
20:36:43 [ERROR] [page 02f9d03e-aa37-4ad3-b889-d6b4c20bfcb7 (Name 前端开发要知道的网络基础)] Failed to fetch image when rendering page.
Have you added `image: { remotePatterns: [{ protocol: "https", hostname: "*.amazonaws.com" }] }` to your Astro config file?

Error: There was an error loading the configured image service. Please see the stack trace for more information.
InvalidImageService: There was an error loading the configured image service. Please see the stack trace for more information.
    at eval (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_rollup@4.28.1_terser@5.36.0_typescript@5.7.2_yaml@2.5.0/node_modules/astro/dist/assets/internal.js:25:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getConfiguredImageService (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_rollup@4.28.1_terser@5.36.0_typescript@5.7.2_yaml@2.5.0/node_modules/astro/dist/assets/internal.js:21:34)
    at async getImage (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_rollup@4.28.1_terser@5.36.0_typescript@5.7.2_yaml@2.5.0/node_modules/astro/dist/assets/internal.js:55:19)
    at async getImage (astro:assets:32:42)
    at async #fetchImage (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/notion-astro-loader@0.4.0_astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_roll_2ibjhaoyvb5densitsoeosfrn4/node_modules/notion-astro-loader/dist/render.js:187:38)
    at async listBlocks (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/notion-astro-loader@0.4.0_astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_roll_2ibjhaoyvb5densitsoeosfrn4/node_modules/notion-astro-loader/dist/render.js:79:25)
    at async awaitAll (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/notion-astro-loader@0.4.0_astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_roll_2ibjhaoyvb5densitsoeosfrn4/node_modules/notion-astro-loader/dist/render.js:54:22)
    at async NotionPageRenderer.render (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/notion-astro-loader@0.4.0_astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_roll_2ibjhaoyvb5densitsoeosfrn4/node_modules/notion-astro-loader/dist/render.js:163:28)
    at async Promise.all (index 19) {
  loc: undefined,
  title: 'Error while loading image service.',
  hint: undefined,
  frame: undefined,
  type: 'AstroError',
  cause: Error: Vite module runner has been closed.
      at SSRCompatModuleRunner.getModuleInformation (file:///Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/vite@6.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_terser@5.36.0_yaml@2.5.0/node_modules/vite/dist/node/module-runner.js:1196:13)
      at SSRCompatModuleRunner.cachedModule (file:///Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/vite@6.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_terser@5.36.0_yaml@2.5.0/node_modules/vite/dist/node/module-runner.js:1186:21)
      at request (file:///Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/vite@6.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_terser@5.36.0_yaml@2.5.0/node_modules/vite/dist/node/module-runner.js:1222:99)
      at dynamicRequest (file:///Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/vite@6.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_terser@5.36.0_yaml@2.5.0/node_modules/vite/dist/node/module-runner.js:1224:124)
      at getConfiguredImageService (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_rollup@4.28.1_terser@5.36.0_typescript@5.7.2_yaml@2.5.0/node_modules/astro/dist/assets/internal.js:21:40)
      at getImage (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_rollup@4.28.1_terser@5.36.0_typescript@5.7.2_yaml@2.5.0/node_modules/astro/dist/assets/internal.js:55:25)
      at getImage (astro:assets:32:82)
      at fileToImageAsset (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/notion-astro-loader@0.4.0_astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_roll_2ibjhaoyvb5densitsoeosfrn4/node_modules/notion-astro-loader/dist/format.js:33:46)
      at #fetchImage (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/notion-astro-loader@0.4.0_astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_roll_2ibjhaoyvb5densitsoeosfrn4/node_modules/notion-astro-loader/dist/render.js:187:86)
      at listBlocks (/Users/bytedance/Code/personal/notion-astro-rev/node_modules/.pnpm/notion-astro-loader@0.4.0_astro@5.0.3_@types+node@22.5.0_jiti@1.21.6_lightningcss@1.27.0_roll_2ibjhaoyvb5densitsoeosfrn4/node_modules/notion-astro-loader/dist/render.js:79:31)
}

```

**Comment by KiritoKing** [comment]
Hey dude, I've found out the root cause of this issue.

It seems that astro doesn't actually start a Vite server when handling content layer loader's syncing process. So, any calls for astro APIs are illegal since no Vite server can handle those 'virtual requests'.

Checkout these codes: 
- https://github.com/withastro/astro/blob/main/packages/astro/src/core/sync/index.ts#L158
- https://github.com/withastro/astro/blob/main/packages/astro/src/core/sync/index.ts#L227

The code lines above indicate that **Vite server is only started for content collection initialization**, and when it's time for layers to run their `load()` functions, the server is disposed, so we can see "module runner is closed" in the error message.

I've found out a stupid way to workaround this sh*t, but it causes memory leak. Just remove the `dispose`!

Hopefully, I can find out the final way to solve this during my vacation haha.

**Comment by KiritoKing** [comment]
Unbelievably! It really works!!!

<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/4ac3bb05-4124-4cbb-b09a-5ca46506e93f" />

**Comment by jalberto** [comment]
I have same issue with notion-content-loader as @KiritoKing and the workaround works.

Is this an issue with content-loaders not following Astro specs or a bug?

**Comment by KiritoKing** [comment]
> I have same issue with notion-content-loader as [@KiritoKing](https://github.com/KiritoKing) and the workaround works.
> 
> Is this an issue with content-loaders not following Astro specs or a bug?

I've done my work on rewrite notion loader's image loading. Here is my fork version of notion loader. [Try this!](https://www.npmjs.com/package/@chlorinec-pkgs/notion-astro-loader?activeTab=readme)

**Comment by FlorianFlatscher** [comment]
I use `import.meta.glob`, which results in this error. I was able to fix it by using it with `eager: true`. This makes sense, because it will actually import all the pieces before destroying the vite server.

**Comment by mastercoms** [comment]
Not for content collections, but the config case mentioned in comments here a few times: I just ended up forking off a Node child process and manually executing a subscript which did the dynamic imports.

**Comment by delucis** [comment]
Confirmed this bug is still present with Astro 5.12.9 using the original reproduction.
