### ISSUE TITLE
RenderUndefinedEntryError from dev server

### ISSUE THREAD

**Issue by andersk** [withastro/astro#12773]
### What version of `starlight` are you using?

0.30.2

### What version of `astro` are you using?

5.0.9

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chromium, Firefox

### Describe the Bug

The [official StackBlitz template](https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics) linked from [getting started](https://starlight.astro.build/getting-started/) shows an error page:

> `RenderUndefinedEntryError`
> ## Attempted to render an undefined content collection entry.
>
> [See Docs Reference](https://docs.astro.build/en/reference/errors/render-undefined-entry-error/)
> Check if the entry is undefined before passing it to `render()`
>
> ### `errors/errors.js:16:5`
>
> ```
> …
>     if (message) this.message = message;
>     ^
> …
> ```
>
> ### Stack Trace
>
> ```
> RenderUndefinedEntryError
>     at new AstroError (/home/projects/kkvilwbjno.github/node_modules/astro/dist/core/errors/errors.js:16:5)
>     at renderEntry (/home/projects/kkvilwbjno.github/node_modules/astro/dist/content/runtime.js:345:11)
>     at eval (/home/projects/kkvilwbjno.github/node_modules/@astrojs/starlight/routes/common.astro:18:71)
>     at AstroComponentInstance.common (/home/projects/kkvilwbjno.github/node_modules/astro/dist/runtime/server/astro-component.js:19:12)
>     at AstroComponentInstance.init (/home/projects/kkvilwbjno.github/node_modules/astro/dist/runtime/server/render/astro/instance.js:38:29)
>     at bufferHeadContent (file:///home/projects/kkvilwbjno.github/node_modules/astro/dist/runtime/server/render/astro/render.js:142:37)
>     at Module.renderToAsyncIterable (file:///home/projects/kkvilwbjno.github/node_modules/astro/dist/runtime/server/render/astro/render.js:159:11)
>     at async Module.renderPage (file:///home/projects/kkvilwbjno.github/node_modules/astro/dist/runtime/server/render/page.js:46:24)
>     at async lastNext (file:///home/projects/kkvilwbjno.github/node_modules/astro/dist/core/render-context.js:179:25)
>     at async eval (file:///home/projects/kkvilwbjno.github/node_modules/astro/dist/i18n/middleware.js:64:22)
> ```

and the following console output:

```
❯ npm install && npm run dev

added 417 packages in 11s

206 packages are looking for funding
  run `npm fund` for details

> @example/starlight-basics@0.0.1 dev
> astro dev

12:38:54 [types] Generated 4ms

 astro  v5.0.9 ready in 8118 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

The collection "docs" does not exist or is empty. Ensure a collection directory with this name exists.
12:39:00 [content] Syncing content
12:39:00 [content] Content config changed
12:39:00 [content] Astro version changed
12:39:00 [content] Clearing content store
12:39:00 [content] Synced content
12:39:00 watching for file changes...
12:39:04 [ERROR] [RenderUndefinedEntryError] 
  Hint:
    Check if the entry is undefined before passing it to `render()`
  Error reference:
    https://docs.astro.build/en/reference/errors/render-undefined-entry-error/
  Stack trace:
    at /home/projects/kkvilwbjno.github/node_modules/astro/dist/core/errors/errors.js:16:5
    [...] See full stack trace in the browser, or rerun with --verbose.
```

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by techfg** [comment]
I've encountered this issue in several projects in Stackblitz and locally.  In all cases, running `npm install` again and/or `npm run astro sync` seems to resolve the issue.  However, in a project I just attempted to upgrade from 4 to 5, nothing seems to resolve the issue and I'm unable to get past it.  I've tried sync, force, etc. and continue to encounter the `The collection "docs" does not exist or is empty. Ensure a collection directory with this name exists.` error along with `RenderUndefinedEntryError`.

Are there any other potential workarounds until this is addressed?

**Comment by ascorbic** [comment]
Is this just occurring on Linux, or is anyone experiencing it on other platforms?

**Comment by oluwatobiss** [comment]
I'm experiencing the same on Windows.

**Comment by techfg** [comment]
Just tested that same site on windows. I got the `The collection "docs" does not exist or is empty. Ensure a collection directory with this name exists.` error but the site rendered and I didn't get the `RenderUndefinedEntryError ` error.

Limited testing, obviously but I think the underlying issue is not platform specific from best I can tell and @oluwatobiss confirmed as much I believe.

**Comment by ascorbic** [comment]
If you'd like to try an experimental build that should fix it, install `astro@experimental--dev-after-sync`

**Comment by andersk** [comment]
Yeah the `experimental--dev-after-sync` build from #12818 seems to work in my project.

**Comment by techfg** [comment]
Seems to be a race condition that causes this so difficult to say for certain if `astro@experimental--dev-after-sync` fully resolves the issue but I tried several attempts running from a "clean" state and haven't been able to reproduce the issue when using it.  Looking good, thank you!

**Comment by Princesseuh** [comment]
Fixing this will probably also fix https://github.com/withastro/astro/issues/12456
