### ISSUE TITLE
💡 RFC: the Astro parser should provide feedback when an element is autoclosed because you tried to put an illegal element inside it

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#1283]
### Background & Motivation

paragraph elements are not able to contain divs, and I was trying to write:

```astro
<p>
 <div></div>
 <div></div>
</p>
```

with not much success. I got "div tried to close p which was not open" or something similar, but the error was that the parser auto-closed `<p>` when it encountered `<div>` since that is not a valid child of `<p>`.

Minimal Log:
```
["ERROR" - 5:02:18 PM] Error formatting document.
ParseError: </p> attempted to close <p> that was already automatically closed by <div>
	at error (/Users/calebjasik/Github/prettier-plugin-astro/node_modules/@astrojs/parser/dist/index.js:4585:15)
	at Parser.error (/Users/calebjasik/Github/prettier-plugin-astro/node_modules/@astrojs/parser/dist/index.js:8295:5)
	at tag (/Users/calebjasik/Github/prettier-plugin-astro/node_modules/@astrojs/parser/dist/index.js:7371:16)
	at new Parser (/Users/calebjasik/Github/prettier-plugin-astro/node_modules/@astrojs/parser/dist/index.js:8255:15)
	at parse (/Users/calebjasik/Github/prettier-plugin-astro/node_modules/@astrojs/parser/dist/index.js:8385:18)
	at Object.parse (/Users/calebjasik/Github/prettier-plugin-astro/src/parse.js:6:25)
```

### Possible solutions
Add a special diagnostic that tells you if the error is because it's not a permitted child.
### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
@natemoo-re do you know if this is still the case in the new compiler? I think the issue here is that plenty of people will try to put a `<div>` inside a `<p>` without realizing this is bad, and we should either silently allow this or give a really clean error / lint warning if it happens.

**Comment by drwpow** [comment]
So the new compiler _does_ allow this, and I don’t think we’re able to throw a parse error. This is the difference between the HTML _spec_ and its _implementation_. In HTML, you may put any elements you’d like inside any other. Of course, that may mean that they may not _render_ where expected, and will certainly show validation errors. But for now, I don’t think our new parser can handle strict validation like this RFC proposes.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
