### ISSUE TITLE
@astrojs/vercel Tailwindcss astro add could not update your astro.config.js file safely.

### ISSUE THREAD

**Issue by brezzy1337** [withastro/astro#12862]
### Astro Info

```block
Astro version            v2.10.15
Package manager          npm
Platform                 linux
Architecture             x64
Adapter                  @astrojs/vercel/edge
Integrations             None or couldn't determine.
```

### Describe the Bug

Trying to install tailwind with the command 
```
npx astro add tailwind
```

This throws this error:

```

 error   Astro could not update your astro.config.js file safely.
  Reason: Unable to install dependencies
  
  You will need to add these integration(s) manually.
  Documentation: https://docs.astro.build/en/guides/integrations-guide/
  File:
    /workspaces/www-digital-space-development-.com/node_modules/astro/dist/cli/add/index.js:173:31
  Code:
    172 |     case 3 /* failure */: {
    > 173 |       throw createPrettyError(new Error(`Unable to install dependencies`));
          |                               ^
      174 |     }
      175 |   }
      176 |   const rawConfigPath = await resolveConfigPath({
  Stacktrace:
Error: Astro could not update your astro.config.js file safely.
Reason: Unable to install dependencies

You will need to add these integration(s) manually.
Documentation: https://docs.astro.build/en/guides/integrations-guide/
    at add (file:///workspaces/www-digital-space-development-.com/node_modules/astro/dist/cli/add/index.js:173:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runCommand (file:///workspaces/www-digital-space-development-.com/node_modules/astro/dist/cli/index.js:96:7)
    at async cli (file:///workspaces/www-digital-space-development-.com/node_modules/astro/dist/cli/index.js:148:5)
```

### What's the expected result?

It should just install tailwind and set up the configuration automatically. I am using @astrojs/vercel which could be causing issues.

Very cool project, loved to see this all smoothed out :)

### Link to Minimal Reproducible Example

https://github.com/brezzy1337/www-digital-space-development-.com

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
We don't extend support to Astro v2, plus your repository isn't visible
