### ISSUE TITLE
Error when building Astro with @astrojs/db and @astrojs/cloudflare in version v5.0.8 astro:content-asset-propagation] module is not defined

### ISSUE THREAD

**Issue by MarcoAntonioGonCas** [withastro/astro#13152]
### Astro Info

```block
Astro                    v5.0.8
Node                     v22.12.0
System                   Windows (x64)
Package Manager          bun
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         astro:db
                         @astrojs/db/file-url
```

### Describe the Bug

- Adding `@astrojs/db`  and `@astrojs/cloudflare`
- Run the build command (astro build --remote).
 
Output

````bash
[ERROR] [vite] x Build failed in 1.46s
  [astro:content-asset-propagation] module is not defined
````
![image](https://github.com/user-attachments/assets/eaefacca-b94f-4e68-b3c0-7da7001f6ee2)

### What's the expected result?

A successful build

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qyps5smw?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by zanhk** [comment]
Getting the same problem

**Comment by noahflk** [comment]
Encountering the same issue with the combo of `@astrojs/mdx`, `@astrojs/cloudflare`, and `@astrojs/db` together. Anyone found a solution?

**Comment by SuKuShaing** [comment]
I'm having the same problem and couldn't get it to work after adding @astro/db.

```json
"@astrojs/db": "^0.14.14",
"@astrojs/mdx": "^4.3.0",
"@astrojs/cloudflare": "^12.5.3",
```

After a lot of searching, I found this in the documentation:
https://docs.astro.build/en/guides/astro-db/#connecting-to-remote-databases
The note says "Non-Node runtimes like Cloudflare and Deno don't currently support DB on server-rendered routes when using libSQL."

I switched to deploying in Vercel and everything worked fine.
```json
"@astrojs/db": "^0.14.14",
"@astrojs/mdx": "^4.2.6",
"@astrojs/vercel": "^8.1.4",
```

**Comment by alexanderniebuhr** [comment]
Is this still an issue with the latest versions?

**Comment by Adammatthiesen** [comment]
> Is this still an issue with the latest versions?

@alexanderniebuhr Hey Alex! I know what the problem is here, and will have a fix here soon! (db by default uses the node version of the `@libsql/client` and we will need to add a switch to enable the usage of `@libsql/client/web` for platforms like cloudflare)

**Comment by nicholasray** [comment]
@Adammatthiesen Is this expected to be fixed in astro 5.14.0? I updated to that version, but am still experiencing the `[astro:content-asset-propagation] module is not defined` error when trying to build:

<img width="2100" height="1718" alt="Image" src="https://github.com/user-attachments/assets/310eb6bd-73bc-4f24-bb1b-672f86f87071" />

You can reproduce at https://stackblitz.com/edit/vitejs-vite-n65qk8et?file=package.json

**Comment by Adammatthiesen** [comment]
This is weird... and does not seem to be directly DB, as of `@astrojs/db@0.18.0` DB now supports a ["web" mode](https://docs.astro.build/en/guides/integrations-guide/db/#mode) for working with non-node environments.  this error seems to be only happening with the `mdx` integration enabled as well... 

https://stackblitz.com/edit/vitejs-vite-elypbesb?file=astro.config.mjs

<img width="1182" height="1191" alt="Image" src="https://github.com/user-attachments/assets/4496f557-80b4-47d6-a43e-c44b7a6a2932" />

**Comment by fubits1** [comment]
hm I'm also using mdx and adapter-cloudflare - below is my error log (for astro build --remote on 5.14.1; same log for 5.14) 

Result of `pnpm why cssesc`: https://gist.github.com/fubits1/ae8a7c21b4cfb43a2ce733390453bb97

But I only ran `pnpm astro add db` today while already being on 5.14 so it at least seems to correlate with the DB setup. I think it even only started to fail after trying to connect with --remote (to Turso).

I just rolled back to the pre-DB state - the build succeeds again. 

I will try to reproduce / narrow down when the error is being introduced and will report back.

21:44:47 [ERROR] [vite] ✗ Build failed in 2.06s
[astro:content-asset-propagation] module is not defined
file: /Users/fubits/Developer/projects/portfolio-astro/src/content/notes/how-to-stay-up-to-date-in-svelte.mdx?astroPropagatedAssets
  Stack trace:
    at eval (/Users/fubits/Developer/projects/portfolio-astro/node_modules/.pnpm/cssesc@3.0.0/node_modules/cssesc/cssesc.js:112:1)
    at SSRCompatModuleRunner.directRequest (file:///Users/fubits/Developer/projects/portfolio-astro/node_modules/.pnpm/vite@6.3.6_@types+node@22.14.1_yaml@2.8.1/node_modules/vite/dist/node/module-runner.js:1284:82)
    at SSRCompatModuleRunner.cachedRequest (file:///Users/fubits/Developer/projects/portfolio-astro/node_modules/.pnpm/vite@6.3.6_@types+node@22.14.1_yaml@2.8.1/node_modules/vite/dist/node/module-runner.js:1179:28)
    at async eval (/Users/fubits/Developer/projects/portfolio-astro/node_modules/.pnpm/astro@5.14.1_@types+node@22.14.1_rollup@4.40.0_typescript@5.9.2_yaml@2.8.1/node_modules/astro/dist/runtime/server/transition.js:6:31)
    at async SSRCompatModuleRunner.directRequest (file:///Users/fubits/Developer/projects/portfolio-astro/node_modules/.pnpm/vite@6.3.6_@types+node@22.14.1_yaml@2.8.1/node_modules/vite/dist/node/module-runner.js:1284:61)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by ascorbic** [comment]
This looks like it's a CJS/ESM issue. The line of code in question is `module.exports = cssesc`. I'm not sure why it's specifically a problem in this circumstance though.

**Comment by fubits1** [comment]
for now I can only narrow it down to mdx in content collections (in my case: local md and mdx in content/notes/)

removing them from the content collection makes the build pass. mdx in pages (imported and rendered as Content) does not impact the build.

Also, removing e.g. Svelte components or Astro components from the content collection mdx does not fix the build.

I will set up a reprex as soon as time allows.

**Comment by PringlePot** [comment]
Any updates? This issue still occurs with mdx and cloudflare
