### ISSUE TITLE
Cannot find module 'cloudflare:email'

### ISSUE THREAD

**Issue by scruffymongrel** [withastro/astro#13159]
### Astro Info

```block
Astro                    v4.16.12
Node                     v22.2.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
```

### Describe the Bug

I'm trying to `import { EmailMessage } from 'cloudflare:email'` in an Astro page.

Normally this kinda import would be used in Workers just fine, but Astro seems unable to do the magic...

When I request the page, I get the following stack trace:

```
Error: Failed to load url cloudflare:email (resolved id: cloudflare:email) in /REDACTED_PATH/src/pages/for/enterprise.astro. Does the file exist?
    at loadAndTransform (file:///REDACTED_PATH/node_modules/.pnpm/vite@5.4.11_@types+node@22.9.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51920:17)
    at async instantiateModule (file:///REDACTED_PATH/node_modules/.pnpm/vite@5.4.11_@types+node@22.9.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52874:44)
```

I'm using the following `astro.config.js`:

```js
import { defineConfig } from 'astro/config'
import tailwind from '@astrojs/tailwind'

import cloudflare from '@astrojs/cloudflare'

export default defineConfig({
  adapter: cloudflare({
    imageService: 'passthrough',
    platformProxy: {
      enabled: true
    }
  }),
  integrations: [tailwind()],
  output: 'hybrid',
  vite: {
    ssr: {
      external: ['cloudflare:email']
    }
  }
})
```

### What's the expected result?

I would like for the page to render without error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6doees

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
The code linked by Alex should fix this. If you still face an issue with the latest version of the cloudflare adapter, please reopen

**Comment by taojoe** [comment]
hello, 

cloudflare now support email  local development, should the adapter be updated?
https://developers.cloudflare.com/email-routing/email-workers/local-development/

**Comment by taojoe** [comment]
this issue should be reopened.

**Comment by florian-lefebvre** [comment]
You're welcome to send a PR!

**Comment by alexanderniebuhr** [comment]
I have not checked the requirements, but do we know if we need to change the adapter. On the first look it should already work, and just needs a docs update maybe?

**Comment by florian-lefebvre** [comment]
I think `cloudflare:email` may need to be added to externals by the adapter?

**Comment by alexanderniebuhr** [comment]
I just read again and it states that it does only work with `wrangler dev`.. That means it will not work with `astro dev` and the current `PlatformProxy`, that will unblocked whenever we adopt Vite's new Environment API. Known that it should already work with `astro build` and `wrangler dev`. `astro dev` can't be supported due to the limitations I outlined.

**Comment by alexanderniebuhr** [comment]
As stated before it is [not supported](https://developers.cloudflare.com/workers/wrangler/api/#supported-bindings) by `getPlatformProxy`, so we can't do anything to support this in `astro dev`. I'll close this issue again, since we track potential usage of Vite's Environment API in different issues.
