### ISSUE TITLE
🐛 BUG: blog start template doesn't run

### ISSUE THREAD

**Issue by altano** [withastro/astro#1647]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When creating a `blog` starter using `npm init astro` I get a site that won't run. `npm run dev` gives me the error:

```
file:///home/alan/src/alan.norbauer.com-astro/node_modules/astro/dist/build/bundle/js.js:2
import {rollup} from "rollup";
        ^^^^^^
SyntaxError: Named export 'rollup' not found. The requested module 'rollup' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

### Steps to Reproduce

(using node v17.0.1)

1. `npm init astro` using template `blog`
4. `npm i`
5. `npm run dev`

```
alan@code ~/s/alan.norbauer.com-astro> npm i && npm run dev
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated vscode-emmet-helper@2.1.2: This package has been renamed to @vscode/emmet-helper, please update to the new name

added 908 packages, and audited 909 packages in 9s

194 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> @example/blog@0.0.1 dev
> astro dev

file:///home/alan/src/alan.norbauer.com-astro/node_modules/astro/dist/build/bundle/js.js:2
import {rollup} from "rollup";
        ^^^^^^
SyntaxError: Named export 'rollup' not found. The requested module 'rollup' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'rollup';
const {rollup} = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

**Comment by ubarilan** [comment]
I have the same issue but with a different library: `@fortawesome/free-brands-svg-icons`

Here's my code:
```ts
import {
    faGithub,
    faLinkedin,
    faDiscord,
} from "@fortawesome/free-brands-svg-icons";
```

Here's the error I'm getting:
``` 
error   Named export 'faGithub' not found. The requested module '@fortawesome/free-brands-svg-icons' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from '@fortawesome/free-brands-svg-icons';
  const { faGithub, faLinkedin, faDiscord } = pkg;
  ```

**Comment by stephanbogner** [comment]
**I had the same issue for `find-up` (using Astro version `1.3.0` on MacOS)**

- Running `npm install find-up` (to version `6.3.0`) fixed it ... but ...
- ... that is kinda weird because it seems [find-up is not a dependency in Astro 1.3.0 anymore](https://www.npmjs.com/package/astro/v/1.3.0?activeTab=dependencies) 🤷
- I honestly don't understand it. This happened just after I updated to Astro 1.3.0. Maybe the actual fix was running `npm install` again to get rid of some local conflicting versions. Unfortunately I can't reproduce it anymore but I am still gonna post this if somebody else discovers the same issue.

**Comment by narsiliko** [comment]
**I have the same problem with the `Vue3Marquee`**
Using `Astro 1.6.0`
Here is the console output:
```bash
$ npm run build

> @example/minimal@0.0.1 build
> astro build

16:38:00 [build] output target: static
16:38:00 [build] Collecting build info...
16:38:00 [build] Completed in 12ms.
16:38:00 [build] Building static entrypoints...
16:38:02 [build] Completed in 1.28s.

 building client 
Completed in 683ms.


 generating static routes 
 error   Named export 'Vue3Marquee' not found. The requested module 'vue3-marquee' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'vue3-marquee';
  const { Vue3Marquee } = pkg;
  
  File:
    file
  Stacktrace:
file:///home/***/dist/entry.mjs?time=1668584282824:4
/* empty css                                 */import { Vue3Marquee } from 'vue3-marquee';
                                                        ^^^^^^^^^^^
SyntaxError: Named export 'Vue3Marquee' not found. The requested module 'vue3-marquee' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue3-marquee';
const { Vue3Marquee } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async generatePages (file:///home/***/node_modules/astro/dist/core/build/generate.js:53:20)
    at async staticBuild (file:///home/***/node_modules/astro/dist/core/build/static-build.js:70:5)
    at async AstroBuilder.build (file:///home/***/node_modules/astro/dist/core/build/index.js:87:5)
    at async AstroBuilder.run (file:///home/***/node_modules/astro/dist/core/build/index.js:128:7)
    at async build (file:///home/***/node_modules/astro/dist/core/build/index.js:22:3)
    at async runCommand (file:///home/***/node_modules/astro/dist/cli/index.js:191:14)
```
