### ISSUE TITLE
🐛 BUG: Rehype & Remark do not support imported plugins

### ISSUE THREAD

**Issue by tkon99** [withastro/astro#2061]
### What version of `astro` are you using?

0.21.5

### What package manager are you using?

npm

### What operating system are you using?

Windows (reproduced in Linux)

### Describe the Bug

Remark and Rehype plugins only work when referenced by a string (e.g. 'rehype-slug') in the render config.
The [documentation ](https://docs.astro.build/guides/markdown-content/#:~:text=%5Bimport(%27remark%2Dautolink%2Dheadings%27)%2C%20%7B%20behavior%3A%20%27prepend%27%20%7D%5D%2C) specifically lists importing a plugin in the config as supported but this does not work.

It results in:
```
TypeError: Cannot read properties of undefined (reading 'call')
    at Function.freeze (file:///home/projects/github-4k6igf/node_modules/unified/lib/index.js:147:36)
    at Function.process (file:///home/projects/github-4k6igf/node_modules/unified/lib/index.js:386:15)
    at renderMarkdown (file:///home/projects/github-4k6igf/node_modules/@astrojs/markdown-remark/dist/index.js:88:121)
    at async renderMarkdownWithFrontmatter (file:///home/projects/github-4k6igf/node_modules/@astrojs/markdown-remark/dist/index.js:54:17)
    at async Context.load (file:///home/projects/github-4k6igf/node_modules/astro/dist/vite-plugin-markdown/index.js:46:28)
    at async Object.load (/home/projects/github-4k6igf/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:42399:32)
    at async doTransform (/home/projects/github-4k6igf/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:56704:24)
```

This results in the inability to use user-written plugins (outside of npm packages).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4k6igf?devtoolsheight=33&file=astro.config.mjs

**Comment by AnweshGangula** [comment]
is this issue fixed? I'm still facing this issue even when using v0.22.13
https://stackblitz.com/edit/github-4k6igf-nw8mnf?devtoolsheight=33&file=astro.config.mjs

**Comment by amykapernick** [comment]
I'm also having this issue on 0.22.20

**Comment by AnweshGangula** [comment]
I was able to get it to work in the following Stackblitz using `await` while importing `rehype-slug`:

https://stackblitz.com/edit/github-ajreza-yea7u7?file=astro.config.mjs
