### ISSUE TITLE
🐛 BUG: Can't use a less than symbol ( < ) within a markdown page

### ISSUE THREAD

**Issue by KenCorbettTruepic** [withastro/astro#2155]
### What version of `astro` are you using?

0.21.11

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

For some reason, any time there is a less than in the markdown it causes an `Unable to parse` error.

```
Unable to parse {"file":"/src/pages/index.astro","line":1,"column":4}
1  |  a < 3;
   |     ^
2  |  
3  |  ```
Error: Unable to parse {"file":"/src/pages/index.astro","line":1,"column":4}
1  |  a < 3;
   |     ^
2  |  
3  |  ```
    at traverseHtml (/home/projects/github-nkh4mv-yxvy4d/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:21232:15)
    at async devHtmlHook (/home/projects/github-nkh4mv-yxvy4d/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:56966:5)
    at async applyHtmlTransforms (/home/projects/github-nkh4mv-yxvy4d/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:21542:21)
    at async render (file:///home/projects/github-nkh4mv-yxvy4d/node_modules/astro/dist/core/ssr/index.js:209:12)
    at async Module.ssr (file:///home/projects/github-nkh4mv-yxvy4d/node_modules/astro/dist/core/ssr/index.js:228:12)
    at async AstroDevServer.handleRequest (file:///home/projects/github-nkh4mv-yxvy4d/node_modules/astro/dist/core/dev/index.js:231:20)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nkh4mv-yxvy4d?file=src%2Fpages%2Findex.astro

**Comment by tkon99** [comment]
Hi Ken, I am not sure what you are trying to accomplish here. Your Minimal Reproducible Example looks like it is using markdown syntax in a `.astro` file (which expects HTML tags, causing these errors). I see you are importing the `Markdown` component but it is not used.

To use markdown in Astro either:

1. Create a `.md` file and write markdown
2. Use the `<Markdown>` component in a `.astro` file

Please see the below stackblitz for an example of each of these (see `index.astro` and `index2.md`).
https://stackblitz.com/edit/github-nkh4mv-dtxpzv?file=src/pages/index.astro

If you have any further questions please reach out on [the discord server](https://astro.build/chat) for support.

**Comment by KenCorbettTruepic** [comment]
Ok, I see my mistake now.  Thanks for the response @tkon99!
