### ISSUE TITLE
🐛 BUG: Vite fails to load SCSS with @astro/renderer-lit

### ISSUE THREAD

**Issue by naiyerasif** [withastro/astro#2185]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When I use `@astro/renderer-lit` for components, Vite throws the following error and hence, the styles in SCSS files fail to load even though `sass` is installed. 

```sh
3:58:01 PM [vite] Internal server error: Preprocessor dependency "sass" not found. Did you install it?
  Plugin: vite:css
  File: /home/projects/github-rf8o2e/src/styles/main.scss?direct
      at loadPreprocessor (/home/projects/github-rf8o2e/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:20477:15)
      at scss (/home/projects/github-rf8o2e/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:20482:20)
      at compileCSS (/home/projects/github-rf8o2e/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:20219:40)
      at async TransformContext.transform (/home/projects/github-rf8o2e/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:19865:50)
      at async Object.transform (/home/projects/github-rf8o2e/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:42419:30)
      at async doTransform (/home/projects/github-rf8o2e/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:56766:29) (x2)
```

I checked the exact same setup with `@astro/renderer-svelte` and it works as expected.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rf8o2e

**Comment by jaydanurwin** [comment]
Just ran into this today and didn't realize the renderer was the issue. Thanks for filing this!

**Comment by FredKSchott** [comment]
Still not sure what's going on here, but I confirmed that this is fixed by https://github.com/withastro/astro/pull/2323

**Comment by Enteleform** [comment]
Still experiencing this issue. Currently have all 6 renderers enabled @ `astro.config.mjs/renderers`.

The error is no longer thrown after disabling `@astrojs/renderer-lit`.

**Comment by jaydanurwin** [comment]
I believe this is being worked on over on the Lit repo here:

https://github.com/lit/lit/issues/2393#issuecomment-1018676367
