### ISSUE TITLE
🐛 BUG: .astro files break when adding apostrophe to HTML's title tag

### ISSUE THREAD

**Issue by Yan-Thomas** [withastro/astro#2395]
### What version of `astro` are you using?

0.22.13

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When adding an apostrophe to any HTML title tag on .astro files, you get an Internal Error with a cryptic/misleading error message.

Error log in the minimal reproducible example:
```
/home/projects/github-kmp3ni-fqobhy/src/pages/index.astro: Unexpected "..."

Error: Transform failed with 1 error:
/home/projects/github-kmp3ni-fqobhy/src/pages/index.astro:32:12: error: Unexpected "..."
    at failureErrorWithLog (/home/projects/github-kmp3ni-fqobhy/node_modules/esbuild/lib/main.js:1493:15)
    at eval (/home/projects/github-kmp3ni-fqobhy/node_modules/esbuild/lib/main.js:1282:29)
    at eval (/home/projects/github-kmp3ni-fqobhy/node_modules/esbuild/lib/main.js:629:9)
    at handleIncomingPacket (/home/projects/github-kmp3ni-fqobhy/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/projects/github-kmp3ni-fqobhy/node_modules/esbuild/lib/main.js:596:7)
    at Socket.EventEmitter.emit (https://github-kmp3ni-fqobhy.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:126633)
    at addChunk (https://github-kmp3ni-fqobhy.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:508416)
    at readableAddChunk (https://github-kmp3ni-fqobhy.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:508137)
    at Socket.Readable.push (https://github-kmp3ni-fqobhy.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:508804)
    at _0x212164.onStreamRead [as onread] (https://github-kmp3ni-fqobhy.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:535934)
```

If, useful, you can also check the error log of when I found the bug in my personal project:
```
C:/Users/Pichau/Documents/Projects/yanthomas-dev/src/layouts/BlogPostsLayout.astro: Expected ">" but found "post"

Error: Transform failed with 1 error:
C:/Users/Pichau/Documents/Projects/yanthomas-dev/src/layouts/BlogPostsLayout.astro:60:47: error: Expected ">" but found "post"
    at failureErrorWithLog (C:\Users\Pichau\Documents\Projects\yanthomas-dev\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\Pichau\Documents\Projects\yanthomas-dev\node_modules\esbuild\lib\main.js:1282:29
    at C:\Users\Pichau\Documents\Projects\yanthomas-dev\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\Users\Pichau\Documents\Projects\yanthomas-dev\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\Users\Pichau\Documents\Projects\yanthomas-dev\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

I'm giving a look at the Astro codebase, If I find anything useful or a solution I will add a comment here and/or make a PR!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kmp3ni-fqobhy?file=src/pages/index.astro

**Comment by boehs** [comment]
another error generated by the following code

```
---
// Component imports and setup JavaScript go here!
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>Welcome to Astro'</title>
		<style>
			/* scoped CSS styles go here: */
		</style>
	</head>

	<body>
		<h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
	</body>
</html>
```

(I removed `/* h1 { ... } */`)

The following is generated:

```
Unable to parse {"file":"/src/pages/index.astro","line":46,"column":1}
43 |  		<h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
44 |  	</body>
45 |  </html>
   |          ^
46 |  </title></head><body></body></html>
Error: Unable to parse {"file":"/src/pages/index.astro","line":46,"column":1}
43 |  		<h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
44 |  	</body>
45 |  </html>
   |          ^
46 |  </title></head><body></body></html>
    at traverseHtml (/home/projects/github-kmp3ni-mfacby/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:21232:15)
    at async devHtmlHook (/home/projects/github-kmp3ni-mfacby/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:56966:5)
    at async applyHtmlTransforms (/home/projects/github-kmp3ni-mfacby/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:21542:21)
    at async render (file:///home/projects/github-kmp3ni-mfacby/node_modules/astro/dist/core/ssr/index.js:212:12)
    at async Module.ssr (file:///home/projects/github-kmp3ni-mfacby/node_modules/astro/dist/core/ssr/index.js:231:12)
    at async AstroDevServer.handleRequest (file:///home/projects/github-kmp3ni-mfacby/node_modules/astro/dist/core/dev/index.js:235:20)
```

**Comment by jonathantneal** [comment]
Confirmed in latest Astro. I believe this is a compiler issue.
