### ISSUE TITLE
🐛 BUG: Using a slash character in a nested template literal in a component prop throws an error

### ISSUE THREAD

**Issue by edazpotato** [withastro/astro#2418]
### What version of `astro` are you using?

0.22.14

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When using a slash character (`/`) inside of a nested template literal in a component prop, an error is thrown.
Example code:
```astro
---
import TestComponent from '../components/TestComponent.astro';
const enviroment: "dev" | "prod" = "dev";
---
<!-- note how removing the slash from the string below fixes the error -->
<TestComponent text={`${enviroment === "dev" ? `Test / Development` : "Production"} text`} />
```
Error message:
```
Error: Transform failed with 1 error:
/home/projects/github-sw4whj-uv9buh/src/pages/index.astro:27:219: error: Expected "}" but found ")"
    at failureErrorWithLog (/home/projects/github-sw4whj-uv9buh/node_modules/esbuild/lib/main.js:1493:15)
    at eval (/home/projects/github-sw4whj-uv9buh/node_modules/esbuild/lib/main.js:1282:29)
    at eval (/home/projects/github-sw4whj-uv9buh/node_modules/esbuild/lib/main.js:629:9)
    at handleIncomingPacket (/home/projects/github-sw4whj-uv9buh/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/projects/github-sw4whj-uv9buh/node_modules/esbuild/lib/main.js:596:7)
    at Socket.EventEmitter.emit (https://github-sw4whj-uv9buh.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:126633)
    at addChunk (https://github-sw4whj-uv9buh.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:508416)
    at readableAddChunk (https://github-sw4whj-uv9buh.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:508137)
    at Socket.Readable.push (https://github-sw4whj-uv9buh.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:508804)
    at _0x212164.onStreamRead [as onread] (https://github-sw4whj-uv9buh.w.staticblitz.com/blitz.d4ed89204e54de5c40d109298317e6dc4d60aef7.js:6:535934)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sw4whj-uv9buh?file=src/pages/index.astro

**Comment by jonathantneal** [comment]
Confirmed. This appears related to the compiler.
