### ISSUE TITLE
🐛 BUG: TypeError: Cannot read properties of undefined (reading 'split') processing .env

### ISSUE THREAD

**Issue by jladmore** [withastro/astro#2577]
### What version of `astro` are you using?

0.23.0-next.6

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When the .env file has the following environment variable defined

PUBLIC_CURRENCY_SYMBOL="$"

we get a crash upon build 

Jonathons-MacBook-Pro:crayons-astro jono$ npm run dev

> @example/starter@0.0.1 dev
> astro dev

TypeError: Cannot read properties of undefined (reading 'split')
    at /Users/jono/Development/crayons-astro/node_modules/vite/dist/node/chunks/dep-1412e872.js:70782:33
    at Array.reduce (<anonymous>)
    at _interpolate (/Users/jono/Development/crayons-astro/node_modules/vite/dist/node/chunks/dep-1412e872.js:70768:18)
    at expand (/Users/jono/Development/crayons-astro/node_modules/vite/dist/node/chunks/dep-1412e872.js:70812:32)
    at loadEnv (/Users/jono/Development/crayons-astro/node_modules/vite/dist/node/chunks/dep-1412e872.js:71436:13)
    at resolveConfig (/Users/jono/Development/crayons-astro/node_modules/vite/dist/node/chunks/dep-1412e872.js:70919:9)
    at async Object.createServer (/Users/jono/Development/crayons-astro/node_modules/vite/dist/node/chunks/dep-1412e872.js:56404:20)
    at async dev (file:///Users/jono/Development/crayons-astro/node_modules/astro/dist/core/dev/index.js:20:22)
    at async cli (file:///Users/jono/Development/crayons-astro/node_modules/astro/dist/cli/index.js:83:9)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-owsap7?

**Comment by jladmore** [comment]
This was not happening on ^0.22.20

**Comment by jonathantneal** [comment]
Yes, it seems something is relying on this being a string without converting it into a string.

**Comment by FredKSchott** [comment]
Confirmed fixed in v0.24.0
