### ISSUE TITLE
🐛 BUG: Loss of reactivty in production build if hydrated component is used in md

### ISSUE THREAD

**Issue by yoroshikun** [withastro/astro#2592]
### What version of `astro` are you using?

0.23.0-beta.6

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When using any of the beta versions (tested 3 4 and 6) if a markdown file imports a component (.astro in this case) and opts to use hydration (client:load in this case as per the blog example) by importing the components though the setup frontmatter, this will effectively remove reactivity from the app as the vendor js errors. Same issue has appeared in both preact and react that i have tested so far.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at vendor.474e8c50.js:19:1211
    at vendor.474e8c50.js:19:1861
```

Issue only occurs when in production after building and running though the preview

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ggd64w?file=src/pages/other.md

**Comment by bholmesdev** [comment]
Hm, looks like you were applying a `client` directive to a `.astro` component in that example. Astro components are not hydrate-able just to clarify ([see docs](https://docs.astro.build/en/core-concepts/framework-components/#can-i-hydrate-astro-components))!

In any case, we bumped to the latest `0.24` and attempted to use the same `Counter` inside that markdown file. Looks like this is working as expected. Feel free to re-open if you're still running into trouble!
