### ISSUE TITLE
🐛 BUG: vite:import-analysis error with `vercel dev`

### ISSUE THREAD

**Issue by JuanM04** [withastro/astro#2639]
### What version of `astro` are you using?

0.23.0

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

**Steps to reproduce**
1. `npm init astro` (I used the minimal template)
2. `vercel link`
3. Set the development command to `astro dev --port $PORT`
4. `vercel dev`

This error will be thrown no matter which page you open:

```
[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: /home/juanm04/dev/tests/test-vercel/src/pages/index.astro?html-proxy=&index=0.js
  6  |                  <meta charset="utf-8" />
  7  |                  <meta name="viewport" content="width=device-width" />
  8  |                  <title>Astro</title>
     |                        ^
  9  |          </head>
  10 |          <body>
      at formatError (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38082:46)
      at TransformContext.error (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38078:19)
      at TransformContext.transform (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:69759:22)
      at async Object.transform (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38318:30)
      at async doTransform (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:53014:29)
```

### Link to Minimal Reproducible Example

Described above

**Comment by arnoson** [comment]
I still have this problem with astro `1.0.0-beta.27` on windows 10
using this code in my `index.astro` page
```js
<main>{projects.map(project => <Project project={project} />)}</main>
```

throws this error:
```
[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make 
sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
```
