### ISSUE TITLE
🐛 BUG: export split across multiple lines is erroneously an error

### ISSUE THREAD

**Issue by nhynes** [withastro/astro#2688]
### What version of `astro` are you using?

0.23.2

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

If the first line of the frontmatter is `export const = '...';` and the rvalue is long and gets moved to the next line due to e.g., prettier, esbuild will raise the following complaint:
```
 error: Unexpected "export"
    at failureErrorWithLog (/.../node_modules/.pnpm/esbuild@0.13.7/node_modules/esbuild/lib/main.js:1493:15)
    at /.../node_modules/.pnpm/esbuild@0.13.7/node_modules/esbuild/lib/main.js:1282:29
    at /.../node_modules/.pnpm/esbuild@0.13.7/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/.../node_modules/.pnpm/esbuild@0.13.7/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/.../node_modules/.pnpm/esbuild@0.13.7/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/great-swanson-9gsjjn

**Comment by natemoo-re** [comment]
Looks like this works fine in plain `esbuild`, so I'm betting our compiler is outputting incorrect JS.
