### ISSUE TITLE
🐛 BUG: `astro dev` exits when `sass` is enabled and a file is moved

### ISSUE THREAD

**Issue by eti0** [withastro/astro#2858]
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

it seems like either `vite` or `astro dev` crashes when a file is moved around. this occurs when `sass` is used.
to reproduce, use the stackblitz example and move `src/pages/another-page.astro` to some other directory.

on stackblitz the process keeps running despite the error, but getting the error locally exits the `astro dev` process.

this issue occurs with either `npm` or `pnpm`, i haven't tried with `yarn` though.

<details>
<summary>example crash log</summary>

```
(node:11) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'file')
    at handleFileAddUnlink (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:53637:60)
    at FSWatcher.eval (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:56569:9)
    at FSWatcher.EventEmitter.emit (https://github-cse1kf.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:131338)
    at FSWatcher.emitWithAll (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:44571:8)
    at FSWatcher._emit (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:44663:8)
    at NodeFsHandler$1._handleFile (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:43253:14)
    at NodeFsHandler$1._addToNodeFs (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:43490:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'file')
    at handleFileAddUnlink (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:53637:60)
    at FSWatcher.eval (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:56572:9)
    at FSWatcher.EventEmitter.emit (https://github-cse1kf.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:131338)
    at eval (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:44612:16)
    at Map.forEach (<anonymous>)
    at Timeout.eval [as _onTimeout] (/home/projects/github-cse1kf/node_modules/vite/dist/node/chunks/dep-9c153816.js:44611:30)
    at listOnTimeout (https://github-cse1kf.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:289777)
    at processTimers (https://github-cse1kf.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:290592)
    at https://github-cse1kf.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:15:197005
    at https://github-cse1kf.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:15:197316
(node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

</details>

i'm not really sure if it's a vite kind of issue or an astro one. hopefully this is an easy fix.

in the meantime, i don't mind getting the error printed out to my shell, the only bother is that the process gets shut down as soon as the error happens. if there is some way to just "ignore" the error message and keep the process running, i'd love to know about it.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cse1kf?file=src/components/Button.astro

**Comment by FredKSchott** [comment]
I believe this was fixed in a recent version of Vite. If you can update your repro to the latest version of Astro and you can still reproduce, please create another issue!
