### ISSUE TITLE
🐛 BUG: Crash when running `rmdirSync` on `dist` (after running `yarn build`)

### ISSUE THREAD

**Issue by obj-obj** [withastro/astro#2881]
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

yarn (berry)

### What operating system are you using?

Linux

### Describe the Bug

Crash when removing `dist` directory (after running `yarn build`).
Manually running `rm -rf dist` before `yarn build` fixes it.
Not sure exactly what's causing the error, I am currently dying of homework so I will isolate the error later

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Buffer
at new NodeError (node:internal/errors:372:5)
at validateString (node:internal/validators:120:11)
at Object.isAbsolute (node:path:1157:5)
at VirtualFS.mapToBase (/home/objobj/code/quiltmc.org/.pnp.cjs:9075:24)
at VirtualFS.rmdirSync (/home/objobj/code/quiltmc.org/.pnp.cjs:8924:39)
at PosixFS.rmdirSync (/home/objobj/code/quiltmc.org/.pnp.cjs:8924:24)
at URLFS.rmdirSync (/home/objobj/code/quiltmc.org/.pnp.cjs:8924:24)
at _rmdirSync (node:internal/fs/rimraf:260:21)
at rimrafSync (node:internal/fs/rimraf:193:7)
at node:internal/fs/rimraf:253:9
```

### Link to Minimal Reproducible Example

I must do homework so I will isolate the error and post an example later

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by obj-obj** [comment]
Either yarn being scuffed or it got fixed (I switched to `pnpm`)
