### ISSUE TITLE
🐛 BUG: Svelte components crash dev if imported with a shortened path

### ISSUE THREAD

**Issue by Tc-001** [withastro/astro#2921]
### What version of `astro` are you using?

0.25.3

### What package manager are you using?

yarn / npm / pnpm

### What operating system are you using?

Linux

### Describe the Bug

# How to reproduce

1. Create a project with a svelte integration
2. Place this in `tsconfig.json`:
```js
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "component:*": [
        "src/components/*"
      ]
    },
  }
}
```
3. Create a `components/Foo.svelte`, leave it empty
4. In `index.astro` write the following:
```astro
---
//import Foo from "component:Foo.svelte"
import Foo from "../components/Foo.svelte"
---
<Foo client:only/>
```
5. Run dev server
6. Notice everything working
7. Swap the commented/uncommented lines
8. Notice it failing with an error:
```
Cannot read property 'endsWith' of null

TypeError: Cannot read property 'endsWith' of null
    at ModuleGraph.resolveUrl (/sandbox/node_modules/vite/dist/node/chunks/dep-9c153816.js:53501:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.resolve (file:///sandbox/node_modules/astro/dist/core/render/dev/index.js:96:45)
    at async Module.generateHydrateScript (/node_modules/astro/dist/runtime/server/hydration.js:61:152)
    at async Module.renderComponent (/node_modules/astro/dist/runtime/server/index.js:225:22)
    at async _render (/node_modules/astro/dist/runtime/server/index.js:43:11)
    at async renderAstroComponent (file:///sandbox/node_modules/astro/dist/runtime/server/index.js:389:20)
    at async renderPage (file:///sandbox/node_modules/astro/dist/runtime/server/index.js:346:20)
    at async render (file:///sandbox/node_modules/astro/dist/core/render/core.js:86:14)
    at async render (file:///sandbox/node_modules/astro/dist/core/render/dev/index.js:85:17)
```

# Issue

The error (likely) comes from these lines here in vite:
https://github.com/vitejs/vite/blob/4ffd82d2d4759bc3efa368bca54613aaa1f45acc/packages/vite/src/node/server/moduleGraph.ts#L222-L223

Because in our case, `url === "component:Foo.svelte"`, the parse for pathname will return null, erroring the subsequent check.

This is only a surface level analysis, and the root issue may be elsewhere. I do not know enough about how Astro interacts with vite to say.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/bold-hill-yxjkmw?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Tc-001** [comment]
Forgot to say, but it seems to build just fine.

**Comment by FredKSchott** [comment]
Oh wow! I'm surprised this breaks / maybe we're using that method incorrectly.

we might need to move this up higher to happen before `resolveUrl()` gets called: 
```
if (!resolvedUrl.startsWith(".") && !resolvedUrl.startsWith("/")) {
  return "/@id" + prependForwardSlash(resolvedUrl);
}
```

**Comment by tony-sull** [comment]
Haven't had a chance to fully track this down yet, but this is hit in our server runtime where it tries to generate the hydration script [here](https://github.com/withastro/astro/blob/be899fdd1a5408e41e63a5f7c8be7753a8fafda8/packages/astro/src/runtime/server/hydration.ts#L100)

Astro probably just needs to account for these path shorthands when resolving component file URLs
