### ISSUE TITLE
🐛 BUG: Adding via PNPM or manual install fails due to missing peer dependency

### ISSUE THREAD

**Issue by itrew** [withastro/astro#3032]
### What version of `astro` are you using?

1.0.0-beta.5

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When trying to add svelte to the project using `pnpx astro add svelte` I get the following error:

```
✖ Installing dependencies...
 error   Astro could not update your astro.config.js file safely.
  Reason: Unable to install dependencies

  You will need to add these integration(s) manually.
  Documentation: https://docs.astro.build/en/guides/integrations-guide/
    at add (file:///C:/Users/IANTRE~1/AppData/Local/Temp/dlx-6344/5/node_modules/.pnpm/astro@1.0.0-beta.5/node_modules/astro/dist/core/add/index.js:157:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cli (file:///C:/Users/IANTRE~1/AppData/Local/Temp/dlx-6344/5/node_modules/.pnpm/astro@1.0.0-beta.5/node_modules/astro/dist/cli/index.js:91:16)
 ERROR  Command failed with exit code 1: C:\Users\Ian Trewella\AppData\Local\pnpm\astro.CMD add svelte
```

Next, trying to install the integration manually (with the known peer dependency Svelte) using `pnpm add -D svelte @astrojs/svelte` I get the following error:

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @astrojs/svelte
  └─┬ @sveltejs/vite-plugin-svelte
    └── ✕ missing peer vite@^2.9.0
Peer dependencies that should be installed:
  vite@^2.9.0
```

This hints at a missing Vite dependency, even though Vite@^2.9.1 is a [dependency of Astro](https://github.com/withastro/astro/blob/d1f292199ce309c55c57827a8de0409bd73bb3e8/packages/astro/package.json#L135) and is already installed.

### Link to Minimal Reproducible Example

Can't figure out how to install PNPM on these sandboxes.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by itrew** [comment]
Same issue when trying to manually install the Vue integration using `pnpm add -d @astrojs/vue vue@^3.2.30`.

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @astrojs/vue
  └─┬ @vitejs/plugin-vue
    └── ✕ missing peer vite@^2.5.10
Peer dependencies that should be installed:
  vite@^2.5.10
```

**Comment by natemoo-re** [comment]
Do you have `shamefully-hoist` enabled? That might fix it!

**Comment by itrew** [comment]
Yes, in the .npmrc file in the project folder. Was generated as part of the Astro 'Minimal' start.

```
# Expose Astro dependencies for `pnpm` users
shamefully-hoist=true
```

**Comment by itrew** [comment]
Adding the following PNPM config to my `package.json` fixed the issue for now. Not sure if that is a long term solution or not.

```
 "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "@babel/core",
        "@babel/plugin-transform-react-jsx",
        "vite"
      ]
    }
  },
```

**Comment by jcayzac** [comment]
> Do you have `shamefully-hoist` enabled? That might fix it!

While a working workaround, can we please not call this a "fix", and reopen this issue? This basically disable most of what pnpm is about.
