### ISSUE TITLE
🐛 BUG: Can't use certain Solid based UI libraries

### ISSUE THREAD

**Issue by naomiHauret** [withastro/astro#3076]
### What version of `astro` are you using?

1.0.0-beta.7

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Solid based UI libraries like `solid-reach`, `@guillotin/solid`,  `solid-headless` or `@suid/material` crash the project with the following error: 

```
 error   Unable to render ModalSolidHeadless!
  
  There is 1 renderer configured in your `astro.config.mjs` file,
  but it was not able to server-side render ModalSolidHeadless.
  
  Did you mean to enable `@astrojs/react`, `@astrojs/preact`, `@astrojs/vue` or `@astrojs/svelte`?
    at Module.renderComponent (/@fs/workspace/astro/packages/astro/dist/runtime/server/index.js:187:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) (x7)
4:18:55 PM [vite] Internal server error: Failed to resolve entry for package "/workspace/astro/examples/framework-solid/". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "/workspace/astro/examples/framework-solid/". The package may have incorrect main/module/exports specified in its package.json.
      at packageEntryFailure (/workspace/astro/node_modules/.pnpm/vite@2.9.1_sass@1.50.0/node_modules/vite/dist/node/chunks/dep-611778e0.js:38290:11)
      at resolvePackageEntry (/workspace/astro/node_modules/.pnpm/vite@2.9.1_sass@1.50.0/node_modules/vite/dist/node/chunks/dep-611778e0.js:38286:9)
      at tryResolveFile (/workspace/astro/node_modules/.pnpm/vite@2.9.1_sass@1.50.0/node_modules/vite/dist/node/chunks/dep-611778e0.js:38002:38)
      at tryFsResolve (/workspace/astro/node_modules/.pnpm/vite@2.9.1_sass@1.50.0/node_modules/vite/dist/node/chunks/dep-611778e0.js:37984:16)
      at Context.resolveId (/workspace/astro/node_modules/.pnpm/vite@2.9.1_sass@1.50.0/node_modules/vite/dist/node/chunks/dep-611778e0.js:37820:28)
      at Object.resolveId (/workspace/astro/node_modules/.pnpm/vite@2.9.1_sass@1.50.0/node_modules/vite/dist/node/chunks/dep-611778e0.js:36470:55)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async ModuleGraph.resolveUrl (/workspace/astro/node_modules/.pnpm/vite@2.9.1_sass@1.50.0/node_modules/vite/dist/node/chunks/dep-611778e0.js:56090:26)
      at async ModuleGraph.getModuleByUrl (/workspace/astro/node_modules/.pnpm/vite@2.9.1_sass@1.50.0/node_modules/vite/dist/node/chunks/dep-611778e0.js:55970:23)

```

Using `client:only` will prevent the crash but won't render the component.

### Link to Minimal Reproducible Example

https://withastro-astro-yz4pyg8icjb.ws-eu38.gitpod.io/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Vite loads npm packages with regular Node.js, and you can't import a `.jsx` file in Node. So if you want to use these packages you need to mark them as `noExternal` which tells Vite to compile them the same way it compiles your local code.

See this example: https://stackblitz.com/edit/github-4eracq?file=astro.config.mjs&on=stackblitz
