### ISSUE TITLE
🐛 BUG: Can't use variable in an HTML table's <caption>?

### ISSUE THREAD

**Issue by sarah11918** [withastro/astro#3091]
### What version of `astro` are you using?

1.0.0 beta 8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

CodeSandbox

### Describe the Bug

When I try to use a variable (instead of plain text) inside a `<table>`'s `<caption>` tag, all manner of weird things happen.
e.g.
```
---
const myCaption = "TEST"
---
<table>
 <caption>{myCaption}</caption>
...
</table>
```

In my project on Gitpod, I get a 500 error and need to restart the dev server:

```
Transform failed with 1 error:
/workspace/bowl/src/pages/leaderboards.astro:64:214: ERROR: Expected ")" but found "}"
Error: Transform failed with 1 error:
/workspace/bowl/src/pages/leaderboards.astro:64:214: ERROR: Expected ")" but found "}"
    at failureErrorWithLog (/workspace/bowl/node_modules/esbuild/lib/main.js:1603:15)
    at /workspace/bowl/node_modules/esbuild/lib/main.js:1392:29
    at /workspace/bowl/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/workspace/bowl/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/workspace/bowl/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

A minimal reproduction on CodeSandbox does not give an error, but the table does lose its "tableness" (and in another attempt, the caption was both causing the table not to render as a table AND displaying BELOW the (no-longer-a-)table. 

NOTE: I can seem to put the variable in any other part of the table, just not the caption.

![Screenshot 2022-04-12 11 32 24](https://user-images.githubusercontent.com/5098874/162987047-a7b26b53-e465-41a7-b324-6a848e6ad38a.png)
![Screenshot 2022-04-12 11 31 58](https://user-images.githubusercontent.com/5098874/162987051-d6580e3e-0593-4feb-8597-a9d80d58990d.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/exciting-water-k6n2x8?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dasDaniel** [comment]
looks like `inCaptionIM` doesn't handle expressions (no `StartExpressionToken` and `EndExpressionToken` cases)
in https://github.com/withastro/compiler/blob/main/internal/parser.go#L1833

While not valid html, using an expression in `<colgroup>` has the same result - it closes the `table` and `body` tags prematurely.

**Comment by matthewp** [comment]
Awesome investigation work @dasDaniel! Any chance you'd be able to submit a fix?

**Comment by dasDaniel** [comment]
> Awesome investigation work @dasDaniel! Any chance you'd be able to submit a fix?

thanks, I'm not really setup to for golang ATM (nor done any golang yet), so would take me a while to get a PR ready.

**Comment by natemoo-re** [comment]
Going to transfer this to the compiler repo! I bet I can fix this soon.
