### ISSUE TITLE
🐛 BUG: `@astrojs/compiler` panic

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#3111]
%23%23%23 Describe the Bug
    
    `@astrojs/compiler` encountered an unrecoverable error when compiling the following file.
    
    **src/components/ConfigOption.astro**
    ```astro
    ---
import { Code, Markdown } from 'astro/components'

**Comment by jasikpark** [comment]
To Reproduce: install and build https://github.com/DefinedNet/nebula-docs/pull/23

**Comment by jasikpark** [comment]
```
> astro build

03:48:19 PM [config] Set "buildOptions.site" to generate correct canonical URLs and sitemap
03:48:19 PM [build] Initial setup...
03:48:19 PM [build] Collecting page data...
panic: html: bad parser state: originalIM was set twice

goroutine 13 [running]:
github.com/withastro/compiler/internal.(*parser).setOriginalIM(...)
        github.com/withastro/compiler/internal/parser.go:531
github.com/withastro/compiler/internal.inHeadIM(0x47a900)
        github.com/withastro/compiler/internal/parser.go:910 +0x227
github.com/withastro/compiler/internal.(*parser).parseCurrentToken(0x47a900)
        github.com/withastro/compiler/internal/parser.go:2782 +0x13
github.com/withastro/compiler/internal.(*parser).parse(0x47a900)
        github.com/withastro/compiler/internal/parser.go:2809 +0x3
github.com/withastro/compiler/internal.ParseWithOptions({0x6f880, 0x430e20}, {0x0, 0x0, 0x0})
        github.com/withastro/compiler/internal/parser.go:2869 +0x18
github.com/withastro/compiler/internal.Parse(...)
        github.com/withastro/compiler/internal/parser.go:2826
main.Transform.func1.1.1({0x456500, 0x128}, 0x4485a0, {{}, 0x7ff8000400000085, 0x59ee88})
        ./astro-wasm.go:186 +0xb
created by main.Transform.func1.1
        ./astro-wasm.go:183 +0x3
exit code: 2
Error: Uh oh, the Astro compiler encountered an unrecoverable error!
    
    Please open
    a GitHub issue using the link below:
    https://github.com/withastro/astro/issues/new?labels=compiler&title=%F0%9F%90%9B+BUG%3A+%60%40astrojs%2Fcompiler%60+panic&body=%23%23%23+Describe+the+Bug%0A++++%0A++++%60%40astrojs%2Fcompiler%60+encountered+an+unrecoverable+error+when+compiling+the+following+file.%0A++++%0A++++**src%2Fcomponents%2FConfigOption.astro**%0A++++%60%60%60astro%0A++++---%0Aimport+%7B+Code%2C+Markdown+%7D+from+%27astro%2Fcomponents%27%3B%0A%0Aconst+%7BisRequired%2C+description%2C+example%7D+%3D+Astro.props%3B%0A---%0A%0A%3Cslot%2F%3E%0A%7BisRequired+%26%26+%3Cp+class%3D%22mt-16+badge+badge-info%22%3ERequired%3C%2Fp%3E%7D%0A%7Bdescription%3F.trim%28%29+%26%26+%3CMarkdown+content%3D%7Bdescription%7D%2F%3E%7D%0A%7Bexample+%26%26+%3CCode+code%3D%7Bexample%7D+lang%3D%27yaml%27+%2F%3E%7D%0A%0A++++%60%60%60%0A++++
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
Go program has already exited
3:48:21 PM [vite] Error when evaluating SSR module /workspace/nebula-docs/src/pages/nebula/[locale]/[slug].astro:
Error: Go program has already exited
    at Go._resume (file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/wasm_exec.js:435:19)
    at Object.transform (file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/wasm_exec.js:447:16)
    at file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/index.js:41:82
    at new Promise (<anonymous>)
    at Object.transform (file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/index.js:41:40)
    at file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/index.js:5:51
Error: Go program has already exited
    at Go._resume (file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/wasm_exec.js:435:19)
    at Object.transform (file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/wasm_exec.js:447:16)
    at file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/index.js:41:82
    at new Promise (<anonymous>)
    at Object.transform (file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/index.js:41:40)
    at file:///workspace/nebula-docs/node_modules/@astrojs/compiler/node/index.js:5:51
```

for the full shell output
