### ISSUE TITLE
🐛 BUG: Components in dynamically imported markdown break prod builds

### ISSUE THREAD

**Issue by bholmesdev** [withastro/astro#3134]
### What version of `astro` are you using?

1.0.0-beta.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm, pnpm

### What operating system are you using?

Mac

### Describe the Bug

I import a Svelte component into a markdown file using the `setup` script:

```md
---
setup: import DynamicVisual from './DynamicVisual.svelte'
---
<DynamicVisual client:load />
```
Then, I load this markdown onto a `.astro` page using `Astro.glob`:

```astro
---
const articles = await Astro.glob('../components/*.md')
---
...
{articles.map(article => <article.Content />)}
```

This raises an exception during production builds:
```bash
Error: Cannot find the built path for /src/components/DynamicVisual.svelte
      at Object.resolve (file:///Users/benholmes/Repositories/astro/packages/astro/dist/core/build/generate.js:137:15)
      at generateHydrateScript (file:///Users/benholmes/Repositories/astro/packages/astro/test/fixtures/astro-markdown-css/dist/entry.mjs:102:165)
      at renderComponent (file:///Users/benholmes/Repositories/astro/packages/astro/test/fixtures/astro-markdown-css/dist/entry.mjs:452:28)
```

**Extra details**
- this does not occur on development server
- `await import` has the same effect as `Astro.glob`
- changing the `client` directive to `client:only` has no effect
- following the stacktrace, this occurs in [the `hydration.ts` file](https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/server/hydration.ts#L128-L136) where components are resolved to their bundled chunks
- digging into the `dist` result for that markdown file, I noticed the component details were in-lined instead of splitting to a separate chunk. Maybe that's the cause? Example output:

```js
// chunks/chunk.XXXX.mjs
import { e as create_ssr_component, f as escape, c as createMetadata, a as createAstro, b as createComponent, r as render, d as renderComponent } from '../entry.mjs';
import 'shorthash';
import 'html-escaper';
import 'serialize-javascript';

var DynamicVisual_svelte_svelte_type_style_lang = '';

/* test/fixtures/astro-markdown-css/src/components/DynamicVisual.svelte generated by Svelte v3.47.0 */

const css = {
	code: "button.svelte-1b7ffas{color:#f00}",
	map: null
};

const DynamicVisual = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let count = 0;
	$$result.css.add(css);
	return `<button class="${"svelte-1b7ffas"}">Count up ${escape(count)}</button>`;
});

var $$module1 = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	'default': DynamicVisual
}, Symbol.toStringTag, { value: 'Module' }));

const metadata = { "headers": [{ "depth": 1, "slug": "example-markdown-document-with-a-more-visuals", "text": "Example markdown document, with a more Visuals" }], "source": "\n# Example markdown document, with a more Visuals\n\n<DynamicVisual client:load />\n", "html": '<h1 id="example-markdown-document-with-a-more-visuals">Example markdown document, with a more Visuals</h1>\n<DynamicVisual client:load />' };
const frontmatter = { "astro": { "headers": [{ "depth": 1, "slug": "example-markdown-document-with-a-more-visuals", "text": "Example markdown document, with a more Visuals" }], "source": "\n# Example markdown document, with a more Visuals\n\n<DynamicVisual client:load />\n", "html": '<h1 id="example-markdown-document-with-a-more-visuals">Example markdown document, with a more Visuals</h1>\n<DynamicVisual client:load />' } };
const $$metadata = createMetadata("/src/markdown/article2.md", { modules: [{ module: $$module1, specifier: "../components/DynamicVisual.svelte", assert: {} }], hydratedComponents: [DynamicVisual], clientOnlyComponents: [], hydrationDirectives: /* @__PURE__ */ new Set(["load"]), hoisted: [] });
const $$Astro = createAstro("/src/markdown/article2.md", "https://astro.build", "file:///Users/benholmes/Repositories/astro/packages/astro/test/fixtures/astro-markdown-css/");
const $$Article2 = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Article2;
  return render`<h1 id="example-markdown-document-with-a-more-visuals">Example markdown document, with a more Visuals</h1>
${renderComponent($$result, "DynamicVisual", DynamicVisual, { "client:load": true, "client:component-hydration": "load", "client:component-path": $$metadata.getPath(DynamicVisual), "client:component-export": $$metadata.getExport(DynamicVisual) })}`;
});

export { $$metadata, $$Article2 as default, frontmatter, metadata };
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ycz8vp-kddjya?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Tc-001** [comment]
Can reproduce it in `1.0.0-beta.17` by doing `import {Content} from "../components/test.md"` where `test.md` imports and uses a svelte component

https://codesandbox.io/s/tender-volhard-dsgbtq (fork the sandbox, create a new terminal, run `yarn run build`)

**Comment by Tc-001** [comment]
🤔  It could be triggered by hydrating components of md files in general

**Comment by robinloeffel** [comment]
Hey everyone! I'm somehow still able to reproduce this bug. I'm using `v1.9.2` of Astro and `v1.0.2` of the Svelte integration.

Here's my code:

```astro
---

// ...

import MainLayout from "~/layouts/MainLayout.astro";
import BlockRenderer from "~/components/utils/BlockRenderer.astro";

import HeroRichtextCta from "~/components/blocks/Hero/HeroRichtextCta.svelte";
import MagazineContent from "~/components/blocks/MagazineContent/MagazineContent.svelte";

// ...

---

{
  () => {
   // ...

    return (
      <MainLayout { ...layoutProps }>
        // ...

        {
          pageType === "mag_overview" && <>
            { heroProps && <HeroRichtextCta client:visible { ...heroProps } /> }
            {
              children && <>
                <MagazineContent
                  client:visible
                  breadcrumbs={ magazineAside?.parent && breadcrumbs }
                  aside={ magazineAside?.parent && magazineAside }
                  children={ children }
                />
              </>
            }
          </>
        }

        // ...
      </MainLayout>
    );
  }
}

```

What I don't get is that the `MagazineContent` component works perfectly when hydrated, but `HeroRichtextCta` doesn't. It doesn't happen on `astro dev`, but only on `astro build`. Everything works flawlessly, if I don't hydrate the `HeroRichtextCta` component.

I haven't been tinkering around with Astro for too long, so maybe I'm overlooking something. Would appreciate any kind of help, if it isn't a bug!

Here's also the code of the Hero component, which isn't really anything special.
<details>
<summary>HeroRichtextCta.svelte</summary>

```svelte
<script lang="ts">
  import type { HeroRichtextCtaFragment } from "~/types/dato.generated";
  import type { ConvertPageReference } from "~/lib/getAllPages";

  import { onMount } from "svelte";
  import Hero from "./Base/Hero.svelte";
  import Button from "~/components/atoms/Button.svelte";

  type BaseModel = ConvertPageReference<HeroRichtextCtaFragment>;

  export let heroRichtextCtaTitle: BaseModel["heroRichtextCtaTitle"];
  export let heroRichtextCtaText: BaseModel["heroRichtextCtaText"] = null;
  export let heroRichtextCtaCta: BaseModel["heroRichtextCtaCta"];
  export let heroRichtextCtaMarquee: BaseModel["heroRichtextCtaMarquee"];
  export let heroRichtextCtaMedia: BaseModel["heroRichtextCtaMedia"];
  export let heroRichtextCtaColor: BaseModel["heroRichtextCtaColor"];
  export let heroRichtextCtaPattern: BaseModel["heroRichtextCtaPattern"];

  const [ uiCta ] = heroRichtextCtaCta;
  const [ media ] = heroRichtextCtaMedia;

  const handleCtaClickGtm = () => {
    window.dataLayer.push({
      // ...
    });
  };

  onMount(() => {
    window.dataLayer.push({
      // ...
    });
  });
</script>

<Hero
  title={ heroRichtextCtaTitle }
  text={ heroRichtextCtaText }
  marquee={ heroRichtextCtaMarquee }
  color={ heroRichtextCtaColor }
  pattern={ heroRichtextCtaPattern }
  { media }
>
  <div class="hero-richtext-cta">
    {#if uiCta}
      <Button
        on:click={ handleCtaClickGtm }
        { ...uiCta }
        extraClasses={[ "hero-richtext-cta__cta" ]}
      />
    {/if}
  </div>
</Hero>

<style lang="scss">
  @use "../../../styles/variables";
  @use "../../../styles/mixins/breakpoints";

  .hero-richtext-cta {
    display: flex;
    margin-top: variables.$space-24;

    @include breakpoints.lg-up {
      margin-top: variables.$space-40;
    }
  }

  :global(.hero-richtext-cta__cta) {
    flex: 1;
    text-align: center;

    @include breakpoints.sm-up {
      flex: unset;
      text-align: unset;
    }
  }
</style>

```
</details>

**Comment by robinloeffel** [comment]
I case anyone else is still experiencing this issue: Upgrading Astro and the Svelte integration to v2 fixed the problem!
