### ISSUE TITLE
🐛 BUG: The server could not finish this Suspense boundary

### ISSUE THREAD

**Issue by Crisis2010** [withastro/astro#3135]
### What version of `astro` are you using?

1.0.0-beta.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I tried to lazy load huge component with React 18 and Suspense, but got an Error.

In my case i cant render in only in SSR because of animation. Maybe I'm doing something wrong?

```js
Uncaught Error: The server could not finish this Suspense boundary, likely due to an error during server rendering. Switched to client rendering.
    at updateDehydratedSuspenseComponent (chunk-PDRTL27X.js:15121:100)
    at updateSuspenseComponent (chunk-PDRTL27X.js:14908:28)
    at beginWork (chunk-PDRTL27X.js:15676:22)
    at beginWork$1 (chunk-PDRTL27X.js:18884:22)
    at performUnitOfWork (chunk-PDRTL27X.js:18363:20)
    at workLoopSync (chunk-PDRTL27X.js:18300:13)
    at renderRootSync (chunk-PDRTL27X.js:18279:15)
    at performConcurrentWorkOnRoot (chunk-PDRTL27X.js:17844:83)
    at workLoop (chunk-PDRTL27X.js:197:42)
    at flushWork (chunk-PDRTL27X.js:176:22)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9cpjmy-pkb9zu?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Here's a similar issue with Next.js: https://github.com/vercel/next.js/issues/35564

It sounds like we need to use streaming rendering maybe, going to try that out.
