### ISSUE TITLE
🐛 BUG: Go/Vite breaks - Multiple Root Nodes (Fragments)

### ISSUE THREAD

**Issue by AGS1130** [withastro/astro#3204]
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

macOS Monterey Version 12.0.1

### Describe the Bug

Hey there 😄 

First, thank you for creating this framework! The framework is phenomenal and it has been a joy to work with.

I'm working on migrating a Gatsby site with Astro and was moving some components in a page when I put one of my components outside the Root Node making the page have multiple root nodes. I would expect something like this since it borrows from JSX, but the error message legit scared me to the point that I thought it was going to explode 😱 

Two things come to mind when experiencing this:

1. Can we please include an [Errors message](https://github.com/vercel/next.js/tree/canary/errors) page in the docs? This can help as you track and fix bugs toward stable 1.0 🎉 
2. If possible, can you please create a different error message that is similar to React?
### Request
 ```bash 
You cannot have Multiple Roots in the same DOM node
```
### Actual
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x0 addr=0x0 pc=0x0]

goroutine 10 [running]:
github.com/withastro/compiler/internal.inTableIM(0x47a6c0)
        github.com/withastro/compiler/internal/parser.go:1725 +0x9f
github.com/withastro/compiler/internal.(*parser).parseCurrentToken(0x47a6c0)
        github.com/withastro/compiler/internal/parser.go:2798 +0x13
github.com/withastro/compiler/internal.(*parser).parse(0x47a6c0)
        github.com/withastro/compiler/internal/parser.go:2825 +0x3
github.com/withastro/compiler/internal.ParseWithOptions({0x6faa0, 0x4303a0}, {0x0, 0x0, 0x0})
        github.com/withastro/compiler/internal/parser.go:2885 +0x18
github.com/withastro/compiler/internal.Parse(...)
        github.com/withastro/compiler/internal/parser.go:2842
main.Transform.func1.1.1({0x516800, 0x797}, 0x4483f0, {{}, 0x7ff8000400000054, 0x4116b8})
        ./astro-wasm.go:186 +0xb
created by main.Transform.func1.1
        ./astro-wasm.go:183 +0x3
exit code: 2
Error: Uh oh, the Astro compiler encountered an unrecoverable error!
...
4:14:37 PM [vite] Error when evaluating SSR module /src/layouts/Layout.astro:
Error: Go program has already exited
    at Go._resume (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/wasm_exec.js:435:19)
    at Object.transform (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/wasm_exec.js:447:16)
    at file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:41:82
    at new Promise (<anonymous>)
    at Object.transform (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:41:40)
    at file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:5:51
4:14:37 PM [vite] Error when evaluating SSR module /project/src/pages/support.astro:
Error: Go program has already exited
    at Go._resume (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/wasm_exec.js:435:19)
    at Object.transform (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/wasm_exec.js:447:16)
    at file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:41:82
    at new Promise (<anonymous>)
    at Object.transform (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:41:40)
    at file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:5:51
 error   Go program has already exited
    at Go._resume (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/wasm_exec.js:435:19)
    at Object.transform (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/wasm_exec.js:447:16)
    at file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:41:82
    at new Promise (<anonymous>)
    at Object.transform (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:41:40)
    at file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:5:51
 error   Go program has already exited
    at Go._resume (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/wasm_exec.js:435:19)
    at Object.transform (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/wasm_exec.js:447:16)
    at file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:41:82
    at new Promise (<anonymous>)
    at Object.transform (file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:41:40)
    at file:///project/node_modules/.pnpm/@astrojs+compiler@0.14.2/node_modules/@astrojs/compiler/node/index.js:5:51 (x2)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-hxjhfq?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
An Errors messages page is a great idea!

Unfortunately I'm having trouble reproducing this error. It seems to be working for me on StackBlitz. Is there any chance you can share the complete project files at the point that this error occurred?

**Comment by AGS1130** [comment]
Hey @natemoo-re  👋🏽 

Thanks for the reply 😄 

I have a [repo ](https://github.com/AGS1130/astro_3204)that recreates the issue for me. LMK if you need anything else.
