### ISSUE TITLE
🐛 BUG: .css import not getting detected as stylesheet, causing crash

### ISSUE THREAD

**Issue by ownchoice** [withastro/astro#3226]
### What version of `astro` are you using?

1.0.0-beta.17

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows 10

### Describe the Bug

Astro fails to import import `.css` files from a package (Open Props) into an `.astro` page.

I installed the `open-props` package and I need to import `open-props/normalize` and `open-props/buttons` (both valid exports, `.min.css` files) but when I import them in an `.astro` page likes this:
```js
import 'open-props/normalize';
import 'open-props/buttons';
```

I get the following error:
```
500: Internal Error

Unknown file extension ".css" for C:\git\first-astro-site\website\node_modules\open-props\normalize.min.css

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for C:\git\first-astro-site\website\node_modules\open-props\normalize.min.css
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:13:42)
    at ESMLoader.load (node:internal/modules/esm/loader:303:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:58)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:244:11)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

But If I import the exact same files in a `.css` file that I created like this:
```css
@import 'open-props/normalize';
@import 'open-props/buttons';
```

It works, and that just a `styles.css` file that I import in the exact same `.astro` page like this:
```
import '../styles/styles.css';
```

If I change the imports in the .astro page to:
```js
import 'open-props/normalize.min.css';
import 'open-props/buttons.min.css';
```

I get the following error (which as far as I know is working as intended):
```
500: Internal Error

Missing "./normalize.min.css" export in "open-props" package

Error: Missing "./normalize.min.css" export in "open-props" package
    at bail (C:\git\first-astro-site\website\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:37698:8)
    at resolve (C:\git\first-astro-site\website\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:37775:10)
    at resolveExports (C:\git\first-astro-site\website\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:38441:12)
    at resolveDeepImport (C:\git\first-astro-site\website\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:38459:31)
    at tryNodeResolve (C:\git\first-astro-site\website\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:38232:20)
    at Context.resolveId (C:\git\first-astro-site\website\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:38040:28)
    at Object.resolveId (C:\git\first-astro-site\website\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36609:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Context.resolve (C:\git\first-astro-site\website\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36383:23)
```

Codesandbox wasn'te able to reproduce reliably the error, but Stackblitz seems to work just like in my machine:

- [https://stackblitz.com/edit/github-vvfhne](https://stackblitz.com/edit/github-vvfhne)
- [https://codesandbox.io/s/elegant-sutherland-e9sfui](https://codesandbox.io/s/elegant-sutherland-e9sfui)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vvfhne

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
I'm amazed we don't test for this, I could have sworn that we did. This should be added to our `0-css` test fixture.

**Comment by aheidelberg** [comment]
I have the same issue with https://swiperjs.com/react#usage

```jsx
import 'swiper/css';
```

But doing this in a `.css` doesn't fix it for me, I'm still getting the same error.

```css
@import 'swiper/css';
```

```
Unknown file extension ".css" for /home/alex/dev/astro-site/node_modules/swiper/swiper.min.css
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /home/alex/dev/astro-side/node_modules/swiper/swiper.min.css
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at async Promise.all (index 0)
```

**Comment by bholmesdev** [comment]
Confirmed this is still an issue in the latest beta. Working on a fix! But for now, try importing these modules inside a `<script>` tag _instead_ of within the frontmatter:

```js
<script>
	import 'css-pkg/test'
</script>
```

Still debugging why this is the case 👍

**Comment by bholmesdev** [comment]
☝️ Update: figured it out! Adding a note on `ssr.noExternal` to our docs. This should solve your issue @ownchoice:

```js
// astro.config.js
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  vite: {
    ssr: {
      noExternal: ['open-props'],
    }
  }
});
```
