### ISSUE TITLE
🐛 BUG: .tsx file in solid-js template causes build error

### ISSUE THREAD

**Issue by trusktr** [withastro/astro#3249]
### What version of `astro` are you using?

1.0.0-beta.19

### Are you using an SSR adapter? If so, which one?

Whatever comes with solid-js starter

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

With this commit,

https://github.com/trusktr/astrohack-1/commit/08be1bd1249fd14e29e4422b17dba3272dfdc9f4

I get this error on initial build:

```
7:52:39 PM [vite] Error when evaluating SSR module /home/trusktr/src/astrohack-1/src/pages/index.astro:
Error: failed to load module for ssr: ../components/Counter.jsx
    at instantiateModule (/home/trusktr/src/astrohack-1/node_modules/vite/dist/node/chunks/dep-3397b401.js:59107:15)
 error   failed to load module for ssr: ../components/Counter.jsx
    at instantiateModule (/home/trusktr/src/astrohack-1/node_modules/vite/dist/node/chunks/dep-3397b401.js:59107:15)
```

The site shows the error in the browser. Upon refresh, the error changes to this:

```
 error   Expected an exported Astro component but received typeof undefined
    at render (file:///home/trusktr/src/astrohack-1/node_modules/astro/dist/core/render/core.js:82:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async render (file:///home/trusktr/src/astrohack-1/node_modules/astro/dist/core/render/dev/index.js:99:17)
    at async ssr (file:///home/trusktr/src/astrohack-1/node_modules/astro/dist/core/render/dev/index.js:139:10)
    at async handleRequest (file:///home/trusktr/src/astrohack-1/node_modules/astro/dist/vite-plugin-astro-server/index.js:230:22)
```

The temporary workaround is to rename the `.tsx` file to `.jsx` as in this commit:

https://github.com/trusktr/astrohack-1/commit/1026b9efd4134b5a0a20a04f680d5c948fe9bf0f

### Link to Minimal Reproducible Example

https://github.com/trusktr/astrohack-1/commit/08be1bd1249fd14e29e4422b17dba3272dfdc9f4

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
@trusktr does the issue get resolved if you keep the file as `Counter.tsx`, but then rename the import to `import Counter from '../components/Counter';`? @Princesseuh is currently tracking this issue down and it would be great to know if this is related!

**Comment by natemoo-re** [comment]
Here's a StackBlitz link https://stackblitz.com/edit/github-sjchvk?file=src%2Fpages%2Findex.astro

**Comment by matthewp** [comment]
This is fixed now!
