### ISSUE TITLE
🐛 BUG: create-astro crashes: “could not download”

### ISSUE THREAD

**Issue by ron-wolf** [withastro/astro#3316]
### What version of `astro` are you using?

1.0.0-beta.27

### Are you using an SSR adapter? If so, which one?

None (N/A)

### What package manager are you using?

Tried PNPM, then NPM, then Yarn

### What operating system are you using?

Mac (macOS 10.14.6 Mojave)

### Describe the Bug

On `create-astro@0.12.0`, everything succeeds until the `Copying project files...` step. My install fails, printing `could not download https://github.com/withastro/astro/archive/8ca19fa14245700ee2aeb25c4ebf5010984af9e7.tar.gz` to the standard error descriptor.

Here I have run the command by itself to isolate only the relevant command output:

![image](https://user-images.githubusercontent.com/7342888/167280765-7e826bbb-d2b7-4e80-9689-aa576ade6840.png)

I have tried this with `npm@8.9.0`, `yarn@1.22.15`, and `pnpm@7.0.0`. All three produce the same issue.

I could not reproduce this issue in a minimal environment. Nevertheless, any help pinpointing the issue so I and others may avoid it in the future would be greatly appreciated. I am willing to submit a Pull Request for this issue.

I have also attached a [debug log](https://github.com/withastro/astro/files/8646297/2022-05-08T03_22_37_981Z-debug-0.log).

### Link to Minimal Reproducible Example

N/A (the issue stops me from even creating such an environment)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ron-wolf** [comment]
Update: re-ran with `--verbose` argument. Got the following error output:

```
DegitError: could not download https://github.com/withastro/astro/archive/8ca19fa14245700ee2aeb25c4ebf5010984af9e7.tar.gz
    at Degit._cloneWithTar (/Users/Ron/.local/etc/yarn/global/node_modules/degit/dist/index-688c5d50.js:14299:10)
    [at processTicksAndRejections (node:internal/process/task_queues:96:5)]
    at async Degit.clone (/Users/Ron/.local/etc/yarn/global/node_modules/degit/dist/index-688c5d50.js:14096:4)
    at async main (file:///Users/Ron/.local/etc/yarn/global/node_modules/create-astro/dist/index.js:95:7) {
  code: 'COULD_NOT_DOWNLOAD',
  url: 'https://github.com/withastro/astro/archive/8ca19fa14245700ee2aeb25c4ebf5010984af9e7.tar.gz',
  original: Error: EACCES: permission denied, mkdir '/Users/Ron/.degit'
      at Object.mkdirSync (node:fs:1349:3)
      at mkdirp (/Users/Ron/.local/etc/yarn/global/node_modules/degit/dist/index-688c5d50.js:13943:26)
      at mkdirp (/Users/Ron/.local/etc/yarn/global/node_modules/degit/dist/index-688c5d50.js:13940:2)
      at mkdirp (/Users/Ron/.local/etc/yarn/global/node_modules/degit/dist/index-688c5d50.js:13940:2)
      at mkdirp (/Users/Ron/.local/etc/yarn/global/node_modules/degit/dist/index-688c5d50.js:13940:2)
      at Degit._cloneWithTar (/Users/Ron/.local/etc/yarn/global/node_modules/degit/dist/index-688c5d50.js:14281:6)
      [at processTicksAndRejections (node:internal/process/task_queues:96:5)]
      at async Degit.clone (/Users/Ron/.local/etc/yarn/global/node_modules/degit/dist/index-688c5d50.js:14096:4)
      at async main (file:///Users/Ron/.local/etc/yarn/global/node_modules/create-astro/dist/index.js:95:7) {
    errno: -13,
    syscall: 'mkdir',
    code: 'EACCES',
    path: '/Users/Ron/.degit'
  }
}
```

Bracketed lines are those that show up only when using `npm`. I was not able to reproduce with `pnpm` due to the `create-astro` executable being deleted upon build failure.

The solution in my case was to create the directory `~/.degit` myself, as I maintain the practice of keeping my home directory read-only for security and management purposes. In my case, I symlinked it to `~/.cache/degit`, since [according to the XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html#:~:text=%24XDG_CACHE_HOME%20defines%20the%20base%20directory%20relative%20to%20which%20user%2Dspecific%20non%2Dessential%20data%20files%20should%20be%20stored.%20If%20%24XDG_CACHE_HOME%20is%20either%20not%20set%20or%20empty%2C%20a%20default%20equal%20to%20%24HOME/.cache%20should%20be%20used.) that is where “user-specific non-essential data files” go.

Closing this here, as a solution has been found and the original problem is with `degit`, not with Astro itself. Similar issues occur with the main JS package managers, and home directory usage seems to be the state of things in JS, as elsewhere.
