### ISSUE TITLE
🐛 BUG: Improve error messages when style imports are not at the top of frontmatter

### ISSUE THREAD

**Issue by ran-dall** [withastro/astro#3323]
### What version of `astro` are you using?

1.0.0-beta.27

### Are you using an SSR adapter? If so, which one?

Nope

### What package manager are you using?

NPM

### What operating system are you using?

Linux (Gentoo)

### Describe the Bug

I've been trying to pull in my `style.scss` into my project, in the same way illustrated in the documentation...

```js
import '../styles/style.scss';
```

...but it doesn't work out. 

```shell
 error   Transform failed with 1 error:
  /mnt/site/src/layouts/BaseHead.astro:29:7: ERROR: Unexpected "'../styles/style.scss'"
  File:
    /mnt/site/src/layouts/BaseHead.astro
  Code:
      28 | <link rel="stylesheet" href="/css/swiper.min.css">
    > 29 | <link rel="stylesheet" href="/css/bootstrap.min.css">
         |       ^
      31 | <!-- SOCIAL MEDIA META -->
      32 | <meta property="og:description" >
    
  Stacktrace:
    at failureErrorWithLog (/mnt/site/node_modules/esbuild/lib/main.js:1603:15)
    at /mnt/MCU/node_modules/esbuild/lib/main.js:1392:29
    at /mnt/MCU/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/mnt/site/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/mnt/site/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

Here is my `BaseHead.astro`

```html
---
const {title, page, description, keywords, image, url} = Astro.props;

import '../styles/style.scss';
---

<style lang="scss">
 @import url("../styles/style.scss")
</style>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="format-detection" content="telephone=no">
<meta name="theme-color" content="#bf8d4e"/>
<title>{title} | {page}</title>
<meta name="author" content="Mountain Cabins Utah">
<meta name="description" content={description}>
<meta name="keywords" content={keywords}>

<!-- FAVICON FILES -->
<link href="ico/apple-touch-icon-144-precomposed.png" rel="apple-touch-icon" sizes="144x144">
<link href="ico/apple-touch-icon-114-precomposed.png" rel="apple-touch-icon" sizes="114x114">
<link href="ico/apple-touch-icon-72-precomposed.png" rel="apple-touch-icon" sizes="72x72">
<link href="ico/apple-touch-icon-57-precomposed.png" rel="apple-touch-icon">
<link href="ico/favicon.png" rel="shortcut icon">

<!-- CSS FILES -->
<link rel="stylesheet" href="/css/fontawesome.min.css">
<link rel="stylesheet" href="/css/animate.min.css">
<link rel="stylesheet" href="/css/fancybox.min.css">
<link rel="stylesheet" href="/css/odometer.min.css">
<link rel="stylesheet" href="/css/swiper.min.css">
<link rel="stylesheet" href="/css/bootstrap.min.css">


<!-- SOCIAL MEDIA META -->
<meta property="og:description" content="Mountain Cabins Utah | Premiere Cabin Rentals in Utah">
<meta property="og:image" content={image}>
<meta property="og:site_name" content={title}>
<meta property="og:title" content={page}>
<meta property="og:type" content="website">
<meta property="og:url" content={url}>

<!-- TWITTER META -->
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content={title}>
<meta name="twitter:description" content={description}}>
<meta name="twitter:image" content={image}>
```

Upon asking for some assistance on GitHub. @aFuzzyBear suggested trying to remove the `import` statement and use...

```html
<style lang="scss">
 @import url('../styles/style.scss')
</style>
```

...which didn't produce a critical error, but didn't exactly work either...

![Screenshot from 2022-05-10 10-07-24](https://user-images.githubusercontent.com/17261190/167684341-081256b1-ed62-4206-9d64-c39a6da71fc9.png)

...and it did still throw an error in the console, despite it not being a critical error.

```shell
[vite:css] @import must precede all other statements (besides @charset or empty @layer)
``` 

Therefore, it was concluded that atm it might be better for me to use `astro-stylesheets`; but it would be helpful to open this bug ticket as well, as this situation seems like a glitch.

### Link to Minimal Reproducible Example

https://github.com/Mountain-Cabins-Utah/Website

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
@ran-dall the original issue was just that the `import '../styles/style.scss'` came after the `const { ... }` line

Imports and exports should always be at the top of the frontmatter, but keeping this open so we can add a clear build message here!

**Comment by natemoo-re** [comment]
**Note from Triage Call**

- Larger fix needed here to just remove this limitation. We don't want to ship v1.0 with the current rough edge that requires specific import ordering.
- @natemoo-re to tackle next sprint

**Comment by FredKSchott** [comment]
Thanks for filing! This was fixed in the RC! If you're still seeing this issue, please comment and we can reopen to debug.
