### ISSUE TITLE
🐛 BUG: The requested module '@astrojs/markdown-remark' does not provide an export named 'default'

### ISSUE THREAD

**Issue by mattgeowild** [withastro/astro#3364]
### What version of `astro` are you using?

1.0.0-beta.28

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

```
file:///home/projects/withastro-astro-zcezkf/astro.config.mjs:2
import astroRemark from '@astrojs/markdown-remark';
       ^^^^^^^^^^^
SyntaxError: The requested module '@astrojs/markdown-remark' does not provide an export named 'default'
    at ModuleJob._instantiate (https://withastro-astro-zcezkf.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:986330)
    at async ModuleJob.run (https://withastro-astro-zcezkf.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:987148)
    at async Promise.all (index 0)
    at async ESMLoader.import (https://withastro-astro-zcezkf.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:1208898)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-zcezkf

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! This is intentional, the exports from `@astrojs/markdown-remark` are `renderMarkdown`, `DEFAULT_REHYPE_PLUGINS`, `DEFAULT_REMARK_PLUGINS`.

We recently [updated our config](https://docs.astro.build/en/reference/configuration-reference/#markdown-options) so that you shouldn't have to reference `@astrojs/markdown-remark` at all. If you're on an older version of Astro where you do need to reference the `@astrojs/markdown-remark` plugin, I'd suggest pinning the dependency to a compatible version.
