### ISSUE TITLE
🐛 BUG: newline character in Solid template throws error

### ISSUE THREAD

**Issue by Enteleform** [withastro/astro#3371]
### What version of `astro` are you using?

1.0.0-beta.28

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

Yarn

### What operating system are you using?

Windows

### Describe the Bug

Adding the following markup to a Solid template will result in an error. 

```jsx
<div class="Multiline">
  {`<portal-destination\n`     }
  {`  transfer-mode="Single"\n`}
  {`/>`                        }
</div>
```

- The error does not occur on [Solid Playground](https://playground.solidjs.com/?hash=1591083771&version=1.3.16).
- The error does not occur in Astro when the `\n` characters are removed.
- The error did not occur with some previous versions of `astro` and `@astro/solid-js`, although I can't pinpoint when it started.

**Error:**
```
[plugin:astro:jsx] /home/projects/github-v4lcfq/src/components/Counter.jsx: Cannot read properties of undefined (reading 'length')
/home/projects/github-v4lcfq/src/components/Counter.jsx
    at memoizedBinarySearch (/home/projects/github-v4lcfq/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:138:29)
    at traceSegmentInternal (/home/projects/github-v4lcfq/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:513:21)
    at Object.exports.traceSegment (/home/projects/github-v4lcfq/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:393:20)
    at originalPositionFor (/home/projects/github-v4lcfq/node_modules/@ampproject/remapping/dist/remapping.umd.js:90:38)
    at traceMappings (/home/projects/github-v4lcfq/node_modules/@ampproject/remapping/dist/remapping.umd.js:59:30)
    at remapping (/home/projects/github-v4lcfq/node_modules/@ampproject/remapping/dist/remapping.umd.js:203:30)
    at mergeSourceMap (/home/projects/github-v4lcfq/node_modules/@babel/core/lib/transformation/file/merge-map.js:22:30)
    at generateCode (/home/projects/github-v4lcfq/node_modules/@babel/core/lib/transformation/file/generate.js:76:41)
    at run (/home/projects/github-v4lcfq/node_modules/@babel/core/lib/transformation/index.js:55:33
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v4lcfq?file=src%2Fcomponents%2FCounter.jsx&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by forspamonly2** [comment]
seems related:

same error occurs on every multiline jsx attribute.

```html
<div class="Multiline huge-tailwind-mess 
            more-tailwind-mess">
</div>
```

https://stackblitz.com/edit/github-v4lcfq-98efmd?file=src%2Fcomponents%2FCounter.jsx&on=stackblitz

**Comment by natemoo-re** [comment]
Hmm, odd. Thanks for confirming that this isn't an upstream issue! I wonder if this could be an old bug and we need to upgrade some of our Solid dependencies?

We'll definitely take a look at this!
