### ISSUE TITLE
🐛 BUG: Internal server error: File URL path must be absolute

### ISSUE THREAD

**Issue by MR-Mostafa** [withastro/astro#3387]
### What version of `astro` are you using?

1.0.0-beta.28

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows 10

### Note: Only Windows 10 has this issue.

**The demo works fine, but when I test this code locally (in windows 10), it causes this error.**

```
[vite] Internal server error: File URL path must be absolute
Plugin: vite:import-analysis
File: /@fs/C:/Users/.../Desktop/project/src/components/Card.astro?astro&type=script&index=0
      at new NodeError (node:internal/errors:371:5)
      at getPathFromURLWin32 (node:internal/url:1390:11)
      at fileURLToPath (node:internal/url:1420:22)
      at Context.resolveId (file:///C:/Users/.../Desktop/project/node_modules/astro/dist/vite-plugin-astro/index.js:52:24)
      at Object.resolveId (C:\Users\...\Desktop\project\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38837:55)
      at async TransformContext.resolve (C:\Users\...\Desktop\project\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38611:23)
      at async normalizeUrl (C:\Users\...\Desktop\project\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:56824:34)
      at async TransformContext.transform (C:\Users\...\Desktop\project\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:56979:57)
      at async Object.transform (C:\Users\...\Desktop\project\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38900:30)
      at async doTransform (C:\Users\...\Desktop\project\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:55857:29)
```

**Node Version:** v16.13.1
**Npm Version:** 8.1.2
**Yarn Version:** 1.22.15

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wosta1-hdbxpu

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MR-Mostafa** [comment]
Also, I tested with Windows 10 Pro (19044.1586) and Manjaro (21.2.6), but:
1) In Windows 10 Pro the same error appeared
2) in Manjaro (21.2.6) there were no problems or errors

**Comment by dperolio** [comment]
Following this, hopefully we can get a response soon. Having this same issue on Windows 11. This wasn't happening until just today (I believe) after I upgraded to from 1.0.0-beta.27 to 1.0.0-beta.29, but I downgraded back to 1.0.0-beta.27 and it's still happening now.

**Comment by natemoo-re** [comment]
Very strange, thanks for opening an issue! This seems to be a problem with our script resolution logic, which we have to ensure is relative to the file it is authored in.

Separately, @dperolio can you share a reproduction for whatever is throwing those errors? Would help determine if these are the same issue.

**Comment by dperolio** [comment]
> Very strange, thanks for opening an issue! This seems to be a problem with our script resolution logic, which we have to ensure is relative to the file it is authored in.
> 
> Separately, @dperolio can you share a reproduction for whatever is throwing those errors? Would help determine if these are the same issue.

Sure, I've set up a barebones repo here which demonstrates all of the issues from this thread. https://github.com/dperolio/immerse-testing

**Comment by stabas** [comment]
I also have same issue!

**Comment by matthewp** [comment]
Sorry everyone, looking into this now.
