### ISSUE TITLE
🐛 BUG: Astro.new starters throw a few errors and many assorted warnings in the browser inspector

### ISSUE THREAD

**Issue by KyleFontenot** [withastro/astro#3403]
### What version of `astro` are you using?

1.0.0-beta.30

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Mac locally. StackBlitz throws same errors too though

## Errors
Using just the basic starter template from Astro.new for solid, Here is the error thrown:
```
5:01:41 PM [vite] Internal server error: Cannot set properties of undefined (setting 'isSelfAccepting')
  Plugin: vite:import-analysis
  File: /home/projects/kkvinqjga.github/node_modules/.vite/deps/astro_client_visible_js.js?v=da542fda
      at ModuleGraph.updateModuleInfo (/home/projects/kkvinqjga.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:57342:29)
      at TransformContext.transform (/home/projects/kkvinqjga.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:57117:57)
      at async Object.transform (/home/projects/kkvinqjga.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:38900:30)
      at async doTransform (/home/projects/kkvinqjga.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:55857:29)
```

Within the browser visible.js throws:
``` 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```
## Warnings
Two warnings throw referencing `/@id/...`
```
DevTools failed to load source map: Could not load content for https://kkvinqjga--github--3000.local.webcontainer.io/@id/@astrojs/solid-js/@astrojs_solid-js_client_js.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
While hundreds of warnings relate to `/node_modules/...` all ending in `.map`:
```
DevTools failed to load source map: Could not load content for https://kkvinqjga--github--3000.local.webcontainer.io/node_modules/.vite/deps/chunk-Q54O36CC.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-solid?file=package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by KyleFontenot** [comment]
dperolio on Discord mentioned that he gets exact errors without Solid. (s)he has React involved but doesn't look like the culprit. Looks Astro - Vite related especially with the thrown error

**Comment by natemoo-re** [comment]
Thanks for the report! Good to know that this isn't Solid-specific but is something to do with the `/@id/` URLs we're using internally.

Since this is happening with our out-of-the-box starter templates, we'll try to get to this as soon as possible.

**Comment by scott-the-brewer** [comment]
Just wanted to add I'm encountering the same issue when upgrading from `beta.28` to `beta.29`. I'm using `solid-js`.

**Comment by scott-the-brewer** [comment]
@bholmesdev Working great for me thanks, no issues

**Comment by connorads** [comment]
Still broken when running `astro dev` here on https://github.com/connorads/connoradams.co.uk/pull/13 with `beta.41`
❌ `astro dev` `Cannot set properties of undefined (setting 'isSelfAccepting')`
✅ `astro build` works fine

Didn't manage to narrow down the exact cause yet
But if anyone is curious and wants to reproduce and investigate it's quick to do using GitHub Codespaces
1. Go to https://github.com/connorads/connoradams.co.uk
2. Create Codespace
3. `npm run dev` or `npx astro dev`
4. View website
5. See error in console
![image](https://user-images.githubusercontent.com/10026538/172453319-ab192749-ded9-450c-bb7e-466aef623ab3.png)
![image](https://user-images.githubusercontent.com/10026538/172453752-57ed0305-bcf3-4b52-b5a4-e9d42dcfbd6f.png)
If not using Codespaces (i.e. run locally) you'll see the error as a pop up too (not sure why this is suppressed on Codespaces)
![image](https://user-images.githubusercontent.com/10026538/172454640-7817c97f-66e4-4f34-b1f9-170b01171bf8.png)

**Comment by Holben888** [comment]
@connorads Yep, we have a few reports of similar issues. Looks like we fixed the issue on our starters and other “small” starters, but it reappears at scale. Currently tracking on #3465

**Comment by bholmesdev** [comment]
Noticing the `js.map` flags were _not_ resolved. We have a Vite core fix for the `isSelfAccepting` issue that _might_ address this as well, but I'm re-opening to track!
