### ISSUE TITLE
🐛 BUG: Astro SSR fails to bundle functions for Netlify

### ISSUE THREAD

**Issue by nnelgxorz** [withastro/astro#3469]
### What version of `astro` are you using?

1.0.0-beta.36

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When deploying to Netlify the site builds but gives the following waning.

```
9:54:19 AM: ❯ The following Node.js modules use dynamic expressions to include files:
9:54:19 AM: - astro
9:54:19 AM:
9:54:19 AM: Because files included with dynamic expressions aren't bundled with your serverless functions by default,
this may result in an error when invoking a function. To resolve this error, you can mark these Node.js
9:54:19 AM: modules as external in the [functions] section of your `netlify.toml` configuration file:
9:54:19 AM:
9:54:19 AM: [functions]
9:54:19 AM: external_node_modules = ["astro"]
9:54:19 AM:
9:54:19 AM: Visit https://ntl.fyi/dynamic-imports for more information.
```

After deploying, visiting the site gives this error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/astro/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /var/task/astro/node_modules/node-fetch/src/index.js from /var/task/astro/.netlify/functions-internal/entry.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /var/task/astro/node_modules/node-fetch/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/var/task/astro/.netlify/functions-internal/entry.js:8208:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

If I set Astro as external in my netlfiy.toml per the build warning, the build fails at the Deploy Site step with this warning:

```
10:42:10 AM: The function "BUMP-ENROLLMENT" is larger than the 50MB limit. Please consider reducing it.
10:42:10 AM: The function "UPDATE" is larger than the 50MB limit. Please consider reducing it.
10:42:10 AM: The function "SUBMISSION-CREATED" is larger than the 50MB limit. Please consider reducing it.
10:42:10 AM: The function "SEND-EMAIL" is larger than the 50MB limit. Please consider reducing it.
10:42:11 AM: The function "ENTRY" is larger than the 50MB limit. Please consider reducing it.
```

### Link to Minimal Reproducible Example

https://deploy-preview-29--kk9-dog-training.netlify.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nnelgxorz** [comment]
Issue seems to be related to having a Netlify Functions folder inside of your Astro project. I moved my Functions folder outside of Astro and the build works again.

Closing for now and will reopen if I get a better minimal example.
