### ISSUE TITLE
🐛 BUG: Astro thinks '<' in markdown math block is beginning of shorthand Fragment

### ISSUE THREAD

**Issue by nemo-omen** [withastro/astro#3513]
### What version of `astro` are you using?

1.0.0-beta.38

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When using `remark-math` and `rehype-katex` Astro throws an error when I attempt to include the '<' symbol. It also throws the same error when using KaTeX syntax, `\lt`.

Error:

```bash
panic: Unable to assign attributes when using <> Fragment shorthand syntax!

To fix this, please change
  < /mo>
to use the longhand Fragment syntax:
  <Fragment /mo>


goroutine 7 [running]:
github.com/withastro/compiler/internal.(*Tokenizer).Next(0x4a43c0)
        github.com/withastro/compiler/internal/token.go:1460 +0x1c2
github.com/withastro/compiler/internal.(*parser).parse(0x47a360)
        github.com/withastro/compiler/internal/parser.go:2830 +0x1e
github.com/withastro/compiler/internal.ParseWithOptions({0x70ee0, 0x430120}, {0x0, 0x0, 0x0})
        github.com/withastro/compiler/internal/parser.go:2898 +0x18
github.com/withastro/compiler/internal.Parse(...)
        github.com/withastro/compiler/internal/parser.go:2855
main.Transform.func1.1.1({0x4ca000, 0xef65}, 0x4481b0, {{}, 0x7ff800040000001f, 0x410d68})
        ./astro-wasm.go:211 +0xb
created by main.Transform.func1.1
        ./astro-wasm.go:208 +0x3
exit code: 2
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4jdjtj-dy8aae?file=src/pages/index.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! There's something going on with the way we're transforming Markdown _before_ passing it to the Astro compiler. Definitely taking a look at this ASAP.
