### ISSUE TITLE
🐛 BUG: page-ssr injected scripts do not have access to the Astro variable

### ISSUE THREAD

**Issue by FugiTech** [withastro/astro#3601]
### What version of `astro` are you using?

v1.0.0-beta.46

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows (WSL2 w/ Ubuntu)

### Describe the Bug

The [docs for `injectScript`](https://docs.astro.build/en/reference/integrations-reference/#injectscript-option) say that it is "Injected into the frontmatter of every Astro page component", which implies that it would have access to anything the frontmatter does and potentially the ability to export functions like `getStaticPaths`.

Instead, attempting to use frontmatter-specific variables like `Astro` causes errors. 

```
Error when evaluating SSR module astro:scripts/page-ssr.js:
ReferenceError: Astro is not defined
    at astro:scripts/page-ssr.js:1:13
    at instantiateModule (/home/projects/github-1nama1/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:50286:15)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1nama1?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! We'll have to decide what the intention is here and either update the docs or update the implementation

**Comment by tony-sull** [comment]
Community Call 6/21:  This is an implementation detail of how the Astro global is added to the build, we'll need to update the documentation to make it clear that the Astro global isn't available in `injectScript` :+1:

**Comment by natemoo-re** [comment]
The docs for this feature have been updated to be more clear!

If you'd like to create an [RFC discussion](https://github.com/withastro/rfcs) with specific use cases we can look into adding support for the type of injection you were looking for.
