### ISSUE TITLE
🐛 BUG: Large objects from Astro to UI Framework as properties cause memory error

### ISSUE THREAD

**Issue by mkv27** [withastro/astro#3802]
### What version of `astro` are you using?

1.0.0-beta.63

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Large objects cause this memory error in Vercel:
```
ERROR	Unhandled Promise Rejection 
{"errorType":"Runtime.UnhandledPromiseRejection",
"errorMessage":"RangeError: Maximum call stack size exceeded","reason":{"errorType":"RangeError",
"errorMessage":"Maximum call stack size exceeded",
"stack":["RangeError: Maximum call stack size exceeded","    
at _a.arrayBuffer (file:///var/task/node_modules/astro/dist/runtime/server/response.js:52:18)","   
 at processTicksAndRejections (node:internal/process/task_queues:96:5)","   
  at async setResponse (file:///var/task/node_modules/@astrojs/vercel/dist/serverless/request-transform.js:65:17)","    
  at async Server.handler (file:///var/task/node_modules/@astrojs/vercel/dist/serverless/entrypoint.js:21:5)"]},
  "promise":{},
  "stack":["Runtime.UnhandledPromiseRejection: RangeError: Maximum call stack size exceeded","    
  at process.<anonymous> (file:///var/runtime/index.mjs:775:15)","    
  at process.emit (node:events:539:35)","    
  at emit (node:internal/process/promises:140:20)","    
  at processPromiseRejections (node:internal/process/promises:274:27)","    
  at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yjkevk?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Very odd, thanks for the reproduction, we'll take a look at this as soon as we can!

@matthewp any insight into what's going on here?

**Comment by matthewp** [comment]
Yeah, somewhat of an idea, i'll take this one.
