### ISSUE TITLE
🐛 BUG: Using a comment alongside "mode: 'md'" causes compiler error

### ISSUE THREAD

**Issue by crutchcorn** [withastro/astro#3879]
### What version of `astro` are you using?

1.0.0-beta.65

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

When I attempt to use an HTML comment in an `index.md` file:

```
<!-- Test -->
```

And change my `astro.config.mjs` file to the following:

```
import { defineConfig } from 'astro/config';

export default defineConfig({
	markdown: {
		mode: 'md'
	}
});
```

To avoid MDX processing, I get the following compiler error:

<details>
<summary>The bug output</summary>

```
   git  Astro  astro-markdown-parse-comment-fail  main  ≢ 
↳  yarn dev
yarn run v1.22.19
$ astro dev
   astro  v1.0.0-beta.65 started in 30ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues

 error   Transform failed with 1 error:
  C:/Users/crutchcorn/git/Astro/astro-markdown-parse-comment-fail/src/pages/index.md:42:71: ERROR: Syntax error "e"
  File:
    C:/Users/crutchcorn/git/Astro/astro-markdown-parse-comment-fail/src/pages/index.md
  Stacktrace:
    at failureErrorWithLog (C:\Users\crutchcorn\git\Astro\astro-markdown-parse-comment-fail\node_modules\esbuild\lib\main.js:1605:15)
    at C:\Users\crutchcorn\git\Astro\astro-markdown-parse-comment-fail\node_modules\esbuild\lib\main.js:1394:29
    at C:\Users\crutchcorn\git\Astro\astro-markdown-parse-comment-fail\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (C:\Users\crutchcorn\git\Astro\astro-markdown-parse-comment-fail\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (C:\Users\crutchcorn\git\Astro\astro-markdown-parse-comment-fail\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

</details>

### Link to Minimal Reproducible Example

https://github.com/crutchcorn/astro-markdown-parse-comment-fail

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by crutchcorn** [comment]
Working through debugging this...

If I add a debugger line to evaluate this output:

https://github.com/withastro/astro/blob/main/packages/markdown/remark/src/index.ts#L116

I get the following HTML:

```
"<p>{/<em><!-- Test --></em>/}</p>"
```

Which is inaccurate for a few reasons:

1) Why is there a `p` tag?
2) Why is there an `<em>` tag?
3) Why is there `{/` and `/}`?
