### ISSUE TITLE
🐛 BUG: `import.meta.glob() can only accept string literals`

### ISSUE THREAD

**Issue by andygrunwald** [withastro/astro#3946]
### What version of `astro` are you using?

1.0.0-beta.72

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

According to the docs of [@astro/rss](https://docs.astro.build/en/guides/rss/#1-importmetaglob-result), you can use the vite's functionality for `import.meta.glob()`:

> See [Vite’s glob import documentation](https://vitejs.dev/guide/features.html#glob-import) for more on this import syntax.

On [vites documentation](https://vitejs.dev/guide/features.html#glob-import) it is stated that you can use multiple patterns for `import.meta.glob()`:

```js
const modules = import.meta.glob(['./dir/*.js', './another/*.js'])
```

Running code like

```js
import rss from '@astrojs/rss';

// Docs: https://docs.astro.build/en/guides/rss/
export const get = () => rss({
    title: 'Buzz’s Blog',
    description: 'A humble Astronaut’s guide to the stars',
    site: import.meta.env.SITE,
    items: import.meta.glob([
        './blog/post/*.md', 
        './podcast/episode/*.md'
    ])
  });
```

leads to errors like

```
$ npm run dev

> @engineering-kiosk/webpage@0.0.1 dev
> astro dev

  🚀  astro  v1.0.0-beta.72 started in 30ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues

✘ [ERROR] [plugin vite:dep-scan] import.meta.glob() can only accept string literals.

    node_modules/vite/dist/node/chunks/dep-c9998dc6.js:38260:16:
      38260 │     const err = new Error(`import.meta.glob() can only accept string literals.`);
            ╵                 ^

    at error$2 (/path/to/webpage/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:38260:17)
    at lexGlobPattern (/path/to/webpage/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:38215:21)
    at transformImportGlob (/path/to/webpage/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:38109:46)
    at transformGlob (/path/to/webpage/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:39736:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callback (/path/to/webpage/node_modules/esbuild/lib/main.js:990:28)
    at async handleRequest (/path/to/webpage/node_modules/esbuild/lib/main.js:718:30)

  This error came from the "onLoad" callback registered here:

    node_modules/vite/dist/node/chunks/dep-c9998dc6.js:39696:18:
      39696 │             build.onLoad({ filter: JS_TYPES_RE }, ({ path: id }) => {
            ╵                   ~~~~~~

    at setup (/path/to/webpage/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:39696:19)
    at handlePlugins (/path/to/webpage/node_modules/esbuild/lib/main.js:852:23)
    at Object.buildOrServe (/path/to/webpage/node_modules/esbuild/lib/main.js:1146:7)
    at /path/to/webpage/node_modules/esbuild/lib/main.js:2092:17
    at new Promise (<anonymous>)
    at Object.build (/path/to/webpage/node_modules/esbuild/lib/main.js:2091:14)
    at Object.build (/path/to/webpage/node_modules/esbuild/lib/main.js:1938:51)
    at /path/to/webpage/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:39414:54
    at Array.map (<anonymous>)

Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-c9998dc6.js:38260:16: ERROR: [plugin: vite:dep-scan] import.meta.glob() can only accept string literals.
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tohbhv-fhkz1e?file=src/pages/rss.xml.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is a feature of Vite 3. We are in the process of upgrading from Vite 2 (which does not have this) to Vite 3 (which does). Closing as this will be implemented when we ship Vite 3.
