### ISSUE TITLE
🐛 BUG: 1.0.0-rc.1 - Creating Node specific "proccess" in cloudflare _worker.js bundle

### ISSUE THREAD

**Issue by davycoe** [withastro/astro#4060]
### What version of `astro` are you using?

1.0.0-rc.1

### Are you using an SSR adapter? If so, which one?

Cloudflare 0.3.0

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Version 1.0.0-rc.1 seems to be including node specific `process.env` and breaking Cloudflare SSR adapter.

reverting back to astro 1.0.0-beta.73 fixes it for now.

```
[pages:err] ReferenceError: process is not defined
    at /home/coe/code/plz/dist/_worker.js:1:21032
    at /home/coe/code/plz/dist/_worker.js:1:209
    at /home/coe/code/plz/dist/_worker.js:10:3149
    at SourceTextModule.evaluate (node:internal/vm/module:224:23)
    at VMScriptRunner.runAsModule (/usr/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:38:18)
    at VMScriptRunner.run (/usr/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:82:17)
    at EventTarget.#reload (/usr/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:748:13)
    at EventTarget.getPlugins (/usr/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:985:5)
    at createServer (/usr/lib/node_modules/wrangler/node_modules/@miniflare/http-server/src/index.ts:355:19)
    at startServer (/usr/lib/node_modules/wrangler/node_modules/@miniflare/http-server/src/index.ts:456:18)

✘ [ERROR] Could not start Miniflare.

```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-muccrz?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Also reported here: https://discord.com/channels/830184174198718474/1001705275541168138
