### ISSUE TITLE
🐛 BUG: Including wrangler in dev dependencies crashes preview, (Shiki) Node specifics being run/bundled

### ISSUE THREAD

**Issue by davycoe** [withastro/astro#4061]
### What version of `astro` are you using?

1.0.0-beta.73 || 1.0.0-rc.1

### Are you using an SSR adapter? If so, which one?

Cloudflare 0.3.0

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Crashes when running preview  `"preview": "wrangler pages dev dist/"`

Seems related to Shiki syntax highlighter.

```
[coe@arch plz]$ yarn preview                                                                                                                                           
yarn run v1.22.19                                                                                                                                                      
$ wrangler pages dev dist/                                                                                                                                             
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issu                                              es/new/choose                                                                                                                                                          
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮                                              
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit                                                 │                                              
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                                              
✘ [ERROR] [plugin checkForNodeBuiltins] Detected a Node builtin module import while Node compatibility is disabled.
Add node_compat = true to your wrangler.toml file to enable Node compatibility.

    node_modules/shiki/dist/index.esm.js:1639:33:
      1639 │             const path = require('path');
           ╵                                  ~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/wrangler/wrangler-dist/cli.js:114397:11:
      114397 │     build6.onResolve({
             ╵            ~~~~~~~~~

    at setup (/home/coe/code/plz/node_modules/wrangler/wrangler-dist/cli.js:114397:12)
    at handlePlugins (/home/coe/code/plz/node_modules/wrangler/node_modules/esbuild/lib/main.js:843:23)
    at Object.buildOrServe (/home/coe/code/plz/node_modules/wrangler/node_modules/esbuild/lib/main.js:1137:7)
    at /home/coe/code/plz/node_modules/wrangler/node_modules/esbuild/lib/main.js:2085:17
    at new Promise (<anonymous>)
    at Object.build (/home/coe/code/plz/node_modules/wrangler/node_modules/esbuild/lib/main.js:2084:14)
    at Object.build (/home/coe/code/plz/node_modules/wrangler/node_modules/esbuild/lib/main.js:1931:51)
    at bundleWorker (/home/coe/code/plz/node_modules/wrangler/wrangler-dist/cli.js:114434:33)
    at build6 (/home/coe/code/plz/node_modules/wrangler/wrangler-dist/cli.js:114544:17)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bcdncf?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by davycoe** [comment]
Just to add running Wrangler from global bin works as expected.
example: `wrangler2 pages dev dist/`

**Comment by matthewp** [comment]
Thanks! This is an interesting, I'll investigate.

**Comment by matthewp** [comment]
This might get fixed by https://github.com/withastro/astro/pull/4072. Going to test afterwards.

**Comment by davycoe** [comment]
All seems to be working now I've upgraded the to the latest:
- astro@1.0.0-rc.2
- @astrojs/cloudflare@0.4.0

Thanks!  🚀
