### ISSUE TITLE
🐛 BUG: @astrojs/vercel completely broken with new RC release

### ISSUE THREAD

**Issue by lostra01** [withastro/astro#4066]
### What version of `astro` are you using?

v1.0.0-rc.1

### Are you using an SSR adapter? If so, which one?

Vercel - Serverless (^0.3.0)

### What package manager are you using?

npm

### What operating system are you using?

MacOS Ventura

### Describe the Bug

With the new RC release any target of the Vercel integration (serverless, edge, static) runs fine on `run dev` but completely breaks on `run build` with the following error:

```
 generating static routes 
(node:17) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
 error   Cannot use import statement outside a module
    at compileFunction (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:6:341448)
    at wrapSafe (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:6:218347)
    at Module.prototype._compile (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:6:218723)
    at Module._extensions[".js"] (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:6:219743)
    at Module.prototype.load (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:6:217769)
    at Module._load (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:6:215340)
    at <anonymous> (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:6:983447)
    at _evaluate (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:15:285353)
    at evaluate (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:15:284512)
    at run (https://github-sdxvh2.w-corp.staticblitz.com/blitz.872be04de15f32da2f6e3973878bcc22a4a17b5d.js:6:987351)
    at <anonymous> (<anonymous>)
```

Removing the Vercel integration allows the site to build correctly, albeit in SSG mode. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sdxvh2?file=astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
`output: 'server'` is required for SSR in the new RC. We are warning about this in most of the adapters, maybe I forgot to add it to Vercel. Let me take a look.
