### ISSUE TITLE
Edge runtime error: Buffer is not defined

### ISSUE THREAD

**Issue by BurntCaramel** [withastro/astro#4323]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

Deno

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When deploying to Deno Deploy or running locally with Deno, I receive this error:
```
Server running on port 8085
01:43:51 pm [ssr] ReferenceError: Buffer is not defined
    at renderPage (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:5767:28)
    at async render (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:6560:10)
    at async App.renderPage_fn (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:7499:22)
    at async App.render (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:7451:22)
    at async Server.handler (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:7580:14)
    at async Server.#respond (https://deno.land/std@0.132.0/http/server.ts:298:18)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tdn4cu?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by QuiiBz** [comment]
I've encountered the same error when targeting any edge runtime (discussion on [the Discord](https://ptb.discord.com/channels/830184174198718474/845430950191038464/1008397963959218256)). Looking at the docs of cloudflare workers and deno deploy, none of them provides an API for `Buffer` which makes sense since it's a node-specific API.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! I will take a look at the PR you submitted, really appreciate it!

**Comment by FredKSchott** [comment]
Note for PR (or followup PR): Can we make sure that this code path is hit inside of our Deno test?
