### ISSUE TITLE
Chart.js with Vue: Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by panwauu** [withastro/astro#4437]
### What version of `astro` are you using?

1.0.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

The issue comes up when trying to use vue with [chart.js](https://www.chartjs.org/) and a [vue-chartjs wrapper](https://vue-chartjs.org/). The compenent looks something like this:

```vue
<template>
  <Bar :chart-options="chartOptions"  :chart-data="chartData" />
</template>

<script setup>
import { ref, computed } from 'vue';
import { Bar } from 'vue-chartjs';
import * as ChartImport from 'chart.js';
const { Chart,  Title,  Tooltip,  Legend,  BarElement,  CategoryScale,  LinearScale } = ChartImport;
Chart.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale);
//...
</script>
```

Using `dev` there are no problems and everything is rendering fine. Using `build` and `preview` the site still renders but I get the following errors/warnings:

During the `build` step, the following warning comes up:
```
TypeError: Cannot read properties of undefined (reading 'register')
    at setup (file:///home/projects/github-xex2du-mxge2r/dist/entry.mjs?time=1661258166778:1287:7)
    at _sfc_main.setup (file:///home/projects/github-xex2du-mxge2r/dist/entry.mjs?time=1661258166778:1345:23)
    at callWithErrorHandling (/home/projects/github-xex2du-mxge2r/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/home/projects/github-xex2du-mxge2r/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/home/projects/github-xex2du-mxge2r/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/home/projects/github-xex2du-mxge2r/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderVNode (/home/projects/github-xex2du-mxge2r/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:292:22)
    at renderComponentSubTree (/home/projects/github-xex2du-mxge2r/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:256:13)
    at renderComponentVNode (/home/projects/github-xex2du-mxge2r/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
    at Module.renderToString (/home/projects/github-xex2du-mxge2r/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
[Vue warn]: Component <Anonymous> is missing template or render function.
```

In the Browser, after using the `preview`, I get the following error:
```
runtime-core.esm-bundler.2fc439e1.js:1: Hydration completed but contains mismatches.
```

(Originated from this [Discord Channel](https://discord.com/channels/830184174198718474/992558929181683863))

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xex2du-mxge2r?file=src/components/Chart.vue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This looks like a packaging issue from `chart.js` in dev, Astro/Vite is able to read it's `module` field to get the ESM bundle, but in static builds that executes the code in nodejs, nodejs doesn't understand `module`, hence it loads the CJS version. Since both have different export shape, you can do something like this to workaround:

```js
const {
  Chart,
  Title,
  Tooltip,
  Legend,
  BarElement,
  CategoryScale,
  LinearScale,
} = ChartImport.default ? ChartImport.default : ChartImport;
```

Once chart.js releases 4.0, this should be fixed too. Closing for now as it's a library packaging issue.
