### ISSUE TITLE
Internal server error: Transform failed with 1 error

### ISSUE THREAD

**Issue by Jelenkee** [withastro/astro#4505]
### What version of `astro` are you using?

1.1.0

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Sometimes when the dev server is running and I make some changes on my components, I get this error in my Layout.
```
[1] 22:12:12 [vite] Internal server error: Transform failed with 1 error:
[1] /home/gaus/Projects/commerze/packages/astro/src/layouts/layout.astro?astro&type=script&index=0&lang.ts:2:7: ERROR: Expected "(" but found "\"modern-normalize\""
[1]   Plugin: vite:esbuild
[1]   File: /home/gaus/Projects/commerze/packages/astro/src/layouts/layout.astro?astro&type=script&index=0&lang.ts
[1]   
[1]   Expected "(" but found "\"modern-normalize\""
[1]   1  |  ---
[1]   2  |  import "modern-normalize";
[1]      |         ^
[1]   3  |  import "../main.scss";
[1]   4  |  import Header from "../layouts/header.astro";
[1]   
[1]       at failureErrorWithLog (/home/gaus/Projects/commerze/node_modules/esbuild/lib/main.js:1621:15)
[1]       at /home/gaus/Projects/commerze/node_modules/esbuild/lib/main.js:1410:29
[1]       at /home/gaus/Projects/commerze/node_modules/esbuild/lib/main.js:675:9
[1]       at handleIncomingPacket (/home/gaus/Projects/commerze/node_modules/esbuild/lib/main.js:772:9)
[1]       at Socket.readFromStdout (/home/gaus/Projects/commerze/node_modules/esbuild/lib/main.js:641:7)
[1]       at Socket.emit (node:events:527:28)
[1]       at addChunk (node:internal/streams/readable:315:12)
[1]       at readableAddChunk (node:internal/streams/readable:289:9)
[1]       at Socket.Readable.push (node:internal/streams/readable:228:10)
[1]       at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

After refreshing my browser the error is gone. It is difficult to reproduce.

Here my layout.astro
```html
---
import "modern-normalize";
import "../main.scss";
import Header from "../layouts/header.astro";
import Footer from "../layouts/footer.astro";
import { NAME } from "../ts/utils";
import { Toaster } from "svelte-french-toast";
---

<html lang="de">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{NAME}</title>
        <link rel="stylesheet" href="/g/uno.css" />
    </head>

    <body class="mx-auto max-w-1440px main-color flex flex-col h-screen">
        <Header />
        <main class="grow p-3">
            <slot />
        </main>

        <Footer />
        <Toaster client:idle />
        <script>
            import { getWishlist, getCart } from "../ts/cutils";
            getWishlist();
            getCart();
        </script>
    </body>
</html>

```

### Link to Minimal Reproducible Example

Sorry, not really reproducible

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @Jelenkee, sorry for taking so long to respond. Given the error message, I believe this was caused by the fact that esbuild was attempting to optimize your page. Is this something that still happens to you? Is there any more information you can give us to help you track down why this occurs?

Otherwise I'm not really sure how I can help here.

**Comment by matthewp** [comment]
I'm going to close since we haven't received a response. Happy to reopen if you can help me with some more information requested above. Or file a new issue when you have more information. Thank you!
