### ISSUE TITLE
[astro-rss] Could not resolve index.md

### ISSUE THREAD

**Issue by isaced** [withastro/astro#4598]
### What version of `astro` are you using?

1.1.3

### Are you using an SSR adapter? If so, which one?

None (local)

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Here is my `src/pages` directory structure:

```
➜  tree src/pages 
src/pages
├── about.md
├── contact.md
├── disclaimer.md
├── index.md
├── rss.xml.js
```

Here is my rss.xml.js file:

```javascript
import rss from '@astrojs/rss';

export const get = () => rss({
    title: 'Buzz’s Blog',
    description: 'A humble Astronaut’s guide to the stars',
    site: import.meta.env.SITE,
    items: import.meta.glob('./*.md'),
    customData: `<language>en-us</language>`,
});
```

and error log:

```
$ astro dev
  🚀  astro  v1.0.9 started in 72ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

url:/about, frontmatter:[object Object]
url:/contact, frontmatter:[object Object]
url:/disclaimer, frontmatter:[object Object]
url:, frontmatter:[object Object]                     ---- this post is 'index.md'
 error   [RSS] When passing an import.meta.glob result directly, you can only glob ".md" files within /pages! Consider mapping the result to an array of RSSFeedItems. See the RSS docs for usage examples: https://docs.astro.build/en/guides/rss/#2-list-of-rss-feed-objects
Error: [RSS] When passing an import.meta.glob result directly, you can only glob ".md" files within /pages! Consider mapping the result to an array of RSSFeedItems. See the RSS docs for usage examples: https://docs.astro.build/en/guides/rss/#2-list-of-rss-feed-objects
    at file:///Users/isaced/Projects/cocoaz/node_modules/@astrojs/rss/dist/index.js:12:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async Proxy.getRSS (file:///Users/isaced/Projects/cocoaz/node_modules/@astrojs/rss/dist/index.js:36:13)
    at async call (file:///Users/isaced/Projects/cocoaz/node_modules/astro/dist/core/endpoint/index.js:11:20)
    at async call (file:///Users/isaced/Projects/cocoaz/node_modules/astro/dist/core/endpoint/dev/index.js:5:10)
    at async handleRequest (file:///Users/isaced/Projects/cocoaz/node_modules/astro/dist/vite-plugin-astro-server/index.js:251:22)
```

I added a line of log output in this place, and found that the url of 'index.md' was empty, is this what is causing the error? maybe we should skip `index.md`?

https://github.com/withastro/astro/blob/4ee997da43e0357caaa9566de495afcf4e924803/packages/astro-rss/src/index.ts#L55-L63

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tlsw9o?on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by X7md** [comment]
I was having the same issue but with `mdx`, and I do this as workaround.

https://github.com/X7md/mushkhbat/blob/f34cce99e72e0c4cda8b262aa90ba00d88a8e8cd/src/pages/rss.xml.js#L2-L3

**Comment by bholmesdev** [comment]
Ah, I think I know the issue here! We pass an empty string `""` for your homepage route today, rather than a `"/"`. This is likely tripping up our type check. Will make a fix 👍
