### ISSUE TITLE
import "node:assert" causes transform error

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#4632]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

This page fails to render:

```
---
import assert from "node:assert";
---
<p>Hello</p>
```

Error message:

```
 error   Transform failed with 1 error:
  /home/projects/github-em18nv/src/pages/index.astro:21:48: ERROR: Expected "{" but found "from"
  File:
    /home/projects/github-em18nv/src/pages/index.astro
  Stacktrace:
Error: Transform failed with 1 error:
/home/projects/github-em18nv/src/pages/index.astro:21:48: ERROR: Expected "{" but found "from"
    at failureErrorWithLog (/home/projects/github-em18nv/node_modules/esbuild/lib/main.js:1624:15)
    at eval (/home/projects/github-em18nv/node_modules/esbuild/lib/main.js:1413:29)
    at eval (/home/projects/github-em18nv/node_modules/esbuild/lib/main.js:678:9)
    at handleIncomingPacket (/home/projects/github-em18nv/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/home/projects/github-em18nv/node_modules/esbuild/lib/main.js:644:7)
    at EventEmitter.emit (https://github-em18nv.w.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:155574)
    at addChunk (https://github-em18nv.w.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:656479)
    at readableAddChunk (https://github-em18nv.w.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:656183)
    at Readable.push (https://github-em18nv.w.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:656867)
    at _0x244c2a.onStreamRead [as onread] (https://github-em18nv.w.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:783980)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-em18nv?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
It seems not be caused by `"node:assert"` but rather just by naming an import `assert`. Here's where it still gets that error if you instead import a local module: https://stackblitz.com/edit/github-em18nv-cgrfj2?file=src%2Fpages%2Findex.astro,src%2Fassert.js

If you change the thing you are importing to `assert2` it works. Very odd.

**Comment by shishkin** [comment]
Thanks @matthewp!
