### ISSUE TITLE
Slotting into non-children prop of React component fails

### ISSUE THREAD

**Issue by agomai** [withastro/astro#4806]
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

As an equivalent of [named slots](https://docs.astro.build/en/core-concepts/astro-components/#slots), React components use other props than `children` to which content (React nodes) can be passed.
Passing content from Astro components to these non-children props only works for strings – it fails if:
1. the content passed to a non-`children` prop is an element
2. the content passed to a non-`children` prop is passed via a `<slot>` of a wrapping astro component

Consider this exemplary React component:

`layouts/example-layout.tsx`
~~~typescript
import type { ReactNode } from 'react';

type ExampleProps = {
  // this is the "named slot" equivalent
  header?: ReactNode;
  children: ReactNode;
};

export default function ExampleLayout({ header, children }: ExampleProps) {
  return (
    <div>
      {header}
      {children}
    </div>
  );
}
~~~

And this wrapping Astro component:

`layouts/example-wrapper-layout-with-header.astro`
~~~astro
---
import ExampleLayout from './example-layout';
---
<ExampleLayout header={<slot name="header" />}>
  <slot />
</ExampleLayout>
~~~

These usage in a page fail:

`pages/index.astro`
~~~astro
---
import ExampleLayout from '../layouts/example-layout';
/*
💥 FAILS 2. the content passed to a non-`children` prop is passed via a `<slot>` of a wrapping astro component

[plugin:astro:build] Transform failed with 1 error:
/home/projects/github-8ubpke/src/layouts/example-wrapper-layout-with-header.astro:33:92: ERROR: Expected ">" but found "name"
/home/projects/github-8ubpke/src/layouts/example-wrapper-layout-with-header.astro:33:92
Error: Transform failed with 1 error:
/home/projects/github-8ubpke/src/layouts/example-wrapper-layout-with-header.astro:33:92: ERROR: Expected ">" but found "name"
    at failureErrorWithLog (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:1624:15)
    at eval (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:1413:29)
    at eval (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:678:9)
    at handleIncomingPacket (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:644:7)
    at EventEmitter.emit (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:155574)
    at addChunk (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:656716)
    at readableAddChunk (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:656420)
    at Readable.push (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:657104)
    at _0x364bb2.onStreamRead [as onread] (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:784218)
    at Object.emit (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:257778)
    at _0x5d8443 (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:259441)
    at Object._0x410bdf [as emit] (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:256037)
    at https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:258716
    at Map.forEach (<anonymous>)
    at _0x393aaf (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:258677
*/
import ExampleWrapperLayoutWithHeader from '../layouts/example-wrapper-layout-with-header.astro';
---

<html lang="en">
	<head><title>Astro</title></head>
	<body>
		<!-- 👍 WORKS -->
		<ExampleLayout header={`Direct slotting of string into non-children prop works`}>
			Direct "slotting" of string into children prop works
		</ExampleLayout>


		
		<!--
		💥 FAILS: 1. the content passed to a non-`children` prop is an element

		[plugin:astro:build] Transform failed with 1 error:
/home/projects/github-8ubpke/src/pages/index.astro:52:85: ERROR: Expected ")" but found "\"slotting\""
/home/projects/github-8ubpke/src/pages/index.astro:52:85
Error: Transform failed with 1 error:
/home/projects/github-8ubpke/src/pages/index.astro:52:85: ERROR: Expected ")" but found "\"slotting\""
    at failureErrorWithLog (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:1624:15)
    at eval (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:1413:29)
    at eval (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:678:9)
    at handleIncomingPacket (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/home/projects/github-8ubpke/node_modules/esbuild/lib/main.js:644:7)
    at EventEmitter.emit (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:155574)
    at addChunk (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:656716)
    at readableAddChunk (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:656420)
    at Readable.push (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:657104)
    at _0x364bb2.onStreamRead [as onread] (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:6:784218)
    at Object.emit (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:257778)
    at _0x5d8443 (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:259441)
    at Object._0x410bdf [as emit] (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:256037)
    at https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:258716
    at Map.forEach (<anonymous>)
    at _0x393aaf (https://github-8ubpke.w.staticblitz.com/blitz.829380144b30b4dc31bd04f9b94de7766022f986.js:8:258677
		-->
		<ExampleLayout header={<span>Direct "slotting" of element into non <code>children</code> fails</span>}>
			<span>Direct "slotting" of element into <code>children</code> works</span>
		</ExampleLayout>

		<!--
		💥 FAILS 2. the content passed to a non-`children` prop is passed via a `<slot>` of a wrapping astro component (due import error above)
		-->
		<ExampleWrapperLayoutWithHeader>
			<span slot="header">Indirect (via wrapper) "slotting" of element into non-children prop fails</span>
			Indirect (via wrapper) "slotting" of string into children prop works
		</ExampleWrapperLayoutWithHeader>
	</body>
</html>

~~~

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8ubpke?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
That's because you're passing an Astro component into a React component. Slots are special cases that we convert to React components, but we can't do so for arbitrary props. There has been some discussion about allowing "slot props", but I think this would be a new feature that needs an RFC. I would start a discussion here: https://github.com/withastro/rfcs/discussions

**Comment by njfamirm** [comment]
after 3 years, what is solution?
