### ISSUE TITLE
Can't SSR render react component in preact/compat

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#4880]
### What version of `astro` are you using?

1.3.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I render [react-map-gl](https://github.com/visgl/react-map-gl) React component in Astro with preact integration and preact/compat enabled. It all works fine locally with `astro dev`. But when I deploy to Vercel I get the following error:

```json
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "Error: [object Object] is not a valid HTML tag name in <[object Object] ...component props here...>",
  "reason": {
    "errorType": "Error",
    "errorMessage": "[object Object] is not a valid HTML tag name in <[object Object] ...component props here...>",
    "stack": [
      "Error: [object Object] is not a valid HTML tag name in <[object Object] ...component props here...>",
      "    at A (file:///var/task/node_modules/preact-render-to-string/dist/index.mjs:1:6811)",
      "    at A (file:///var/task/node_modules/preact-render-to-string/dist/index.mjs:1:6174)",
      "    at S (file:///var/task/node_modules/preact-render-to-string/dist/index.mjs:1:4775)",
      "    at Object.renderToStaticMarkup$1 (file:///var/task/entry.js:92:15)",
      "    at renderComponent (file:///var/task/entry.js:1117:66)",
      "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
    ]
  },
  "promise": {},
  "stack": [
    "Runtime.UnhandledPromiseRejection: Error: [object Object] is not a valid HTML tag name in <[object Object] ...component props here...>",
    "    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)",
    "    at process.emit (node:events:539:35)",
    "    at emit (node:internal/process/promises:140:20)",
    "    at processPromiseRejections (node:internal/process/promises:274:27)",
    "    at processTicksAndRejections (node:internal/process/task_queues:97:32)"
  ]
}
```

(I removed the actual props but they also contain `[object Object] if not primitive`)

I can't reproduce it on stackblitz, but here is the best effort of the repro.

I would love to try to debug and contribute a fix but would need some guidance.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7zieut

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by shishkin** [comment]
Interestingly, switching the component to `client:only="preact"` make it work albeit doesn't render imported CSS. Which is probably a separate issue.

**Comment by davidvpe** [comment]
I've created issue #5167 cause I am having that second issue @shishkin is mentioning when using `client:only="react"`

**Comment by torchsmith** [comment]
I have this problem as well.

**Comment by torchsmith** [comment]
I'm trying to build static - no provider.

**Comment by torchsmith** [comment]
@shishkin try adding the react-map-gl to astro config under: `vite.ssr.noExternal`.

This fixed the problem for me and could possibly fix it for you.

Also here is a related issue from preact that helped me understand the problem some
https://github.com/preactjs/preact-render-to-string/issues/159

**Comment by shishkin** [comment]
Thanks @torchsmith for the suggestion. I won't be able to try it since I moved on from that react library.

Unfortunately, vercel provider still seems like a huge hack at the moment. It fails with confusing error messages and has no obvious way to test the build locally.

**Comment by bluwy** [comment]
If using `vite.ssr.noExternal`, I'm pretty sure the overrides documented [here](https://docs.astro.build/en/guides/integrations-guide/preact/#compat) isn't used that's causing problems. I'll close this for now assuming that's the fix, but feel free to ping me if there's still an issue with it!

**Comment by bluwy** [comment]
Thanks for the ping. That's strange though 🤔 That means the react component library is still importing `react` code somehow. Maybe you could check `node_modules` if `react` and `react-dom` exists, and whether their `package.json` contains `"name": "@preact/compat"` instead. I think it worked when I last tried it.

Using `noExternal` is fine though, but that means you're bundling the library, which may or may not be something you'd want.

**Comment by stormynight9** [comment]
any updates on this?
