### ISSUE TITLE
Error happens when astro + react + antd

### ISSUE THREAD

**Issue by brandonxiang** [withastro/astro#4895]
### What version of `astro` are you using?

1.2.3

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

error happens in entry.mjs when I set up a project about astro + react + antd.

It happens when I build this bundle.

```
 building client 
Completed in 1.44s.


 generating static routes 
 error   Cannot find module '/Users/weipingxiang/test/my-astro-site/node_modules/antd/es/breadcrumb.js' imported from /Users/weipingxiang/test/my-astro-site/dist/entry.mjs
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/weipingxiang/test/my-astro-site/node_modules/antd/es/breadcrumb.js' imported from /Users/weipingxiang/test/my-astro-site/dist/entry.mjs
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)
```

### Link to Minimal Reproducible Example

https://github.com/brandonxiang/astro-react-antd

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by brandonxiang** [comment]
correct path is： node_modules/antd/es/breadcrumb/index.js
