### ISSUE TITLE
@astro/image: moving away from sharp breaks GIF compatibility

### ISSUE THREAD

**Issue by panwauu** [withastro/astro#4936]
### What version of `astro` are you using?

1.4.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Before 0.8.x and by using sharp we can transform GIF to webp without any problems.

With the new updates and the new transformer, I can't use GIFs anymore:
1) When using `format='webp'`, I get `Buffer has an unsupported format` with the default settings.
2) When using no format, I get the error: 
```
Error: Unknown image output: "undefined" used for /radar.gif?date=30
    at SquooshService.transform (/node_modules/@astrojs/image/dist/loaders/squoosh.js:92:13)
    at Module.get (C:\Users\bauma\source\wetter\client\node_modules\@astrojs\image\dist\endpoint.js:32:66)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async call (file:///C:/Users/bauma/source/wetter/client/node_modules/astro/dist/core/endpoint/index.js:20:20)
    at async call (file:///C:/Users/bauma/source/wetter/client/node_modules/astro/dist/core/endpoint/dev/index.js:5:10)
    at async handleRoute (file:///C:/Users/bauma/source/wetter/client/node_modules/astro/dist/vite-plugin-astro-server/index.js:272:20)       
    at async handleRequest (file:///C:/Users/bauma/source/wetter/client/node_modules/astro/dist/vite-plugin-astro-server/index.js:213:12)     
Unknown image output: "undefined" used for https://www.zebrafell.de/wetter/wolke.gif?date=30
```

(One problem may be that I am using the url with a query string https://.../image.gif?date=0)
(I have problems getting the stackblitz to work as even the normal image is not loaded)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tynear?file=package.json&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Using sharp is still supported via a configuration option: https://docs.astro.build/en/guides/integrations-guide/image/#installing-sharp-optional

Let me know if that works for you!

**Comment by panwauu** [comment]
By using sharp it does still work. Still we had some problems installing sharp and subsequently, I would like to use it without.
