### ISSUE TITLE
Cannot use layout within ternary expression

### ISSUE THREAD

**Issue by awwong1** [withastro/astro#5224]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When a layout is used in a ternary expression, Astro throws a transform/compile error.

`src/layouts/BaseLayout.astro`
```astro
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
  <meta name="viewport" content="width=device-width" />
  <meta name="generator" content={Astro.generator} />
  <title>Astro</title>
</head>
<body>
  <slot />
</body>
</html>
```

`src/pages/index.astro`
```astro
---
import BaseLayout from "../layouts/BaseLayout.astro"

const toggleError = false;
---

<!-- this throws an error, even if not called -->
{toggleError ? <BaseLayout>
	<h1>SITE: {Astro.site}</h1>
	<p>BASE_URL: {import.meta.env.BASE_URL}</p>
</BaseLayout> : <>
	<h1>SITE: {Astro.site}</h1>
	<p>BASE_URL: {import.meta.env.BASE_URL}</p>
</>}

<!-- this is fine -->
<BaseLayout>
	<h1>SITE: {Astro.site}</h1>
	<p>BASE_URL: {import.meta.env.BASE_URL}</p>
</BaseLayout>
```

Error:
```text
[plugin:astro:build] Transform failed with 1 error:
/home/projects/github-lfwuxd/src/pages/index.astro:28:250: ERROR: Expected ":" but found "}"

/home/projects/github-lfwuxd/src/pages/index.astro:28:250

Error: Transform failed with 1 error:
/home/projects/github-lfwuxd/src/pages/index.astro:28:250: ERROR: Expected ":" but found "}"
    at failureErrorWithLog (/home/projects/github-lfwuxd/node_modules/esbuild/lib/main.js:1624:15)
    at start/< (/home/projects/github-lfwuxd/node_modules/esbuild/lib/main.js:1413:29)
    at sendRequest/< (/home/projects/github-lfwuxd/node_modules/esbuild/lib/main.js:678:17)
    at handleIncomingPacket (/home/projects/github-lfwuxd/node_modules/esbuild/lib/main.js:775:17)
    at readFromStdout (/home/projects/github-lfwuxd/node_modules/esbuild/lib/main.js:644:27)
    at EventEmitter.prototype.emit (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:155574)
    at S.prototype.emit (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:1408649)
    at addChunk (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:656479)
    at readableAddChunk (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:656183)
    at Readable.prototype.push (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:656867)
    at onStreamRead (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:783982)
    at _0x6e841d/< (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8:254118)
    at _0x432ffb (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8:255719)
    at _0x4c36e3 (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8:252475)
    at _0x5cea1c/< (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8:254966)
    at _0x5cea1c (https://github-lfwuxd.w-corp.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8:254934
```

Expected behaviour: Astro can render layouts within ternary expressions.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lfwuxd?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by awwong1** [comment]
Workaround is to just not use the ternary.
```astro
{toggleError && <BaseLayout>
	<h1>SITE: {Astro.site}</h1>
	<p>BASE_URL: {import.meta.env.BASE_URL}</p>
</BaseLayout>}
{!toggleError && <>
	<h1>SITE: {Astro.site}</h1>
	<p>BASE_URL: {import.meta.env.BASE_URL}</p>
</>}

```

**Comment by chenxsan** [comment]
Seems to be a bug in compiler https://github.com/withastro/compiler/issues/466

**Comment by natemoo-re** [comment]
Thanks for the issue! Definitely a compiler bug, I'll try to get this fixed ASAP.

In the meantime, this might be a slightly cleaner workaround.

```astro
---
import BaseLayout from "../layouts/BaseLayout.astro"

const toggleError = false;
const Wrapper = toggleError ? BaseLayout : Fragment;
---

<Wrapper>
  <h1>SITE: {Astro.site}</h1>
  <p>BASE_URL: {import.meta.env.BASE_URL}</p>
</Wrapper>
```

**Comment by matthewp** [comment]
Moving to the compiler repo.
