### ISSUE TITLE
@astrojs/image import fail on build and warning on dev

### ISSUE THREAD

**Issue by TPoret** [withastro/astro#5380]
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn v1.22.19

### What operating system are you using?

WSL

### Describe the Bug

When using `import()` in .astro file I get a warning when running `yarn run dev` and an error on `yarn run build`. However if I replace the import with a string it does not bug.

The dev preview work (I can see the image loaded even with the warning) while I cannot release it because the build fail.

I use node v16.18.0

```<Image src={import(`../${imgSource}`)} alt="whatever" />``` bug
`<Image src={import("../assets/test.jpg")} alt="whatever" />` work

The code used
```astro
<Picture
    src={import(`../${imgSource}`)}
    widths={[200, 400, 800]}
    sizes="(max-width: 800px) 100vw, 800px"
    alt="whatever"
/>
<Image src={import(`../${imgSource}`)} alt="whatever" />
```
The warning I get in dev
```
13 |    const { imgSource } = Astro2.props;
14 |    return $$render`${$$renderComponent($$result, "Picture", Picture, { "src": import(`../${imgSource}`), "widths": [200, 400, 800], "sizes": "(max-width: 800px) 100vw, 800px", "alt": "whatever" })}
15 |  ${$$renderComponent($$result, "Image", Image, { "src": import(`../${imgSource}`), "alt": "whatever" })}`;
   |                                                                ^
16 |  });
17 |  export default $$Card;
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.

  Plugin: vite:import-analysis
  File: /home/tporet/astro-image-import-bug/src/components/Card.astro
```
The error I get in build
```
yarn run v1.22.19
$ astro build
11:31:59 AM [build] output target: static
11:31:59 AM [build] Collecting build info...
11:31:59 AM [build] Completed in 65ms.
11:31:59 AM [build] Building static entrypoints...
[plugin:vite:dynamic-import-vars] invalid import "../${imgSource}". A file extension must be included in the static part of the import. For example: import(`./foo/${bar}.js`).
[plugin:vite:dynamic-import-vars] invalid import "../${imgSource}". A file extension must be included in the static part of the import. For example: import(`./foo/${bar}.js`). (x2)
11:32:04 AM [build] Completed in 5.16s.

 generating static routes 
▶ src/pages/index.astro
  └─ /index.html (+17ms)
▶ src/pages/[test].astro
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/tporet/astro-image-import-bug/assets/test.jpg' imported from /home/tporet/astro-image-import-bug/dist/entry.mjs
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:330:11)
    at moduleResolve (node:internal/modules/esm/resolve:907:10)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:521:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14) {
  code: 'ERR_MODULE_NOT_FOUND'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Link to Minimal Reproducible Example

https://githubbox.com/TPoret/astro-img-bug
Navigate to /test to see the warning

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Did you read the warning and error? You can't dynamically import that way.

**Comment by TPoret** [comment]
> Did you read the warning and error? You can't dynamically import that way.

Yes I read and sorry I fail to see what I am doing wrong, It is the same in the docs examples.

See https://docs.astro.build/en/guides/images/ the
 ```astro
<!-- local image imports can also be inlined directly-->
<Image src={import('../assets/logo.png')} alt={localAlt}/>
```
part.

Do inline means not passing a variable to the import statement ?

**Comment by matthewp** [comment]
This is the warning to look at:

```
invalid import "../${imgSource}". A file extension must be included in the static part of the import. For example: import(`./foo/${bar}.js`).
```

So instead of doing:

```astro
<Image src={import(`../${imgSource}`)} alt="whatever" />
```

You should do:

```astro
<Image src={import(`../${imgSource}.png`)} alt="whatever" />
```

And include the extension.

**Comment by TPoret** [comment]
@matthewp Thank for your answer, I did not think of that as I thought it wanted me to put ".js "extension.

But still it is not working.

I find it weird that without explicit extension we have 2 different behavior between "dev" and "build".

Anyway I updated my code and now I get the following error:

```
 error   Unknown variable dynamic import: ../assets/test.jpg
  File:
    /src/components/Card.astro:15:131
  Stacktrace:
Error: Unknown variable dynamic import: ../assets/test.jpg
    at eval (/@vite/dynamic-import-helper:9:96)
    at new Promise (<anonymous>)
    at Module.__vite_ssr_exports__.default (/@vite/dynamic-import-helper:8:12)
    at eval (/src/components/Card.astro:15:131)
    at Module.renderToIterable (/node_modules/astro/dist/runtime/server/render/astro.js:79:27)
    at renderAstroComponentInline (/node_modules/astro/dist/runtime/server/render/component.js:75:52)
    at renderAstroComponentInline.next (<anonymous>)
    at Module.renderChild (/node_modules/astro/dist/runtime/server/render/any.js:32:5)
    at async AstroComponent.[Symbol.asyncIterator] (/node_modules/astro/dist/runtime/server/render/astro.js:37:7)
    at async Module.renderAstroComponent (/node_modules/astro/dist/runtime/server/render/astro.js:48:20)

/@vite/dynamic-import-helper:9
        (typeof queueMicrotask === 'function' ? queueMicrotask : setTimeout)(reject.bind(null, new Error('Unknown variable dynamic import: ' + path)));
                                                                                               ^

Error: Unknown variable dynamic import: ../assets/test.jpg
    at eval (/@vite/dynamic-import-helper:9:96)
    at new Promise (<anonymous>)
    at Module.__vite_ssr_exports__.default (/@vite/dynamic-import-helper:8:12)
    at eval (/src/components/Card.astro:16:127)
    at Module.renderToIterable (/node_modules/astro/dist/runtime/server/render/astro.js:79:27)
    at renderAstroComponentInline (/node_modules/astro/dist/runtime/server/render/component.js:75:52)
    at renderAstroComponentInline.next (<anonymous>)
    at Module.renderChild (/node_modules/astro/dist/runtime/server/render/any.js:32:5)
    at async AstroComponent.[Symbol.asyncIterator] (/node_modules/astro/dist/runtime/server/render/astro.js:37:7)
    at async Module.renderAstroComponent (/node_modules/astro/dist/runtime/server/render/astro.js:48:20)
error Command failed with exit code 1
```

The project is available at https://codesandbox.io/s/github/TPoret/astro-img-bug.

**Comment by tobyhage** [comment]
Here the same issue. 

// According documentation (and working) -> image imports can also be inlined directly
<Image src={import('../assets/hero.png')} alt="descriptive text" />

// Not working
<Image src={import(`../${imgSource}.png`)} alt="whatever" />

// Warning in dev and not working when build
<Image src={import(`../${imgSource}`)} alt="whatever" />

Hopefully can somebody explain why this is not working.

Is this a bug?!
Is it not possible?!
Or are both @TPoret and I using this the wrong way

**Comment by bluwy** [comment]
@TPoret I think it's because you're expecting `imgSource` to work with it's containging `/`. According to https://vitejs.dev/guide/features.html#dynamic-import

> Note that variables only represent file names one level deep. If file is 'foo/bar', the import would fail. For more advanced usage, you can use the [glob import](https://vitejs.dev/#glob-import) feature.

You can only access images one-level deep.

**Comment by justuspfaue** [comment]
Hey, I am having problems with the same thing. I am getting `TypeError: Unkown file extension ".png" for /path/FileMaker.png`

I use import("../assets/"+image+".png"), where image is the Filename (only one level).

Any ideas/hints?
