### ISSUE TITLE
@astro/vercel breaks when returning a body string

### ISSUE THREAD

**Issue by WesSouza** [withastro/astro#5463]
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

Vercel

### What is the Node.js version?

18

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Returning a body string breaks on Vercel if Node.js version is set to 18.

```ts
export const get: APIRoute = async function get() {
  // Breaks on Vercel on Node 18
  return { body: 'Ok' };
};
```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ArrayBuffer
    at new NodeError (node:internal/errors:393:5)
    at write_ (node:_http_outgoing:843:11)
    at ServerResponse.write (node:_http_outgoing:808:15)
    at setResponse (file:///var/task/node_modules/.pnpm/@astrojs+vercel@2.3.4/node_modules/@astrojs/vercel/dist/serverless/request-transform.js:74:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.handler (file:///var/task/node_modules/.pnpm/@astrojs+vercel@2.3.4/node_modules/@astrojs/vercel/dist/serverless/entrypoint.js:22:5)
```

The error is on https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/serverless/request-transform.ts#L106.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yvnj7o?file=src%2Fpages%2Fstring-body.ts&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Maybe this needs to be `response.text()` instead to workaround compat issue with nodejs 18.
