### ISSUE TITLE
Internal Server Error: Transform failed with 1 error. When extending Object prototype.

### ISSUE THREAD

**Issue by iivvaannxx** [withastro/astro#5470]
### What version of `astro` are you using?

1.6.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux, the server runs inside an Ubuntu Docker image (node:latest).

### Describe the Bug

What I am trying to do is very simple. 

I want to extend some of the default classes (String, Object...) with some utility of my own. As I am using Typescript, I have an `extensions.d.ts` file somewhere in my project where there's something declared like:

```typescript

declare global {

    // ...

    interface Object {

        'map': (callback: (key: string, value: any) => [string, any]) => { [key: string]: any };
        'log': () => void;
    }

    // ...
}
```

Then, there's also the implementation for that on another file `source/extensions/object.ts` where I write:
```typescript

Object.prototype.map = function (this: any, callback: (key: string, value: any) => [string, any]) => { [key: string]: any } {

    // Implementation here...
}

Object.prototype.log = function (this: any): void {

    // Implementation here...
}

```
Then when the server updates the code and I try to import this code like `import '@source/extensions/object.ts'` (route defined inside the `tsconfig.json`) a random error appears which says:

```log
Plugin: vite:esbuild
2022-11-25 00:31:52   File: /srv/www/website/source/modules/layouts/Page.astro?astro&type=script&index=2&lang.ts:246:12
2022-11-25 00:31:52   
2022-11-25 00:31:52   Invalid option in transform() call: "log"
2022-11-25 00:31:52   
2022-11-25 00:31:52   
2022-11-25 00:31:52       at failureErrorWithLog (/srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:1566:15)
2022-11-25 00:31:52       at /srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:839:20
2022-11-25 00:31:52       at responseCallbacks.<computed> (/srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:671:9)
2022-11-25 00:31:52       at handleIncomingPacket (/srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:726:9)
2022-11-25 00:31:52       at Socket.readFromStdout (/srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:647:7)
2022-11-25 00:31:52       at Socket.emit (node:events:513:28)
2022-11-25 00:31:52       at Socket.emit (node:domain:489:12)
2022-11-25 00:31:52       at addChunk (node:internal/streams/readable:324:12)
2022-11-25 00:31:52       at readableAddChunk (node:internal/streams/readable:297:9)
2022-11-25 00:31:52       at Readable.push (node:internal/streams/readable:234:10)
2022-11-25 00:31:52 11:31:52 PM [vite] Internal server error: Transform failed with 1 error:
2022-11-25 00:31:52 /srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:246:12: ERROR: Invalid option in transform() call: "log"

Plugin: vite:esbuild
2022-11-25 00:31:52   File: /srv/www/website/source/modules/layouts/Page.astro?astro&type=script&index=2&lang.ts:246:12
2022-11-25 00:31:52   
2022-11-25 00:31:52   Invalid option in transform() call: "map"
2022-11-25 00:31:52   
2022-11-25 00:31:52   
2022-11-25 00:31:52       at failureErrorWithLog (/srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:1566:15)
2022-11-25 00:31:52       at /srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:839:20
2022-11-25 00:31:52       at responseCallbacks.<computed> (/srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:671:9)
2022-11-25 00:31:52       at handleIncomingPacket (/srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:726:9)
2022-11-25 00:31:52       at Socket.readFromStdout (/srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:647:7)
2022-11-25 00:31:52       at Socket.emit (node:events:513:28)
2022-11-25 00:31:52       at Socket.emit (node:domain:489:12)
2022-11-25 00:31:52       at addChunk (node:internal/streams/readable:324:12)
2022-11-25 00:31:52       at readableAddChunk (node:internal/streams/readable:297:9)
2022-11-25 00:31:52       at Readable.push (node:internal/streams/readable:234:10)
2022-11-25 00:31:52 11:31:52 PM [vite] Internal server error: Transform failed with 1 error:
2022-11-25 00:31:52 /srv/www/website/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:246:12: ERROR: Invalid option in transform() call: "map"
```

And I can't figure out why this is happening, so I thought to post this issue and see if it could be a bug.

I can successfully extend other classes like `String` or `Array` and use them in my code without any error. This only happens when trying to extend the `Object` class.

By the way, I could not reproduce this issue exactly as it happens to me, but when trying, I got another random issue (see screenshot below) that also happens when trying to extend the `Object` prototype. They may be related.

![image](https://user-images.githubusercontent.com/47715589/203876904-ddfe1e71-c167-4503-b330-e5961018229b.png)

The linked example gives this error, which I don't receive on my local server, but still, it's odd.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-klgsxp?file=src/extensions/object.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

### EDIT

 I've decided to take another approach to write those utility methods, as it's actually not a good practice at all to extend the prototype of those types and it was mainly for syntactic sugar. I will leave the issue open in case it leads to some bug correction, but feel free to close it if you want.

**Comment by bluwy** [comment]
> I've decided to take another approach to write those utility methods, as it's actually not a good practice at all to extend the prototype of those types and it was mainly for syntactic sugar. I will leave the issue open in case it leads to some bug correction, but feel free to close it if you want.

Yeah it's not recommended to do this in JS. Looks like the error happens because `.map` isn't re-implemented correctly. Closing for now.
