### ISSUE TITLE
Error reporting fails on undefined error index

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#5526]
### What version of `astro` are you using?

astro@0.0.0-error-overlay-20221130171441

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Getting an undefined property access on `errors[i].message`

https://github.com/withastro/astro/blob/a1885ea2f59f26cbdae10c298e1e0d1063d9dca1/packages/astro/src/core/errors/dev/utils.ts#L51

may be useful to enable "noUnindexedAccess" in the repo for typescript..

```
file:///Users/calebjasik/Git/aoc-astro/node_modules/.pnpm/astro@0.0.0-error-overlay-20221130171441/node_modules/astro/dist/core/errors/dev/utils.js:41
      err[i].message = text;
                     ^

TypeError: Cannot set properties of undefined (setting 'message')
    at file:///Users/calebjasik/Git/aoc-astro/node_modules/.pnpm/astro@0.0.0-error-overlay-20221130171441/node_modules/astro/dist/core/errors/dev/utils.js:41:22
    at Array.forEach (<anonymous>)
    at collectErrorMetadata (file:///Users/calebjasik/Git/aoc-astro/node_modules/.pnpm/astro@0.0.0-error-overlay-20221130171441/node_modules/astro/dist/core/errors/dev/utils.js:38:14)
    at onError (file:///Users/calebjasik/Git/aoc-astro/node_modules/.pnpm/astro@0.0.0-error-overlay-20221130171441/node_modules/astro/dist/vite-plugin-astro-server/request.js:59:33)
    at runWithErrorHandling (file:///Users/calebjasik/Git/aoc-astro/node_modules/.pnpm/astro@0.0.0-error-overlay-20221130171441/node_modules/astro/dist/vite-plugin-astro-server/controller.js:68:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleRequest (file:///Users/calebjasik/Git/aoc-astro/node_modules/.pnpm/astro@0.0.0-error-overlay-20221130171441/node_modules/astro/dist/vite-plugin-astro-server/request.js:39:3)
 ELIFECYCLE  Command failed with exit code 1.

aoc-astro on  main [!] via  v16.17.1 took 4s 
❯ 
```

### Link to Minimal Reproducible Example

https://github.com/jasikpark/aoc-astro/blob/astro-dev-server-bug/src/pages/aoc/02/index.mdx
https://stackblitz.com/~/github.com/jasikpark/aoc-astro/blob/astro-dev-server-bug/src/pages/aoc/02/index.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jasikpark** [comment]
@Princesseuh helped me w/ this in discord, it's unrelated to #5495

**Comment by Princesseuh** [comment]
Not marking as a p5 since it doesn't affect a lot of users, but this one is pretty important because it crash the dev server

**Comment by wulinsheng123** [comment]
What link do I access can replicate this bug?

![image](https://user-images.githubusercontent.com/27261522/205482625-1a5a4910-c14b-44a7-85d2-ba147bd4eac1.png)
nothing happen in my client

**Comment by jasikpark** [comment]
ah, i may have not uploaded the commit that triggers it

**Comment by jasikpark** [comment]
I updated the branch linked, it should trigger now by running the dev server && loading <http://localhost:3000/aoc/02/>

**Comment by wulinsheng123** [comment]
> I updated the branch linked, it should trigger now by running the dev server && loading http://localhost:3000/aoc/02/

Thanks let me try late

**Comment by wulinsheng123** [comment]
Yes, I got it. i'm trying to fix it
