### ISSUE TITLE
Cannot use import statement outside a module 

### ISSUE THREAD

**Issue by dicekymt** [withastro/astro#5530]
### What version of `astro` are you using?

1.6.12

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I embed the code which is output  by React with [Spline](https://github.com/splinetool/react-spline)  and build it, I occur the following error.

```
(node:95941) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/dicek/Dev/my-portfolio/node_modules/@splinetool/react-spline/dist/react-spline.es.js:29
import require$$0, { forwardRef, useRef, useState, useEffect } from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1048:15)
    at Module._compile (node:internal/modules/cjs/loader:1083:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:528:24)
    at async generatePages (file:///Users/dicek/Dev/my-portfolio/node_modules/astro/dist/core/build/generate.js:52:20)
    at async staticBuild (file:///Users/dicek/Dev/my-portfolio/node_modules/astro/dist/core/build/static-build.js:61:5)
    at async AstroBuilder.build (file:///Users/dicek/Dev/my-portfolio/node_modules/astro/dist/core/build/index.js:86:5)
    at async AstroBuilder.run (file:///Users/dicek/Dev/my-portfolio/node_modules/astro/dist/core/build/index.js:127:7)
    at async build (file:///Users/dicek/Dev/my-portfolio/node_modules/astro/dist/core/build/index.js:21:3)
    at async runCommand (file:///Users/dicek/Dev/my-portfolio/node_modules/astro/dist/cli/index.js:150:14)
    at async cli (file:///Users/dicek/Dev/my-portfolio/node_modules/astro/dist/cli/index.js:168:5) {
  plugin: undefined,
  hint: undefined
}

Node.js v18.8.0
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zmu4ac?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
The `@splinetool/react-spline` package isn't correctly published: https://publint.bjornlu.com/@splinetool/react-spline@2.2.3. Please open an issue in their repo instead to fix it.
