### ISSUE TITLE
astro@1.6.15: imports from dynamic paths breaking

### ISSUE THREAD

**Issue by Ehesp** [withastro/astro#5596]
### What version of `astro` are you using?

1.6.15

### Are you using an SSR adapter? If so, which one?

Vercel and Node (although this is in local dev)

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm using tRPC & an API route to handle my requests at the path: `src/pages/api/trpc/[trpc].ts`, and it returns some named exports.

Within my `src/pages/embed.astro` page, I import from this path:

```ts
import { caller } from 'src/pages/api/trpc/[trpc]';
```

On Astro 1.6.14 this works as expected, however on 1.6.15, an error is thrown. Although, the actual output and website functions fine. It also doesn't seem to show every time I refresh, just randomly. I assume this is due to the dynamic path name?

```
 error   __vite_ssr_import_6__.caller is not a function
File:
    /src/pages/embed/[id].astro:23:48
TypeError: __vite_ssr_import_6__.caller is not a function
    at eval (/src/pages/embed/[id].astro:23:48)
    at renderPage (/node_modules/astro/dist/runtime/server/render/page.js:89:36)
    at renderPage (/node_modules/astro/dist/core/render/core.js:86:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async renderPage (/node_modules/astro/dist/core/render/dev/index.js:105:10)
    at async handleRoute (/node_modules/astro/dist/vite-plugin-astro-server/route.js:148:20)
    at async run (/node_modules/astro/dist/vite-plugin-astro-server/request.js:45:14)
    at async runWithErrorHandling (/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (/node_modules/astro/dist/vite-plugin-astro-server/request.js:39:3)
```

I'm trying to replicate this in the StackBlitz but it does not error. I can however confirm that rolling back to 1.6.14 never shows this error.

I also thought using a relative path might help to solve the issue, but it still errors.

```ts
import { caller } from '../api/trpc/[trpc]';
```

### Link to Minimal Reproducible Example

N/A - See above

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Ehesp** [comment]
Yeah, not entirely sure if that's wise or not but it seems to have been working ok. Let me try and reproduce - it's happens on mine and a colleagues machine, but i couldn't get it to happen on StackBlitz. I'll spend some time later trying to nail down the cause.

**Comment by matthewp** [comment]
Closing as this is stale, please open a new issue if still occurring on 2.x. Thanks!

**Comment by Ehesp** [comment]
Haven't seen this since upgrading.
