### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by chenxsan** [withastro/astro#5620]
### What version of `astro` are you using?

1.7.1, along with `mdx` and `tailwindcss` integrations.

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I was migrating my site to take advantage of the new [`Content Collection`](https://docs.astro.build/en/guides/content-collections/) feature, btw, love the feature a lot.

But I kept running into this error:

<details>
<summary>Maximum call stack size exceeded</summary>

```
> astro dev

Debugger attached.
03:20:52 PM [content] Types generated
03:20:52 PM [content] Watching src/content/ for changes
  🚀  astro  v1.7.1 started in 836ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
Maximum call stack size exceeded
 error   Maximum call stack size exceeded
  File:
    astro:content
  Stacktrace:
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at removeTimestampQuery (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:11824:16)
    at ModuleGraph.getModuleById (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:60685:39)
    at getModuleInfo (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40183:37)
    at TransformContext.getModuleInfo (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40239:20)
    at file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:36:72
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:13:22)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
    at addHeadInjectionInTree (file:///Users/sam/Documents/githubRepos/my-app/node_modules/.pnpm/astro@1.7.1/node_modules/astro/dist/vite-plugin-head-propagation/index.js:21:9)
```
</details>

So I checked the `vite-plugin-head-propagation` file here https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-head-propagation/index.ts, and found something a little strange there.

We can see a `seen` Set initialized, and there was a check `seen.has(parent.id)`, but I can't find anything like `seen.add(parent.id)`.

And adding `seen.add(parent.id)` seems to get the above error fixed, but I'm not sure I'm right here since I don't know much about Vite.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1dq3z5?file=src/pages/about.md

1. run `npm run dev`
2. access the `/about` page first
3. then access the `/blog/hi` page
4. then you can see the error

Note that the order of 2 and 3 matters here, you can't reproduce the error if you access `/blog/hi` before `/about`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
> We can see a `seen` Set initialized, and there was a check `seen.has(parent.id)`, but I can't find anything like `seen.add(parent.id)`.
> 
> And adding `seen.add(parent.id)` seems to get the above error fixed, but I'm not sure I'm right here since I don't know much about Vite.

This seems like the exact fix we need. Would you like to send a PR to add this?
