### ISSUE TITLE
"fetch failed" for `<Image>` component when transforming local images

### ISSUE THREAD

**Issue by septatrix** [withastro/astro#5699]
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When using the astro image feature with a local image, the images do not get loaded an instead an error is printed by the development server:

```js
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadRemoteImage (/home/septatrix/Documents/programming/cv/node_modules/@astrojs/image/dist/endpoint.js:13:17)
    at async Module.get (/home/septatrix/Documents/programming/cv/node_modules/@astrojs/image/dist/endpoint.js:29:19)
    at async call (file:///home/septatrix/Documents/programming/cv/node_modules/astro/dist/core/endpoint/index.js:70:20)
    at async call (file:///home/septatrix/Documents/programming/cv/node_modules/astro/dist/core/endpoint/dev/index.js:15:10)
    at async handleRoute (file:///home/septatrix/Documents/programming/cv/node_modules/astro/dist/vite-plugin-astro-server/route.js:117:20)
    at async run (file:///home/septatrix/Documents/programming/cv/node_modules/astro/dist/vite-plugin-astro-server/request.js:45:14)
    at async runWithErrorHandling (file:///home/septatrix/Documents/programming/cv/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///home/septatrix/Documents/programming/cv/node_modules/astro/dist/vite-plugin-astro-server/request.js:39:3) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  }
}
```

A hint by @mundry (https://github.com/withastro/astro/issues/5051#issuecomment-1367467896) seemed to hint at this being a problem with IPv4/IPv6. I have been able to confirm this though I am not sure how to resolve this issue:

When listing all active sockets on my PC using `ss -tlpn` shows that the dev server only binds to `[::1]:3000`. This is the first confusing part because the default (on Linux but also Node.js in general) should be that IPv6 sockets also bind to IPv4, as the [`ipv6Only`](https://nodejs.org/dist/latest-v18.x/docs/api/net.html#serverlistenoptions-callback) option defaults to `false`. Second, even though the image is a local one and `isRemoteImage` detects this correctly, the image is still loaded via `loadRemoteImage` instead of direct filesystem access. As a consequence `fetch` is invoked on the theoretically correct URL of  `http://localhost:3000/avatar-square.jpg`. Here however, Node.js' fetch implementation seems to first find the IPv4 address for localhost and tries to fetch image from that IP. This is the action which leads to the above error. (In this scenario I would have expected nodejs to retry with the IPv6 IP but that does not happen.)

I also have checked whether the URL being fetched properly works. `curl -6 "http://localhost:3000/avatar-square.jpg"` works as expected and `curl -4 ...` does not (due to only binding on IPv6).

My current workaround is to start astro using `npm run dev -- --host 127.0.0.1` to force binding to the IPv4 address. This is definitely not a suitable resolution in the long run. Currently, I can think of two ways to fix this:

1. If `isRemoteImage` is false, simply load the image via direct filesystem access. This seems the easiest and might even increase performance, though I am not sure if I might miss a reason why this might not be possible.
2. Investigate why the server only binds to IPv6 and does not use dual-stack. This also seems to be the case with upstream Vite so asking for their opinion might be a good idea.

It seem like the behaviour of `fetch` to not try other IP addresses is intended, so I do not expect a change there. Furthermore it might be possible to rewrite the URL and replace `localhost` with the correct IP address though this is rather limiting und hacky.

### Link to Minimal Reproducible Example

Not reproducible on stackblitz as the server binds differently there

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
mark

**Comment by Princesseuh** [comment]
Hello! We won't be fixing this issue in `@astrojs/image`, as we're entering maintenance mode for it. However, this issue also affects the new `astro:assets` feature, as such when we get to it, we'll fix it there.

**Comment by matthewp** [comment]
`@astrojs/image` has been removed from Astro. You should begin migrating over to `astro:assets` instead which is our Image component going forward. Thanks!

**Comment by matthewp** [comment]
Sorry about that, this affects `astro:assets` as well.
