### ISSUE TITLE
Base url does not work(Getting ReferenceError: xxx is not defined)

### ISSUE THREAD

**Issue by jonghyo** [withastro/astro#5740]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When I use ``astro.config.mjs`` [base](https://docs.astro.build/ja/reference/configuration-reference/#base) option, it does not work.

Here is my ``astro.config.mjs``.

```javascript
import { defineConfig } from 'astro/config';
import preact from '@astrojs/preact';
import react from '@astrojs/react';
// https://astro.build/config
import tailwind from '@astrojs/tailwind';

// https://astro.build/config
import mdx from '@astrojs/mdx';

// https://astro.build/config
export default defineConfig({
	site: 'https://palette.pages.devops.aslead.cloud/',
	base: process.env.BASE_URL || '/foo/',
	integrations: [
		// Enable Preact to support Preact JSX components.
		preact(),
		// Enable React for the Algolia search component.
		react(),
		tailwind(),
		mdx(),
	],
});
```

I access, http://localhost:3000/foo/, I get below error message.

```
ReferenceError: foo is not defined
    at eval (C:\Users\exampleUser\Desktop\example-project\src\pages\index.astro:16:240)
    at renderPage (file:///C:/Users/exampleUser/Desktop/example-project/node_modules/astro/dist/runtime/server/render/page.js:89:36)
    at renderPage (file:///C:/Users/exampleUser/Desktop/example-project/node_modules/astro/dist/core/render/core.js:86:26)
    at async renderPage (file:///C:/Users/exampleUser/Desktop/example-project/node_modules/astro/dist/core/render/dev/index.js:105:10)
    at async handleRoute (file:///C:/Users/exampleUser/Desktop/example-project/node_modules/astro/dist/vite-plugin-astro-server/route.js:152:20)
    at async run (file:///C:/Users/exampleUser/Desktop/example-project/node_modules/astro/dist/vite-plugin-astro-server/request.js:45:14)
    at async runWithErrorHandling (file:///C:/Users/exampleUser/Desktop/example-project/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///C:/Users/exampleUser/Desktop/example-project/node_modules/astro/dist/vite-plugin-astro-server/request.js:39:3)
```

``example-project\src\pages\index.astro`` is below.

```html
<script is:inline>
	// Redirect your homepage to the first page of documentation.
	// If you have a landing page, remove this script and add it here!
	window.location.pathname = `${import.meta.env.BASE_URL}intro/introduction`;
</script>
```

It works fine, I access http://localhost:3000/foo/intro/introduction directly.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/jonghyo/astro-docs-template/tree/feat/issue?file=package.json&terminal=start

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I think the problem here is that Astro doesn't touch `is:inline` scripts so the `import.meta.env.BASE_URL` statement isn't properly transformed.

Another option to using a blocking client-side script it to use a `meta` refresh tag.

```astro
<meta http-equiv="refresh" content={`0;URL='${import.meta.env.BASE_URL}intro/introduction'`} />
```
