### ISSUE TITLE
[vite] Internal server error: [postcss]

### ISSUE THREAD

**Issue by Akiyamka** [withastro/astro#5755]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

```
node -v
v18.12.1
```
Steps to reproduce:
1. Install template with recommended settings
```
$ npm create astro@latest

npm create astro@latest
Need to install the following packages:
  create-astro@1.2.4
Ok to proceed? (y) y

╭─────╮  Houston:
│ ◠ ◡ ◠  I'll be your assistant today.
╰─────╯

 astro   v1.9.0 Launch sequence initiated.

✔ Where would you like to create your new project? … .
✔ How would you like to setup your new project? › a few best practices (recommended)
          ■■▶ Copying project files...(node:115653) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✔ Template copied!
✔ Would you like to install npm dependencies? (recommended) … yes
          ■■▶ Installing packages 📦
✔ Packages installed!
✔ Would you like to initialize a new git repository? (optional) … no

◼  Sounds good! You can come back and run git init later.

✔ How would you like to setup TypeScript? › Strict
✔ TypeScript settings applied!

  next   Liftoff confirmed. Explore your project!
         Run npm run dev to start the dev server. CTRL+C to stop.
         Add frameworks like react or tailwind using astro add.

         Stuck? Join us at https://astro.build/chat

╭─────╮  Houston:
│ ◠ ◡ ◠  Good luck out there, astronaut!
╰─────╯
```
Run dev mode
```
$ npm start
```
Open browser at http://localhost:3000/ and see next error
(same in browser and terminal)
```
7:26:02 PM [vite] Internal server error: [postcss] /home/.../astro-debug/src/layouts/Layout.astro?astro&type=style&index=0&lang.css:6:9: Unknown word
  Plugin: vite:css
  File: /home/akiyamka/git/_experements/astro-debug/src/layouts/Layout.astro?astro&type=style&index=0&lang.css:6:9
  4  |  }
  5  |  
  6  |  const { title } = Astro.props;
     |           ^
  7  |  ---
  8  |  
      at Input.error (/home/akiyamka/git/_experements/astro-debug/node_modules/postcss/lib/input.js:148:16)
      at Parser.unknownWord (/home/akiyamka/git/_experements/astro-debug/node_modules/postcss/lib/parser.js:540:22)
      at Parser.other (/home/akiyamka/git/_experements/astro-debug/node_modules/postcss/lib/parser.js:164:12)
      at Parser.parse (/home/akiyamka/git/_experements/astro-debug/node_modules/postcss/lib/parser.js:72:16)
      at parse (/home/akiyamka/git/_experements/astro-debug/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/home/akiyamka/git/_experements/astro-debug/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/home/akiyamka/git/_experements/astro-debug/node_modules/postcss/lib/processor.js:28:14)
      at compileCSS (file:///home/akiyamka/git/_experements/astro-debug/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:44128:14)
      at async TransformContext.transform (file:///home/akiyamka/git/_experements/astro-debug/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:43616:55)
      at async Object.transform (file:///home/akiyamka/git/_experements/astro-debug/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:30)

```

### Link to Minimal Reproducible Example

not needed

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I can't reproduce this. Can you provide a stackblitz link of the issue?

**Comment by Akiyamka** [comment]
I could not reproduce this in stakblitz or codesandobx.
As it turned out, the reason was the service worker that was left running on localhost:3000 from another project. Forcibly stopping it fixes the problem.
Thank you for your reply!
