### ISSUE TITLE
Error: Cannot find the built path for {path to react component}

### ISSUE THREAD

**Issue by madex1** [withastro/astro#6005]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

In development mode everything is ok, but when i'm trying to build project, i have the next error:

```
[madex@madex-desktop blog]$ npm run build

> @example/minimal@0.0.1 build
> astro build

14:27:51 [build] output target: static
14:27:51 [build] Collecting build info...
14:27:51 [build] Completed in 36ms.
14:27:51 [build] Building static entrypoints...
14:27:57 [build] Completed in 5.99s.

 building client 
Completed in 3.45s.


 generating static routes 
▶ src/pages/index.astro
file:///home/madex/work/gamingcy/blog/node_modules/astro/dist/core/build/generate.js:252
        throw new Error(`Cannot find the built path for ${specifier}`);
              ^

Error: Cannot find the built path for /home/madex/work/gamingcy/blog/src/components/ui/subscribe-form/subscribe-form.jsx
    at Object.resolve (file:///home/madex/work/gamingcy/blog/node_modules/astro/dist/core/build/generate.js:252:15)
    at generateHydrateScript (file:///home/madex/work/gamingcy/blog/dist/chunks/astro.11b9295e.mjs:790:48)
    at renderFrameworkComponent (file:///home/madex/work/gamingcy/blog/dist/chunks/astro.11b9295e.mjs:1580:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async renderChild (file:///home/madex/work/gamingcy/blog/dist/chunks/astro.11b9295e.mjs:868:11)
    at async RenderTemplateResult.[Symbol.asyncIterator] (file:///home/madex/work/gamingcy/blog/dist/chunks/astro.11b9295e.mjs:226:7)
    at async renderAstroTemplateResult (file:///home/madex/work/gamingcy/blog/dist/chunks/astro.11b9295e.mjs:234:20)
    at async renderChild (file:///home/madex/work/gamingcy/blog/dist/chunks/astro.11b9295e.mjs:885:5)
    at async renderSlot (file:///home/madex/work/gamingcy/blog/dist/chunks/astro.11b9295e.mjs:913:22)

```

index.astro
```
---
import Layout from "../components/layout/layout.astro";
import SubscribeForm from "../components/ui/subscribe-form/subscribe-form.jsx";
---
<Layout>
    <main class="main">
        
        <SubscribeForm client:load wide/>

    </main>
</Layout>
```

subscribe-form.jsx
```
import React, {useState} from "react";
import css from './subscribe-form.module.styl';

const SubscribeForm = ({wide}) => {
    const [email, setEmail] = useState("");
    const [loading, setLoading] = useState(false);
    const [subscribed, setSubscribed] = useState(false);
    const [error, setError] = useState('');
  
    const submitEmail = () => {
      setLoading(true)
      fetch(`${import.meta.env.PUBLIC_MOO}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({email})
        })
        .then((response) => response.json())
        .then((data) => {
          console.log(data)

          setLoading(false)

          if(data.error.length) {
            setError(data.error[0])
          } else {
            setSubscribed(true);
            setEmail("");
            setError("");
          }
        })
    };
  
    const buttonText = "Subscribe";
    const successText = "✔ Subscribed!";

    return (
        <div className={css.subscribeForm}>
            {!wide && (
                <>
                    <div className={css.title}>Subscribe to get new offers and 10% discount</div>
                    <div className={css.descr}>Get more benefits by subscribing to our newsletters</div>
                </>
            )}
            
            {error && (<div className={css.error}>{error}</div>)}

            <input type="email" placeholder="Enter your email" value={email} onChange={(e) => { setEmail(e.target.value) }}/>

            {loading ? (
                <div style={{textAlign: 'center', marginTop: '5px'}}>
                    <svg width="32px" height="32px" viewBox="0 0 128 128" xmlSpace="preserve">
                        <rect x="0" y="0" width="100%" height="100%" fill="#F4F4F4" />
                        <g>
                        <path
                            d="M105.54 39.9l13.56-6.42s-9.67-26.82-47.05-30.1C31.68-.1 15.25 35.6 15.25 35.6S31.13 9.55 63.6 11.1c32.6 1.53 41.96 28.8 41.96 28.8zm-41.6 72.52l-1.2 14.97s28.15 5.04 49.67-25.7c23.3-33.2.46-65.34.46-65.34s14.7 26.8-2.86 54.13c-17.66 27.5-46.05 21.9-46.05 21.9zm-42.06-72.3L9.52 31.58S-8.96 53.4 6.9 87.42c17.12 36.73 56.38 33.03 56.38 33.03s-30.56-.68-45.46-29.55c-14.96-29 4.06-50.8 4.06-50.8z"
                            fill="#477666"
                        />
                        <animateTransform
                            attributeName="transform"
                            type="rotate"
                            from="0 63.9 64.2"
                            to="120 63.9 64.2"
                            dur="1080ms"
                            repeatCount="indefinite"
                        />
                        </g>
                    </svg>
                </div>
            ) : (
                <button type="submit" onClick={submitEmail} disabled={subscribed}>
                    {subscribed ? successText : buttonText}
                </button>
            )}
        </div>
    )
} 

export default SubscribeForm;
```

**The same code works fine in stackblitz :(**

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-r4rpxh?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by madex1** [comment]
I found out the solution. You shouldn't use jsx extension importing components.

``` import SubscribeForm from "../components/ui/subscribe-form/subscribe-form";```
