### ISSUE TITLE
@astrojs/image throw `Unknown image output: "undefined"......` errors on implementation

### ISSUE THREAD

**Issue by POPOEVER** [withastro/astro#6042]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

I'm switching from native img element to astro/image to serve local images, but on replacing <img /> with <Image />

```
---
import { Image } from '@astrojs/image/components';
...
---
...
<Image src={content.data.image.url} alt={content.data.image.alt} width={900} height={400} />
...
```

I got errors immediately in console like below:

```
Unknown image output: "undefined" used for /images/franklin-mint-shelby-cobra-collection.jpeg
Error: Unknown image output: "undefined" used for /images/franklin-mint-shelby-cobra-collection.jpeg
    at SquooshService.transform (/node_modules/@astrojs/image/dist/loaders/squoosh.js:93:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.get (/Users/popo/Projects/POCACH/Development/Private-Collection/node_modules/@astrojs/image/dist/endpoint.js:33:30)
    at async call (file:///Users/popo/Projects/POCACH/Development/Private-Collection/node_modules/astro/dist/core/endpoint/index.js:70:20)
    at async call (file:///Users/popo/Projects/POCACH/Development/Private-Collection/node_modules/astro/dist/core/endpoint/dev/index.js:15:10)
    at async handleRoute (file:///Users/popo/Projects/POCACH/Development/Private-Collection/node_modules/astro/dist/vite-plugin-astro-server/route.js:117:20)
    at async run (file:///Users/popo/Projects/POCACH/Development/Private-Collection/node_modules/astro/dist/vite-plugin-astro-server/request.js:46:14)
    at async runWithErrorHandling (file:///Users/popo/Projects/POCACH/Development/Private-Collection/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///Users/popo/Projects/POCACH/Development/Private-Collection/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:3)
```

And in browser console, the image throws in error like below

```
GET http://localhost:3000/_image?w=900&h=400&href=%2Fimages%2Ffranklin-mint-shelby-cobra-collection.jpeg 500 (Internal Server Error)
```

Installing Sharp also brought more issues, so I'm not using astro/image with Sharp, any thoughts on this? Thanks.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8llgsj?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You need to set the `format` attribute

**Comment by POPOEVER** [comment]
> You need to set the `format` attribute. We're in the process of improving documentation and types on this, sorry for the inconvenience!
> 
> I'll close this issue, since this was brought up in quite a bit of issues already

Yes I tried all attributes, local image, remote image, nothing works. I only found one issue mentioning this here through google, and it seems closed w/o a practical solution, if there IS a solution, could you pls leave me a link? Thank you.

**Comment by iway1** [comment]
what format attribute?

**Comment by Princesseuh** [comment]
> what format attribute?

The Image takes a format attribute https://docs.astro.build/en/guides/integrations-guide/image/#format

(or formats, in the case of Picture)
