### ISSUE TITLE
 Cannot destructure property 'buildConfig' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by newathnow** [withastro/astro#6137]
### What version of `astro` are you using?

2.0.6

### Are you using an SSR adapter? If so, which one?

SSR NODE

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I am getting this error when try run astro build:

 astro build

 error   Cannot destructure property 'buildConfig' of 'undefined' as it is undefined.
  File:
    /Users/test/Desktop/project_name/astro-noon/beta_news/node_modules/@astrojs/node/dist/index.js:43:31
  Code:
    42 |       },
    > 43 |       "astro:build:start": ({ buildConfig }) => {
         |                               ^
      44 |         if (needsBuildConfig) {
      45 |           _options.client = buildConfig.client.toString();
      46 |           _options.server = buildConfig.server.toString();
  Stacktrace:
TypeError: Cannot destructure property 'buildConfig' of 'undefined' as it is undefined.
    at Object.astro:build:start (file:///Users/test/Desktop/project_name/astro-noon/beta_news/node_modules/@astrojs/node/dist/index.js:43:31)
    at runHookBuildStart (file:///Users/test/Desktop/project_name/astro-noon/beta_news/node_modules/astro/dist/integrations/index.js:160:59)
    at async AstroBuilder.build (file:///Users/test/Desktop/project_name/astro-noon/beta_news/node_modules/astro/dist/core/build/index.js:65:5)
    at async AstroBuilder.run (file:///Users/test/Desktop/project_name/astro-noon/beta_news/node_modules/astro/dist/core/build/index.js:127:7)
    at async build (file:///Users/test/Desktop/project_name/astro-noon/beta_news/node_modules/astro/dist/core/build/index.js:21:3)
    at async runCommand (file:///Users/test/Desktop/project_name/astro-noon/beta_news/node_modules/astro/dist/cli/index.js:157:14)
    at async cli (file:///Users/test/Desktop/project_name/astro-noon/beta_news/node_modules/astro/dist/cli/index.js:180:5)
    
    
    
    
    
i worked on 1.9.2 upgraded to 2.0.6

  "dependencies": {
    "@astrojs/image": "^0.14.0",
    "@astrojs/node": "^4.0.0",
    "@astrojs/partytown": "^1.0.2",
    "astro": "^2.0.6",
    "axios": "^1.2.2",
    "calculate-readtime": "^0.0.3",
    "cookie": "^0.5.0",
    "date-fns": "^2.29.3",
    "fs-extra": "^11.1.0",
    "http-cookie-agent": "^5.0.2",
    "javascript-time-ago": "^2.5.9",
    "jquery": "^3.6.3",
    "reading-time-estimator": "^1.7.2",
    "sharp": "^0.31.3",
    "swiper": "^8.4.6",
    "tough-cookie": "^4.1.2",
    "undici": "^5.15.0"
  }

not sure whats wrong 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-j8s3qs?file=astro.config.mjs,package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Updating the Node integration to the latest version (5.0.3) should fix your issue

**Comment by newathnow** [comment]
thanks worked

**Comment by newathnow** [comment]
mm now have other problem:D 

[ssr] Error: Expected an exported Astro component but received typeof undefined

when visit dinamic route (aka fetching from api information) getting this error

**Comment by MoustaphaDev** [comment]
Closing as solved, you can create a new issue or ask for support in the [Astro discord](https://astro.build/chat)
