### ISSUE TITLE
App breaks when adding vue

### ISSUE THREAD

**Issue by silveltman** [withastro/astro#6155]
### What version of `astro` are you using?

1.6.14

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn

### What operating system are you using?

windows

### Describe the Bug

When adding manually I get the following error:

The requested module 'vite' does not provide an export named 'isCSSRequest'
file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/@vitejs/plugin-vue/dist/index.mjs:2
import { isCSSRequest, normalizePath as normalizePath$1, transformWithEsbuild, formatPostcssSourceMap, createFilter } from 'vite';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadConfigWithVite (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/core/config/vite-load.js:77:22)
    at async resolveConfigPath (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/core/config/config.js:111:20)
    at async tryLoadConfig (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/core/config/config.js:148:22)
    at async openConfig (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/core/config/config.js:131:18)
    at async runCommand (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/cli/index.js:117:76)
    at async cli (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/cli/index.js:168:5)
    
    
    When using Astro add vue I get the following error:
    
    PS C:\Users\silve\Documents\web-dev\astro\sil-veltman> yarn dev
yarn run v1.22.19
$ astro dev
 error   Cannot read properties of undefined (reading 'postcss')
  File:
    C:\Users\silve\Documents\web-dev\astro\sil-veltman\node_modules\@astrojs\tailwind\dist\index.js:78:22
  Code:
    77 |         const tailwindConfig = (userConfig == null ? void 0 : userConfig.value) ?? getDefaultTailwindConfig(config.srcDir);
    > 78 |         config.style.postcss.plugins.push(tailwindPlugin(tailwindConfig));
         |                      ^
      79 |         config.style.postcss.plugins.push(autoprefixerPlugin);
      80 |         if (applyBaseStyles) {
      81 |           injectScript("page-ssr", `import '@astrojs/tailwind/base.css';`);
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'postcss')
    at Object.astro:config:setup (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/@astrojs/tailwind/dist/index.js:78:22)
    at async withTakingALongTimeMsg (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/integrations/index.js:15:18)
    at async runHookConfigSetup (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/integrations/index.js:69:7)
    at async createContainer (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/core/dev/container.js:31:14)
    at async createContainerWithAutomaticRestart (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/core/dev/restart.js:90:28)
    at async dev (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/core/dev/dev.js:10:19)
    at async runCommand (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/cli/index.js:141:7)
    at async cli (file:///C:/Users/silve/Documents/web-dev/astro/sil-veltman/node_modules/astro/dist/cli/index.js:180:5)

error Command failed with exit code 1.

### Link to Minimal Reproducible Example

not atm

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by silveltman** [comment]
Seems to be fixed by updating all my packages.

Leaving this here for the people searching for this error
