### ISSUE TITLE
Percent in file name causes error in Content Collection

### ISSUE THREAD

**Issue by braden-w** [withastro/astro#6217]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Including a percent in a file name in the `Content` folder results in the following error:

```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at https://aonipxqowgithub-1pqc.w-credentialless.staticblitz.com/blitz.ce29b75f029c88a5dcc9b3dccb923c5bcb86e937.js:6:144075
    at Module.fileURLToPath (https://aonipxqowgithub-1pqc.w-credentialless.staticblitz.com/blitz.ce29b75f029c88a5dcc9b3dccb923c5bcb86e937.js:6:144080)
    at isOnIgnoreList (file://file:///home/projects/aonipxqow.github/node_modules/astro/dist/content/utils.js:149:53)
    at Module.getEntryType (file://file:///home/projects/aonipxqow.github/node_modules/astro/dist/content/utils.js:138:39)
    at handleEvent (file://file:///home/projects/aonipxqow.github/node_modules/astro/dist/content/types-generator.js:94:32)
    at Object.queueEvent (file://file:///home/projects/aonipxqow.github/node_modules/astro/dist/content/types-generator.js:181:17)
    at FSWatcher.eval (file://file:///home/projects/aonipxqow.github/node_modules/astro/dist/content/server-listeners.js:59:24)
    at EventEmitter.emit (https://aonipxqowgithub-1pqc.w-credentialless.staticblitz.com/blitz.ce29b75f029c88a5dcc9b3dccb923c5bcb86e937.js:6:155690)
    at FSWatcher.emitWithAll (file://file:///home/projects/aonipxqow.github/node_modules/vite/dist/node/chunks/dep-3007b26d.js:50373:8)
```

While the error seems initially understandable, the Astro generated slug **already** strips non-alphanumeric characters, so the percent is not included in the end URL. It would be useful to be able to include percents, as my current workflow has several files that include % signs in their titles.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/blog?file=src/content/blog/problem%.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Can confirm that this is still a problem, even on the latest!
