### ISSUE TITLE
Crash of esbuild due to deadlock in `astro check`

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#6345]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

n/a

### What package manager are you using?

npm

### What operating system are you using?

Mac / Linux

### Describe the Bug

```
Run npm run check:astro

> defined-www@1.0.0 check:astro
> astro check

astro check
11:49:4[6](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:7) PM [content] No content directory found. Skipping type generation.
-  Getting diagnostics for Astro files in /home/runner/work/www/www/…
✔  Getting diagnostics for Astro files in /home/runner/work/www/www/…
/home/runner/work/www/www/src/components/atoms/FeatureDetails.astro:162:9 Error: Type 'ImageMetadata' is not assignable to type 'string'.
161          class="FeatureDetails_img"
162          src={secureSvgPath}
             ~~~
163          loading="lazy"

/home/runner/work/www/www/src/components/atoms/FeatureDetails.astro:1[7](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:8)0:9 Error: Type 'ImageMetadata' is not assignable to type 'string'.
169          class="FeatureDetails_img"
170          src={simpleSvgPath}
             ~~~
171          loading="lazy"

/home/runner/work/www/www/src/components/atoms/FeatureDetails.astro:17[8](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:9):[9](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:10) Error: Type 'ImageMetadata' is not assignable to type 'string'.
177          class="FeatureDetails_img"
178          src={fastSvgPath}
             ~~~
179          loading="lazy"

/home/runner/work/www/www/src/pages/blog/[...page].astro:56:7 Error: Type 'PaginationPage' is not assignable to type 'Page<Post>'.
  Types of property 'data' are incompatible.
    Type 'MarkdownOrMDXInstance[]' is not assignable to type 'Post[]'.
      Type 'MarkdownOrMDXInstance' is not assignable to type 'Post'.
        Type 'MDXInstance<MarkdownFrontmatter>' is missing the following properties from type 'MarkdownInstance<MarkdownFrontmatter>': rawContent, compiledContent
55        meta={{ title: assert(BlogMeta.title), description: assert(BlogMeta.description) }}
56        page={page}
          ~~~~
57      />

Result (64 files): 
- 4 errors
- 0 warnings
- 0 hints

fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
	github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
	github.com/evanw/esbuild/cmd/esbuild/service.go:127 +0x59
main.runService(0x1)
	github.com/evanw/esbuild/cmd/esbuild/service.go:181 +0x530
main.main()
	github.com/evanw/esbuild/cmd/esbuild/main.go:230 +0x21c

goroutine 6 [chan receive]:
main.runService.func1()
	github.com/evanw/esbuild/cmd/esbuild/service.go:111 +0x3e
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:[10](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:11)9 +0x1e5

goroutine 7 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc000bc43c0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x[11](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:12)0
main.runService.func3()
	github.com/evanw/esbuild/cmd/esbuild/service.go:138 +0x39
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:135 +0x354

goroutine 677 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc00070bb00})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0002d2590, 0x10}, {0xc0004a9800, 0x56}, {0x926856, 0x4}, {0xc0004a9800, 0x49}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0002d2590, 0x10}, {0xc0004a9800, 0x49}, {0x0, 0x0}, {{0xc0004a9800, 0x56}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5[12](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:13)0, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:[13](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:14)31 +0xb57

goroutine 648 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc00097e9c0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc000426260, 0xf}, {0xc0000d00a0, 0x41}, {0x926856, 0x4}, {0xc0000d00a0, 0x38}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc000426260, 0xf}, {0xc0000d00a0, 0x38}, {0x0, 0x0}, {{0xc0000d00a0, 0x41}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 679 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc0002e37a0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0000b7ca0, 0x[14](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:15)}, {0xc000035770, 0x4b}, {0x926856, 0x4}, {0xc000035770, 0x3e}, 0x4, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0000b7ca0, 0x14}, {0xc000035770, 0x3e}, {0x0, 0x0}, {{0xc000035770, 0x4b}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x2[15](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:16)
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 678 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc0002cf830})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0002d2aa0, 0xc}, {0xc0004a9aa0, 0x55}, {0x926856, 0x4}, {0xc0004a9aa0, 0x3a}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0002d2aa0, 0xc}, {0xc0004a9aa0, 0x3a}, {0x0, 0x0}, {{0xc0004a9aa0, 0x55}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:[16](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:17)11 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 653 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc0004e0360})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0002e52d0, 0x5}, {0xc0000343c0, 0x4d}, {0x926856, 0x4}, {0xc0000343c0, 0x3f}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0002e52d0, 0x5}, {0xc0000343c0, 0x3f}, {0x0, 0x0}, {{0xc0000343c0, 0x4d}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 667 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc000bc4390})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0008155b0, 0x5}, {0xc000034820, 0x50}, {0x926856, 0x4}, {0xc000034820, 0x34}, 0x3, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0008155b0, 0x5}, {0xc000034820, 0x34}, {0x0, 0x0}, {{0xc000034820, 0x50}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 665 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc0006a4b70})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc000427fd0, 0x5}, {0xc000628a80, 0x54}, {0x926856, 0x4}, {0xc000628a80, 0x30}, 0x3, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc000427fd0, 0x5}, {0xc000628a80, 0x30}, {0x0, 0x0}, {{0xc000628a80, 0x54}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 655 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc00065a210})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc000427f70, 0xd}, {0xc000034be0, 0x48}, {0x926856, 0x4}, {0xc000034be0, 0x30}, 0x3, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc000427f70, 0xd}, {0xc000034be0, 0x30}, {0x0, 0x0}, {{0xc000034be0, 0x48}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 675 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc00019ecc0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0000b78a0, 0x[17](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:18)}, {0xc000035130, 0x47}, {0x926856, 0x4}, {0xc000035130, 0x40}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0000b78a0, 0x17}, {0xc000035130, 0x40}, {0x0, 0x0}, {{0xc000035130, 0x47}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 666 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc0004e03c0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0001ee3[18](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:19), 0x5}, {0xc000628f00, 0x58}, {0x926856, 0x4}, {0xc000628f00, 0x30}, 0x3, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0001ee318, 0x5}, {0xc000628f00, 0x30}, {0x0, 0x0}, {{0xc000628f00, 0x58}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 642 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc00097ea20})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc00068cca0, 0x9}, {0xc0000d0050, 0x43}, {0x926856, 0x4}, {0xc0000d0050, 0x35}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc00068cca0, 0x9}, {0xc0000d0050, 0x35}, {0x0, 0x0}, {{0xc0000d0050, 0x43}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 680 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc0003b6cf0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0002e4378, 0x4}, {0xc000035950, 0x4d}, {0x926856, 0x4}, {0xc000035950, 0x3e}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0002e4378, 0x4}, {0xc000035950, 0x3e}, {0x0, 0x0}, {{0xc000035950, 0x4d}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 652 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc0002faea0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0005d1490, 0x5}, {0xc0000d00f0, 0x4b}, {0x926856, 0x4}, {0xc0000d00f0, 0x3f}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0005d1490, 0x5}, {0xc0000d00f0, 0x3f}, {0x0, 0x0}, {{0xc0000d00f0, 0x4b}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 635 [chan receive]:
github.com/evanw/esbuild/internal/bundler.(*scanner).scanAllDependencies(0xc000081000)
	github.com/evanw/esbuild/internal/bundler/bundler.go:1783 +0x218
github.com/evanw/esbuild/internal/bundler.ScanBundle({_, _, _, _, _, _}, {_, _}, _, {0xc0001a65a0, ...}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:1200 +0x81f
github.com/evanw/esbuild/pkg/api.rebuildImpl({0xc000556660, {0x0, 0x0, 0x0}, {0x0, 0x1, 0x0, 0x5, 0xc00028a2a0}, {0xc0001a65a0, ...}, ...}, ...)
	github.com/evanw/esbuild/pkg/api/api_impl.go:1184 +0x245
github.com/evanw/esbuild/pkg/api.buildImpl({0x0, 0x5, 0x0, 0xc000559f20, 0x2, {0x0, 0x0}, 0x0, 0x8, {0xc0005562a0, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:888 +0x877
github.com/evanw/esbuild/pkg/api.Build(...)
	github.com/evanw/esbuild/pkg/api/api.go:375
main.(*serviceType).handleBuildRequest(0xc000023dd0, 0x559920?, 0x927ea1?)
	github.com/evanw/esbuild/cmd/esbuild/service.go:507 +0x965
main.(*serviceType).handleIncomingPacket(0xc0002337a0?, {0xc000138900?, 0xc0001c3a40?, 0xc0002a38a0?})
	github.com/evanw/esbuild/cmd/esbuild/service.go:239 +0x[19](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:20)1
main.runService.func4()
	github.com/evanw/esbuild/cmd/esbuild/service.go:169 +0x32
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:168 +0x546

goroutine 681 [chan receive]:
main.(*serviceType).sendRequest(0xc000023dd0, {0x8c09c0, 0xc0003b7da0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0002e4d70, 0x5}, {0xc000035c[20](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:21), 0x4b}, {0x926856, 0x4}, {0xc000035c20, 0x42}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0002e4d70, 0x5}, {0xc000035c20, 0x42}, {0x0, 0x0}, {{0xc000035c20, 0x4b}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x[21](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:22)5
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc000[22](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:23)ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x30dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:1331 +0xb57

goroutine 682 [chan receive]:
main.(*serviceType).sendRequest(0xc0000[23](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:24)dd0, {0x8c09c0, 0xc0006a4a50})
	github.com/evanw/esbuild/cmd/esbuild/service.go:210 +0x110
main.(*serviceType).convertPlugins.func2.3({{0xc0006491e0, 0xc}, {0xc000035e00, 0x4d}, {0x9[26](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:27)856, 0x4}, {0xc000035e00, 0x42}, 0x2, {0x0, ...}})
	github.com/evanw/esbuild/cmd/esbuild/service.go:800 +0x5f4
github.com/evanw/esbuild/pkg/api.(*pluginImpl).onResolve.func1({{0xc0006491e0, 0xc}, {0xc000035e00, 0x42}, {0x0, 0x0}, {{0xc000035e00, 0x4d}, {0x926856, 0x4}, ...}, ...})
	github.com/evanw/esbuild/pkg/api/api_impl.go:1611 +0x215
github.com/evanw/esbuild/internal/bundler.RunOnResolvePlugins({_, _, _}, _, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc000[28](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:29)a2a0}, ...)
	github.com/evanw/esbuild/internal/bundler/bundler.go:793 +0x8d5
github.com/evanw/esbuild/internal/bundler.parseFile({{0xa0e158, 0xc0000b51c0}, {0xc00022ad20, 0xc000263c08, 0xc000263c20, 0xc0000b5120, 0x5, 0xc00028a2a0}, 0xc000054c00, 0xc000556660, ...})
	github.com/evanw/esbuild/internal/bundler/bundler.go:393 +0x[30](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:31)dc
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
	github.com/evanw/esbuild/internal/bundler/bundler.go:13[31](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:32) +0xb[57](https://github.com/DefinedNet/www/actions/runs/4248018292/jobs/7386700752#step:5:58)
Error: Process completed with exit code 1.
```

### Link to Minimal Reproducible Example

private repo, I will attempt a repro soon

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I think we already have a report and repro at https://github.com/withastro/astro/issues/6306

**Comment by jasikpark** [comment]
thx!
