### ISSUE TITLE
Cannot import raw SVG from GitHub

### ISSUE THREAD

**Issue by Stratis-Dermanoutsos** [withastro/astro#6370]
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have created a Documentation page using Astro.
Also, I created an SVG icon using Figma. The icon can be found at <https://github.com/Stratis-Dermanoutsos/Full-Stack-Notes/blob/main/Images/Full_Stack_Notes_icon.svg>.

What I am trying to do is import that SVG from GitHub using the <https://raw.githubusercontent.com> URL.
Specifically, for my SVG the URL is <https://raw.githubusercontent.com/Stratis-Dermanoutsos/Full-Stack-Notes/main/Images/Full_Stack_Notes_icon.svg>.
Currently, I added the file to my `public` directory and import it from there as follows:

```js
import appIcon from '/public/icon.svg?raw';
```

To get it from the URL, I am using the `await import` method as such:

```js
const { default: appIcon } = await import('https://raw.githubusercontent.com/Stratis-Dermanoutsos/Full-Stack-Notes/main/Images/Full_Stack_Notes_icon.svg?raw');
```

With this, I get en error saying

```
Cannot find module 'https://raw.githubusercontent.com/Stratis-Dermanoutsos/Full-Stack-Notes/main/Images/Full_Stack_Notes_icon.svg?raw' imported from '/Users/stratis/Downloads/Full-Stack-Notes/src/layouts/MainLayout.astro'
Error: Cannot find module 'https://raw.githubusercontent.com/Stratis-Dermanoutsos/Full-Stack-Notes/main/Images/Full_Stack_Notes_icon.svg?svg' imported from '/Users/stratis/Downloads/Full-Stack-Notes/src/layouts/MainLayout.astro'
    at nodeImport (file:///Users/stratis/Downloads/Full-Stack-Notes/node_modules/vite/dist/node/chunks/dep-9912c491.js:52428:25)
    at ssrImport (file:///Users/stratis/Downloads/Full-Stack-Notes/node_modules/vite/dist/node/chunks/dep-9912c491.js:52351:20)
    at ssrDynamicImport (file:///Users/stratis/Downloads/Full-Stack-Notes/node_modules/vite/dist/node/chunks/dep-9912c491.js:52378:16)
    at eval (/src/layouts/MainLayout.astro:35:38)
    at AstroComponentInstance.MainLayout [as factory] (/node_modules/astro/dist/runtime/server/astro-component.js:22:12)
    at AstroComponentInstance.init (/node_modules/astro/dist/runtime/server/render/astro/instance.js:31:29)
    at AstroComponentInstance.render (/node_modules/astro/dist/runtime/server/render/astro/instance.js:36:18)
    at render.next (<anonymous>)
    at Module.renderChild (/node_modules/astro/dist/runtime/server/render/any.js:30:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async [Symbol.asyncIterator] (/node_modules/astro/dist/runtime/server/render/astro/render-template.js:34:7)
    at async renderAstroTemplateResult (file:///Users/stratis/Downloads/Full-Stack-Notes/node_modules/astro/dist/runtime/server/render/astro/render-template.js:37:20)
    at async read (file:///Users/stratis/Downloads/Full-Stack-Notes/node_modules/astro/dist/runtime/server/render/page.js:106:32)
```

I am certain at the syntax is correct though. The application works just fine using the same command with the public directory's path:

```js
const { default: appIcon } = await import('/public/icon.svg?raw');
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ynp5js?file=src/components/Header/AstroLogo.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
`import` cannot import HTTP URLs, you need to `fetch` the file. Additionally, importing from `public` is not recommended.

**Comment by Stratis-Dermanoutsos** [comment]
Thank you, I was actually about to post the answer I found.

I solved the issue using the following code:

```js
const appIcon = await fetch(SITE.appIcon).then(res => res.text());
```
