### ISSUE TITLE
The development server closes

### ISSUE THREAD

**Issue by luisBazanDev** [withastro/astro#6378]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Code:
```
import { Preset, CordsRange } from "../types";
export default function PresetContainer({ item: Preset }) {
  const keys = Object.keys(item).map((key) => {
    return typeof item[key];
  });
  return <div>{JSON.stringify(keys)}</div>;
}
```
Error:
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

ReferenceError: item is not defined
    at PresetContainer (/src/components/PresetContainer.tsx:10:28)
    at renderWithHooks (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5662:16)
    at renderIndeterminateComponent (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5735:15)
    at renderElement (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6080:14)
    at retryTask (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6532:5)
    at performWork (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6580:7)
    at D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6904:12
    at scheduleWork (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:78:3)
    at startWork (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6903:3)
    at renderToNodeStreamImpl (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:7048:3)
    at Object.renderToStaticNodeStream (D:\Projects\TwitchKillMe\wiki\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:7061:10)
    at eval (@astrojs/react/server.js:130:46)
    at new Promise (<anonymous>)
    at renderToStaticNodeStreamAsync (@astrojs/react/server.js:129:9)
    at async Object.renderToStaticMarkup (@astrojs/react/server.js:93:11)
    at async renderFrameworkComponent (/node_modules/astro/dist/runtime/server/render/component.js:178:26)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qxcsfr?file=src/components/test.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
Your code isn't valid TypeScript.

Here's the correct way to do what you want to do
```diff
interface TestType {
  value1: string;
}
- export default function Test({ item: TestType }) {
+export default function Test({ item } : { item: TestType }) {
  if (item) return <h1>{item.value}</h1>;
  else return <h1>Test</h1>;
}
```

[See more on that here](https://www.typescriptlang.org/docs/handbook/2/functions.html#parameter-destructuring)
