### ISSUE TITLE
Get 500 error with a prerender 404 page and cloudflare SSR

### ISSUE THREAD

**Issue by sperjar** [withastro/astro#6511]
### What version of `astro` are you using?

2.1.0, 2.1.2

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm,pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

# Problem: Get this Error When prerender 404 page

```
GET /_astro/index.11c12019.css 500 Internal Server Error (142.91ms)
15:22:51 [ssr] Error: Expected an exported Astro component but received typeof undefined
at Va (/home/projects/github-9dgysh/dist/\_worker.js:60:9174)
at Se.dt (/home/projects/github-9dgysh/dist/\_worker.js:60:15323)
at Se.render (/home/projects/github-9dgysh/dist/\_worker.js:60:14118)
at Object.fetch (/home/projects/github-9dgysh/dist/\_worker.js:92:2761)
at ServiceWorkerGlobalScope.[kDispatchFetch] (/home/projects/github-9dgysh/node_modules/@miniflare/core/src/standards/event.ts:385:13)
```

# My config

1. @astrojs/cloudflare in SSR mode.
2. create a prerendered 404 page.
3. preview (not dev) mode access `/aaa` (or any other path will cause 404 error)

# Reproduction

```
npm run build && npm run dev
```

the Press `b` open a browser, access `/aaa` (or any other path will cause 404 error).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9dgysh?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Does this happen when deployed or only when running `astro preview`?

**Comment by sperjar** [comment]
@natemoo-re, deployment and preview mode both cause the problem when using Cloudflare Integration.

**Comment by bluwy** [comment]
I haven't dig completely into it, but the error seems to come from

https://github.com/withastro/astro/blob/04dddd783da3235aa9ed523d2856adf86b792b5f/packages/astro/src/core/app/index.ts#L131-L134

where when hitting a 404, `mod` is a noop `() => {}` instead of the `404.astro` file being rendered. I'm not sure why yet but this seems like a bug.

This also looks similar to https://github.com/withastro/astro/issues/6177#issuecomment-1422779509
