### ISSUE TITLE
Astro >= 2.1.1 cannot compile with tofsjonas/sortable

### ISSUE THREAD

**Issue by patrickdung** [withastro/astro#6625]
### What version of `astro` are you using?

2.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

The NPM source: https://github.com/tofsjonas/sortable#b-import-files-in-javascript

Here's the line I added:
a)
cat src/layouts/BaseLayout.astro
import '$node_modules/sortable-tablesort/sortable.min.js'
b) package.json
    "sortable-tablesort": "^2.0.1",

Error messages:
```
 generating static routes
 error   document is not defined
  Hint:
    Browser APIs are not available on the server.

    If the code is in a framework component, try to access these objects after rendering using lifecycle methods or use a `client:only` directive to make the component exclusively run on the client.

    See https://docs.astro.build/en/guides/troubleshooting/#document-or-window-is-not-defined for more information.

  File:
    /data/projects/webdev/astro/projects/astro-for-bug-reports/node_modules/astro/dist/core/build/generate.js:70:20
  Code:
    69 |   const ssrEntryURL = new URL("./" + serverEntry + `?time=${Date.now()}`, outFolder);
    > 70 |   const ssrEntry = await import(ssrEntryURL.toString());
         |                    ^
      71 |   const builtPaths = /* @__PURE__ */ new Set();
      72 |   if (opts.settings.config.output === "server") {
      73 |     for (const pageData of eachPrerenderedPageData(internals)) {
  Stacktrace:
ReferenceError: document is not defined
    at file:///data/projects/webdev/astro/projects/astro-for-bug-reports/dist/chunks/pages/all.4728c9f4.mjs:24:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async generatePages (file:///data/projects/webdev/astro/projects/astro-for-bug-reports/node_modules/astro/dist/core/build/generate.js:70:20)
    at async staticBuild (file:///data/projects/webdev/astro/projects/astro-for-bug-reports/node_modules/astro/dist/core/build/static-build.js:78:7)
    at async AstroBuilder.build (file:///data/projects/webdev/astro/projects/astro-for-bug-reports/node_modules/astro/dist/core/build/index.js:124:5)
    at async AstroBuilder.run (file:///data/projects/webdev/astro/projects/astro-for-bug-reports/node_modules/astro/dist/core/build/index.js:156:7)
    at async build (file:///data/projects/webdev/astro/projects/astro-for-bug-reports/node_modules/astro/dist/core/build/index.js:37:3)
    at async runCommand (file:///data/projects/webdev/astro/projects/astro-for-bug-reports/node_modules/astro/dist/cli/index.js:168:14)
    at async cli (file:///data/projects/webdev/astro/projects/astro-for-bug-reports/node_modules/astro/dist/cli/index.js:203:5)
```

Here's the problem repo:
https://github.com/patrickdung/astro-for-bug-reports

Please note I do not have the compile problem with Astro 2.1.0.

### Link to Minimal Reproducible Example

https://github.com/patrickdung/astro-for-bug-reports

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
As the error message describes, this library doesn't work in server-side code because it uses browser APIs. You want to import it into a script tag instead:


```astro
---
---
<script>
 import '$node_modules/sortable-tablesort/sortable.min.js'
</script>
```

**Comment by patrickdung** [comment]
@matthewp 
ok, it works, thanks.
