### ISSUE TITLE
`astro dev` causes error with layouts

### ISSUE THREAD

**Issue by gene-fls** [withastro/astro#6780]
### What version of `astro` are you using?

2.2.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

After installing Astro globally as an npm module, `astro dev` runs a local development preview of the current project. However, when using a layout (even a blank one), it throws the following error: 
```
TypeError: Cannot read properties of undefined (reading 'has')
    at Module.isAPropagatingComponent (/node_modules/astro/dist/runtime/server/render/astro/factory.js:27:52)
    at Module.createAstroComponentInstance (/node_modules/astro/dist/runtime/server/render/astro/instance.js:61:29)
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/render/component.js:296:34)
    at Object.default (eval at instantiateModule (file:///home/gene/.nvm/versions/node/v19.7.0/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-79892de8.js:53995:28), <anonymous>:58:28)
    at new AstroComponentInstance (/node_modules/astro/dist/runtime/server/render/astro/instance.js:23:32)
    at Module.createAstroComponentInstance (/node_modules/astro/dist/runtime/server/render/astro/instance.js:60:20)
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/render/component.js:296:34)
    at eval (eval at instantiateModule (file:///home/gene/.nvm/versions/node/v19.7.0/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-79892de8.js:53995:28), <anonymous>:48:63)
    at index (/node_modules/astro/dist/runtime/server/astro-component.js:22:12)
    at renderPage (file:///home/gene/.nvm/versions/node/v19.7.0/lib/node_modules/astro/dist/runtime/server/render/page.js:91:36)
```
    
It does not appear to be reproducible on Stackblitz because global modules aren't an option there (as far as I know, at least). But removing layouts "fixes" the issue, as does using `npm run dev` instead of `astro dev`. 

### Link to Minimal Reproducible Example

Not applicable

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Installing Astro globally is not supported or recommended. Does installing it into your project works correctly?

**Comment by gene-fls** [comment]
Having it installed globally isn't what's causing the bug (as I understand it), it's the usage of the `astro dev` command instead of `npm run dev`, though it's only available because of the global installation.

**Comment by Princesseuh** [comment]
`npm run dev` is a shortcut for `astro dev`, it's literally the same command. One runs your local install, the other run your global install.

**Comment by gene-fls** [comment]
But `astro dev` won't work as a command if not installed globally, right?

**Comment by gene-fls** [comment]
Okay, so then this isn't an issue then? 

Perhaps there could be a bit more clarity on the subject, I began using `astro dev` because the dev output (`use --host to expose`) wasn't working and I didn't know that the correct command is `npm run dev -- --host`.

**Comment by Princesseuh** [comment]
Not a technical issue at least! I'll ask our docs team to clarify this so it doesn't happen again, sorry for the inconvenience
