### ISSUE TITLE
extension oficial not support vscodium

### ISSUE THREAD

**Issue by learfen** [withastro/astro#6798]
### What version of `astro` are you using?

v0.28.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

2023-04-09 03:51:27.183 [error] EPERM: operation not permitted, rename 'c:\Users\User\AppData\Roaming\VSCodium\CachedExtensionVSIXs\.dc1fc34d-d776-4568-bf94-d0740c737577' -> 'c:\Users\User\AppData\Roaming\VSCodium\CachedExtensionVSIXs\astro-build.astro-vscode-0.28.0-win32-x64': Download: EPERM: operation not permitted, rename 'c:\Users\User\AppData\Roaming\VSCodium\CachedExtensionVSIXs\.dc1fc34d-d776-4568-bf94-d0740c737577' -> 'c:\Users\User\AppData\Roaming\VSCodium\CachedExtensionVSIXs\astro-build.astro-vscode-0.28.0-win32-x64'
    at vt.download (vscode-file://vscode-app/c:/Program%20Files/VSCodium/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:92:187042)
    at async F.install (vscode-file://vscode-app/c:/Program%20Files/VSCodium/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:93:25863)
    at async F.doRun (vscode-file://vscode-app/c:/Program%20Files/VSCodium/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:93:23426)

### Link to Minimal Reproducible Example

www.google.com

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is a bug with OpenVSX, you should be able to download certain versions (maybe the one right before latest), but their servers had an issue while uploading the latest version.
