### ISSUE TITLE
[RSS] Invalid or missing options: Invalid input (items)

### ISSUE THREAD

**Issue by teinett** [withastro/astro#6833]
### What version of `astro` are you using?

2.2.3

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

any

### Describe the Bug

**I have content collection 'blog' and would like to have RSS for it.**

I use packages: 
- "@astrojs/mdx": "^0.18.4",
- "@astrojs/node": "^5.1.1",
- "@astrojs/rss": "^2.3.2",
- "astro": "^2.2.3",

My file of rss.xml.js:
```
import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';

export async function get(context) {
  const allPosts = await getCollection('blog', (post) => {
    return !post.data.isDraft && post.data.date <= new Date();
  });
  const sortedPosts = allPosts.sort(
    (a, b) => b.data.date.valueOf() - a.data.date.valueOf()
  );

  const posts = sortedPosts.slice(0, 10);

  return rss({
    xmlns: { h: 'http://www.w3.org/TR/html4/' },
    title: 'my title',
    description: 'my description',
    site: context.site,
    customData: '<language>en-us</language>',
    items: posts.map((post) => ({
      title: `Post ${post.data.id}`,
      pubDate: post.data.date,
      description:
        post.data.description || post.data.excerpt || post.data.content || [],
      link: `/post/${post.data.id}/`,
    })),
  });
}
```

**Expected**: successfully generated RSS feed.

**Received**: With command `npm run dev` I receive an error on the page http://localhost:3000/rss.xml: 

```
[RSS] Invalid or missing options: Invalid input (items)
dist/index.js:57:26

Error: [RSS] Invalid or missing options:
Invalid input (items)
    at validateRssOptions (file://file:///home/projects/github-ge48w2/node_modules/@astrojs/rss/dist/index.js:57:26)
    at async Proxy.getRSS (file://file:///home/projects/github-ge48w2/node_modules/@astrojs/rss/dist/index.js:47:31)
    at async Module.call (file://file:///home/projects/github-ge48w2/node_modules/astro/dist/core/endpoint/index.js:88:20)
    at async Module.call (file://file:///home/projects/github-ge48w2/node_modules/astro/dist/core/endpoint/dev/index.js:30:10)
    at async Module.handleRoute (file://file:///home/projects/github-ge48w2/node_modules/astro/dist/vite-plugin-astro-server/route.js:133:20)
    at async run (file://file:///home/projects/github-ge48w2/node_modules/astro/dist/vite-plugin-astro-server/request.js:63:14)
    at async Module.runWithErrorHandling (file://file:///home/projects/github-ge48w2/node_modules/astro/dist/vite-plugin-astro-server/controller.js:83:5)
    at async Module.handleRequest (file://file:///home/projects/github-ge48w2/node_modules/astro/dist/vite-plugin-astro-server/request.js:57:3)
```

Screenshot is attached:
<img width="1251" alt="" src="https://user-images.githubusercontent.com/1038168/231677172-2e857c37-2c43-4c76-a4f6-0ac64992ef7e.png">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ge48w2?file=src/pages/rss.xml.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
`description` is a string, but eventually you assign an empty array. Have you tried an empty string?

**Comment by teinett** [comment]
@ematipico I see! It was the suggestion from Copilot for this string.

Changed:
```
return rss({
   ...
 items: posts.map((post) => ({
     ...
      description:
        post.data.description || post.data.excerpt || post.data.content || '',
      ...
    })),
  });
```

It works now. Thanks!

**Comment by pixelsbyeryc** [comment]
I’m having the same issue when trying to build the project:

```bash
 generating static routes
▶ src/pages/index.astro
  └─ /index.html (+22ms)
λ src/pages/rss.xml.js
 error   [RSS] Invalid or missing options:
  Invalid input (items)
  File:
    /Users/name/Projects/site.dev/node_modules/@astrojs/rss/dist/index.js:40:26
  Code:
    39 |   }
    > 40 |   const formattedError = new Error(
         |                          ^
      41 |     [
      42 |       `[RSS] Invalid or missing options:`,
      43 |       ...parsedResult.error.errors.map(
```

Using the default rss file:

```js
import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';
import { SITE_TITLE, SITE_DESCRIPTION } from '../consts';

export async function get(context) {
	const posts = await getCollection('notes');
	return rss({
		title: SITE_TITLE,
		description: SITE_DESCRIPTION,
		site: context.site,
		items: posts.map((post) => ({
			...post.data,
			link: `/notes/${post.slug}/`,
		})),
	});
}
```

Here's my config.ts:

```ts
import { defineCollection, z } from 'astro:content';

const notes = defineCollection({
	// Type-check frontmatter using a schema
	schema: z.object({
		title: z.string(),
    draft: z.boolean(),
		description: z.string().optional(),
		// Transform string to Date object
		pubDate: z
			.string()
			.or(z.date())
			.transform((val) => new Date(val)),
		updatedDate: z
			.string()
			.optional()
			.transform((str) => (str ? new Date(str) : undefined)),
		heroImage: z.string().optional(),
	}),
});

export const collections = { notes };
```

**Comment by ematipico** [comment]
@pixelsbyeryc 

Make sure your notes respect the schema of items: https://www.npmjs.com/package/@astrojs/rss#rssfeeditem

Open a new issue if you have troubles.

**Comment by molavec** [comment]
In my case, I changed `pubDate` for a custom porperty name `publishedDate` in the frontmatter.

The [@astrojs/rss package](https://awsm.page/astro/rss-frontmatter-error-markdown/) is used to create an RSS feed for a website. To create the feed, it is required to include at least the `title` and `pubDate` information.

**Comment by Harryalways317** [comment]
This will happen if one of the pages in post dosen't have all the params mentioned. if you dont have data keep default values or else handle it in  rss.xml.js
