### ISSUE TITLE
Build not working on Astro 2.3.0, `npm run dev` works as before

### ISSUE THREAD

**Issue by wiesys** [withastro/astro#6901]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Today I updated Astro from 2.1.2 to 2.3.0 and it stopped building. Development (`npm run dev`) works as expected and without errors.

I get a strange and I believe misleading error message that  there is an error in the `package.json` file:
```
[commonjs--resolver] Failed to resolve entry for package "/Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/.". The package may have incorrect main/module/exports specified in its package.json.
transforming (929) node_modules/antd/es/card/Grid.js error   Failed to resolve entry for package "/Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/.". The package may have incorrect main/module/exports specified in its package.json.
  File:
    /Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23367:11
  Code:
    23366 | function packageEntryFailure(id, details) {
    > 23367 |     throw new Error(`Failed to resolve entry for package "${id}". ` +
            |           ^
      23368 |         `The package may have incorrect main/module/exports specified in its package.json` +
      23369 |         (details ? ': ' + details : '.'));
      23370 | }
  Stacktrace:
Error: Failed to resolve entry for package "/Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/.". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23367:11)
    at resolvePackageEntry (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23364:5)
    at tryCleanFsResolve (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23034:28)
    at tryFsResolve (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/vite/dist/node/chunks/dep-24daf00c.js:22981:17)
    at Object.resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/vite/dist/node/chunks/dep-24daf00c.js:22837:24)
    at file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:24526:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:24426:28)
    at async resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:23323:26)
    at async ModuleLoader.resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:23587:15)
    at async Object.resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/vite/dist/node/chunks/dep-24daf00c.js:8005:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:24426:28)
    at async resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:23323:26)
    at async ModuleLoader.resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:23587:15)
    at async Object.resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/astro/dist/vite-plugin-config-alias/index.js:48:28)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:24426:28)
    at async resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:23323:26)
    at async ModuleLoader.resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:23587:15)
    at async Object.resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/vite/dist/node/chunks/dep-24daf00c.js:8005:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:24426:28)
    at async resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:23323:26)
    at async ModuleLoader.resolveId (file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:23587:15)
    at async file:///Users/viesturs/www/SCADA/lasma--VADC-2/stage-2/node_modules/rollup/dist/es/shared/node-entry.js:23875:50
```  

My `package.json`:
```
{
  "name": "@example/basics",
  "type": "module",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@ant-design/icons": "^5.0.1",
    "@astrojs/react": "^2.0.2",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "antd": "^5.0.4",
    "astro": "^2.0.4",
    "date-fns": "^2.29.3",
    "file-saver": "^2.0.5",
    "immer": "^9.0.16",
    "papaparse": "^5.4.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "xlsx": "^0.18.5",
    "zustand": "^4.1.5"
  },
  "devDependencies": {
    "@types/file-saver": "^2.0.5",
    "@types/papaparse": "^5.3.7"
  }
}
```

It seems like it somehow could be connected with the `antd` package because if I try to build a simple React component, it builds fine. Although the latest `antd` in combination with Astro 2.1.2 builds fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4bnarv

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wiesys** [comment]
I tested a bit more and chose a theoretically similar package to the `antd` – `react-bootstrap` and can confirm that it is not working also with the `react-bootstrap`: https://stackblitz.com/edit/github-4bnarv-dk3bep

The same as with `antd` – `npm run dev` works fine, `npm run build` throws an error.

**Comment by wiesys** [comment]
One more detail – if I add `client:only` prop to the Bootstrap component, it works, but unfortunately not for Antd.

**Comment by JetLi2K** [comment]
Your astro version appear to be 2.0.4?

**Comment by wiesys** [comment]
No – It was 2.0.4 when I started the project (first time run `npm install astro`), but **“^”** (in `^2.0.4`) means  “Compatible with version” or to put it more simply “update to the latest `2.x.x`”, so currently if I run `npm update` it updates to 2.3.0, which is the latest version “2”.

The exact version is located in `package-lock.json` (or `yarn.lock`, if you are using yarn).

Mine is:
```
...
 "node_modules/astro": {
      "version": "2.3.0",
      "resolved": "https://registry.npmjs.org/astro/-/astro-2.3.0.tgz",
      "integrity": "sha512-1t8U6vDHQLT0gw0IXZLtJKDIShCcJwOuh0K1JyPgFwu1famb/ggyvsqp9nxBZIbNV8BcAWDHrJA+Z7hh1oEiWA==",
...
```

**Comment by younes-zeboudj** [comment]
I had a similar error (the message was different though) where build fails and `dev run` succeed. Added `client:only` to my react component fixed it. In my case the component needed client side rendering anyway.
