### ISSUE TITLE
Error when using render() in getStaticPaths()

### ISSUE THREAD

**Issue by silveltman** [withastro/astro#7094]
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Yarn

### What operating system are you using?

Mac

### What browser are you using?

Brave

### Describe the Bug

I want to use the async render() function to get the slug of the first heading in the markdown content. I then want to use this heading to create the slug for the collection page.

I tried the following function:
```
export async function getStaticPaths() {
  const materialenEntries = await getCollection('collections')

  // Create an async function inside map() and resolve with Promise.all()
  const pathsPromises = materialenEntries.map(async (entry) => {
    const { headings } = await entry.render()
    const slug = headings[0].slug
    return {
      params: { collectionSeo: slug },
    }
  })

  // Resolve all promises
  const paths = await Promise.all(pathsPromises)
  return { paths }
}
```

But it give the following error:
```
Cannot read properties of undefined (reading 'slug')
  File:
    /Users/silveltman/Documents/GitHub/astro/vda-bouwmaterialen-V2/src/pages/[collectionSeo].astro:17:30
  Code:
    > 17 |   // Resolve all promises
         |                              ^
      18 |   const paths = await Promise.all(pathsPromises)
      19 |   return { paths }
      20 | }
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'slug')
    at eval (/src/pages/[collectionSeo].astro:17:30)
    at async Promise.all (index 0)
    at async Module.getStaticPaths (/src/pages/[collectionSeo].astro:22:17)
    at async callGetStaticPaths (file:///Users/silveltman/Documents/GitHub/astro/vda-bouwmaterialen-V2/node_modules/astro/dist/core/render/route-cache.js:21:17)
    at async getParamsAndProps (file:///Users/silveltman/Documents/GitHub/astro/vda-bouwmaterialen-V2/node_modules/astro/dist/core/render/core.js:39:25)
    at async matchRoute (file:///Users/silveltman/Documents/GitHub/astro/vda-bouwmaterialen-V2/node_modules/astro/dist/vite-plugin-astro-server/route.js:27:31)
    at async run (file:///Users/silveltman/Documents/GitHub/astro/vda-bouwmaterialen-V2/node_modules/astro/dist/vite-plugin-astro-server/request.js:44:28)
    at async runWithErrorHandling (file:///Users/silveltman/Documents/GitHub/astro/vda-bouwmaterialen-V2/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///Users/silveltman/Documents/GitHub/astro/vda-bouwmaterialen-V2/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:3)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-a7zep3

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your reproduction is all kind of broken, it starts up on a very (2 years old!) Astro version, and the code has many mistakes preventing it from working even after fixing the version. Nonetheless, after fixing everything, it works: https://stackblitz.com/edit/astro-zubb9t?file=src/pages/[test].astro

**Comment by silveltman** [comment]
I just pickers the first Google result for 'astro stackblitz', my bad.

Thanks for helping out though!
