### ISSUE TITLE
Astro 2.5.0 + node adapter : issue with mime module

### ISSUE THREAD

**Issue by nsteinmetz** [withastro/astro#7122]
### What version of `astro` are you using?

2.5.0

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

```
{
  "name": "@legalwatch/landing",
  "type": "module",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro",
    "test": "vitest",
    "test:e2e": "cypress open",
    "test:e2e:run": "cypress run"
  },
  "dependencies": {
    "@astrojs/node": "^5.1.4",
    "@astrojs/tailwind": "^3.1.3",
    "@astrojs/vue": "^2.2.0",
    "@mailpace/mailpace.js": "^0.1.1",
    "@tailwindcss/forms": "^0.5.3",
    "astro": "^2.5.0",
    "axios": "^1.4.0",
    "daisyui": "^2.51.6",
    "tailwindcss": "^3.3.2",
    "vue": "^3.3.4"
  },
  "packageManager": "pnpm@8.5.1",
  "devDependencies": {
    "cypress": "^12.12.0",
    "eslint": "^8.40.0",
    "vitest": "^0.31.1"
  },
  "engines": {
    "node": ">=18.0.0 <20.0.0"
  }
}
```

`pnpm build` runs without any issues :

```
pnpm build  

> @legalwatch/landing@0.0.1 build /Users/nsteinmetz/Documents/Projets/javascript/lw-landing
> astro build

20:58:41 [content] No content directory found. Skipping type generation.
20:58:41 [build] output target: server
20:58:41 [build] deploy adapter: @astrojs/node
20:58:41 [build] Collecting build info...
20:58:41 [build] Completed in 277ms.
20:58:41 [build] Building server entrypoints...

🌼 daisyUI components 2.51.6  https://daisyui.com
  ✔︎ Including:  base, components, 1 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 
  

🌼 daisyUI components 2.51.6  https://daisyui.com
  ✔︎ Including:  base, components, 1 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 
  
20:58:43 [build] Completed in 1.73s.

 building client 
Completed in 504ms.


 finalizing server assets 

20:58:43 [build] Rearranging server assets...
20:58:43 [build] Server built in 2.53s
20:58:43 [build] Complete!
```

Node starts correctly:

```
❯ node ./dist/server/entry.mjs 
Server listening on http://127.0.0.1:3000
```

But once I open the page:

```
file:///Users/nsteinmetz/Documents/Projets/javascript/lw-landing/dist/server/entry.mjs:5667
  var type = mime.lookup(path);
                  ^

TypeError: mime.lookup is not a function
    at SendStream.type (file:///Users/nsteinmetz/Documents/Projets/javascript/lw-landing/dist/server/entry.mjs:5667:19)
    at SendStream.send (file:///Users/nsteinmetz/Documents/Projets/javascript/lw-landing/dist/server/entry.mjs:5460:8)
    at onstat (file:///Users/nsteinmetz/Documents/Projets/javascript/lw-landing/dist/server/entry.mjs:5562:10)
    at FSReqCallback.oncomplete (node:fs:209:5)

Node.js v18.16.0
```

On browser side, I have:

```
Error when loading module whose source is  « http://127.0.0.1:3000/_astro/ContactForm.a2a31c9b.js ». [127.0.0.1:3000:352:76](http://127.0.0.1:3000/)
Error when loading module whose source is  « http://127.0.0.1:3000/_astro/client.6f488b54.js ». [127.0.0.1:3000:352:76](http://127.0.0.1:3000/)
Uncaught (in promise) TypeError: error loading dynamically imported module [127.0.0.1:3000:352:117](http://127.0.0.1:3000/)
```

```
❯ tree dist 
dist
├── client
│   ├── _astro
│   │   ├── ContactForm.a6b45ecb.js
│   │   ├── client.6f488b54.js
│   │   ├── index.e729e241.css
│   │   └── runtime-dom.esm-bundler.dec3e0af.js
│   └── favicon.ico
└── server
    ├── chunks
    │   ├── astro.34f24616.mjs
    │   └── pages
    │       └── all.c90da2d6.mjs
    └── entry.mjs
```

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Could your lockfiles be out of date or something? No changes related to `mime` that I can find.  Are you using that package yourself?

**Comment by nsteinmetz** [comment]
lockfile is up to date.

I could see that `mime.lookup()` is tied with mime 1.x whereas it was replaced with `mime.getType()` in 2.x+

If I change this on line 5667, next error is:

```
file:///Users/nsteinmetz/Documents/Projets/javascript/lw-landing/dist/server/entry.mjs:5674
  var charset = mime.charsets.lookup(type);
                              ^

TypeError: Cannot read properties of undefined (reading 'lookup')
    at SendStream.type (file:///Users/nsteinmetz/Documents/Projets/javascript/lw-landing/dist/server/entry.mjs:5674:31)
    at SendStream.send (file:///Users/nsteinmetz/Documents/Projets/javascript/lw-landing/dist/server/entry.mjs:5460:8)
    at onstat (file:///Users/nsteinmetz/Documents/Projets/javascript/lw-landing/dist/server/entry.mjs:5562:10)
    at FSReqCallback.oncomplete (node:fs:209:5)
```


Sees we have mime and mime2 packages:

```
❯ tree node_modules |rg mime
├── mime
├── mime 2
├── mime-db
├── mime-db 2
├── mime-types
├── mime-types 2
```

**Comment by nsteinmetz** [comment]
Think i found the culprit (at least the first traces):

```
  /@astrojs/node@5.1.4(astro@2.5.0):
    resolution: {integrity: sha512-/YfI6UsWz/ibzSR7YrXkXhsalP2A9VybY8Y40k8jr2bHh4kHGIQnMPx2372g0ZlNnTt5yv7lYD65XzSAYztWhA==}
    peerDependencies:
      astro: ^2.5.0
    dependencies:
      '@astrojs/webapi': 2.1.1
      astro: 2.5.0
      send: 0.18.0
      server-destroy: 1.0.1
    transitivePeerDependencies:
      - supports-color
    dev: false
```

and `send` requires mime1.6:

```
  /send@0.18.0:
    resolution: {integrity: sha512-qqWzuOjSFOuqPjFe4NOsMLafToQQwBSOEpS+FwEt3A2V3vKubTquT3vmLTQpFgMXp8AlFWFuP1qKaJZOtPpVXg==}
    engines: {node: '>= 0.8.0'}
    dependencies:
      debug: 2.6.9
      depd: 2.0.0
      destroy: 1.2.0
      encodeurl: 1.0.2
      escape-html: 1.0.3
      etag: 1.8.1
      fresh: 0.5.2
      http-errors: 2.0.0
      mime: 1.6.0
      ms: 2.1.3
      on-finished: 2.4.1
      range-parser: 1.2.1
      statuses: 2.0.1
    transitivePeerDependencies:
      - supports-color
    dev: false
```

**Comment by nsteinmetz** [comment]
Seems it was updated in a 1.0-beta1 which never changed since 2022:

https://github.com/pillarjs/send/blob/1.0/package.json

**Comment by nsteinmetz** [comment]
Ok `send` package was introduced with the standalone mode of node adapter:

https://github.com/withastro/astro/commit/e55af8a23233b6335f45b7a04b9d026990fb616c#diff-53407763c42de8fd7aa143579ffd5b21221f23ae0d75a308dd95a2c23e33d7c9

**Comment by matthewp** [comment]
Please provide a reproduction. I haven't been able to recreate in a local project.

**Comment by nsteinmetz** [comment]
Hi @matthewp,

I'll try with latest version of astro and if I reproduce it provide the related code by end of the week.

**Comment by bluwy** [comment]
@nsteinmetz I cloned it locally and not seeing any errors after `pnpm build` and `node ./dist/server/entry.mjs`. Perhaps you have to re-install the deps?

**Comment by nsteinmetz** [comment]
@bluwy 
after the `node ./dist/server/entry.mjs`
when you go ho http://localhost:3000, you don't have the errror ?


Till I don't access the site, it works - once I access it, I have the mime issue on backend side and rendering is partial/weird in the browser.

**Comment by nsteinmetz** [comment]
Started with the new folder I used for publishing this sample, it works as expected - weird.

So there should be something on my side -> closing.

**Comment by nsteinmetz** [comment]
Removed once more node_modules and it finally works also in original project folder ?!
