### ISSUE TITLE
Getting errors while installing astro integrations using `quick install` through bun. But `manual install` of integrations works as expected.

### ISSUE THREAD

**Issue by prosenjitjoy** [withastro/astro#7211]
### What version of `astro` are you using?

2.5.5 

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

bun

### What operating system are you using?

Linux

### What browser are you using?

Chrome

## Problem Statement
I am following the official recipe [Use Bun with Astro](https://docs.astro.build/en/recipes/bun/). Everything works well until i went to to add official tailwind integration. It's giving me the following errors.
```sh
prosenjit@joy:~/astro-bun$ bun x astro add tailwind
✔ Resolving packages...

  Astro will run the following command:
  If you skip this step, you can always run it yourself later

 ╭─────────────────────────────────────────────────────────────────╮
 │ npm install @astrojs/tailwind astro@^2.5.0 tailwindcss@^3.0.24  │
 ╰─────────────────────────────────────────────────────────────────╯

✔ Continue? … yes
✖ Installing dependencies...
 error   Astro could not update your astro.config.js file safely.
  Reason: Unable to install dependencies
  
  You will need to add these integration(s) manually.
  Documentation: https://docs.astro.build/en/guides/integrations-guide/
  File:
    /home/prosenjit/astro-bun/node_modules/astro/dist/core/add/index.js:157:31
  Code:
    156 |     case 3 /* failure */: {
    > 157 |       throw createPrettyError(new Error(`Unable to install dependencies`));
          |                               ^
      158 |     }
      159 |   }
      160 |   const rawConfigPath = await resolveConfigPath({ cwd, flags, fs: fsMod });
  Stacktrace:
Error: Astro could not update your astro.config.js file safely.
Reason: Unable to install dependencies

You will need to add these integration(s) manually.
Documentation: https://docs.astro.build/en/guides/integrations-guide/
    at add (file:///home/prosenjit/astro-bun/node_modules/astro/dist/core/add/index.js:157:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runCommand (file:///home/prosenjit/astro-bun/node_modules/astro/dist/cli/index.js:108:14)
    at async cli (file:///home/prosenjit/astro-bun/node_modules/astro/dist/cli/index.js:209:5)

error: "astro" exited with code 1 (SIGHUP)
```

So, I followed the official [integration guide](https://docs.astro.build/en/guides/integrations-guide/tailwind/) to install manully as suggested in the errors. And everything works as expected. I entered the following to manually install tailwind integration.
```sh
prosenjit@joy:~/astro-bun$ bun install @astrojs/tailwind tailwindcss
bun add v0.6.3 (e869fc09)

 installed @astrojs/tailwind@3.1.3
 installed tailwindcss@3.3.2 with binaries:
  - tailwind
  - tailwindcss


 48 packages installed [5.83s]
prosenjit@joy:~/astro-bun$ nano astro.config.mjs 
prosenjit@joy:~/astro-bun$ cat astro.config.mjs 
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  // ...
  integrations: [tailwind()],
});

```
## Expected Behavior
`astro add` should work as expected with bun. Meaning running `bun x astro add 'integration name'` should automatically install astro integration and modify `astro.config.mjs` file.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by thiagozf** [comment]
I'm experiencing the same problem. Why was this issue closed? Did you find a fix?

**Comment by Devccss** [comment]
hello, this option worked for me, and I tried several alternatives before: https://astro-tips.dev/tips/tailwind-v4/
