### ISSUE TITLE
process.binding() is not supported in Bun.

### ISSUE THREAD

**Issue by cottamcha** [withastro/astro#7238]
### What version of `astro` are you using?

@latest

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Bun

### What operating system are you using?

Windows 10

### What browser are you using?

Chrome

### Describe the Bug

cant use Bun with astro. could be a problem with node api

```
bun x create-astro@latest my-astro-project-using-bun
6 | let writev = fs.writev
7 | /* istanbul ignore next */
8 | if (!writev) {
9 |   // This entire block can be removed if support for earlier than Node.js  
10 |   // 12.9.0 is not needed.
11 |   const binding = process.binding('fs')
                      ^
TypeError: process.binding() is not supported in Bun. If that breaks something, 
please file an issue and include a reproducible code sample.
      at /tmp/create-astro@latest--bunx/node_modules/fs-minipass/index.js:11:18 
      at /tmp/create-astro@latest--bunx/node_modules/tar/lib/create.js:7:6      
      at /tmp/create-astro@latest--bunx/node_modules/tar/index.js:4:20
      at /tmp/create-astro@latest--bunx/node_modules/giget/dist/shared/giget.5e7ec864.mjs:4:0
error: "create-astro" exited with code 1 (SIGHUP)```

### Link to Minimal Reproducible Example

bun x create-astro@latest my-astro-project-using-bun

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
We do not support Bun officially. Please file an issue on their repo: https://github.com/oven-sh/bun
