### ISSUE TITLE
run dev works, run build fails - simple component trouble

### ISSUE THREAD

**Issue by seccentral** [withastro/astro#7345]
### What version of `astro` are you using?

2.6.2

### Are you using an SSR adapter? If so, which one?

Netlify (build fails anywhere tho, including local)

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

### What browser are you using?

Brave 

### Describe the Bug

Hello, 
I'm a newbie, started learning js about a month ago and astro last week. I'm running into a weird problem that I need help fixing.

I reproduced the bug in a basic empty astro project with tailwind and daisyui added on top since thats what i use in my project and uploaded this to https://github.com/seccentral/component-test 
The problem is that this works perfectly fine in dev mode, zero issuess whatsoever but fails with a hard error on build : 

```
PS G:\coding\js\astro\component-test> npm run build

> component-test@0.0.1 build
> astro build

11:07:46 AM [content] No content directory found. Skipping type generation.
11:07:46 AM [build] output target: static
11:07:46 AM [build] Collecting build info...
11:07:46 AM [build] Completed in 162ms.
11:07:46 AM [build] Building static entrypoints...

🌼 daisyUI 3.0.20 https://daisyui.com
╰╮
 ╰─ ✔︎ [ 2 ] themes are enabled. You can add more themes or make your own theme:
      https://daisyui.com/docs/themes

    ❤︎ Support daisyUI: https://opencollective.com/daisyui


warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
11:07:48 AM [build] Completed in 1.16s.

 generating static routes 
▶ src/pages/index.astro
  └─ /index.html (+18ms)
▶ src/pages/components/MenuButton.astro
undefined undefined
 error   Cannot read properties of null (reading 'default')
  File:
    src/pages/components/MenuButton.astro
  Stacktrace:
TypeError: Cannot read properties of null (reading 'default')
    at file:///G:/coding/js/astro/component-test/dist/chunks/pages/MenuButton.astro.9133ce95.mjs:12:39
    at MenuButton (file:///G:/coding/js/astro/component-test/dist/chunks/astro.26c80813.mjs:1148:12)
    at renderPage (file:///G:/coding/js/astro/component-test/node_modules/astro/dist/runtime/server/render/page.js:96:36)
    at renderPage (file:///G:/coding/js/astro/component-test/node_modules/astro/dist/core/render/core.js:110:24)
    at generatePath (file:///G:/coding/js/astro/component-test/node_modules/astro/dist/core/build/generate.js:453:26)
    at async generatePage (file:///G:/coding/js/astro/component-test/node_modules/astro/dist/core/build/generate.js:188:5)
    at async generatePages (file:///G:/coding/js/astro/component-test/node_modules/astro/dist/core/build/generate.js:117:7)
    at async staticBuild (file:///G:/coding/js/astro/component-test/node_modules/astro/dist/core/build/static-build.js:85:7)
    at async AstroBuilder.build (file:///G:/coding/js/astro/component-test/node_modules/astro/dist/core/build/index.js:124:5)
    at async AstroBuilder.run (file:///G:/coding/js/astro/component-test/node_modules/astro/dist/core/build/index.js:156:7)
```

The error ` error   Cannot read properties of null (reading 'default')`  is somehow related to my component. I really don't understand why. 
Also, this happens whether I reference MenuButton.astro or not. In the supplied public repo example, I have removed all references to MenuButton and the error still persists. 
I am seriously missing some very important information, I tried asking in discord, did not solve my problem. 
Please help ? 

### Link to Minimal Reproducible Example

https://-it-will-not-build-so-i-can-not.com-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You want to move your `components/` folder outside of pages. Inside inside `pages/` get built as though it were a page.
