### ISSUE TITLE
npm create astro@latest looks for... pnpm?

### ISSUE THREAD

**Issue by arjunindia** [withastro/astro#7379]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

On running `npm create astro@latest`, 

```
file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: pnpm config get registry
'pnpm' is not recognized as an internal or external command,
operable program or batch file.
    at makeError (file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRegistry (file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/create-astro/dist/index.js:228:31)
    at async file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/create-astro/dist/index.js:279:20 {
  shortMessage: 'Command failed with exit code 1: pnpm config get registry',
  command: 'pnpm config get registry',
  escapedCommand: 'pnpm config get registry',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "'pnpm' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0
npm ERR! code 1
npm ERR! path D:\htmlcss
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-astro

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2023-06-12T16_42_49_111Z-debug-0.log
 htmlcss  npm create astro@latest
file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: pnpm config get registry
'pnpm' is not recognized as an internal or external command,
operable program or batch file.
    at makeError (file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRegistry (file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/create-astro/dist/index.js:228:31)
    at async file:///C:/Users/user/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/create-astro/dist/index.js:279:20 {
  shortMessage: 'Command failed with exit code 1: pnpm config get registry',
  command: 'pnpm config get registry',
  escapedCommand: 'pnpm config get registry',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "'pnpm' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0
npm ERR! code 1
npm ERR! path D:\htmlcss
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-astro

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2023-06-12T16_43_24_485Z-debug-0.log
```

### Link to Minimal Reproducible Example

Reproduction likely  isn't possible on an online platform, but have the error logs instead: https://pastebin.com/raw/VG9qGsiD

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Thanks for this @arjunindia! I know we rely on the which-pm-runs package to detect this. To be sure, does this error occur at the "install dependencies" CLI step or immediately at the start of the CLI?

**Comment by arjunindia** [comment]
this happens right after:
```
Need to install the following packages:
  create-astro@3.1.7
Ok to proceed? (y) y
```
So I guess yeah immediately

**Comment by bholmesdev** [comment]
@arjunindia Ah interesting. Do you get this error using `create` for other starters as well? Ex. try `npm create vite@latest`

**Comment by bholmesdev** [comment]
Think I have a fix! @arjunindia do you mind running this to verify?

```sh
npm create astro@next--pm-fix
```

**Comment by bholmesdev** [comment]
Closed to merge into the latest patch. Let us know if the issue persists!

**Comment by arjunindia** [comment]
It works great now! Thanks! Now I can keep using this amazing framework again
