### ISSUE TITLE
Error using asynchronous imports with experimental assets api

### ISSUE THREAD

**Issue by eyrewiut** [withastro/astro#7382]
### What version of `astro` are you using?

2.6.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

I am trying to import images dynamically for use with the `<Image/>` component (experimental assets version).

It works perfectly fine if I use a regular import statement like so: `import image from "../assets/images/placeholder.jpg";`

However, whenever I pass an async import statement to either `<Image/>` or `getImage` it throws the following error:
This happens with any async import statement, even if it is not dynamic.

```
 error   Received unsupported format `undefined` from `undefined`. Currently only jpeg, jpg, png, tiff, webp, gif are supported for optimization.
  Hint:
    If you do not need optimization, using an `img` tag directly instead of the `Image` component might be what you're looking for.
  File:
    /Users/george/Documents/Frontend_Projects/im-showcase-2023/src/pages/team.astro
  Stacktrace:
UnsupportedImageFormat: Received unsupported format `undefined` from `undefined`. Currently only jpeg, jpg, png, tiff, webp, gif are supported for optimization.
    at Object.validateOptions (/Users/george/Documents/Frontend_Projects/im-showcase-2023/node_modules/astro/dist/assets/services/service.js:55:15)
    at Module.getImage (/Users/george/Documents/Frontend_Projects/im-showcase-2023/node_modules/astro/dist/assets/internal.js:36:62)
    at async Module.getImage (astro:assets:16:42)
    at async eval (/Users/george/Documents/Frontend_Projects/im-showcase-2023/src/components/TeamCard.astro:16:15)
    at async AstroComponentInstance.render (/Users/george/Documents/Frontend_Projects/im-showcase-2023/node_modules/astro/dist/runtime/server/render/astro/instance.js:31:7)
    at async Module.renderChild (/Users/george/Documents/Frontend_Projects/im-showcase-2023/node_modules/astro/dist/runtime/server/render/any.js:33:5)
    at async EagerAsyncIterableIterator.next (/Users/george/Documents/Frontend_Projects/im-showcase-2023/node_modules/astro/dist/runtime/server/render/util.js:155:14)
    at async [Symbol.asyncIterator] (/Users/george/Documents/Frontend_Projects/im-showcase-2023/node_modules/astro/dist/runtime/server/render/astro/render-template.js:38:9)
    at async Module.renderAstroTemplateResult (/Users/george/Documents/Frontend_Projects/im-showcase-2023/node_modules/astro/dist/runtime/server/render/astro/render-template.js:47:20)
    at async renderChild (/Users/george/Documents/Frontend_Projects/im-showcase-2023/node_modules/astro/dist/runtime/server/render/any.js:31:5)
 (x3)

```

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/quiet-sunset-rjhv9t?on=codesandbox&file=%2Fsrc%2Fpages%2Findex.astro%3A1%2C1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
You should never use `src={image.src}`. What you're missing here is using the default export.

```
const fred = (await import("image")).default
```

Otherwise, `fred` is an object with a property called `default` which contains the import's default export, whereas Image and getImage `src` expect the default export of an image import.

**Comment by eyrewiut** [comment]
Thank you! Your suggestion seems to have fixed the problem. For future reference, is there anywhere which documents this behaviour?

**Comment by Princesseuh** [comment]
Since it's not Astro specific, you can find documentation on this behaviour on most websites about JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#importing_defaults
