### ISSUE TITLE
Error: Missing "./dist/runtime/server" specifier in "astro" package

### ISSUE THREAD

**Issue by reinhart1010** [withastro/astro#7388]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I've recently upgraded Astro to the latest version, and also tried to reinstalling all modules, only to find out that pages that require SSR could not be rendered (`pnpm dev`) or built.

```
Error: Missing "./dist/runtime/server" specifier in "astro" package
    at e (file:///Users/shift/Projects/reinhart1010-2023/node_modules/.pnpm/vite@4.3.9_sass@1.63.4/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:16647:25)
    at n (file:///Users/shift/Projects/reinhart1010-2023/node_modules/.pnpm/vite@4.3.9_sass@1.63.4/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:16647:627)
    at o (file:///Users/shift/Projects/reinhart1010-2023/node_modules/.pnpm/vite@4.3.9_sass@1.63.4/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:16647:1297)
    at resolveExportsOrImports (file:///Users/shift/Projects/reinhart1010-2023/node_modules/.pnpm/vite@4.3.9_sass@1.63.4/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23405:20)
    at resolveDeepImport (file:///Users/shift/Projects/reinhart1010-2023/node_modules/.pnpm/vite@4.3.9_sass@1.63.4/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23424:31)
    at tryNodeResolve (file:///Users/shift/Projects/reinhart1010-2023/node_modules/.pnpm/vite@4.3.9_sass@1.63.4/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
    at Context.resolveId (file:///Users/shift/Projects/reinhart1010-2023/node_modules/.pnpm/vite@4.3.9_sass@1.63.4/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
    at Object.resolveId (file:///Users/shift/Projects/reinhart1010-2023/node_modules/.pnpm/vite@4.3.9_sass@1.63.4/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransformContext.resolve (file:///Users/shift/Projects/reinhart1010-2023/node_modules/.pnpm/vite@4.3.9_sass@1.63.4/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42575:23)
```

As a reference I've uploaded my current `package.json` and `astro.config.mjs` on StackBlitz, but the example's project contents are left untouched.

This error is also reproducible when using npm instead on pnpm.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fnwugy?file=src%2Fpages%2Fblog%2F%5B...slug%5D.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by reinhart1010** [comment]
Oh apparently it is caused by one of my components calling an internal Astro method (`unescapeHTML` instead of `unescape` in [`html-escaper` package](https://www.npmjs.com/package/html-escaper)).
