### ISSUE TITLE
SSR `split` does not work with Cloudflare

### ISSUE THREAD

**Issue by alexanderniebuhr** [withastro/astro#7462]
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

The new SSR `split` function does not work for Cloudflare Adapter.
The documentation let's the user think it should work regardless the adapter, since it is in the general SSR Guide.

```
✘ [ERROR] Could not resolve "/home/projects/github-q6erqj/dist/$server_build/_worker.mjs"

 error   Could not resolve "/home/projects/github-q6erqj/dist/$server_build/_worker.mjs"
  File:
    :1626:15
  Code:
    1625 |   }).join("");
    > 1626 |   let error = new Error(`${text}${summary}`);
           |               ^
      1627 |   error.errors = errors;
      1628 |   error.warnings = warnings;
      1629 |   return error;
  Stacktrace:
Error: Build failed with 1 error:
error: Could not resolve "/home/projects/github-q6erqj/dist/$server_build/_worker.mjs"
    at failureErrorWithLog (file:///home/projects/github-q6erqj/node_modules/esbuild/lib/main.js:1626:15)
    at eval (file:///home/projects/github-q6erqj/node_modules/esbuild/lib/main.js:1038:25)
    at eval (file:///home/projects/github-q6erqj/node_modules/esbuild/lib/main.js:983:52)
    at buildResponseToResult (file:///home/projects/github-q6erqj/node_modules/esbuild/lib/main.js:1036:7)
    at eval (file:///home/projects/github-q6erqj/node_modules/esbuild/lib/main.js:1065:16)
    at responseCallbacks.<computed> (file:///home/projects/github-q6erqj/node_modules/esbuild/lib/main.js:687:9)
    at handleIncomingPacket (file:///home/projects/github-q6erqj/node_modules/esbuild/lib/main.js:742:9)
    at Socket.readFromStdout (file:///home/projects/github-q6erqj/node_modules/esbuild/lib/main.js:663:7)
    at EventEmitter.emit (https://githubq6erqj-sm1d.w-credentialless.staticblitz.com/blitz.131c0a4f.js:35:143925)
    at addChunk (https://githubq6erqj-sm1d.w-credentialless.staticblitz.com/blitz.131c0a4f.js:35:541673)
```

### What's the expected result?

- SSR `split` works for all Adapters with basic support.
- SSR `split` makes use of each Adapter, e.g. Cloudflare Directory Mode + `functions` folder
- (in the meantime, the docs should clarify this)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-q6erqj?file=astro.config.mjs

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
i'm looking into the @astrojs/cloudflare adapter to see if I can submit a PR
