### ISSUE TITLE
Build fails with unclear error indication when vite plugin topLevelAwait is used

### ISSUE THREAD

**Issue by Firfi** [withastro/astro#7474]
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When I use 

`vite: { plugins: [...topLevelAwait() ] }` my builds would fail with `Cannot read properties of undefined (reading 'filter')`

`Cannot read properties of undefined (reading 'filter')` happens inside Astro build scripts which makes me assume it could be Astro issue (case (a) below in "expected result") but not topLevelAwait issue. 

However, I don't exclude the possibility that I may be shooting the messenger, in which case this messenger is worth shooting (unclear error indication, case (b) below in "expected result")

------ FAILED CASE REPRODUCTION --------

this is the case with topLevelAwait()

```
git clone git@github.com:Firfi/nxblog.git topLevelAwait-failure
cd topLevelAwait-failure
git checkout 79e6d7f5d81b6a65607b4aec2e8ee1bcc4365d36
npm install
npx astro build --root packages/astroblog
```

where I get

```
 generating static routes
▶ src/pages/index.astro
 error   Cannot read properties of undefined (reading 'filter')
  File:
    /Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/runtime/server/render/page.js:96:36
  Code:
    95 |   result._metadata.headInTree = ((_b = result.componentMetadata.get(componentFactory.moduleId)) == null ? void 0 : _b.containsHead) ?? false;
    > 96 |   const factoryReturnValue = await componentFactory(result, props, children);
         |                                    ^
      97 |   const factoryIsHeadAndContent = isHeadAndContent(factoryReturnValue);
      98 |   if (isRenderTemplateResult(factoryReturnValue) || factoryIsHeadAndContent) {
      99 |     await bufferHeadContent(result);
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'filter')
    at renderFrameworkComponent (file:///Users/firfi/work/blog/topLevelAwait-failure/dist/packages/astroblog/chunks/astro.90fe6bbf.mjs:2393:36)
    at renderComponent (file:///Users/firfi/work/blog/topLevelAwait-failure/dist/packages/astroblog/chunks/astro.90fe6bbf.mjs:2623:10)
    at Object.default (file:///Users/firfi/work/blog/topLevelAwait-failure/dist/packages/astroblog/chunks/pages/index.astro.cb3ef5f9.mjs:35:6)
    at new AstroComponentInstance (file:///Users/firfi/work/blog/topLevelAwait-failure/dist/packages/astroblog/chunks/astro.90fe6bbf.mjs:1633:32)
    at createAstroComponentInstance (file:///Users/firfi/work/blog/topLevelAwait-failure/dist/packages/astroblog/chunks/astro.90fe6bbf.mjs:1670:20)
    at renderComponent (file:///Users/firfi/work/blog/topLevelAwait-failure/dist/packages/astroblog/chunks/astro.90fe6bbf.mjs:2621:12)
    at file:///Users/firfi/work/blog/topLevelAwait-failure/dist/packages/astroblog/chunks/pages/index.astro.cb3ef5f9.mjs:27:27
    at index (file:///Users/firfi/work/blog/topLevelAwait-failure/dist/packages/astroblog/chunks/astro.90fe6bbf.mjs:1185:12)
    at renderPage (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/runtime/server/render/page.js:96:36)
    at renderPage (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/core/render/core.js:109:24)
    at generatePath (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/core/build/generate.js:457:26)
    at async generatePage (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/core/build/generate.js:193:5)
    at async generatePages (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/core/build/generate.js:118:7)
    at async staticBuild (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/core/build/static-build.js:85:7)
    at async AstroBuilder.build (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/core/build/index.js:124:5)
    at async AstroBuilder.run (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/core/build/index.js:156:7)
    at async build (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/core/build/index.js:37:3)
    at async runCommand (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/cli/index.js:171:14)
    at async cli (file:///Users/firfi/work/blog/topLevelAwait-failure/node_modules/astro/dist/cli/index.js:213:5)
```

------ SUCCESSFUL CASE REPRODUCTION -------

this is the case without topLevelAwait()

```
git clone git@github.com:Firfi/nxblog.git topLevelAwait-success
cd topLevelAwait-success
git checkout 16bc749e99b81f4fd659cc87b4666425fac6eba6
npm install
npx astro build --root packages/astroblog
```

where I get a successful build that I also can run in browser

### What's the expected result?

I expect it to either

- (a) build 
- (b) or at least to point me to a specific misconfiguration error

### Link to Minimal Reproducible Example

git@github.com:Firfi/nxblog.git#79e6d7f5d81b6a65607b4aec2e8ee1bcc4365d36

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hmm, I'm not sure we expect that this plugin could work in Astro unmodified! 

Looks like it's attempting to transform some code in the Astro server runtime, which is causing the failure. If you need to transform top-level await in client side code, you could conditionally apply the plugin using our [`astro:build:setup`](https://docs.astro.build/en/reference/integrations-reference/#astrobuildsetup) integration hook _only when the `target` is `'client'`_, otherwise you'll be incorrectly transforming the server code.

All that being said, Astro doesn't rely on top-level await in the clientside JS that we generate, so it shouldn't be an issue. If you need to use top-level await in your own code, you can always wrap it in an IIFE.
