### ISSUE TITLE
Cannot find module 'astro/config' imported from '/Users/antic/wiki/astro.config.mjs'

### ISSUE THREAD

**Issue by dogeow** [withastro/astro#7501]
### What version of `astro` are you using?

v2.7.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug
```
➜  wiki git:(main) yarn dev
yarn run v1.22.19
warning package.json: No license field
$ astro dev
22:44:09 [vite] Error when evaluating SSR module /Users/antic/wiki/astro.config.mjs: failed to import "astro/config"
|- Error: Cannot find module 'astro/config' imported from '/Users/antic/wiki/astro.config.mjs'
    at nodeImport (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54441:25)
    at ssrImport (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54343:30)
    at eval (/Users/antic/wiki/astro.config.mjs:3:50)
    at instantiateModule (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:15)

22:44:09 [astro] Unable to load /Users/antic/wiki/astro.config.mjs

 error   Cannot find module 'astro/config' imported from '/Users/antic/wiki/astro.config.mjs'
  File:
    /Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54441:25
  Code:
    54440 |         if (!resolved) {
    > 54441 |             const err = new Error(`Cannot find module '${id}' imported from '${importer}'`);
            |                         ^
      54442 |             err.code = 'ERR_MODULE_NOT_FOUND';
      54443 |             throw err;
      54444 |         }
  Stacktrace:
Error: Cannot find module 'astro/config' imported from '/Users/antic/wiki/astro.config.mjs'
    at nodeImport (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54441:25)
    at ssrImport (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54343:30)
    at eval (/Users/antic/wiki/astro.config.mjs:3:50)
    at instantiateModule (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:54405:15)


Failed to load url astro/config (resolved id: astro/config) in /Users/antic/wiki/astro.config.mjs. Does the file exist?
 error   Cannot read properties of undefined (reading 'map')
  File:
    /Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/dist/events/error.js:23:34
  Code:
    22 |     cliCommand: cmd,
    > 23 |     configErrorPaths: err.issues.map((issue) => issue.path.join("."))
         |                                  ^
      24 |   };
      25 |   return [{ eventName: EVENT_ERROR, payload }];
      26 | }
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'map')
    at eventConfigError (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/dist/events/error.js:23:34)
    at handleConfigError (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/dist/cli/index.js:81:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/dist/cli/index.js:143:5
    at async runCommand (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/dist/cli/index.js:137:76)
    at async cli (file:///Users/antic/.nvm/versions/node/v16.16.0/lib/node_modules/astro/dist/cli/index.js:213:5)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### What's the expected result?

Not Error

### Link to Minimal Reproducible Example

None

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
With reproduction, we would likely be able to help. Unfortunately, the stacktrace doesn't help enough.

**Comment by natemoo-re** [comment]
It also looks like you're using `node@16.16.0` but the latest release is `node@16.20.1`. Not sure that will fix anything, but it might help.

Please let us know when you're able to attach a reproduction.

**Comment by dogeow** [comment]
I'm sorry I didn't provide a reproduction before.

Now, after I put it in vercel, I found it was ok.

So, I checked the node_modules folder in my PC and it doesn't exist.

Because the Astro CLI prompted me to install dependencies, I assumed that the npm libraries would be installed like they are in other frameworks.
