### ISSUE TITLE
Handshake problem with graphql request

### ISSUE THREAD

**Issue by alexis-puska** [withastro/astro#7577]
### What version of `astro` are you using?

^2.1.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

windoss (dev), unix (prod /ci)

### What browser are you using?

all

### Describe the Bug

Error when execute astro build : 
```

 generating static routes 
▶ src/pages/[...slug].astro
 error   fetch failed
  File:
    /data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/@astrojs/webapi/node_modules/undici/index.js:109:13
  Code:
    108 |     } catch (err) {
    > 109 |       Error.captureStackTrace(err, this)
          |             ^
      110 |       throw err
      111 |     }
      112 |   }
  Stacktrace:
TypeError: fetch failed
    at fetch (/data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/@astrojs/webapi/node_modules/undici/index.js:109:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.getStaticPaths (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/dist/chunks/pages/all.d9f41395.mjs:3386:20)
    at async callGetStaticPaths (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/core/render/route-cache.js:21:17)
    at async getPathsForRoute (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/core/build/generate.js:164:20)
    at async generatePage (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/core/build/generate.js:145:17)
    at async generatePages (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/core/build/generate.js:79:7)
    at async staticBuild (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/core/build/static-build.js:78:7)
    at async AstroBuilder.build (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/core/build/index.js:124:5)
    at async AstroBuilder.run (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/core/build/index.js:156:7)
    at async build (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/core/build/index.js:37:3)
    at async runCommand (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/cli/index.js:167:14)
    at async cli (file:///data/jenkins/workspace/internet-astro_INTERNE_recette/node_modules/astro/dist/cli/index.js:209:5)

  Cause:
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:727:12)

Build step 'Exécuter un script shell' marked build as failure
Finished: FAILURE

```

The certificate of the server on which we make a graphql request for the content is valid and does not cause any problems when browsing ?

Do you have any idea why the handshake failed ? 

Thx

### What's the expected result?

Build succeded 

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Please request for support at https://astro.build/chat. This doesn't seem to be an Astro bug.

**Comment by yazGR** [comment]
I have the same problem, @alexis-puska  did you find a solution?
