### ISSUE TITLE
"res.writeHead is not a function" in Express/Node middleware.

### ISSUE THREAD

**Issue by vergonha** [withastro/astro#7590]
### What version of `astro` are you using?

v2.7.4

### Are you using an SSR adapter? If so, which one?

Node Adapter, Middleware Mode

### What package manager are you using?

NPM

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Custom middleware and error handling aren't catching Syntax Errors. 

As [official Express documentation](https://expressjs.com/guide/error-handling.html) describes, these are the middlewares to handling errors:

```js
function clientErrorHandler(err, req, res, next) {
  if (req.xhr) {
    res.status(500).send({ error: 'Something failed!' });
  } else {
    next(err);
  }
}

function errorHandler(err, req, res, next) {
  if (res.headersSent) {
    return next(err);
  }
  res.status(500);
  res.render('error', { error: err });
}

app.use(clientErrorHandler);
app.use(errorHandler);
```

However, there is a built-in error in the "dist/server/entry.mjs" file built by astro.

```
TypeError: res.writeHead is not a function
    at eval (file:///home/projects/middleware-astro-error/dist/server/entry.mjs:2639:13)
    at Layer.handle_error (file:///home/projects/middleware-astro-error/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (file:///home/projects/middleware-astro-error/node_modules/express/lib/router/index.js:326:13)
    at eval (file:///home/projects/middleware-astro-error/node_modules/express/lib/router/index.js:286:9)
    at Function.process_params (file:///home/projects/middleware-astro-error/node_modules/express/lib/router/index.js:346:12)
    at next (file:///home/projects/middleware-astro-error/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle_error (file:///home/projects/middleware-astro-error/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (file:///home/projects/middleware-astro-error/node_modules/express/lib/router/index.js:326:13)
    at eval (file:///home/projects/middleware-astro-error/node_modules/express/lib/router/index.js:286:9)
    at Function.process_params (file:///home/projects/middleware-astro-error/node_modules/express/lib/router/index.js:346:12)
```

### What's the expected result?

Error will be handled by express and will be returned as a response in the API endpoint.

### Link to Minimal Reproducible Example

Run with `❯ npm run build && node server.mjs`

https://stackblitz.com/edit/middleware-astro-error?file=astro.config.mjs,server.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Any chance you can submit a PR for this? Should be rather small.
