### ISSUE TITLE
Unable to find the manifest for the module file: entry.index.astro.mjs

### ISSUE THREAD

**Issue by josfaber** [withastro/astro#7663]
### What version of `astro` are you using?

2.8.3

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

macOS Ventura 13.4.1

### What browser are you using?

Chrome 114.0.5735.198

### Describe the Bug

On a new project created with `npm create astro@latest` and mode is `hybrid` (installed node with `npx astro add node`), as soon as I set the build to be splitted, I get the following error (full cli output):
```
> astro build

09:34:27 AM [content] No content directory found. Skipping type generation.
09:34:27 AM [build] output target: hybrid
09:34:27 AM [build] deploy adapter: @astrojs/node
09:34:27 AM [build] Collecting build info...
09:34:27 AM [build] Completed in 26ms.
09:34:27 AM [build] Building hybrid entrypoints...
09:34:28 AM [build] Completed in 1.15s.

 prerendering static routes
Server listening on http://127.0.0.1:3000
 error   Unable to find the manifest for the module file:///Users/jos/workspace/astro-test-1/dist/server/src/pages/entry.index.astro.mjs?time=1689406468435. This is unexpected and likely a bug in Astro, please report.
Error: Unable to find the manifest for the module file:///Users/jos/workspace/astro-test-1/dist/server/src/pages/entry.index.astro.mjs?time=1689406468435. This is unexpected and likely a bug in Astro, please report.
    at generatePages (file:///Users/jos/workspace/astro-test-1/node_modules/astro/dist/core/build/generate.js:112:19)
    at async staticBuild (file:///Users/jos/workspace/astro-test-1/node_modules/astro/dist/core/build/static-build.js:94:7)
    at async AstroBuilder.build (file:///Users/jos/workspace/astro-test-1/node_modules/astro/dist/core/build/index.js:118:5)
    at async AstroBuilder.run (file:///Users/jos/workspace/astro-test-1/node_modules/astro/dist/core/build/index.js:149:7)
    at async build (file:///Users/jos/workspace/astro-test-1/node_modules/astro/dist/core/build/index.js:37:3)
    at async build (file:///Users/jos/workspace/astro-test-1/node_modules/astro/dist/cli/build/index.js:7:3)
    at async runCommand (file:///Users/jos/workspace/astro-test-1/node_modules/astro/dist/cli/index.js:117:7)
    at async cli (file:///Users/jos/workspace/astro-test-1/node_modules/astro/dist/cli/index.js:155:5)
```

astro.config.mjs:
```
import { defineConfig } from 'astro/config';
import node from "@astrojs/node";

export default defineConfig({
  adapter: node({
    mode: "standalone"
  }),
  output: 'hybrid',
  build: {
      split: true
  }
});
```

The output encourages me to file a bug report.

### What's the expected result?

I would expect the build to complete and have a page in the dist folder

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-k4xpsd?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
cc @ematipico, seems to be a problem regarding split + the node adapter (not sure if that's supported yet?)
