### ISSUE TITLE
Netlify Edge adatper fails to build with script splitting enabled

### ISSUE THREAD

**Issue by maddsua** [withastro/astro#7666]
### What version of `astro` are you using?

2.8.3

### Are you using an SSR adapter? If so, which one?

Netlify Edge

### What package manager are you using?

npm

### What operating system are you using?

Windows and Linux

### What browser are you using?

Firefox

### Describe the Bug

Astro fails to build project for Netlify Edge adapter with `build: split` enabled. However, if you run a build without splitting enabled, the consequential builds with the feature enabled will pass, but Netlify does not seem to "see" the function files.
The latest seems like `redirects` problem, it's not being adapted for split edge functions, instead, it still points to `/.netlify/edge-functions/entry`.
Netlify CLI also does not seem to load any of split edge functions and 404 error will be displayed when trying to open local preview

Full build log here:

```bash
❯ npm run build

> @example/minimal@0.0.1 build
> astro build

01:28:49 PM [content] No content directory found. Skipping type generation.
01:28:49 PM [build] output target: server
01:28:49 PM [build] deploy adapter: @astrojs/netlify/edge-functions
01:28:49 PM [build] Collecting build info...
01:28:49 PM [build] Completed in 83ms.
01:28:49 PM [build] Building server entrypoints...
01:28:50 PM [build] Completed in 1.20s.

 finalizing server assets 

01:28:50 PM [build] Rearranging server assets...
✘ [ERROR] Could not resolve "/home/projects/github-jbgv2r-vetxzr/.netlify/edge-functions/entry.js"

 error   Could not resolve "/home/projects/github-jbgv2r-vetxzr/.netlify/edge-functions/entry.js"
  File:
    :1569:15
  Code:
    1568 |   }).join("");
    > 1569 |   let error = new Error(`${text}${summary}`);
           |               ^
      1570 |   error.errors = errors;
      1571 |   error.warnings = warnings;
      1572 |   return error;
  Stacktrace:
Error: Build failed with 1 error:
error: Could not resolve "/home/projects/github-jbgv2r-vetxzr/.netlify/edge-functions/entry.js"
    at failureErrorWithLog (/home/projects/github-jbgv2r-vetxzr/node_modules/@astrojs/netlify/node_modules/esbuild/lib/main.js:1569:15)
    at buildResponseToResult/< (/home/projects/github-jbgv2r-vetxzr/node_modules/@astrojs/netlify/node_modules/esbuild/lib/main.js:1027:28)
    at buildOrServeImpl/< (/home/projects/github-jbgv2r-vetxzr/node_modules/@astrojs/netlify/node_modules/esbuild/lib/main.js:972:67)
    at buildResponseToResult (/home/projects/github-jbgv2r-vetxzr/node_modules/@astrojs/netlify/node_modules/esbuild/lib/main.js:1025:24)
    at buildOrServeContinue/< (/home/projects/github-jbgv2r-vetxzr/node_modules/@astrojs/netlify/node_modules/esbuild/lib/main.js:1137:14)
    at sendRequest/responseCallbacks[id] (/home/projects/github-jbgv2r-vetxzr/node_modules/@astrojs/netlify/node_modules/esbuild/lib/main.js:674:17)
    at handleIncomingPacket (/home/projects/github-jbgv2r-vetxzr/node_modules/@astrojs/netlify/node_modules/esbuild/lib/main.js:729:17)
    at readFromStdout (/home/projects/github-jbgv2r-vetxzr/node_modules/@astrojs/netlify/node_modules/esbuild/lib/main.js:650:27)
    at EventEmitter.prototype.emit (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:35:143926)
    at addChunk (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:35:541673)
    at readableAddChunk (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:35:541377)
    at Readable.prototype.push (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:35:542061)
    at onStreamRead (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:35:894623)
    at _0x460a1e/< (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:37:264632)
    at _0x2290eb (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:37:266235)
    at _0x1c34c1 (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:37:262959)
    at _0x346633/< (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:37:265495)
    at _0x346633 (https://githubjbgv2rvetxzr-0b1e.w-corp.staticblitz.com/blitz.c53ab388.js:37:265473)
```

### What's the expected result?

Expected behavior: project built without errors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jbgv2r-vetxzr?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by maddsua** [comment]
I was able to make Netlify CLI load these split functions by changing file extensions from `.mjs` to `.js`, moving them two levels up (placing them next to the `manifest.json`) and by changing `manifest.json` to reference these scripts. But not, CLI complains about not being able to load multiple files from `chunks` directory:

```bash

◈ Loaded edge function index.astro
◈ Failed to run Edge Function index.astro:
TypeError: Module not found "file:///D:/git/maddsuadev-web/.netlify/edge-functions/chunks/astro.b04ce5be.mjs".
    at file:///D:/git/maddsuadev-web/.netlify/edge-functions/renderers.mjs:1:37
    at async file:///C:/Users/maddsua/AppData/Local/Temp/tmp-10480-N6hnxbtyxfVb/dev.js:7:35 {
  code: "ERR_MODULE_NOT_FOUND"
}
TypeError: Module not found "file:///D:/git/maddsuadev-web/.netlify/edge-functions/chunks/astro.b04ce5be.mjs".
    at file:///D:/git/maddsuadev-web/.netlify/edge-functions/renderers.mjs:1:37
    at async file:///C:/Users/maddsua/AppData/Roaming/nodejs/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/deno/config.ts:7:10 {
  code: "ERR_MODULE_NOT_FOUND"
}

```

Indeed, there is no such folder anywhere to be found. Here is a tree of `.netlify` directory:

```bash
└───edge-functions
    └───entry.src
        └───pages
            └───store
                └───product
```

**Comment by Princesseuh** [comment]
cc @ematipico

**Comment by ematipico** [comment]
@maddsua The edge functions adapter doesn't support `split: true`. Check the documentation: https://github.com/withastro/astro/blob/main/packages/integrations/netlify/README.md#per-page-functions

This feature is supported only for Netlify functions. This is in line with the Vercel adapter.

**Comment by maddsua** [comment]
@ematipico All right, thanks! I didn't expect Netlify Edge being less popular, as it's actually pretty good.
@matthewp I guess, now I know where to spend my free time - will try to implement support for the Edge
