### ISSUE TITLE
"Unable to find the manifest for the module": Vercel adapter + build split

### ISSUE THREAD

**Issue by raulfdm** [withastro/astro#7753]
### What version of `astro` are you using?

2.9.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm (monorepo)

### What operating system are you using?

Mac

### What browser are you using?

not relevant

### Describe the Bug

I updated my project to latest Astro version (2.9.0) and tried to enable `build.split=true`, but I got this:

```
 error   Unable to find the manifest for the module file:///Users/raulmelo/development/raulmelo-studio/apps/website/dist/src/pages/_lang_/entry.index.astro.mjs?time=1689962086151. This is unexpected and likely a bug in Astro, please report.
```

I have no clue what's going on, and unfortunately, for this problem, I cannot give a reproducible repository.

To build my website, I need a few API Tokens, so you won't be able to clone and build.

I'm unsure how I can help investigate the problem, though.

Here's my website repository:  https://github.com/raulfdm/raulmelo-studio

https://github.com/withastro/astro/assets/12464600/9862cb68-e5f4-4c28-b833-2541becfa6da

Let me know if I can do something

### What's the expected result?

It builds in split mode.

### Link to Minimal Reproducible Example

I don't it :(

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jamsch** [comment]
Can reproduce as well on a fairly fresh project. Enabling `build.split = true` results in the same error

<details>
  <summary>Vercel build logs</summary>

```
[20:14:19.483] > app-www@0.0.1 build /vercel/path0
[20:14:19.484] > astro build
[20:14:19.484] 
[20:14:20.867] 08:14:20 AM [content] No content directory found. Skipping type generation.
[20:14:20.868] 08:14:20 AM [build] output target: server
[20:14:20.869] 08:14:20 AM [build] deploy adapter: @astrojs/vercel/edge
[20:14:20.869] 08:14:20 AM [build] Collecting build info...
[20:14:20.869] 08:14:20 AM [build] Completed in 360ms.
[20:14:20.871] 08:14:20 AM [build] Building server entrypoints...
[20:14:23.934] 08:14:23 AM [build] Completed in 3.06s.
[20:14:23.934] 
[20:14:23.934]  building client 
[20:14:26.262] Completed in 2.33s.
[20:14:26.262] 
[20:14:26.268] 
[20:14:26.269]  prerendering static routes 
[20:14:26.392]  error   Unable to find the manifest for the module file:///vercel/path0/dist/src/pages/entry.index.astro.mjs?time=1691396066268. This is unexpected and likely a bug in Astro, please report.
[20:14:26.393] Error: Unable to find the manifest for the module file:///vercel/path0/dist/src/pages/entry.index.astro.mjs?time=1691396066268. This is unexpected and likely a bug in Astro, please report.
[20:14:26.393]     at generatePages (file:///vercel/path0/node_modules/.pnpm/astro@2.10.1_sass@1.64.2/node_modules/astro/dist/core/build/generate.js:110:19)
[20:14:26.393]     at async staticBuild (file:///vercel/path0/node_modules/.pnpm/astro@2.10.1_sass@1.64.2/node_modules/astro/dist/core/build/static-build.js:93:7)
[20:14:26.393]     at async AstroBuilder.build (file:///vercel/path0/node_modules/.pnpm/astro@2.10.1_sass@1.64.2/node_modules/astro/dist/core/build/index.js:121:5)
[20:14:26.393]     at async AstroBuilder.run (file:///vercel/path0/node_modules/.pnpm/astro@2.10.1_sass@1.64.2/node_modules/astro/dist/core/build/index.js:152:7)
[20:14:26.393]     at async build (file:///vercel/path0/node_modules/.pnpm/astro@2.10.1_sass@1.64.2/node_modules/astro/dist/core/build/index.js:37:3)
[20:14:26.393]     at async build (file:///vercel/path0/node_modules/.pnpm/astro@2.10.1_sass@1.64.2/node_modules/astro/dist/cli/build/index.js:20:3)
[20:14:26.394]     at async runCommand (file:///vercel/path0/node_modules/.pnpm/astro@2.10.1_sass@1.64.2/node_modules/astro/dist/cli/index.js:110:7)
[20:14:26.394]     at async cli (file:///vercel/path0/node_modules/.pnpm/astro@2.10.1_sass@1.64.2/node_modules/astro/dist/cli/index.js:148:5)
[20:14:26.418]  ELIFECYCLE  Command failed with exit code 1.
[20:14:26.437] Error: Command "pnpm run build" exited with 1
```
</details>

My Astro config right now is very minimal:

```js
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import react from "@astrojs/react";
import vercelEdge from "@astrojs/vercel/edge";
import prefetch from "@astrojs/prefetch";

export default defineConfig({
  output: "server",
  integrations: [tailwind(), react(), prefetch()],
  adapter: vercelEdge({
    analytics: false,
  }),
  build: {
    split: true,
  },
});
```
