### ISSUE TITLE
ERROR: Unexpected "default" on production build

### ISSUE THREAD

**Issue by artalar** [withastro/astro#7772]
### What version of `astro` are you using?

2.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Arc

### Describe the Bug

[I have an Astro component](https://github.com/artalar/reatom/blob/docs-remove-preact/docs/src/components/Repl.astro) with a `script` tag containing regular TypeScript and imports, which is always fine for development. When I tried to run a production build, it failed.

```sh
> npm run build

> @reatom/docs@0.0.1 build
> astro build

$ tsx sync-readme-to-pages.ts
02:26:57 PM [content] Types generated 199ms
02:26:57 PM [build] output target: static
02:26:57 PM [build] Collecting build info...
02:26:57 PM [build] Completed in 413ms.
02:26:57 PM [build] Building static entrypoints...
You are attempting to render <Repl client:load />, but Repl is an Astro component. Astro components do not render in the client and should not have a hydration directive. Please use a framework component for client rendering.
02:27:00 PM [build] Completed in 2.67s.

 building client 
[astro:build] Transform failed with 1 error:
astro-entry:/Users/artalar/Documents/code/reatom/docs/src/components/Repl.astro:25:26: ERROR: Unexpected "default"
file: astro-entry:/Users/artalar/Documents/code/reatom/docs/src/components/Repl.astro:25:26

Unexpected "default"
23 |  Astro.self = $$Repl;
24 |  
25 |  return $$render`export ${ default } from "/Users/artalar/Documents/code/reatom/docs/src/components/Repl.astro"`;
   |                            ^
26 |  }, 'astro-entry:/Users/artalar/Documents/code/reatom/docs/src/components/Repl.astro', undefined);
27 |  export default $$Repl;

transforming (44) node_modules/sucrase/dist/esm/transformers/JestHoistTransformer.js error   Unexpected "default"
  File:
    astro-entry:/Users/artalar/Documents/code/reatom/docs/src/components/Repl.astro:25:26
  Stacktrace:
Error: Transform failed with 1 error:
astro-entry:/Users/artalar/Documents/code/reatom/docs/src/components/Repl.astro:25:26: ERROR: Unexpected "default"
    at failureErrorWithLog (/Users/artalar/Documents/code/reatom/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/artalar/Documents/code/reatom/docs/node_modules/vite/node_modules/esbuild/lib/main.js:847:29
    at responseCallbacks.<computed> (/Users/artalar/Documents/code/reatom/docs/node_modules/vite/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/artalar/Documents/code/reatom/docs/node_modules/vite/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/artalar/Documents/code/reatom/docs/node_modules/vite/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)

```

### What's the expected result?

I want the same behavior as in the dev mode, SSG generates no HTML, but loads the script in the client.

### Link to Minimal Reproducible Example

https://github.com/artalar/reatom/pull/605

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
There's a `client:load` directive on the `.astro` component. That's not supported, as the error message says. The `script` in this file will already automatically run on the client.

```
You are attempting to render <Repl client:load />, but Repl is an Astro component. Astro components do not render in the client and should not have a hydration directive.
```

**Comment by artalar** [comment]
I get it, I don't need to use directives at all. Got it, thank you!
