### ISSUE TITLE
undici? telemetry? Node version bug?

### ISSUE THREAD

**Issue by georgekakarlis** [withastro/astro#7804]
### What version of `astro` are you using?

2.9.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome, Firefox Dev

### Describe the Bug

Hey! First-timer here. And sorry in advance for the long post.
 I was developing my 3rd site today with Astro. The two times before was phenomenal! Although today I run into an issue/bug. As I am creating new app @latest, then having already Nodejs 20.2.0 on my Mac I could not run the npm run dev command. The error I was getting was quite strange. Wherever I search for it I could not found any solution. This is the error :  
```
astro dev

  🚀  astro  v2.9.3 started in 80ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
/Users/~/Desktop/astro-blog/node_modules/web-streams-polyfill/dist/polyfill.js:362
            throw new TypeError(context + " is not a ReadableStream.");
                  ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (/Users/~/Desktop/astro-blog/node_modules/web-streams-polyfill/dist/polyfill.js:362:19)
    at convertReadableWritablePair (/Users/~/Desktop/astro-blog/node_modules/web-streams-polyfill/dist/polyfill.js:3524:9)
    at ReadableStream.pipeThrough (/Users/~/Desktop/astro-blog/node_modules/web-streams-polyfill/dist/polyfill.js:3608:29)
    at fetchFinale (node:internal/deps/undici/undici:11082:56)
    at mainFetch (node:internal/deps/undici/undici:10974:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.2.0
```   
.   With some searching and downgrading to Nodejs 18.17.0 LTS I quickly found that there is a dependency which I dont remember installing and is called Undici. It is "native" on the latest Nodejs version that is supposed to replace the http. And after that I found this piece of code 
```
"node_modules/@astrojs/telemetry": {
      "version": "2.1.1",
      "resolved": "https://registry.npmjs.org/@astrojs/telemetry/-/telemetry-2.1.1.tgz",
      "integrity": "sha512-4pRhyeQr0MLB5PKYgkdu+YE8sSpMbHL8dUuslBWBIdgcYjtD1SufPMBI8pgXJ+xlwrQJHKKfK2X1KonHYuOS9A==",
      "dependencies": {
        "ci-info": "^3.3.1",
        "debug": "^4.3.4",
        "dlv": "^1.1.3",
        "dset": "^3.1.2",
        "is-docker": "^3.0.0",
        "is-wsl": "^2.2.0",
        "undici": "^5.22.0",   <-- THIS ONE
        "which-pm-runs": "^1.1.0"
      },
      "engines": {
        "node": ">=16.12.0"
      }
```
. that the telemetry of Astro (which I use) uses this library and I cant run my project in Dev mode. What changed?

### What's the expected result?

If we update it, it should work? IDK im asking genuine :) 

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/basics?file=package-lock.json&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by georgekakarlis** [comment]
i fixed it! It was a mismatch between the versions of dependecies (nodejs, astro) My fault! Deleted the package-lock.json and the node_modules, npm install and now its working fine!!  :)
