### ISSUE TITLE
image-endpoint.js route collision

### ISSUE THREAD

**Issue by GrantBirki** [withastro/astro#7967]
### What version of `astro` are you using?

2.9.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

When using `2.9.1` of `astro` I have no problems running `npm run dev` (aka `astro dev`). However, when upgrading to `2.9.2` I can no longer run my application locally with `npm run dev`. Builds still work fine though.

Here is the error message when running `npm run dev` on `2.9.2`:

```bash
> astrowind@0.0.0 start
> astro dev

 error   An integration attempted to inject a route that is already used in your project: "/_image" at "node_modules/@astrojs/image/dist/endpoint.js".
  This route collides with: "node_modules/astro/dist/assets/image-endpoint.js".
Error: An integration attempted to inject a route that is already used in your project: "/_image" at "node_modules/@astrojs/image/dist/endpoint.js".
This route collides with: "node_modules/astro/dist/assets/image-endpoint.js".
    at file:///Users/grantbirkinbine/code/astrowind/node_modules/astro/dist/core/routing/manifest/create.js:275:13
    at Array.forEach (<anonymous>)
    at createRouteManifest (file:///Users/grantbirkinbine/code/astrowind/node_modules/astro/dist/core/routing/manifest/create.js:253:15)
    at configureServer (file:///Users/grantbirkinbine/code/astrowind/node_modules/astro/dist/vite-plugin-astro-server/plugin.js:19:26)
    at _createServer (file:///Users/grantbirkinbine/code/astrowind/node_modules/vite/dist/node/chunks/dep-75f53616.js:65106:30)
    at async createContainer (file:///Users/grantbirkinbine/code/astrowind/node_modules/astro/dist/core/dev/container.js:45:22)
    at async createContainerWithAutomaticRestart (file:///Users/grantbirkinbine/code/astrowind/node_modules/astro/dist/core/dev/restart.js:89:28)
    at async dev (file:///Users/grantbirkinbine/code/astrowind/node_modules/astro/dist/core/dev/dev.js:33:19)
    at async dev (file:///Users/grantbirkinbine/code/astrowind/node_modules/astro/dist/cli/dev/index.js:13:10)
    at async runCommand (file:///Users/grantbirkinbine/code/astrowind/node_modules/astro/dist/cli/index.js:108:22)
```

### What's the expected result?

I would expect `npm run dev` to work the same way as it has on every other patch version of Astro. I would expect my website to come online locally.

You can checkout the link at the "minimal reproducible example" below and run `npm i && npm run dev` to see the same error.

Related: https://github.com/GrantBirki/astrowind/pull/194 a pull request that can be checked out and replicate the steps listed above as well

### Link to Minimal Reproducible Example

https://github.com/GrantBirki/astrowind/tree/e96676042389e97a62f4f9e974adee08b7ff14bc

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
That template has both experimental assets and `@astrojs/image` enabled, which are incompatible. As documented here: https://docs.astro.build/en/guides/assets/#convert-from-astrojsimage

This has always been the case since day one, so I'm not sure why you're getting this message just now.

**Comment by GrantBirki** [comment]
Thank you @Princesseuh! I Tried your first suggested method first ("removing `@astrojs/image`) but failed miserably when trying to replace all occurrences of `<Picture/>` with `<Image/>`. I also had all sorts of busted imports to the `src/assets/` dir and couldn't figure out how to fix them. Here is the PR where I failed -> https://github.com/GrantBirki/astrowind/pull/200

So I tried the next best option which was just to simply remove [experimental assets](https://github.com/GrantBirki/astrowind/pull/199/files#diff-e0f0c5adbe0b9ca5d0b57caf5cea33a8d88899fd02a43df1e9862b185f8a1e5fL27-L29) and this worked perfectly. Thanks! 🚀
