### ISSUE TITLE
[3.0.0-beta.2] Build fails while rendering MDX

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#8080]
### What version of `astro` are you using?

3.0.0-beta.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm (also applies to npm)

### What operating system are you using?

Linux

### What browser are you using?

N/A

### Describe the Bug

Build fails when rendering MDX-page with Astro `3.0.0-beta.2`.

```console
$ pnpm build

> @fflaten/website@0.0.1 build /workspaces/Website
> astro build

06:38:08 PM [content] Types generated 259ms
06:38:08 PM [build] output target: static
06:38:08 PM [build] Collecting build info...
06:38:08 PM [build] Completed in 377ms.
06:38:08 PM [build] Building static entrypoints...
[astro:jsx] Cannot destructure property 'jsxTransformOptions' of 'renderer' as it is undefined.
file: /workspaces/Website/src/content/blog/rockets-blogs-and-powershell.mdx
 error   Cannot destructure property 'jsxTransformOptions' of 'renderer' as it is undefined.
  File:
    /workspaces/Website/src/content/blog/rockets-blogs-and-powershell.mdx
  Stacktrace:
TypeError: Cannot destructure property 'jsxTransformOptions' of 'renderer' as it is undefined.
    at transformJSX (file:///workspaces/Website/node_modules/.pnpm/astro@3.0.0-beta.2_@types+node@20.5.0_sass@1.65.1_typescript@5.1.6/node_modules/astro/dist/vite-plugin-mdx/index.js:15:11)
    at Object.transform (file:///workspaces/Website/node_modules/.pnpm/astro@3.0.0-beta.2_@types+node@20.5.0_sass@1.65.1_typescript@5.1.6/node_modules/astro/dist/vite-plugin-mdx/index.js:89:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async transform (file:///workspaces/Website/node_modules/.pnpm/rollup@3.26.3/node_modules/rollup/dist/es/shared/node-entry.js:24243:16)
    at async ModuleLoader.addModuleSource (file:///workspaces/Website/node_modules/.pnpm/rollup@3.26.3/node_modules/rollup/dist/es/shared/node-entry.js:24443:30)

 ELIFECYCLE  Command failed with exit code 1.
```

Repro:
1. Created a new project with `create-astro`
2. `npx astro add mdx`
3. Add a sample mdx-file in pages referencing the default layout
4. Build (using 2.10.7) = OK
5. Upgrade to `astro 3.0.0-beta.2` and `@astrojs/mdx 1.0.0-beta.0`. Build fails.
6. Rename mdx-file to `.md`. Build works.

### What's the expected result?

Build should work.

### Link to Minimal Reproducible Example

Stackblitz not compatible. See above.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Whoops! Looks like we missed a codepath when refactoring our JSX support. We'll take a look at this.

**Comment by matthewp** [comment]
I think I forgot to add a changeset for the MDX integration, so the `beta.0` here doesn't have the updated code.

**Comment by matthewp** [comment]
This is now fixed with beta.3 and mdx beta.1, thanks for reporting!
