### ISSUE TITLE
"Internal server error: URI malformed" when visiting dynamic param (SSR) with encoded symbol %

### ISSUE THREAD

**Issue by artmsv** [withastro/astro#8274]
### Astro info

```block
❯ astro info

Astro version            v2.10.14
Package manager          npm
Platform                 linux
Architecture             x64
Adapter                  @astrojs/node
Integrations             None or couldn't determine.
```

### What browser are you using?

Chrome

### Describe the Bug

If I pass escape symbols to the page with dynamic param `[slug].astro` app will throw 500 in `astro dev`, `astro preview`, and after build with node integration 

To reproduce visit `/blog/%2F` page in stackblitz

```
3:58:03 PM [vite] Internal server error: URI malformed
      at decodeURI (<anonymous>)
      at devBaseMiddleware (file:///home/projects/github-oiqdwp-nnenjt/node_modules/astro/dist/vite-plugin-astro-server/base.js:32:22)
      at call (file:///home/projects/github-oiqdwp-nnenjt/node_modules/vite/dist/node/chunks/dep-df561101.js:50665:7)
      at next (file:///home/projects/github-oiqdwp-nnenjt/node_modules/vite/dist/node/chunks/dep-df561101.js:50609:5)
      at Function.handle (file:///home/projects/github-oiqdwp-nnenjt/node_modules/vite/dist/node/chunks/dep-df561101.js:50612:3)
      at Server.app (file:///home/projects/github-oiqdwp-nnenjt/node_modules/vite/dist/node/chunks/dep-df561101.js:50477:37)
      at EventEmitter.emit (https://githuboiqdwpnnenjt-exbq.w-credentialless.staticblitz.com/blitz.33975f1d.js:45:8318)
      at parserOnIncoming (https://githuboiqdwpnnenjt-exbq.w-credentialless.staticblitz.com/blitz.33975f1d.js:126:13762)
      at _0x27379b.parserOnHeadersComplete (https://githuboiqdwpnnenjt-exbq.w-credentialless.staticblitz.com/blitz.33975f1d.js:85:1175)
      at https://githuboiqdwpnnenjt-exbq.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:392568
```

### What's the expected result?

should return 404 page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-oiqdwp-nnenjt?file=package.json,src%2Fpages%2Fblog%2F[slug].astro,astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Can confirm. Looks like this isn't the only place we hit this problem 
https://github.com/withastro/astro/issues/6217

**Comment by bluwy** [comment]
I can't seem to get the error for `/%2F`, but I'm able to get the malform uri error for `/%` or `/%abc`. `%2F` gives a different error of:

```
18:11:51 [ERROR] Expected "slug" to be a string
  Stack trace:
    at /Users/bjorn/Work/repros/astro-percent/node_modules/.pnpm/path-to-regexp@6.2.1/node_modules/path-to-regexp/dist/index.js:237:19
    [...] See full stack trace in the browser, or rerun with --verbose.
```

As the decoded path is essentially `/blog//`, which isn't quite a valid path. I'll send a PR to fix the error for `/%` though. There was an issue with the error overlay presenting the page on the browser.

**Comment by gambolputty** [comment]
I'm still getting `Expected "slug" to be a string` when I navigate to `[slug].astro` and "slug" is `%2F`, like:

`mywebsite.com/section/%2F`

in astro@4.3.6
