### ISSUE TITLE
Astro 3 + Vercel + redirect throws "The argument 'path' must be a string or Uint8Array without null bytes."

### ISSUE THREAD

**Issue by raulfdm** [withastro/astro#8315]
### Astro info

```block
Astro version            v3.0.3
Package manager          pnpm
Platform                 darwin
Architecture             arm64
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/react
```

### What browser are you using?

Not relevant

### Describe the Bug

After migrating to Astro 3, using Vercel adapter + redirect in the config throws an error:

```
11:58:12 [build] Building server entrypoints...
[vite:load-fallback] Could not load @astro-page:/uses (imported by @astro-page-split:/uses): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00@astro-page:/uses'
 error   Could not load @astro-page:/uses (imported by @astro-page-split:/uses): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00@astro-page:/uses'
TypeError [PLUGIN_ERROR]: Could not load @astro-page:/uses (imported by @astro-page-split:/uses): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00@astro-page:/uses'
    at TypeError.get (https://githubvnkvuj-ebm4.w-credentialless.staticblitz.com/blitz.33975f1d.js:67:7048)
    at eval (/home/projects/github-vnkvuj/node_modules/.pnpm/astro@3.0.3/node_modules/astro/dist/core/errors/dev/utils.js:35:11)
    at Module.collectErrorMetadata (/home/projects/github-vnkvuj/node_modules/.pnpm/astro@3.0.3/node_modules/astro/dist/core/errors/dev/utils.js:34:7)
    at throwAndExit (/home/projects/github-vnkvuj/node_modules/.pnpm/astro@3.0.3/node_modules/astro/dist/cli/throw-and-exit.js:31:55)
    at cli (/home/projects/github-vnkvuj/node_modules/.pnpm/astro@3.0.3/node_modules/astro/dist/cli/index.js:164:11)
/home/projects/github-vnkvuj/apps/website:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  website@0.0.1 build: `astro build`
Exit status 1
```

### What's the expected result?

Compiles without error

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vnkvuj?file=README.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by raulfdm** [comment]
https://github.com/withastro/astro/assets/12464600/a6131402-b555-4136-9fce-b7a15454fad1

**Comment by ematipico** [comment]
Thank you, @raulfdm, you always provide the most amazing reproductions! A fix is on the way :)
