### ISSUE TITLE
[BUG][Astro 3] Failed to parse source for import analysis because the content contains invalid JS syntax

### ISSUE THREAD

**Issue by 100gle** [withastro/astro#8359]
### Astro Info

```block
Astro                    v3.0.6
Node                     v20.5.1
System                   macOS (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/sitemap
                         @astrojs/tailwind
                         @astrojs/solid-js
                         astro-expressive-code
                         @astrojs/mdx
                         @astrojs/partytown
                         astro-compress
```

### Describe the Bug

I try to upgrade my blog from Astro 2.x to Astro 3.0 following the [v3 guides](https://docs.astro.build/en/guides/upgrade-to/v3/). But something wrong was happened when I ran dev server. the error information is:

```
Failed to parse source for import analysis because the content contains invalid JS syntax. If you use tsconfig.json, make sure to not set jsx to preserve.
```

however, the `jsx` configuration is automatically set by `@astro/solid` integration in `tsconfig.json`:

```diff
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "strictNullChecks": true,
+    "jsx": "preserve",
+    "jsxImportSource": "solid-js",
    "baseUrl": ".",
    "paths": {
      "~*": [
        "src/*"
      ],
    }
  }
}
```

even I commented the `jsx: "preserve"` the error still occurs. the full outputs in console are:

```
23:17:38 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you use tsconfig.json, make sure to not set jsx to preserve.
  Plugin: vite:import-analysis
  File: /Users/macbookpro/Repos/astro-preserve-jsx-bug/src/components/DarkMode.tsx:52:17
  50 |            >
  51 |              <path d="M17.8 13.75a1 1 0 0 0-.859-.5A7.488 7.488 0 0 1 10.52 2a1 1 0 0 0 0-.969A1.035 1.035 0 0 0 9.687.5h-.113a9.5 9.5 0 1 0 8.222 14.247 1 1 0 0 0 .004-.997Z" />
  52 |            </svg>
     |                  ^
  53 |          }
  54 |        >
      at formatError (file:///Users/macbookpro/Repos/astro-preserve-jsx-bug/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:43993:46)
      at TransformContext.error (file:///Users/macbookpro/Repos/astro-preserve-jsx-bug/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:43989:19)
      at TransformContext.transform (file:///Users/macbookpro/Repos/astro-preserve-jsx-bug/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:41740:22)
      at async Object.transform (file:///Users/macbookpro/Repos/astro-preserve-jsx-bug/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:30)
      at async loadAndTransform (file:///Users/macbookpro/Repos/astro-preserve-jsx-bug/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///Users/macbookpro/Repos/astro-preserve-jsx-bug/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
```

my node version is: 

```shell
$ node -v
v20.5.1
```

### What's the expected result?

Everything without any changes is OK in my blog with Astro 2.x version but not Astro 3.0. So just hope the issue can be fixed.

### Link to Minimal Reproducible Example

https://github.com/100gle/astro-preserve-jsx-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your Solid integration is outdated. The latest version is `3.0.0`. `pnpm install @astrojs/solid-js@latest` should do it
