### ISSUE TITLE
AVIF images aren't recognized as imports

### ISSUE THREAD

**Issue by ThatOneCalculator** [withastro/astro#8376]
### Astro Info

```block
Astro                    v3.0.7
Node                     v19.8.1
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             astro-icon
                         astro-rome
                         astro-sitemap
                         astro-preload
                         @astrojs/prefetch
                         astro-i18next
                         auto-import
                         @thewebforge/astro-code-blocks
                         @astrojs/mdx
                         astro-robots-txt
                         astro-purgecss
                         astro-compress
```

### Describe the Bug

With Astro assets, if I try and do

```
import { Image } from "astro:assets";
import fishImage from "../images/firefishreal.avif";
```

I get the error:

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

MissingImageDimension: Missing width and height attributes for /src/images/firefishreal.avif. When using remote images, both dimensions are always required in order to avoid CLS.
    at Object.validateOptions (/home/kainoa/Git/joinfirefish/node_modules/.pnpm/astro@3.0.7_sass@1.66.1_stylus@0.60.0/node_modules/astro/dist/assets/services/service.js:48:15)
    at Module.getImage (/home/kainoa/Git/joinfirefish/node_modules/.pnpm/astro@3.0.7_sass@1.66.1_stylus@0.60.0/node_modules/astro/dist/assets/internal.js:63:68)
    at async Module.getImage (astro:assets:16:42)
    at async eval (/home/kainoa/Git/joinfirefish/node_modules/.pnpm/astro@3.0.7_sass@1.66.1_stylus@0.60.0/node_modules/astro/components/Image.astro:24:17)
    at async AstroComponentInstance.render (/home/kainoa/Git/joinfirefish/node_modules/.pnpm/astro@3.0.7_sass@1.66.1_stylus@0.60.0/node_modules/astro/dist/runtime/server/render/astro/instance.js:37:7)
    at async Object.render (/home/kainoa/Git/joinfirefish/node_modules/.pnpm/astro@3.0.7_sass@1.66.1_stylus@0.60.0/node_modules/astro/dist/runtime/server/render/component.js:334:7)
    at async Module.renderChild (/home/kainoa/Git/joinfirefish/node_modules/.pnpm/astro@3.0.7_sass@1.66.1_stylus@0.60.0/node_modules/astro/dist/runtime/server/render/any.js:34:5)
    at async Object.renderToFinalDestination (/home/kainoa/Git/joinfirefish/node_modules/.pnpm/astro@3.0.7_sass@1.66.1_stylus@0.60.0/node_modules/astro/dist/runtime/server/render/util.js:119:7)
    at async RenderTemplateResult.render (/home/kainoa/Git/joinfirefish/node_modules/.pnpm/astro@3.0.7_sass@1.66.1_stylus@0.60.0/node_modules/astro/dist/runtime/server/render/astro/render-template.js:45:9)
    at async Module.renderChild (/home/kainoa/Git/joinfirefish/node_modules/.pnpm/astro@3.0.7_sass@1.66.1_stylus@0.60.0/node_modules/astro/dist/runtime/server/render/any.js:34:5) {
  loc: undefined,
  title: 'Missing image dimensions',
  hint: 'If your image is inside your `src` folder, you probably meant to import it instead. See [the Imports guide for more information](https://docs.astro.build/en/guides/imports/#other-assets).',
  frame: undefined,
  type: 'AstroError'
}
```

However, if I do

```
import { Image } from "astro:assets";
import fishImage from "../images/firefishreal.webp";
```

It works.

### What's the expected result?

.avif images to be importable like .webp

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment]
This is already an issue https://github.com/withastro/astro/issues/8056
