### ISSUE TITLE
Build fails with Node 20.6

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#8411]
### Astro Info

```block
Astro                    v3.0.8
Node                     v20.6.0
System                   Linux (x64) // also Windows (x64)
Package Manager          pnpm        // also npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

<img width="610" alt="image" src="https://github.com/withastro/astro/assets/69170106/ffef129b-9a5d-4b91-bc03-da54b93e8040">

### What's the expected result?

Users are able to build their projects.

### Link to Minimal Reproducible Example

Any astro project on Node 20.6

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
https://github.com/babel/babel/issues/15927

**Comment by nathanchere** [comment]
Downgrading to nodejs 20.5 at least works around it until the fix is released.

**Comment by unitof** [comment]
Pasting text of errors I get for better searchability—took a while to find this https://github.com/nodejs/node/issues/49497#issuecomment-1707941920!

When running `astro dev` or `astro build`:
```
/Users/jacob/repos/nc/wv-learningcenter/node_modules/@babel/core/lib/index.js:7
Object.defineProperty(exports, "File", {
       ^

TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/Users/jacob/repos/nc/wv-learningcenter/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/jacob/repos/nc/wv-learningcenter/node_modules/@babel/core/lib/config/helpers/config-api.js:16:9)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.6.0
npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: wv-learningcenter-web 
npm ERR!   at location: /Users/jacob/repos/nc/wv-learningcenter/apps/web 
```

When running `astro add`:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Cannot redefine property: Hub
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/astro/node_modules/@babel/traverse/lib/index.js:6:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/astro/node_modules/@babel/traverse/lib/path/index.js:9:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14) {
⋮
```

**Comment by lilnasy** [comment]
Yeah figured a message by astro would be nice for this reason. It is hard to get to the bottom of this as a user.

But they fixed it, so hopefully it's a matter of a few hours before 20.6.1 is released.

**Comment by adaptive** [comment]
20.6.1 fix it and released.

**Comment by nathanchere** [comment]
Does fix it. Still broken with nodejs 20.6.1-1 (i use arch btw)

**Comment by bluwy** [comment]
I don't really think there's much we can do at this point. If you're still seeing the issue in 20.6.1, please report it to nodejs. Or you can upgrade the babel dependencies to latest. Closing this as resolved.

**Comment by backflip** [comment]
20.6.1 fixes the issue for me.

**Comment by nathanchere** [comment]
Switching to [bun](https://github.com/oven-sh/bun) also fixed this issue.
