### ISSUE TITLE
Missing sharp on an old eeepc (Mx Linux 64 bit)

### ISSUE THREAD

**Issue by ziriuz84** [withastro/astro#8538]
### Astro Info

```block
Astro                    v3.0.13
Node                     v18.17.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @vite-pwa/astro-integration
                         @astrojs/tailwind
```

### Describe the Bug

I'm using an old eeepc 1015pn to do some work on my pwa with astro. I upgraded all packages with npm-packages-update and installed latest version of all. Installed packages are listed below
```
AAS App@0.0.1 /home/sirio/Progetti/AASApp
├── @astrojs/tailwind@5.0.0
├── @babel/preset-env@7.22.15
├── @babel/preset-typescript@7.22.15
├── @netlify/functions@2.0.2
├── @vite-pwa/astro@0.1.3
├── astro@3.0.13
├── chart.js@4.4.0
├── mime-types@2.1.35
├── moment@2.29.4
├── node-fetch@3.3.2
├── sass@1.66.1
├── sharp@0.32.5
├── tailwindcss@3.3.3
├── typescript@5.2.2
└── vite-plugin-pwa@0.16.5

```
When I run the app with npm run dev and I encounter an Image component npm exits with Illegal instruction. If I build it it gives Missing sharp error with this traceback

```
 generating optimized images 
 error   Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
  Hint:
    See Sharp's installation instructions for more information:  https://sharp.pixelplumbing.com/install . If you are not relying on `astro:assets` to optimize, transform, or process any images, you can configure a passthrough image service instead of installing Sharp. See  https://docs.astro.build/en/reference/errors/missing-sharp  for more information.
    
    See  https://docs.astro.build/en/guides/images/#default-image-service  for more information on how to migrate to another image service.
  Error reference:
    https://docs.astro.build/en/reference/errors/missing-sharp/
  File:
    /home/sirio/Progetti/AASApp/node_modules/astro/dist/assets/build/generate.js:74:22
  Code:
    73 |   const imageService = await getConfiguredImageService();
    > 74 |   resultData.data = (await imageService.transform(imageData, { ...options, src: originalImagePath }, config.image)).data;
         |                      ^
      75 |   try {
      76 |     if (useCache) {
      77 |       if (isLocalImage) {
  Stacktrace:
MissingSharp: Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
    at loadSharp (file:///home/sirio/Progetti/AASApp/dist/chunks/sharp_5d11af0e.mjs:20:11)
    at async Object.transform (file:///home/sirio/Progetti/AASApp/dist/chunks/sharp_5d11af0e.mjs:31:15)
    at async generateImage (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/assets/build/generate.js:74:22)
    at async generateImage (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/core/build/generate.js:174:26)
    at async generatePages (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/core/build/generate.js:155:5)
    at async staticBuild (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/core/build/static-build.js:85:7)
    at async AstroBuilder.build (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/core/build/index.js:127:5)
    at async AstroBuilder.run (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/core/build/index.js:158:7)
    at async build (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/core/build/index.js:37:3)
    at async build (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/cli/build/index.js:20:3)
    at async runCommand (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/cli/index.js:116:7)
    at async cli (file:///home/sirio/Progetti/AASApp/node_modules/astro/dist/cli/index.js:144:5)
```

Both works flawlessly with my other PCs. 

### What's the expected result?

It builds with optimized images via Image component

### Link to Minimal Reproducible Example

I think a reproduction via Stackbliz is useless, the problem is relative to this installation. But I can provide more hardware specs or data of my OS if needed

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Since it's an uncommon arch, you probably need to follow the instructions on this page: https://sharp.pixelplumbing.com/install

If this is not an option, you can alternatively use the Squoosh image service instead.

**Comment by ziriuz84** [comment]
I installed also with npm install sharp@latest, but without success. I will try to build from source or try to use squoosh, but it's a strange behaviour. Maybe there're some dependencies on OS that are not ok? It's a normal Intel x64 machine with a Debian-based distro.

**Comment by ziriuz84** [comment]
Just an edit: the package manager is plain npm

**Comment by ziriuz84** [comment]
I solved with squoosh. Is there a way to investigate further?

**Comment by matthewp** [comment]
It seems doubtful that Astro is at play here. Not sure we can help further. If you figure out what is going on and it is an Astro issue please open a PR to fix the problem, thank you!
