### ISSUE TITLE
Can't add tailwind from an integration

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#8919]
### Astro Info

```block
Astro                    v3.3.4
Node                     v18.14.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             integration
```

### Describe the Bug

When adding the tailwind integration from an integration (in another workspace) `updateConfig` in `astro:config:setup`, it throws the following error:
```
 error   [postcss] Cannot read properties of undefined (reading 'blocklist')
  File:
    D:/DEV/PROJECTS/florian-lefebvre/astro-integration-tailwind-bug/packages/integration/style.css
  Stacktrace:
TypeError: [postcss] Cannot read properties of undefined (reading 'blocklist')
    at createContext (D:\DEV\PROJECTS\florian-lefebvre\astro-integration-tailwind-bug\node_modules\.pnpm\tailwindcss@3.3.5\node_modules\tailwindcss\lib\lib\setupContextUtils.js:1186:76)
    at getContext (D:\DEV\PROJECTS\florian-lefebvre\astro-integration-tailwind-bug\node_modules\.pnpm\tailwindcss@3.3.5\node_modules\tailwindcss\lib\lib\setupContextUtils.js:1255:19)
    at D:\DEV\PROJECTS\florian-lefebvre\astro-integration-tailwind-bug\node_modules\.pnpm\tailwindcss@3.3.5\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:118:81
    at D:\DEV\PROJECTS\florian-lefebvre\astro-integration-tailwind-bug\node_modules\.pnpm\tailwindcss@3.3.5\node_modules\tailwindcss\lib\processTailwindFeatures.js:48:11
    at plugins (D:\DEV\PROJECTS\florian-lefebvre\astro-integration-tailwind-bug\node_modules\.pnpm\tailwindcss@3.3.5\node_modules\tailwindcss\lib\plugin.js:38:69)    
    at LazyResult.runOnRoot (D:\DEV\PROJECTS\florian-lefebvre\astro-integration-tailwind-bug\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\lazy-result.js:329:16)
    at LazyResult.runAsync (D:\DEV\PROJECTS\florian-lefebvre\astro-integration-tailwind-bug\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\lazy-result.js:258:26)
    at LazyResult.async (D:\DEV\PROJECTS\florian-lefebvre\astro-integration-tailwind-bug\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\lazy-result.js:160:30)
    at LazyResult.then (D:\DEV\PROJECTS\florian-lefebvre\astro-integration-tailwind-bug\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\lazy-result.js:404:17)
```

### What's the expected result?

It shouldn't crash

### Link to Minimal Reproducible Example

https://github.com/florian-lefebvre/astro-integration-tailwind-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Adding another integration in this way is not supported. Tailwind also uses the same hook, but that stage of hooks would have already been executed by the time tailwind is added.

I will keep this open to hear other maintainers' thoughts on whether it should be supported as a new feature.

**Comment by florian-lefebvre** [comment]
So that really depends on the integration right? I wanted to do this after seeing starlight adding sitemaps and mdx integrations

**Comment by lilnasy** [comment]
That'sa good point.

Also I just realised - as a workaround, you might be able to call tailwind integration's hook manually in your integration's hook.

**Comment by lilnasy** [comment]
`await tailwind["astro:config:setup"](...args)`

**Comment by florian-lefebvre** [comment]
For anyone reading this, right syntax is
```ts
await tailwind().hooks["astro:config:setup"]?.(...args);
```
and it doesn't work

**Comment by lilnasy** [comment]
It doesn't seem to be related to Astro. Tailwind's configuration (`integration/tailwind.ts`) fails to gets picked up.

**Comment by florian-lefebvre** [comment]
so `configFile` in tailwind doesn't work the same as `entrypoint` of injectRoute? I assumed it would but maybe it's only a matter of syntax/exports

**Comment by lilnasy** [comment]
It expects a real file.
<img width="500" alt="image" src="https://github.com/withastro/astro/assets/69170106/ac498cdd-ae57-492c-b0a2-9f0bddc2de34">

**Comment by lilnasy** [comment]
Regarding my first reply about adding integrations not being supported, that was incorrect!
- https://github.com/withastro/astro/pull/8672

**Comment by florian-lefebvre** [comment]
yes it works thanks! It may be worth documenting it somewhere or have entrypoint and configFile behave in a similar way

**Comment by lilnasy** [comment]
That's a good idea. Where do you think it should go?

**Comment by florian-lefebvre** [comment]
I guess it's already there at https://docs.astro.build/en/guides/integrations-guide/tailwind/#configfile, my bad!

**Comment by lilnasy** [comment]
Can this issue be closed?
