### ISSUE TITLE
createSafeError | To get as much information as possible from your errors, make sure to throw Error objects instead…

### ISSUE THREAD

**Issue by yayxs** [withastro/astro#8994]
### Astro Info

```block
Astro                    v3.4.3
Node                     v18.18.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

```sh
error   null
  Hint:
    To get as much information as possible from your errors, make sure to throw Error objects instead of `object`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error for more information.
  File:
    D:\gh-code\astro-demo\node_modules\.pnpm\astro@3.4.3\node_modules\astro\dist\core\errors\utils.js:64:19
  Code:
    63 |   } else {
    > 64 |     const error = new Error(JSON.stringify(err));
         |                   ^
      65 |     error.hint = `To get as much information as possible from your errors, make sure to throw Error objects instead of \`${typeof err}\`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error for more information.`;
      66 |     return error;
      67 |   }
  Stacktrace:
Error: null
    at createSafeError (file:///D:/gh-code/astro-demo/node_modules/.pnpm/astro@3.4.3/node_modules/astro/dist/core/errors/utils.js:64:19)
    at throwAndExit (file:///D:/gh-code/astro-demo/node_modules/.pnpm/astro@3.4.3/node_modules/astro/dist/cli/throw-and-exit.js:16:50)
    at cli (file:///D:/gh-code/astro-demo/node_modules/.pnpm/astro@3.4.3/node_modules/astro/dist/cli/index.js:147:11)
```

### What's the expected result?

normal work

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-vwjrx8?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Sorry, without more information, we can't really help. The error is simply saying that throwing an Error instead of a random value would lead to more information. I assume one of your dependency or your code is doing `throw null;` or similar.
