### ISSUE TITLE
Dynamic Redirects not working in SSG

### ISSUE THREAD

**Issue by lorenzolewis** [withastro/astro#9011]
### Astro Info

```block
Astro                    v3.4.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

The following config will error during `astro build`:

```js
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  redirects: {
    'reference/[...slug]': 'references/[...slug]',
  },
});
```

Error:

```
❯ npm run build

> @example/basics@0.0.1 build
> astro build

03:52:03 PM [content] No content directory found. Skipping type generation.
03:52:03 PM [build] output target: static
03:52:03 PM [build] Collecting build info...
03:52:03 PM [build] Completed in 21ms.
03:52:03 PM [build] Building static entrypoints...
03:52:04 PM [build] Completed in 0.78s.

 generating static routes 
▶ src/pages/index.astro
  └─ /index.html (+26ms)
▶ reference/[...slug]
 error   `getStaticPaths()` function is required for dynamic routes. Make sure that you `export` a `getStaticPaths` function from your dynamic route.
  Hint:
    See https://docs.astro.build/en/core-concepts/routing/#dynamic-routes for more information on dynamic routes.
    
    Alternatively, set `output: "server"` or `output: "hybrid"` in your Astro config file to switch to a non-static server build. This error can also occur if using `export const prerender = true;`.
    See https://docs.astro.build/en/guides/server-side-rendering/ for more information on non-static rendering.
  Error reference:
    https://docs.astro.build/en/reference/errors/get-static-paths-required/
  File:
    reference/[...slug]
  Stacktrace:
GetStaticPathsRequired: `getStaticPaths()` function is required for dynamic routes. Make sure that you `export` a `getStaticPaths` function from your dynamic route.
    at new AstroError (/home/projects/github-yxbfga/node_modules/astro/dist/core/errors/errors.js:36:5)
    at Module.validateDynamicRouteModule (/home/projects/github-yxbfga/node_modules/astro/dist/core/routing/validation.js:36:11)
    at Module.callGetStaticPaths (/home/projects/github-yxbfga/node_modules/astro/dist/core/render/route-cache.js:32:26)
    at getPathsForRoute (/home/projects/github-yxbfga/node_modules/astro/dist/core/build/generate.js:258:54)
    at generatePage (/home/projects/github-yxbfga/node_modules/astro/dist/core/build/generate.js:235:23)
    at async Module.generatePages (/home/projects/github-yxbfga/node_modules/astro/dist/core/build/generate.js:163:9)
    at async Module.staticBuild (/home/projects/github-yxbfga/node_modules/astro/dist/core/build/static-build.js:105:7)
    at async AstroBuilder.build (/home/projects/github-yxbfga/node_modules/astro/dist/core/build/index.js:144:5)
    at async AstroBuilder.run (/home/projects/github-yxbfga/node_modules/astro/dist/core/build/index.js:175:7)
    at async Module.build (/home/projects/github-yxbfga/node_modules/astro/dist/core/build/index.js:54:3)
```

### What's the expected result?

If I'm understanding the docs correctly at https://docs.astro.build/en/core-concepts/routing/#configured-redirects, this should result in output HTML files with the meta refresh tag by default. I'm not 100% sure if this is also the expected behaviour for SSG but I read the docs as it is supposed to also be compatible with SSG. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yxbfga?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
You still need to define a target route for `references/[...slug]` in SSG mode. Without that and a getStaticPaths, Astro doesn't know what pages to build.
