### ISSUE TITLE
Astro info throws when xclip is not available

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#9039]
### Astro Info

```block
> @fflaten/website@0.0.1 astro /workspaces/Website
> astro "info"

Astro                    v3.5.0
Node                     v18.16.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             config-watcher
                         auto-import
                         @astrojs/sitemap
                         @astrojs/asides
                         astro-expressive-code
                         @astrojs/mdx
 error   Command failed: which xclip
  File:
    /workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/info/index.js:38:20
  Code:
    37 |   } else {
    > 38 |     const output = execSync("which xclip", { encoding: "utf8" });
         |                    ^
      39 |     if (output[0] !== "/") {
      40 |       return;
      41 |     }
  Stacktrace:
Error: Command failed: which xclip
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at copyToClipboard (file:///workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/info/index.js:38:20)
    at printInfo (file:///workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/info/index.js:28:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runCommand (file:///workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/index.js:69:7)
    at async cli (file:///workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/index.js:144:5)
```

### Describe the Bug

Error is thrown by `execSync` on non-zero exit code (`xclip` was not found). Missing try/catch here: https://github.com/withastro/astro/blob/a888e985384918798e7c2f203e0dee48a4a21225/packages/astro/src/cli/info/index.ts#L53-L57

### What's the expected result?

No error

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Good catch! Do you want to submit a PR that wraps that in a try/catch and bails out in the catch? Would be much appreciated.

**Comment by fflaten** [comment]
Thanks for the quick triage.
Maybe in the weekend, but consider it up for grabs for anyone else. I already have a backlog to tackle 🙂
