### ISSUE TITLE
[astro] params not interpreted as string, when `trailingSlash: 'always'` for API routes

### ISSUE THREAD

**Issue by itsmatteomanf** [withastro/astro#9041]
### Astro Info

```block
Astro                    v3.5.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Whenever you have a build that includes a "page" that is not an `.astro` file, but a `.ts` (or I presume a `.js`) file, it will throw an error complaining that the param is not a string, while it definitely is.

This bug appeared with v3.5.0, it worked perfectly fine with all previous versions.

The local error shows as:

```
 error   Expected "lang" to be a string
  File:
    ./node_modules/.pnpm/path-to-regexp@6.2.1/node_modules/path-to-regexp/dist/index.js:237:19
  Code:
    236 |             var typeOfMessage = repeat ? "an array" : "a string";
    > 237 |             throw new TypeError("Expected \"".concat(token.name, "\" to be ").concat(typeOfMessage));
          |                   ^
      238 |         }
      239 |         return path;
      240 |     };
  Stacktrace:
TypeError: Expected "lang" to be a string
    at Object.generate (./node_modules/.pnpm/path-to-regexp@6.2.1/node_modules/path-to-regexp/dist/index.js:237:19)
    at stringifyParams (file://./node_modules/.pnpm/astro@3.5.0_typescript@5.2.2/node_modules/astro/dist/core/routing/params.js:26:31)
    at findPathItemByKey (file://./node_modules/.pnpm/astro@3.5.0_typescript@5.2.2/node_modules/astro/dist/core/render/route-cache.js:75:21)
    at getParamsAndProps (file://./node_modules/.pnpm/astro@3.5.0_typescript@5.2.2/node_modules/astro/dist/core/render/params-and-props.js:25:29)
    at async createRenderContext (file://./node_modules/.pnpm/astro@3.5.0_typescript@5.2.2/node_modules/astro/dist/core/render/context.js:8:27)
    at async generatePath (file://./node_modules/.pnpm/astro@3.5.0_typescript@5.2.2/node_modules/astro/dist/core/build/generate.js:402:25)
    at async generatePage (file://./node_modules/.pnpm/astro@3.5.0_typescript@5.2.2/node_modules/astro/dist/core/build/generate.js:252:5)
    at async generatePages (file://./node_modules/.pnpm/astro@3.5.0_typescript@5.2.2/node_modules/astro/dist/core/build/generate.js:167:9)
    at async staticBuild (file://./node_modules/.pnpm/astro@3.5.0_typescript@5.2.2/node_modules/astro/dist/core/build/static-build.js:88:7)
    at async AstroBuilder.build (file://./node_modules/.pnpm/astro@3.5.0_typescript@5.2.2/node_modules/astro/dist/core/build/index.js:134:5)

 ELIFECYCLE  Command failed with exit code 1.
```

### What's the expected result?

That the string is accepted as one.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-issue-9041

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by itsmatteomanf** [comment]
@ematipico note that the fix broke the root to default locale redirect, it doesn't respect the setting and does redirect to no trailing slash even with trailingSlash: 'always'.
