### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split') when importing md file content

### ISSUE THREAD

**Issue by heapallocation** [withastro/astro#9146]
### Astro Info

```block
I get this when I run astro info - Error: unknown command "info" for "astro"
Run 'astro --help' for usage.
```

### Describe the Bug

Hi there, I am trying to import md content from a md file using the content component with the following syntax as per the documentation:

`import {Content as test} from '../pages/numpy-glossary/test.md';`

when I add <test /> to my page to display the content I get the following error:

Stack trace:
TypeError: Cannot read properties of undefined (reading 'split')
    at codeToThemedTokens (file:///Users/anon/projects/retrograde-raspberry/node_modules/shikiji/dist/core.mjs:4422:24)
    at codeToHast (file:///Users/anon/projects/retrograde-raspberry/node_modules/shikiji/dist/core.mjs:4659:14)
    at codeToHtml (file:///Users/anon/projects/retrograde-raspberry/node_modules/shikiji/dist/core.mjs:4780:17)
    at Object.codeToHtml (file:///Users/anon/projects/retrograde-raspberry/node_modules/shikiji/dist/core.mjs:4789:37)
    at Object.highlight (/Users/anon/projects/retrograde-raspberry/node_modules/@astrojs/markdown-remark/dist/shiki.js:40:26)
    at /Users/anon/projects/retrograde-raspberry/node_modules/astro/components/Code.astro:101:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Any help would be greatly appreciated!

### What's the expected result?

Display content of the md file.

### Link to Minimal Reproducible Example

what is astro.new? Didn't understand what to do from links sorry.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
> what is astro.new? Didn't understand what to do from links sorry.

astro.new allows you to create an online replication of what you're seeing in your project. We need an example to start investigating the issue. The stacktrace isn't enough.

**Comment by heapallocation** [comment]
Happy to provide an example, but I don't see any steps on how to do so in the links provided. Maybe I'm missing a trick?

**Comment by florian-lefebvre** [comment]
At https://astro.new, you can click on "Open in Stackblitz" 

![image](https://github.com/withastro/astro/assets/69633530/d01f07e3-757d-4852-b1d6-30477355599b)

then create a Stackblitz account at the top right (you can use GitHub). Make the changes necessary to reproduce the bug (ie. as less as possible, to keep it minimal and scoped). Then you can take the url and send it here
