### ISSUE TITLE
Vercel hosting: GenerateContentTypesError: `astro sync` command failed to generate content collection types

### ISSUE THREAD

**Issue by teinett** [withastro/astro#9167]
### Astro Info

```block
Local Astro: 

Astro                    v3.5.5
Node                     v18.18.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/sitemap
                         astro-compress

Astro on Vercel.com - I don't know how to collect this info on Vercel.
```

### If this issue only occurs in one browser, which browser is a problem?

hosting

### Describe the Bug

Astro project does build locally with no errors.

Astro on Vercel hosting doesn't work:

```
[17:35:50.343] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[17:35:50.460] Cloning github.com/urbansheep/untitledsheep-astro (Branch: main, Commit: eccf175)
[17:35:56.592] Cloning completed: 6.132s
[17:35:58.855] Restored build cache
[17:35:58.983] Running "vercel build"
[17:35:59.553] Vercel CLI 32.5.6
[17:36:00.462] Installing dependencies...
[17:36:04.143] 
[17:36:04.144] added 111 packages, and removed 13 packages in 3s
[17:36:04.144] 
[17:36:04.145] 403 packages are looking for funding
[17:36:04.145]   run `npm fund` for details
[17:36:04.163] Detected `package-lock.json` generated by npm 7+
[17:36:04.163] Running "npm run build"
[17:36:05.774] 
[17:36:05.774] > untitled-urbansheep-astro@0.0.1 build
[17:36:05.775] > astro build
[17:36:05.775] 
[17:36:10.373]  error   `astro sync` command failed to generate content collection types: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
[17:36:10.374]   
[17:36:10.374]   If you are installing esbuild with npm, make sure that you don't specify the
[17:36:10.374]   "--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
[17:36:10.374]   of "package.json" is used by esbuild to install the correct binary executable
[17:36:10.375]   for your current platform.
[17:36:10.375]   Hint:
[17:36:10.375]     Check your `src/content/config.*` file for typos.
[17:36:10.375]   Error reference:
[17:36:10.375]     https://docs.astro.build/en/reference/errors/generate-content-types-error/
[17:36:10.375]   File:
[17:36:10.375]     /vercel/path0/node_modules/astro/dist/core/sync/index.js:76:11
[17:36:10.376]   Code:
[17:36:10.376]     75 |     }
[17:36:10.376]     > 76 |     throw new AstroError(
[17:36:10.376]          |           ^
[17:36:10.376]       77 |       {
[17:36:10.376]       78 |         ...AstroErrorData.GenerateContentTypesError,
[17:36:10.377]       79 |         message: AstroErrorData.GenerateContentTypesError.message(safeError.message)
[17:36:10.377]   Stacktrace:
[17:36:10.377] GenerateContentTypesError: `astro sync` command failed to generate content collection types: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
[17:36:10.377] 
[17:36:10.377] If you are installing esbuild with npm, make sure that you don't specify the
[17:36:10.377] "--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
[17:36:10.377] of "package.json" is used by esbuild to install the correct binary executable
[17:36:10.378] for your current platform.
[17:36:10.378]     at syncInternal (file:///vercel/path0/node_modules/astro/dist/core/sync/index.js:76:11)
[17:36:10.378]     at async AstroBuilder.setup (file:///vercel/path0/node_modules/astro/dist/core/build/index.js:93:21)
[17:36:10.378]     at async AstroBuilder.run (file:///vercel/path0/node_modules/astro/dist/core/build/index.js:163:23)
[17:36:10.381]     at async build (file:///vercel/path0/node_modules/astro/dist/core/build/index.js:44:3)
[17:36:10.381]     at async build (file:///vercel/path0/node_modules/astro/dist/cli/build/index.js:21:3)
[17:36:10.381]     at async runCommand (file:///vercel/path0/node_modules/astro/dist/cli/index.js:116:7)
[17:36:10.382]     at async cli (file:///vercel/path0/node_modules/astro/dist/cli/index.js:144:5)
[17:36:10.382] 
[17:36:10.395] Error: Command "npm run build" exited with 1
```

### What's the expected result?

I extected that work will work on hosting Vercel with no errors.

### Link to Minimal Reproducible Example

https://github.com/urbansheep/untitledsheep-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Your project built as expected when I cloned and deployed it to vercel. 
<img width="937" alt="image" src="https://github.com/withastro/astro/assets/69170106/7af52c41-710c-4aab-b7fb-28b7c9a43ca6">
It is possible something in your project config is interfering. You might want to ask vercel support about this.
