### ISSUE TITLE
MIddleware not running on build output

### ISSUE THREAD

**Issue by lvindotexe** [withastro/astro#9169]
### Astro Info

```block
Astro                    v3.5.5
Node                     v20.9.0
System                   Linux (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

This is my `middleware.ts`
```typescript
import { Router } from "astro-router";
import { defineMiddleware } from "astro:middleware";
const app = new Router().use((_, next) => {
    console.log('fuck me')
    return next()
})
export const onRequest = defineMiddleware((ctx, next) => {
    app.handle(ctx, next)
    return next()
})
```
this works as intended during dev and outputs this to the concole
```
  🚀  astro  v3.5.5 started in 910ms
  
  ┃ Local    http://localhost:4321/
  ┃ Network  use --host to expose
  
fuck me
```

however when i run `astro build && astro preview` and i call an endpoint on the page i get the error
```
 finalizing server assets 
04:00:24 PM [build] Rearranging server assets...
04:00:24 PM [build] Server built in 3.25s
04:00:24 PM [build] Complete!
04:00:27 PM [@astrojs/node] Preview server listening on http://localhost:4321
04:00:36 PM [@astrojs/node] Could not render /api/start
TypeError: Router is not a constructor
    at file:///home/al/Code/cc-framework/apps/test/dist/server/@astro-middleware.mjs:5:13
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async #getModuleForRoute (file:///home/al/Code/cc-framework/apps/test/dist/server/entry.mjs:903:28)
    at async NodeApp.render (file:///home/al/Code/cc-framework/apps/test/dist/server/entry.mjs:709:17)
    at async file:///home/al/Code/cc-framework/apps/test/dist/server/entry.mjs:1056:28
```

### What's the expected result?

i expected the build output to function the same as the  dev environment

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-c5cp8n?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
The reproduction you provided builds and serves requests correctly in the stackblitz. I had to add the node adapter btw. Best guess you have to reinstall from npm.

**Comment by lilnasy** [comment]
Your message that I won't repeat here, did get logged into the console by the server on every request.
