### ISSUE TITLE
Project not built properly

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#9453]
### Astro Info

```block
Astro                    v4.0.6
Node                     v20.7.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/markdoc
                         @astrojs/sitemap
                         @astrojs/vue
```

### Describe the Bug

I can't seem to  my project I get this error instead.

```sh
The requested module 'domutils' does not provide an export named 'default'
  Stack trace:
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async file:///home/louiss/main/web-projects/ui/dummy-markdoc-2/dist/chunks/pages/__AiKLcGC2.mjs:280:23
    at async renderToReadableStream (file:///home/louiss/main/web-projects/ui/dummy-markdoc-2/node_modules/.pnpm/astro@4.0.6_typescript@5.3.3/node_modules/astro/dist/runtime/server/render/astro/render.js:35:26)
    at async renderPage (file:///home/louiss/main/web-projects/ui/dummy-markdoc-2/node_modules/.pnpm/astro@4.0.6_typescript@5.3.3/node_modules/astro/dist/core/render/core.js:50:20)
 ELIFECYCLE  Command failed with exit code 1.
``` 

### What's the expected result?

I expected my project to build properly but it did not!

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/louiss0/dummy-markdoc-2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
I can't reproduce any error in the reproduction you shared @louiss0

**Comment by louiss0** [comment]
> I can't reproduce any error in the reproduction you shared @louiss0

What happened were you not able to access it?

**Comment by louiss0** [comment]
Never mind it had something to do with the way the modules were installed.
