### ISSUE TITLE
useContext fails on inital load, after reload it is fine?

### ISSUE THREAD

**Issue by whit3st** [withastro/astro#9576]
### Astro Info

```block
Astro                    v4.0.8
Node                     v21.1.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### Describe the Bug

I have a project with React and I use useContext hook. When I start the development server (happens only in development server), I get an error. After refreshing, the error disappears but I don't know what is causing this to happen.

`Cannot read properties of null (reading 'useContext')`
`cjs/react.development.js:1618:21`

```
TypeError: Cannot read properties of null (reading 'useContext')
    at Module.useContext (C:\Users\Alican\Desktop\cv-astro\node_modules\react\cjs\react.development.js:1618:21)`
    at Work (C:\Users\Alican\Desktop\cv-astro\src\components\work\work.tsx:6:20)
    at Tester (C:\Users\Alican\Desktop\cv-astro\node_modules\@astrojs\react\server.js:39:18)
    at describeNativeComponentFrame (C:\Users\Alican\Desktop\cv-astro\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:3732:7)
    at describeFunctionComponentFrame (C:\Users\Alican\Desktop\cv-astro\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:3827:12)
    at getStackByComponentStackNode (C:\Users\Alican\Desktop\cv-astro\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5294:19)
    at getCurrentStackInDEV (C:\Users\Alican\Desktop\cv-astro\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5460:12)
    at ReactDebugCurrentFrame.getStackAddendum (C:\Users\Alican\Desktop\cv-astro\node_modules\react\cjs\react.development.js:130:16)
    at printWarning (C:\Users\Alican\Desktop\cv-astro\node_modules\react\cjs\react-jsx-dev-runtime.development.js:71:40)
    at error (C:\Users\Alican\Desktop\cv-astro\node_modules\react\cjs\react-jsx-dev-runtime.development.js:61:7)
```

### It is probably something on my end but I can't figured it out and no-one seems to have a problem similar to mine. 

This is my layout.astro file

```
<ThemeContext.Provider value={themes}>
        <ResumeContext.Provider value={resume}>
            <body class={themes[selectedTheme].body + " py-14"}>
                <PrintMenu client:idle />
                <main class="container flex flex-col gap-10 font-in">
                    <slot />
                </main>
            </body>
        </ResumeContext.Provider>
</ThemeContext.Provider>
```

and this is my [project](https://github.com/whit3st/curriculum-vitae). If you start the development server on this repo, you will see an error as well.

### What's the expected result?

On the inital load of development server, I shouldn't see that error and after a refresh, the error disappears.

### Link to Minimal Reproducible Example

https://github.com/whit3st/curriculum-vitae

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Looking at the code snippet only, I think it's related to https://github.com/withastro/roadmap/discussions/742.

AFAIK the context api can't go through several astro islands. To make it work, you'd need to make the whole snippet a react component. On phone rn so I can't run the repro to check myself

**Comment by florian-lefebvre** [comment]
That being said, the reproduction you provided is a complete project, not a minimal reproduction. Please provide one.

**Comment by florian-lefebvre** [comment]
@whit3st if the issue is specific to your project, you may want to join the Astro's Discord for support
