### ISSUE TITLE
suddnely giving error while running : missed comma between flow collection entries

### ISSUE THREAD

**Issue by xkeshav** [withastro/astro#9604]
### Astro Info

```block
Astro                    v4.0.7
Node                     v18.17.1
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/tailwind
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

chrome

### Describe the Bug

Added a blog page under content > post >

create a folder and add **index.mdx** file ( like other pages I have ) but it started giving error.

whe run npm run dev it throw error and stopped with below error

```
missed comma between flow collection entries
  Hint:
    Browser APIs are not available on the server.

    If the code is in a framework component, try to access these objects after rendering using lifecycle methods or use a `client:only` directive to make the component exclusively run on the client.

    See https://docs.astro.build/en/guides/troubleshooting/#document-or-window-is-not-defined for more information.

  Stack trace:
    at generateError (D:\Developer\blog\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at readFlowCollection (D:\Developer\blog\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:718:7)
    at readBlockMapping (D:\Developer\blog\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1089:11)
    at readDocument (D:\Developer\blog\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1525:3)
    at load (D:\Developer\blog\node_modules\gray-matter\node_modules\js-yaml\lib\js-yaml\loader.js:1614:19)

```

### package.json

```json
{
  "name": "xkeshav-portfolio",
  "version": "1.7.5",
  "private": false,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "postbuild": "pagefind --site dist",
    "preview": "astro preview",
    "format": "prettier -w --cache . && prettier -w --cache **/*.astro",
    "check": "astro check"
  },
  "dependencies": {
    "@astrojs/mdx": "^2.0.0",
    "@astrojs/rss": "^4.0.1",
    "@astrojs/sitemap": "^3.0.3",
    "@astrojs/tailwind": "^5.0.3",
    "astro": "^4.0.3",
    "astro-icon": "^0.8.2",
    "rehype-external-links": "^3.0.0",
    "satori": "^0.10.11",
    "satori-html": "^0.3.2",
    "sharp": "^0.33.0"
  },
  "devDependencies": {
    "@astrojs/check": "^0.3.1",
    "@pagefind/default-ui": "^1.0.4",
    "@resvg/resvg-js": "^2.6.0",
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "@tailwindcss/typography": "^0.5.10",
    "@types/eslint": "^8.44.8",
    "@types/prettier": "^3.0.0",
    "@typescript-eslint/eslint-plugin": "^6.13.2",
    "@typescript-eslint/parser": "^6.13.2",
    "astro-eslint-parser": "^0.16.0",
    "autoprefixer": "^10.4.16",
    "eslint": "^8.55.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-astro": "^0.30.0",
    "eslint-plugin-import": "^2.29.0",
    "eslint-plugin-jsx-a11y": "^6.8.0",
    "eslint-plugin-prettier": "^5.0.1",
    "mdast-util-to-string": "^4.0.0",
    "pagefind": "^1.0.4",
    "postcss": "^8.4.32",
    "postcss-html": "^1.5.0",
    "postcss-import": "^15.1.0",
    "prettier": "^3.1.0",
    "prettier-plugin-astro": "0.12.2",
    "prettier-plugin-tailwindcss": "^0.5.9",
    "reading-time": "^1.5.0",
    "remark-unwrap-images": "^4.0.0",
    "tailwindcss": "^3.3.6",
    "typescript": "^5.3.3"
  },
  "packageManager": "npm@10.2.5"
}

```

### astro.config.ts

```js

import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import tailwind from "@astrojs/tailwind";
import { defineConfig } from "astro/config";
import fs from "fs";
import rehypeExternalLinks from "rehype-external-links";
import remarkUnwrapImages from "remark-unwrap-images";
import { remarkReadingTime } from "./src/utils/remark-reading-time";

// https://astro.build/config
export default defineConfig({
  site: "https://xkeshav.com/",
  markdown: {
    remarkPlugins: [remarkUnwrapImages, remarkReadingTime],
    rehypePlugins: [[rehypeExternalLinks, { target: "_blank", rel: ["nofollow, noopener, noreferrer"] }]],
    remarkRehype: { footnoteLabelProperties: { className: [""] } },
    shikiConfig: {
      theme: "dracula",
      wrap: true
    },
  },
  integrations: [
    mdx({}),
    tailwind({
      applyBaseStyles: false,
    }),
    sitemap(),
  ],
  image: {
    domains: [],
  },
  devToolbar: {
    enabled: false,
  },
  // https://docs.astro.build/en/guides/prefetch/
  prefetch: true,
  vite: {
    plugins: [rawFonts([".ttf"])],
    optimizeDeps: {
      exclude: ["@resvg/resvg-js"],
    },
  },
});

function rawFonts(ext: Array<string>) {
  return {
    name: "vite-plugin-raw-fonts",
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore:next-line
    transform(_, id) {
      if (ext.some((e) => id.endsWith(e))) {
        const buffer = fs.readFileSync(id);
        return {
          code: `export default ${JSON.stringify(buffer)}`,
          map: null,
        };
      }
    },
  };
}

```

### What's the expected result?

it shoud render the page succesfully.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by xkeshav** [comment]
fixed. issue was that I forgot to put comma between tags array :(
