### ISSUE TITLE
Running Astro on FreeBSD

### ISSUE THREAD

**Issue by MassivDash** [withastro/astro#9634]
### Astro Info

```block
> astro info

.../node_modules/rollup/dist/native.js:38
	throw new Error(
	      ^

Error: Your current platform "freebsd" and architecture "x64" combination is not yet supported by the native Rollup build. Please use the WASM build "@rollup/wasm-node" instead.

The following platform-architecture combinations are supported:
android-arm
android-arm64
darwin-arm64
darwin-x64
linux-arm
linux-arm64
linux-arm64 (musl)
linux-riscv64
linux-x64
linux-x64 (musl)
win32-arm64
win32-ia32
win32-x64

If this is important to you, please consider supporting Rollup to make a native build for your platform and architecture available.
    at Object.<anonymous> (.../node_modules/rollup/dist/native.js:38:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async runCommand (file:///../node_modules/astro/dist/cli/index.js:70:29)

Node.js v20.10.0
```

### Describe the Bug

I am trying to build a project on a freeBSD server, after seeing the same error on build cmd as above, I tried adding the rollup/wasm plugin 

```
import { defineConfig } from 'astro/config';
import { wasm } from '@rollup/plugin-wasm';

export default defineConfig({
    ...(process.platform === 'freebsd' && { vite: {
        plugins: [wasm()]
      }})
});
```

however i was unsuccessful 

### What's the expected result?

Is there a way around this ? Or am I doomed to fail ? 
I am using a simple starter no fancy stuff, adding the project repo for reference https://github.com/MassivDash/AstroX 

### Link to Minimal Reproducible Example

https://github.com/MassivDash/AstroX 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
As the message says, you need to install the WASM build of Rollup, `@rollup/wasm-node`. The plugin you installed is unrelated.

Astro does not officially support FreeBSD, so we can't assure you that everything will work out of the box, and won't be fixing issues related to this ourselves (nonetheless, we'd accept PRs as long as they do not increase the maintenance burden too much.)
