### ISSUE TITLE
Vercel: Build Error for 404 page

### ISSUE THREAD

**Issue by phenomen** [withastro/astro#9742]
### Astro Info

```block
Astro                    v4.2.1
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/svelte
                         @astrojs/react
                         @astrojs/markdoc                 
                         @astrojs/sitemap
                         keystatic
```

### Describe the Bug

Something broke with either the latest Astro or Vercel adapter and now I get this error on build:
```log
[12:45:02.996] > astro build
[12:45:02.997] 
[12:45:05.517] 18:45:05 Types generated 623ms
[12:45:05.518] 18:45:05 [build] output: "hybrid"
[12:45:05.518] 18:45:05 [build] directory: /vercel/path0/.vercel/output/
[12:45:05.518] 18:45:05 [build] adapter: @astrojs/vercel/serverless
[12:45:05.518] 18:45:05 [build] Collecting build info...
[12:45:05.519] 18:45:05 [build] ✓ Completed in 693ms.
[12:45:05.521] 18:45:05 [build] Building hybrid entrypoints...
[12:45:07.625] 18:45:07 [ERROR] [vite] [31m[vite]: Rollup failed to resolve import "$lib/layouts/Layout.astro" from "/vercel/path0/src/pages/404.astro".
[12:45:07.625] This is most likely unintended because it can break your application at runtime.
[12:45:07.625] If you do want to externalize this module explicitly add it to
[12:45:07.625] `build.rollupOptions.external`[39m
[12:45:07.869] [vite]: Rollup failed to resolve import "$lib/layouts/Layout.astro" from "/vercel/path0/src/pages/404.astro".
[12:45:07.870] This is most likely unintended because it can break your application at runtime.
[12:45:07.870] If you do want to externalize this module explicitly add it to
[12:45:07.870] `build.rollupOptions.external`
[12:45:07.870]   Stack trace:
[12:45:07.870]     at viteWarn (file:///vercel/path0/node_modules/.pnpm/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:67319:27)
[12:45:07.870]     at onRollupWarning (file:///vercel/path0/node_modules/.pnpm/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:67344:9)
[12:45:07.870]     at file:///vercel/path0/node_modules/.pnpm/rollup@4.9.5/node_modules/rollup/dist/es/shared/node-entry.js:17398:13
[12:45:07.870]     at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/.pnpm/rollup@4.9.5/node_modules/rollup/dist/es/shared/node-entry.js:18002:26)
[12:45:07.895]  ELIFECYCLE  Command failed with exit code 1.
[12:45:07.912] Error: Command "pnpm run build" exited with 1
```

My `pages/404.astro` page is quite simple:
```
---
import Layout from "$lib/layouts/Layout.astro";

const meta = {
  title: "404 - Page Not Found",
  description: "Looks like this page does not exist or was moved.",
};
---

<Layout {meta}>
  //some stuff
</Layout>
```
I use Vercel adapter with `hybrid` output. I've tried to clear build cache - no luck.

Looking at issues, it seems something was changed recently by #9615

### What's the expected result?

No build errors.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by phenomen** [comment]
Looks like the issue is not related to 404 page. Even if I completely remove custom 404, I get the same error with another .astro page...
