### ISSUE TITLE
Exclude server endpoints from Vite's dependency optimization

### ISSUE THREAD

**Issue by pilcrowOnPaper** [withastro/astro#9859]
### Astro Info

```block
Astro                    v4.2.6
Node                     v20.2.0
System                   macOS (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

With Astro's current configuration, Vite optimizes all dependencies imported in `src/**`. That causes issues when you import packages that use `.node` files such as `@node-rs/argon2`:

```
✘ [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/@node-rs+argon2-darwin-x64@1.7.0/node_modules/@node-rs/argon2-darwin-x64/argon2.darwin-x64.node

    node_modules/.pnpm/@node-rs+argon2@1.7.0/node_modules/@node-rs/argon2/index.js:159:36:
      159 │             nativeBinding = require('@node-rs/argon2-darwin-x64')
          ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/@node-rs+bcrypt-darwin-x64@1.9.0/node_modules/@node-rs/bcrypt-darwin-x64/bcrypt.darwin-x64.node

    node_modules/.pnpm/@node-rs+bcrypt@1.9.0/node_modules/@node-rs/bcrypt/binding.js:153:36:
      153 │             nativeBinding = require('@node-rs/bcrypt-darwin-x64')
```

We should probably exclude at least server endpoints, which we know won't be used in the client, from Vite's optimization. This should lead to better performance as well.

### What's the expected result?

Server only modules won't be optimized.

### Link to Minimal Reproducible Example

https://github.com/pilcrowOnPaper/astro-deps-optimization-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pilcrowOnPaper** [comment]
In the future, I'd love to see a way to mark modules as server-only, like `.server.ts` in SvelteKit

**Comment by pixelmund** [comment]
@pilcrowOnPaper 

Currently running into some issues using oslo with astro & cloudflare pages
``` bash
[ERROR] Could not resolve "fs"

    node_modules/.pnpm/@node-rs+argon2@1.7.0/node_modules/@node-rs/argon2/index.js:5:45:
      5 │ const { existsSync, readFileSync } = require('fs')
        ╵                                              ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    node_modules/.pnpm/@node-rs+argon2@1.7.0/node_modules/@node-rs/argon2/index.js:6:25:
      6 │ const { join } = require('path')
        ╵                          ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "fs"

    node_modules/.pnpm/@node-rs+bcrypt@1.9.0/node_modules/@node-rs/bcrypt/binding.js:5:45:
      5 │ const { existsSync, readFileSync } = require('fs')
        ╵                                              ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    node_modules/.pnpm/@node-rs+bcrypt@1.9.0/node_modules/@node-rs/bcrypt/binding.js:6:25:
      6 │ const { join } = require('path')
        ╵                          ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/@node-rs+argon2-darwin-arm64@1.7.0/node_modules/@node-rs/argon2-darwin-arm64/argon2.darwin-arm64.node

    node_modules/.pnpm/@node-rs+argon2@1.7.0/node_modules/@node-rs/argon2/index.js:173:36:
      173 │             nativeBinding = require('@node-rs/argon2-darwin-arm64')
          ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/@node-rs+bcrypt-darwin-arm64@1.9.0/node_modules/@node-rs/bcrypt-darwin-arm64/bcrypt.darwin-arm64.node

    node_modules/.pnpm/@node-rs+bcrypt@1.9.0/node_modules/@node-rs/bcrypt/binding.js:165:36:
      165 │             nativeBinding = require('@node-rs/bcrypt-darwin-arm64')
          ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Could not resolve "fs"
  Stack trace:
    at failureErrorWithLog (/Users/julian/Desktop/DEVELOPMENT/projects/form/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1651:15)
    at runOnEndCallbacks (/Users/julian/Desktop/DEVELOPMENT/projects/form/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1486:45)
    at /Users/julian/Desktop/DEVELOPMENT/projects/form/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1086:16
    at handleIncomingPacket (/Users/julian/Desktop/DEVELOPMENT/projects/form/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:764:9)
    at Socket.emit (node:events:518:28)
```

i've already added oslo to my optimizeDeps exclude:
``` js
  vite: {
    optimizeDeps: {
      exclude: ["oslo", "@node-rs/argon2", "@node-rs/bcrypt"],
    }
  },
```

Do you know how to fix this?

**Comment by pilcrowOnPaper** [comment]
@pixelmund Open a new issue on Oslo's repo. FYI you can't use Oslo's password module in non-Node.js runtime
